# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@78d07aea

# .obj1@78d07aea
.obj1@78d07aea := MyFileResource
.obj1@78d07aea.issues := 
.obj1@78d07aea.contentsRoot := .obj77@78d07aea
.obj1@78d07aea.resourceSet := 
.obj1@78d07aea.fileName := src/drivers/block_dev/stm32_sd/Mybuild
.obj1@78d07aea.exports := \
	embox.driver.sd \
	embox.driver.sd.sd \
	embox.driver.sd.stm32f4_sd \
	embox.driver.sd.stm32f4_sd.use_local_buf \
	embox.driver.sd.stm32f4_sd.sd_buf_size \
	embox.driver.sd.stm32f746g_discovery_sd \
	embox.driver.sd.stm32f746g_discovery_sd.use_local_buf \
	embox.driver.sd.stm32f746g_discovery_sd.sd_buf_size \
	embox.driver.sd.stm32f769i_discovery_sd \
	embox.driver.sd.stm32f769i_discovery_sd.use_local_buf \
	embox.driver.sd.stm32f769i_discovery_sd.sd_buf_size
.obj1@78d07aea.exports.embox.driver.sd := \
	.obj77@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.sd := \
	.obj2@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f4_sd := \
	.obj22@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f4_sd.use_local_buf := \
	.obj10@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f4_sd.sd_buf_size := \
	.obj13@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f746g_discovery_sd := \
	.obj49@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f746g_discovery_sd.use_local_buf := \
	.obj30@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f746g_discovery_sd.sd_buf_size := \
	.obj33@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f769i_discovery_sd := \
	.obj76@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f769i_discovery_sd.use_local_buf := \
	.obj57@78d07aea
.obj1@78d07aea.exports.embox.driver.sd.stm32f769i_discovery_sd.sd_buf_size := \
	.obj60@78d07aea

# .obj77@78d07aea
.obj77@78d07aea := MyFileContentRoot
.obj77@78d07aea.__eContents := \
	types/.obj2@78d07aea \
	types/.obj22@78d07aea \
	types/.obj49@78d07aea \
	types/.obj76@78d07aea
.obj77@78d07aea.__eContainer := .obj1@78d07aea
.obj77@78d07aea.imports := 
.obj77@78d07aea.name := embox.driver.sd
.obj77@78d07aea.origin := 

# .obj2@78d07aea
.obj2@78d07aea := MyModuleType
.obj2@78d07aea.__eContents := 
.obj2@78d07aea.__eContainer := fileContentRoot/types.obj77@78d07aea
.obj2@78d07aea.dependent := 
.obj2@78d07aea.subTypes := 
.obj2@78d07aea.modifiers := abstract
.obj2@78d07aea.name := sd
.obj2@78d07aea.origin := 3:17
.obj2@78d07aea.superType := 
.obj2@78d07aea.customStorage := 

# .obj22@78d07aea
.obj22@78d07aea := MyModuleType
.obj22@78d07aea.__eContents := \
	sourcesMembers/.obj17@78d07aea \
	optionsMembers/.obj12@78d07aea \
	optionsMembers/.obj15@78d07aea \
	dependsMembers/.obj19@78d07aea \
	dependsMembers/.obj21@78d07aea \
	annotations/.obj8@78d07aea
.obj22@78d07aea.__eContainer := fileContentRoot/types.obj77@78d07aea
.obj22@78d07aea.dependent := 
.obj22@78d07aea.subTypes := 
.obj22@78d07aea.modifiers := 
.obj22@78d07aea.name := stm32f4_sd
.obj22@78d07aea.origin := 6:8
.obj22@78d07aea.superType := .obj9@78d07aea./
.obj22@78d07aea.customStorage := 

# .obj17@78d07aea
.obj17@78d07aea := MySourceMember
.obj17@78d07aea.__eContents := \
	files/.obj16@78d07aea
.obj17@78d07aea.__eContainer := /sourcesMembers.obj22@78d07aea
.obj17@78d07aea.module := 

# .obj16@78d07aea
.obj16@78d07aea := MyFileName
.obj16@78d07aea.__eContents := 
.obj16@78d07aea.__eContainer := /files.obj17@78d07aea
.obj16@78d07aea.fileName := stm32f4_sd.c

# .obj12@78d07aea
.obj12@78d07aea := MyOptionMember
.obj12@78d07aea.__eContents := \
	options/.obj10@78d07aea
.obj12@78d07aea.__eContainer := /optionsMembers.obj22@78d07aea
.obj12@78d07aea.module := 

# .obj10@78d07aea
.obj10@78d07aea := MyBooleanOption
.obj10@78d07aea.__eContents := \
	defaultValue/.obj11@78d07aea
.obj10@78d07aea.__eContainer := /options.obj12@78d07aea
.obj10@78d07aea.name := use_local_buf
.obj10@78d07aea.origin := 

# .obj11@78d07aea
.obj11@78d07aea := MyBooleanLiteral
.obj11@78d07aea.__eContents := 
.obj11@78d07aea.__eContainer := /defaultValue.obj10@78d07aea
.obj11@78d07aea.isValue := 1

# .obj15@78d07aea
.obj15@78d07aea := MyOptionMember
.obj15@78d07aea.__eContents := \
	options/.obj13@78d07aea
.obj15@78d07aea.__eContainer := /optionsMembers.obj22@78d07aea
.obj15@78d07aea.module := 

# .obj13@78d07aea
.obj13@78d07aea := MyNumberOption
.obj13@78d07aea.__eContents := \
	defaultValue/.obj14@78d07aea
.obj13@78d07aea.__eContainer := /options.obj15@78d07aea
.obj13@78d07aea.name := sd_buf_size
.obj13@78d07aea.origin := 

# .obj14@78d07aea
.obj14@78d07aea := MyNumberLiteral
.obj14@78d07aea.__eContents := 
.obj14@78d07aea.__eContainer := /defaultValue.obj13@78d07aea
.obj14@78d07aea.value := 4096

# .obj19@78d07aea
.obj19@78d07aea := MyDependsMember
.obj19@78d07aea.__eContents := 
.obj19@78d07aea.__eContainer := /dependsMembers.obj22@78d07aea
.obj19@78d07aea.modules := \
	.obj18@78d07aea./
.obj19@78d07aea.module := 

# .obj18@78d07aea
.obj18@78d07aea := ELink
.obj18@78d07aea.eSource := MyFile_DependsMember_modules.obj19@78d07aea
.obj18@78d07aea.eTarget := 
.obj18@78d07aea.name := embox.driver.block_dev
.obj18@78d07aea.origin := 12:10

# .obj21@78d07aea
.obj21@78d07aea := MyDependsMember
.obj21@78d07aea.__eContents := 
.obj21@78d07aea.__eContainer := /dependsMembers.obj22@78d07aea
.obj21@78d07aea.modules := \
	.obj20@78d07aea./
.obj21@78d07aea.module := 

# .obj20@78d07aea
.obj20@78d07aea := ELink
.obj20@78d07aea.eSource := MyFile_DependsMember_modules.obj21@78d07aea
.obj20@78d07aea.eTarget := 
.obj20@78d07aea.name := third_party.bsp.stmf4cube.core
.obj20@78d07aea.origin := 13:10

# .obj8@78d07aea
.obj8@78d07aea := MyAnnotation
.obj8@78d07aea.__eContents := \
	bindings/.obj6@78d07aea
.obj8@78d07aea.__eContainer := target/annotations.obj22@78d07aea
.obj8@78d07aea.type := .obj3@78d07aea./

# .obj6@78d07aea
.obj6@78d07aea := MyOptionBinding
.obj6@78d07aea.__eContents := \
	value/.obj5@78d07aea
.obj6@78d07aea.__eContainer := /bindings.obj8@78d07aea
.obj6@78d07aea.option := .obj7@78d07aea./

# .obj5@78d07aea
.obj5@78d07aea := MyTypeReferenceLiteral
.obj5@78d07aea.__eContents := 
.obj5@78d07aea.__eContainer := /value.obj6@78d07aea
.obj5@78d07aea.value := .obj4@78d07aea./

# .obj4@78d07aea
.obj4@78d07aea := ELink
.obj4@78d07aea.eSource := MyFile_TypeReferenceLiteral_value.obj5@78d07aea
.obj4@78d07aea.eTarget := 
.obj4@78d07aea.name := third_party.bsp.stmf4cube.core
.obj4@78d07aea.origin := 5:15

# .obj7@78d07aea
.obj7@78d07aea := ELink
.obj7@78d07aea.eSource := MyFile_OptionBinding_option.obj6@78d07aea
.obj7@78d07aea.eTarget := 
.obj7@78d07aea.name := value
.obj7@78d07aea.origin := 5:14

# .obj3@78d07aea
.obj3@78d07aea := ELink
.obj3@78d07aea.eSource := MyFile_Annotation_type.obj8@78d07aea
.obj3@78d07aea.eTarget := 
.obj3@78d07aea.name := BuildDepends
.obj3@78d07aea.origin := 5:2

# .obj9@78d07aea
.obj9@78d07aea := ELink
.obj9@78d07aea.eSource := MyFile_ModuleType_superType.obj22@78d07aea
.obj9@78d07aea.eTarget := 
.obj9@78d07aea.name := sd
.obj9@78d07aea.origin := 6:27

# .obj49@78d07aea
.obj49@78d07aea := MyModuleType
.obj49@78d07aea.__eContents := \
	sourcesMembers/.obj42@78d07aea \
	sourcesMembers/.obj44@78d07aea \
	optionsMembers/.obj32@78d07aea \
	optionsMembers/.obj35@78d07aea \
	dependsMembers/.obj46@78d07aea \
	dependsMembers/.obj48@78d07aea \
	annotations/.obj28@78d07aea
.obj49@78d07aea.__eContainer := fileContentRoot/types.obj77@78d07aea
.obj49@78d07aea.dependent := 
.obj49@78d07aea.subTypes := 
.obj49@78d07aea.modifiers := 
.obj49@78d07aea.name := stm32f746g_discovery_sd
.obj49@78d07aea.origin := 17:8
.obj49@78d07aea.superType := .obj29@78d07aea./
.obj49@78d07aea.customStorage := 

# .obj42@78d07aea
.obj42@78d07aea := MySourceMember
.obj42@78d07aea.__eContents := \
	files/.obj41@78d07aea \
	annotations/.obj40@78d07aea
.obj42@78d07aea.__eContainer := /sourcesMembers.obj49@78d07aea
.obj42@78d07aea.module := 

# .obj41@78d07aea
.obj41@78d07aea := MyFileName
.obj41@78d07aea.__eContents := 
.obj41@78d07aea.__eContainer := /files.obj42@78d07aea
.obj41@78d07aea.fileName := stm32f746g_discovery_sd.h

# .obj40@78d07aea
.obj40@78d07aea := MyAnnotation
.obj40@78d07aea.__eContents := \
	bindings/.obj39@78d07aea
.obj40@78d07aea.__eContainer := target/annotations.obj42@78d07aea
.obj40@78d07aea.type := .obj36@78d07aea./

# .obj39@78d07aea
.obj39@78d07aea := MyOptionBinding
.obj39@78d07aea.__eContents := \
	value/.obj38@78d07aea
.obj39@78d07aea.__eContainer := /bindings.obj40@78d07aea
.obj39@78d07aea.option := .obj37@78d07aea./

# .obj38@78d07aea
.obj38@78d07aea := MyStringLiteral
.obj38@78d07aea.__eContents := 
.obj38@78d07aea.__eContainer := /value.obj39@78d07aea
.obj38@78d07aea.value := stm32f7_discovery_sd.h

# .obj37@78d07aea
.obj37@78d07aea := ELink
.obj37@78d07aea.eSource := MyFile_OptionBinding_option.obj39@78d07aea
.obj37@78d07aea.eTarget := 
.obj37@78d07aea.name := target_name
.obj37@78d07aea.origin := 21:17

# .obj36@78d07aea
.obj36@78d07aea := ELink
.obj36@78d07aea.eSource := MyFile_Annotation_type.obj40@78d07aea
.obj36@78d07aea.eTarget := 
.obj36@78d07aea.name := IncludeExport
.obj36@78d07aea.origin := 21:3

# .obj44@78d07aea
.obj44@78d07aea := MySourceMember
.obj44@78d07aea.__eContents := \
	files/.obj43@78d07aea
.obj44@78d07aea.__eContainer := /sourcesMembers.obj49@78d07aea
.obj44@78d07aea.module := 

# .obj43@78d07aea
.obj43@78d07aea := MyFileName
.obj43@78d07aea.__eContents := 
.obj43@78d07aea.__eContainer := /files.obj44@78d07aea
.obj43@78d07aea.fileName := stm32f7_sd.c

# .obj32@78d07aea
.obj32@78d07aea := MyOptionMember
.obj32@78d07aea.__eContents := \
	options/.obj30@78d07aea
.obj32@78d07aea.__eContainer := /optionsMembers.obj49@78d07aea
.obj32@78d07aea.module := 

# .obj30@78d07aea
.obj30@78d07aea := MyBooleanOption
.obj30@78d07aea.__eContents := \
	defaultValue/.obj31@78d07aea
.obj30@78d07aea.__eContainer := /options.obj32@78d07aea
.obj30@78d07aea.name := use_local_buf
.obj30@78d07aea.origin := 

# .obj31@78d07aea
.obj31@78d07aea := MyBooleanLiteral
.obj31@78d07aea.__eContents := 
.obj31@78d07aea.__eContainer := /defaultValue.obj30@78d07aea
.obj31@78d07aea.isValue := 1

# .obj35@78d07aea
.obj35@78d07aea := MyOptionMember
.obj35@78d07aea.__eContents := \
	options/.obj33@78d07aea
.obj35@78d07aea.__eContainer := /optionsMembers.obj49@78d07aea
.obj35@78d07aea.module := 

# .obj33@78d07aea
.obj33@78d07aea := MyNumberOption
.obj33@78d07aea.__eContents := \
	defaultValue/.obj34@78d07aea
.obj33@78d07aea.__eContainer := /options.obj35@78d07aea
.obj33@78d07aea.name := sd_buf_size
.obj33@78d07aea.origin := 

# .obj34@78d07aea
.obj34@78d07aea := MyNumberLiteral
.obj34@78d07aea.__eContents := 
.obj34@78d07aea.__eContainer := /defaultValue.obj33@78d07aea
.obj34@78d07aea.value := 4096

# .obj46@78d07aea
.obj46@78d07aea := MyDependsMember
.obj46@78d07aea.__eContents := 
.obj46@78d07aea.__eContainer := /dependsMembers.obj49@78d07aea
.obj46@78d07aea.modules := \
	.obj45@78d07aea./
.obj46@78d07aea.module := 

# .obj45@78d07aea
.obj45@78d07aea := ELink
.obj45@78d07aea.eSource := MyFile_DependsMember_modules.obj46@78d07aea
.obj45@78d07aea.eTarget := 
.obj45@78d07aea.name := embox.driver.block_dev
.obj45@78d07aea.origin := 26:10

# .obj48@78d07aea
.obj48@78d07aea := MyDependsMember
.obj48@78d07aea.__eContents := 
.obj48@78d07aea.__eContainer := /dependsMembers.obj49@78d07aea
.obj48@78d07aea.modules := \
	.obj47@78d07aea./
.obj48@78d07aea.module := 

# .obj47@78d07aea
.obj47@78d07aea := ELink
.obj47@78d07aea.eSource := MyFile_DependsMember_modules.obj48@78d07aea
.obj47@78d07aea.eTarget := 
.obj47@78d07aea.name := third_party.bsp.st_bsp_api
.obj47@78d07aea.origin := 27:10

# .obj28@78d07aea
.obj28@78d07aea := MyAnnotation
.obj28@78d07aea.__eContents := \
	bindings/.obj26@78d07aea
.obj28@78d07aea.__eContainer := target/annotations.obj49@78d07aea
.obj28@78d07aea.type := .obj23@78d07aea./

# .obj26@78d07aea
.obj26@78d07aea := MyOptionBinding
.obj26@78d07aea.__eContents := \
	value/.obj25@78d07aea
.obj26@78d07aea.__eContainer := /bindings.obj28@78d07aea
.obj26@78d07aea.option := .obj27@78d07aea./

# .obj25@78d07aea
.obj25@78d07aea := MyTypeReferenceLiteral
.obj25@78d07aea.__eContents := 
.obj25@78d07aea.__eContainer := /value.obj26@78d07aea
.obj25@78d07aea.value := .obj24@78d07aea./

# .obj24@78d07aea
.obj24@78d07aea := ELink
.obj24@78d07aea.eSource := MyFile_TypeReferenceLiteral_value.obj25@78d07aea
.obj24@78d07aea.eTarget := 
.obj24@78d07aea.name := third_party.bsp.st_bsp_api
.obj24@78d07aea.origin := 16:15

# .obj27@78d07aea
.obj27@78d07aea := ELink
.obj27@78d07aea.eSource := MyFile_OptionBinding_option.obj26@78d07aea
.obj27@78d07aea.eTarget := 
.obj27@78d07aea.name := value
.obj27@78d07aea.origin := 16:14

# .obj23@78d07aea
.obj23@78d07aea := ELink
.obj23@78d07aea.eSource := MyFile_Annotation_type.obj28@78d07aea
.obj23@78d07aea.eTarget := 
.obj23@78d07aea.name := BuildDepends
.obj23@78d07aea.origin := 16:2

# .obj29@78d07aea
.obj29@78d07aea := ELink
.obj29@78d07aea.eSource := MyFile_ModuleType_superType.obj49@78d07aea
.obj29@78d07aea.eTarget := 
.obj29@78d07aea.name := sd
.obj29@78d07aea.origin := 17:40

# .obj76@78d07aea
.obj76@78d07aea := MyModuleType
.obj76@78d07aea.__eContents := \
	sourcesMembers/.obj69@78d07aea \
	sourcesMembers/.obj71@78d07aea \
	optionsMembers/.obj59@78d07aea \
	optionsMembers/.obj62@78d07aea \
	dependsMembers/.obj73@78d07aea \
	dependsMembers/.obj75@78d07aea \
	annotations/.obj55@78d07aea
.obj76@78d07aea.__eContainer := fileContentRoot/types.obj77@78d07aea
.obj76@78d07aea.dependent := 
.obj76@78d07aea.subTypes := 
.obj76@78d07aea.modifiers := 
.obj76@78d07aea.name := stm32f769i_discovery_sd
.obj76@78d07aea.origin := 31:8
.obj76@78d07aea.superType := .obj56@78d07aea./
.obj76@78d07aea.customStorage := 

# .obj69@78d07aea
.obj69@78d07aea := MySourceMember
.obj69@78d07aea.__eContents := \
	files/.obj68@78d07aea \
	annotations/.obj67@78d07aea
.obj69@78d07aea.__eContainer := /sourcesMembers.obj76@78d07aea
.obj69@78d07aea.module := 

# .obj68@78d07aea
.obj68@78d07aea := MyFileName
.obj68@78d07aea.__eContents := 
.obj68@78d07aea.__eContainer := /files.obj69@78d07aea
.obj68@78d07aea.fileName := stm32f769i_discovery_sd.h

# .obj67@78d07aea
.obj67@78d07aea := MyAnnotation
.obj67@78d07aea.__eContents := \
	bindings/.obj66@78d07aea
.obj67@78d07aea.__eContainer := target/annotations.obj69@78d07aea
.obj67@78d07aea.type := .obj63@78d07aea./

# .obj66@78d07aea
.obj66@78d07aea := MyOptionBinding
.obj66@78d07aea.__eContents := \
	value/.obj65@78d07aea
.obj66@78d07aea.__eContainer := /bindings.obj67@78d07aea
.obj66@78d07aea.option := .obj64@78d07aea./

# .obj65@78d07aea
.obj65@78d07aea := MyStringLiteral
.obj65@78d07aea.__eContents := 
.obj65@78d07aea.__eContainer := /value.obj66@78d07aea
.obj65@78d07aea.value := stm32f7_discovery_sd.h

# .obj64@78d07aea
.obj64@78d07aea := ELink
.obj64@78d07aea.eSource := MyFile_OptionBinding_option.obj66@78d07aea
.obj64@78d07aea.eTarget := 
.obj64@78d07aea.name := target_name
.obj64@78d07aea.origin := 35:17

# .obj63@78d07aea
.obj63@78d07aea := ELink
.obj63@78d07aea.eSource := MyFile_Annotation_type.obj67@78d07aea
.obj63@78d07aea.eTarget := 
.obj63@78d07aea.name := IncludeExport
.obj63@78d07aea.origin := 35:3

# .obj71@78d07aea
.obj71@78d07aea := MySourceMember
.obj71@78d07aea.__eContents := \
	files/.obj70@78d07aea
.obj71@78d07aea.__eContainer := /sourcesMembers.obj76@78d07aea
.obj71@78d07aea.module := 

# .obj70@78d07aea
.obj70@78d07aea := MyFileName
.obj70@78d07aea.__eContents := 
.obj70@78d07aea.__eContainer := /files.obj71@78d07aea
.obj70@78d07aea.fileName := stm32f7_sd.c

# .obj59@78d07aea
.obj59@78d07aea := MyOptionMember
.obj59@78d07aea.__eContents := \
	options/.obj57@78d07aea
.obj59@78d07aea.__eContainer := /optionsMembers.obj76@78d07aea
.obj59@78d07aea.module := 

# .obj57@78d07aea
.obj57@78d07aea := MyBooleanOption
.obj57@78d07aea.__eContents := \
	defaultValue/.obj58@78d07aea
.obj57@78d07aea.__eContainer := /options.obj59@78d07aea
.obj57@78d07aea.name := use_local_buf
.obj57@78d07aea.origin := 

# .obj58@78d07aea
.obj58@78d07aea := MyBooleanLiteral
.obj58@78d07aea.__eContents := 
.obj58@78d07aea.__eContainer := /defaultValue.obj57@78d07aea
.obj58@78d07aea.isValue := 1

# .obj62@78d07aea
.obj62@78d07aea := MyOptionMember
.obj62@78d07aea.__eContents := \
	options/.obj60@78d07aea
.obj62@78d07aea.__eContainer := /optionsMembers.obj76@78d07aea
.obj62@78d07aea.module := 

# .obj60@78d07aea
.obj60@78d07aea := MyNumberOption
.obj60@78d07aea.__eContents := \
	defaultValue/.obj61@78d07aea
.obj60@78d07aea.__eContainer := /options.obj62@78d07aea
.obj60@78d07aea.name := sd_buf_size
.obj60@78d07aea.origin := 

# .obj61@78d07aea
.obj61@78d07aea := MyNumberLiteral
.obj61@78d07aea.__eContents := 
.obj61@78d07aea.__eContainer := /defaultValue.obj60@78d07aea
.obj61@78d07aea.value := 4096

# .obj73@78d07aea
.obj73@78d07aea := MyDependsMember
.obj73@78d07aea.__eContents := 
.obj73@78d07aea.__eContainer := /dependsMembers.obj76@78d07aea
.obj73@78d07aea.modules := \
	.obj72@78d07aea./
.obj73@78d07aea.module := 

# .obj72@78d07aea
.obj72@78d07aea := ELink
.obj72@78d07aea.eSource := MyFile_DependsMember_modules.obj73@78d07aea
.obj72@78d07aea.eTarget := 
.obj72@78d07aea.name := embox.driver.block_dev
.obj72@78d07aea.origin := 40:10

# .obj75@78d07aea
.obj75@78d07aea := MyDependsMember
.obj75@78d07aea.__eContents := 
.obj75@78d07aea.__eContainer := /dependsMembers.obj76@78d07aea
.obj75@78d07aea.modules := \
	.obj74@78d07aea./
.obj75@78d07aea.module := 

# .obj74@78d07aea
.obj74@78d07aea := ELink
.obj74@78d07aea.eSource := MyFile_DependsMember_modules.obj75@78d07aea
.obj74@78d07aea.eTarget := 
.obj74@78d07aea.name := third_party.bsp.st_bsp_api
.obj74@78d07aea.origin := 41:10

# .obj55@78d07aea
.obj55@78d07aea := MyAnnotation
.obj55@78d07aea.__eContents := \
	bindings/.obj53@78d07aea
.obj55@78d07aea.__eContainer := target/annotations.obj76@78d07aea
.obj55@78d07aea.type := .obj50@78d07aea./

# .obj53@78d07aea
.obj53@78d07aea := MyOptionBinding
.obj53@78d07aea.__eContents := \
	value/.obj52@78d07aea
.obj53@78d07aea.__eContainer := /bindings.obj55@78d07aea
.obj53@78d07aea.option := .obj54@78d07aea./

# .obj52@78d07aea
.obj52@78d07aea := MyTypeReferenceLiteral
.obj52@78d07aea.__eContents := 
.obj52@78d07aea.__eContainer := /value.obj53@78d07aea
.obj52@78d07aea.value := .obj51@78d07aea./

# .obj51@78d07aea
.obj51@78d07aea := ELink
.obj51@78d07aea.eSource := MyFile_TypeReferenceLiteral_value.obj52@78d07aea
.obj51@78d07aea.eTarget := 
.obj51@78d07aea.name := third_party.bsp.st_bsp_api
.obj51@78d07aea.origin := 30:15

# .obj54@78d07aea
.obj54@78d07aea := ELink
.obj54@78d07aea.eSource := MyFile_OptionBinding_option.obj53@78d07aea
.obj54@78d07aea.eTarget := 
.obj54@78d07aea.name := value
.obj54@78d07aea.origin := 30:14

# .obj50@78d07aea
.obj50@78d07aea := ELink
.obj50@78d07aea.eSource := MyFile_Annotation_type.obj55@78d07aea
.obj50@78d07aea.eTarget := 
.obj50@78d07aea.name := BuildDepends
.obj50@78d07aea.origin := 30:2

# .obj56@78d07aea
.obj56@78d07aea := ELink
.obj56@78d07aea.eSource := MyFile_ModuleType_superType.obj76@78d07aea
.obj56@78d07aea.eTarget := 
.obj56@78d07aea.name := sd
.obj56@78d07aea.origin := 31:40


__resource-mk/.cache/mybuild/files/src/drivers/block_dev/stm32_sd/Mybuild.mk := .obj1@78d07aea
