# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@eb6dde0c

# .obj1@eb6dde0c
.obj1@eb6dde0c := MyFileResource
.obj1@eb6dde0c.issues := 
.obj1@eb6dde0c.contentsRoot := .obj28@eb6dde0c
.obj1@eb6dde0c.resourceSet := 
.obj1@eb6dde0c.fileName := src/drivers/input/Mybuild
.obj1@eb6dde0c.exports := \
	embox.driver.input \
	embox.driver.input.core \
	embox.driver.input.core.hnd_priority
.obj1@eb6dde0c.exports.embox.driver.input := \
	.obj28@eb6dde0c
.obj1@eb6dde0c.exports.embox.driver.input.core := \
	.obj27@eb6dde0c
.obj1@eb6dde0c.exports.embox.driver.input.core.hnd_priority := \
	.obj2@eb6dde0c

# .obj28@eb6dde0c
.obj28@eb6dde0c := MyFileContentRoot
.obj28@eb6dde0c.__eContents := \
	types/.obj27@eb6dde0c
.obj28@eb6dde0c.__eContainer := .obj1@eb6dde0c
.obj28@eb6dde0c.imports := 
.obj28@eb6dde0c.name := embox.driver.input
.obj28@eb6dde0c.origin := 

# .obj27@eb6dde0c
.obj27@eb6dde0c := MyModuleType
.obj27@eb6dde0c.__eContents := \
	sourcesMembers/.obj6@eb6dde0c \
	sourcesMembers/.obj13@eb6dde0c \
	sourcesMembers/.obj20@eb6dde0c \
	optionsMembers/.obj4@eb6dde0c \
	dependsMembers/.obj22@eb6dde0c \
	dependsMembers/.obj24@eb6dde0c \
	dependsMembers/.obj26@eb6dde0c
.obj27@eb6dde0c.__eContainer := fileContentRoot/types.obj28@eb6dde0c
.obj27@eb6dde0c.dependent := 
.obj27@eb6dde0c.subTypes := 
.obj27@eb6dde0c.modifiers := 
.obj27@eb6dde0c.name := core
.obj27@eb6dde0c.origin := 3:8
.obj27@eb6dde0c.superType := 
.obj27@eb6dde0c.customStorage := 

# .obj6@eb6dde0c
.obj6@eb6dde0c := MySourceMember
.obj6@eb6dde0c.__eContents := \
	files/.obj5@eb6dde0c
.obj6@eb6dde0c.__eContainer := /sourcesMembers.obj27@eb6dde0c
.obj6@eb6dde0c.module := 

# .obj5@eb6dde0c
.obj5@eb6dde0c := MyFileName
.obj5@eb6dde0c.__eContents := 
.obj5@eb6dde0c.__eContainer := /files.obj6@eb6dde0c
.obj5@eb6dde0c.fileName := core.c

# .obj13@eb6dde0c
.obj13@eb6dde0c := MySourceMember
.obj13@eb6dde0c.__eContents := \
	files/.obj12@eb6dde0c \
	annotations/.obj11@eb6dde0c
.obj13@eb6dde0c.__eContainer := /sourcesMembers.obj27@eb6dde0c
.obj13@eb6dde0c.module := 

# .obj12@eb6dde0c
.obj12@eb6dde0c := MyFileName
.obj12@eb6dde0c.__eContents := 
.obj12@eb6dde0c.__eContainer := /files.obj13@eb6dde0c
.obj12@eb6dde0c.fileName := input_dev.h

# .obj11@eb6dde0c
.obj11@eb6dde0c := MyAnnotation
.obj11@eb6dde0c.__eContents := \
	bindings/.obj10@eb6dde0c
.obj11@eb6dde0c.__eContainer := target/annotations.obj13@eb6dde0c
.obj11@eb6dde0c.type := .obj7@eb6dde0c./

# .obj10@eb6dde0c
.obj10@eb6dde0c := MyOptionBinding
.obj10@eb6dde0c.__eContents := \
	value/.obj9@eb6dde0c
.obj10@eb6dde0c.__eContainer := /bindings.obj11@eb6dde0c
.obj10@eb6dde0c.option := .obj8@eb6dde0c./

# .obj9@eb6dde0c
.obj9@eb6dde0c := MyStringLiteral
.obj9@eb6dde0c.__eContents := 
.obj9@eb6dde0c.__eContainer := /value.obj10@eb6dde0c
.obj9@eb6dde0c.value := drivers/input

# .obj8@eb6dde0c
.obj8@eb6dde0c := ELink
.obj8@eb6dde0c.eSource := MyFile_OptionBinding_option.obj10@eb6dde0c
.obj8@eb6dde0c.eTarget := 
.obj8@eb6dde0c.name := path
.obj8@eb6dde0c.origin := 7:17

# .obj7@eb6dde0c
.obj7@eb6dde0c := ELink
.obj7@eb6dde0c.eSource := MyFile_Annotation_type.obj11@eb6dde0c
.obj7@eb6dde0c.eTarget := 
.obj7@eb6dde0c.name := IncludeExport
.obj7@eb6dde0c.origin := 7:3

# .obj20@eb6dde0c
.obj20@eb6dde0c := MySourceMember
.obj20@eb6dde0c.__eContents := \
	files/.obj19@eb6dde0c \
	annotations/.obj18@eb6dde0c
.obj20@eb6dde0c.__eContainer := /sourcesMembers.obj27@eb6dde0c
.obj20@eb6dde0c.module := 

# .obj19@eb6dde0c
.obj19@eb6dde0c := MyFileName
.obj19@eb6dde0c.__eContents := 
.obj19@eb6dde0c.__eContainer := /files.obj20@eb6dde0c
.obj19@eb6dde0c.fileName := keymap.h

# .obj18@eb6dde0c
.obj18@eb6dde0c := MyAnnotation
.obj18@eb6dde0c.__eContents := \
	bindings/.obj17@eb6dde0c
.obj18@eb6dde0c.__eContainer := target/annotations.obj20@eb6dde0c
.obj18@eb6dde0c.type := .obj14@eb6dde0c./

# .obj17@eb6dde0c
.obj17@eb6dde0c := MyOptionBinding
.obj17@eb6dde0c.__eContents := \
	value/.obj16@eb6dde0c
.obj17@eb6dde0c.__eContainer := /bindings.obj18@eb6dde0c
.obj17@eb6dde0c.option := .obj15@eb6dde0c./

# .obj16@eb6dde0c
.obj16@eb6dde0c := MyStringLiteral
.obj16@eb6dde0c.__eContents := 
.obj16@eb6dde0c.__eContainer := /value.obj17@eb6dde0c
.obj16@eb6dde0c.value := drivers/input

# .obj15@eb6dde0c
.obj15@eb6dde0c := ELink
.obj15@eb6dde0c.eSource := MyFile_OptionBinding_option.obj17@eb6dde0c
.obj15@eb6dde0c.eTarget := 
.obj15@eb6dde0c.name := path
.obj15@eb6dde0c.origin := 9:17

# .obj14@eb6dde0c
.obj14@eb6dde0c := ELink
.obj14@eb6dde0c.eSource := MyFile_Annotation_type.obj18@eb6dde0c
.obj14@eb6dde0c.eTarget := 
.obj14@eb6dde0c.name := IncludeExport
.obj14@eb6dde0c.origin := 9:3

# .obj4@eb6dde0c
.obj4@eb6dde0c := MyOptionMember
.obj4@eb6dde0c.__eContents := \
	options/.obj2@eb6dde0c
.obj4@eb6dde0c.__eContainer := /optionsMembers.obj27@eb6dde0c
.obj4@eb6dde0c.module := 

# .obj2@eb6dde0c
.obj2@eb6dde0c := MyNumberOption
.obj2@eb6dde0c.__eContents := \
	defaultValue/.obj3@eb6dde0c
.obj2@eb6dde0c.__eContainer := /options.obj4@eb6dde0c
.obj2@eb6dde0c.name := hnd_priority
.obj2@eb6dde0c.origin := 

# .obj3@eb6dde0c
.obj3@eb6dde0c := MyNumberLiteral
.obj3@eb6dde0c.__eContents := 
.obj3@eb6dde0c.__eContainer := /defaultValue.obj2@eb6dde0c
.obj3@eb6dde0c.value := 200

# .obj22@eb6dde0c
.obj22@eb6dde0c := MyDependsMember
.obj22@eb6dde0c.__eContents := 
.obj22@eb6dde0c.__eContainer := /dependsMembers.obj27@eb6dde0c
.obj22@eb6dde0c.modules := \
	.obj21@eb6dde0c./
.obj22@eb6dde0c.module := 

# .obj21@eb6dde0c
.obj21@eb6dde0c := ELink
.obj21@eb6dde0c.eSource := MyFile_DependsMember_modules.obj22@eb6dde0c
.obj21@eb6dde0c.eTarget := 
.obj21@eb6dde0c.name := embox.kernel.irq
.obj21@eb6dde0c.origin := 12:10

# .obj24@eb6dde0c
.obj24@eb6dde0c := MyDependsMember
.obj24@eb6dde0c.__eContents := 
.obj24@eb6dde0c.__eContainer := /dependsMembers.obj27@eb6dde0c
.obj24@eb6dde0c.modules := \
	.obj23@eb6dde0c./
.obj24@eb6dde0c.module := 

# .obj23@eb6dde0c
.obj23@eb6dde0c := ELink
.obj23@eb6dde0c.eSource := MyFile_DependsMember_modules.obj24@eb6dde0c
.obj23@eb6dde0c.eTarget := 
.obj23@eb6dde0c.name := embox.util.dlist
.obj23@eb6dde0c.origin := 13:10

# .obj26@eb6dde0c
.obj26@eb6dde0c := MyDependsMember
.obj26@eb6dde0c.__eContents := 
.obj26@eb6dde0c.__eContainer := /dependsMembers.obj27@eb6dde0c
.obj26@eb6dde0c.modules := \
	.obj25@eb6dde0c./
.obj26@eb6dde0c.module := 

# .obj25@eb6dde0c
.obj25@eb6dde0c := ELink
.obj25@eb6dde0c.eSource := MyFile_DependsMember_modules.obj26@eb6dde0c
.obj25@eb6dde0c.eTarget := 
.obj25@eb6dde0c.name := embox.kernel.lthread.lthread
.obj25@eb6dde0c.origin := 14:10


__resource-mk/.cache/mybuild/files/src/drivers/input/Mybuild.mk := .obj1@eb6dde0c
