# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@dd12d99c

# .obj1@dd12d99c
.obj1@dd12d99c := MyFileResource
.obj1@dd12d99c.issues := 
.obj1@dd12d99c.contentsRoot := .obj22@dd12d99c
.obj1@dd12d99c.resourceSet := 
.obj1@dd12d99c.fileName := src/compat/posix/stubs/Mybuild
.obj1@dd12d99c.exports := \
	embox.compat.posix \
	embox.compat.posix.stubs
.obj1@dd12d99c.exports.embox.compat.posix := \
	.obj22@dd12d99c
.obj1@dd12d99c.exports.embox.compat.posix.stubs := \
	.obj21@dd12d99c

# .obj22@dd12d99c
.obj22@dd12d99c := MyFileContentRoot
.obj22@dd12d99c.__eContents := \
	types/.obj21@dd12d99c
.obj22@dd12d99c.__eContainer := .obj1@dd12d99c
.obj22@dd12d99c.imports := 
.obj22@dd12d99c.name := embox.compat.posix
.obj22@dd12d99c.origin := 

# .obj21@dd12d99c
.obj21@dd12d99c := MyModuleType
.obj21@dd12d99c.__eContents := \
	sourcesMembers/.obj20@dd12d99c
.obj21@dd12d99c.__eContainer := fileContentRoot/types.obj22@dd12d99c
.obj21@dd12d99c.dependent := 
.obj21@dd12d99c.subTypes := 
.obj21@dd12d99c.modifiers := static
.obj21@dd12d99c.name := stubs
.obj21@dd12d99c.origin := 3:15
.obj21@dd12d99c.superType := 
.obj21@dd12d99c.customStorage := 

# .obj20@dd12d99c
.obj20@dd12d99c := MySourceMember
.obj20@dd12d99c.__eContents := \
	files/.obj2@dd12d99c \
	files/.obj3@dd12d99c \
	files/.obj4@dd12d99c \
	files/.obj5@dd12d99c \
	files/.obj6@dd12d99c \
	files/.obj7@dd12d99c \
	files/.obj8@dd12d99c \
	files/.obj9@dd12d99c \
	files/.obj10@dd12d99c \
	files/.obj11@dd12d99c \
	files/.obj12@dd12d99c \
	files/.obj13@dd12d99c \
	files/.obj14@dd12d99c \
	files/.obj15@dd12d99c \
	files/.obj16@dd12d99c \
	files/.obj17@dd12d99c \
	files/.obj18@dd12d99c \
	files/.obj19@dd12d99c
.obj20@dd12d99c.__eContainer := /sourcesMembers.obj21@dd12d99c
.obj20@dd12d99c.module := 

# .obj2@dd12d99c
.obj2@dd12d99c := MyFileName
.obj2@dd12d99c.__eContents := 
.obj2@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj2@dd12d99c.fileName := daemon.c

# .obj3@dd12d99c
.obj3@dd12d99c := MyFileName
.obj3@dd12d99c.__eContents := 
.obj3@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj3@dd12d99c.fileName := dlfcn.c

# .obj4@dd12d99c
.obj4@dd12d99c := MyFileName
.obj4@dd12d99c.__eContents := 
.obj4@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj4@dd12d99c.fileName := execl.c

# .obj5@dd12d99c
.obj5@dd12d99c := MyFileName
.obj5@dd12d99c.__eContents := 
.obj5@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj5@dd12d99c.fileName := execlp.c

# .obj6@dd12d99c
.obj6@dd12d99c := MyFileName
.obj6@dd12d99c.__eContents := 
.obj6@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj6@dd12d99c.fileName := execvp.c

# .obj7@dd12d99c
.obj7@dd12d99c := MyFileName
.obj7@dd12d99c.__eContents := 
.obj7@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj7@dd12d99c.fileName := flockfile.c

# .obj8@dd12d99c
.obj8@dd12d99c := MyFileName
.obj8@dd12d99c.__eContents := 
.obj8@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj8@dd12d99c.fileName := ftrylockfile.c

# .obj9@dd12d99c
.obj9@dd12d99c := MyFileName
.obj9@dd12d99c.__eContents := 
.obj9@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj9@dd12d99c.fileName := funlockfile.c

# .obj10@dd12d99c
.obj10@dd12d99c := MyFileName
.obj10@dd12d99c.__eContents := 
.obj10@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj10@dd12d99c.fileName := getdtablesize.c

# .obj11@dd12d99c
.obj11@dd12d99c := MyFileName
.obj11@dd12d99c.__eContents := 
.obj11@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj11@dd12d99c.fileName := getgroups.c

# .obj12@dd12d99c
.obj12@dd12d99c := MyFileName
.obj12@dd12d99c.__eContents := 
.obj12@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj12@dd12d99c.fileName := getppid.c

# .obj13@dd12d99c
.obj13@dd12d99c := MyFileName
.obj13@dd12d99c.__eContents := 
.obj13@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj13@dd12d99c.fileName := getpgrp.c

# .obj14@dd12d99c
.obj14@dd12d99c := MyFileName
.obj14@dd12d99c.__eContents := 
.obj14@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj14@dd12d99c.fileName := link.c

# .obj15@dd12d99c
.obj15@dd12d99c := MyFileName
.obj15@dd12d99c.__eContents := 
.obj15@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj15@dd12d99c.fileName := mman.c

# .obj16@dd12d99c
.obj16@dd12d99c := MyFileName
.obj16@dd12d99c.__eContents := 
.obj16@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj16@dd12d99c.fileName := readlinkat.c

# .obj17@dd12d99c
.obj17@dd12d99c := MyFileName
.obj17@dd12d99c.__eContents := 
.obj17@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj17@dd12d99c.fileName := readlink.c

# .obj18@dd12d99c
.obj18@dd12d99c := MyFileName
.obj18@dd12d99c.__eContents := 
.obj18@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj18@dd12d99c.fileName := setpgid.c

# .obj19@dd12d99c
.obj19@dd12d99c := MyFileName
.obj19@dd12d99c.__eContents := 
.obj19@dd12d99c.__eContainer := /files.obj20@dd12d99c
.obj19@dd12d99c.fileName := sigsuspend.c


__resource-mk/.cache/mybuild/files/src/compat/posix/stubs/Mybuild.mk := .obj1@dd12d99c
