# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@051f909b

# .obj1@051f909b
.obj1@051f909b := MyFileResource
.obj1@051f909b.issues := 
.obj1@051f909b.contentsRoot := .obj105@051f909b
.obj1@051f909b.resourceSet := 
.obj1@051f909b.fileName := src/kernel/task/Mybuild
.obj1@051f909b.exports := \
	embox.kernel.task \
	embox.kernel.task.api \
	embox.kernel.task.task_table_api \
	embox.kernel.task.kernel_task \
	embox.kernel.task.multi \
	embox.kernel.task.single \
	embox.kernel.task.task_no_table \
	embox.kernel.task.task_resource \
	embox.kernel.task.task_table \
	embox.kernel.task.task_table.task_table_size
.obj1@051f909b.exports.embox.kernel.task := \
	.obj105@051f909b
.obj1@051f909b.exports.embox.kernel.task.api := \
	.obj8@051f909b
.obj1@051f909b.exports.embox.kernel.task.task_table_api := \
	.obj15@051f909b
.obj1@051f909b.exports.embox.kernel.task.kernel_task := \
	.obj26@051f909b
.obj1@051f909b.exports.embox.kernel.task.multi := \
	.obj51@051f909b
.obj1@051f909b.exports.embox.kernel.task.single := \
	.obj69@051f909b
.obj1@051f909b.exports.embox.kernel.task.task_no_table := \
	.obj81@051f909b
.obj1@051f909b.exports.embox.kernel.task.task_resource := \
	.obj93@051f909b
.obj1@051f909b.exports.embox.kernel.task.task_table := \
	.obj104@051f909b
.obj1@051f909b.exports.embox.kernel.task.task_table.task_table_size := \
	.obj95@051f909b

# .obj105@051f909b
.obj105@051f909b := MyFileContentRoot
.obj105@051f909b.__eContents := \
	types/.obj8@051f909b \
	types/.obj15@051f909b \
	types/.obj26@051f909b \
	types/.obj51@051f909b \
	types/.obj69@051f909b \
	types/.obj81@051f909b \
	types/.obj93@051f909b \
	types/.obj104@051f909b
.obj105@051f909b.__eContainer := .obj1@051f909b
.obj105@051f909b.imports := 
.obj105@051f909b.name := embox.kernel.task
.obj105@051f909b.origin := 

# .obj8@051f909b
.obj8@051f909b := MyModuleType
.obj8@051f909b.__eContents := \
	annotations/.obj7@051f909b
.obj8@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj8@051f909b.dependent := 
.obj8@051f909b.subTypes := 
.obj8@051f909b.modifiers := abstract
.obj8@051f909b.name := api
.obj8@051f909b.origin := 4:17
.obj8@051f909b.superType := 
.obj8@051f909b.customStorage := 

# .obj7@051f909b
.obj7@051f909b := MyAnnotation
.obj7@051f909b.__eContents := \
	bindings/.obj5@051f909b
.obj7@051f909b.__eContainer := target/annotations.obj8@051f909b
.obj7@051f909b.type := .obj2@051f909b./

# .obj5@051f909b
.obj5@051f909b := MyOptionBinding
.obj5@051f909b.__eContents := \
	value/.obj4@051f909b
.obj5@051f909b.__eContainer := /bindings.obj7@051f909b
.obj5@051f909b.option := .obj6@051f909b./

# .obj4@051f909b
.obj4@051f909b := MyTypeReferenceLiteral
.obj4@051f909b.__eContents := 
.obj4@051f909b.__eContainer := /value.obj5@051f909b
.obj4@051f909b.value := .obj3@051f909b./

# .obj3@051f909b
.obj3@051f909b := ELink
.obj3@051f909b.eSource := MyFile_TypeReferenceLiteral_value.obj4@051f909b
.obj3@051f909b.eTarget := 
.obj3@051f909b.name := single
.obj3@051f909b.origin := 3:14

# .obj6@051f909b
.obj6@051f909b := ELink
.obj6@051f909b.eSource := MyFile_OptionBinding_option.obj5@051f909b
.obj6@051f909b.eTarget := 
.obj6@051f909b.name := value
.obj6@051f909b.origin := 3:13

# .obj2@051f909b
.obj2@051f909b := ELink
.obj2@051f909b.eSource := MyFile_Annotation_type.obj7@051f909b
.obj2@051f909b.eTarget := 
.obj2@051f909b.name := DefaultImpl
.obj2@051f909b.origin := 3:2

# .obj15@051f909b
.obj15@051f909b := MyModuleType
.obj15@051f909b.__eContents := \
	annotations/.obj14@051f909b
.obj15@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj15@051f909b.dependent := 
.obj15@051f909b.subTypes := 
.obj15@051f909b.modifiers := abstract
.obj15@051f909b.name := task_table_api
.obj15@051f909b.origin := 8:17
.obj15@051f909b.superType := 
.obj15@051f909b.customStorage := 

# .obj14@051f909b
.obj14@051f909b := MyAnnotation
.obj14@051f909b.__eContents := \
	bindings/.obj12@051f909b
.obj14@051f909b.__eContainer := target/annotations.obj15@051f909b
.obj14@051f909b.type := .obj9@051f909b./

# .obj12@051f909b
.obj12@051f909b := MyOptionBinding
.obj12@051f909b.__eContents := \
	value/.obj11@051f909b
.obj12@051f909b.__eContainer := /bindings.obj14@051f909b
.obj12@051f909b.option := .obj13@051f909b./

# .obj11@051f909b
.obj11@051f909b := MyTypeReferenceLiteral
.obj11@051f909b.__eContents := 
.obj11@051f909b.__eContainer := /value.obj12@051f909b
.obj11@051f909b.value := .obj10@051f909b./

# .obj10@051f909b
.obj10@051f909b := ELink
.obj10@051f909b.eSource := MyFile_TypeReferenceLiteral_value.obj11@051f909b
.obj10@051f909b.eTarget := 
.obj10@051f909b.name := task_no_table
.obj10@051f909b.origin := 7:14

# .obj13@051f909b
.obj13@051f909b := ELink
.obj13@051f909b.eSource := MyFile_OptionBinding_option.obj12@051f909b
.obj13@051f909b.eTarget := 
.obj13@051f909b.name := value
.obj13@051f909b.origin := 7:13

# .obj9@051f909b
.obj9@051f909b := ELink
.obj9@051f909b.eSource := MyFile_Annotation_type.obj14@051f909b
.obj9@051f909b.eTarget := 
.obj9@051f909b.name := DefaultImpl
.obj9@051f909b.origin := 7:2

# .obj26@051f909b
.obj26@051f909b := MyModuleType
.obj26@051f909b.__eContents := \
	sourcesMembers/.obj17@051f909b \
	dependsMembers/.obj21@051f909b \
	dependsMembers/.obj23@051f909b \
	dependsMembers/.obj25@051f909b
.obj26@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj26@051f909b.dependent := 
.obj26@051f909b.subTypes := 
.obj26@051f909b.modifiers := 
.obj26@051f909b.name := kernel_task
.obj26@051f909b.origin := 11:8
.obj26@051f909b.superType := 
.obj26@051f909b.customStorage := 

# .obj17@051f909b
.obj17@051f909b := MySourceMember
.obj17@051f909b.__eContents := \
	files/.obj16@051f909b
.obj17@051f909b.__eContainer := /sourcesMembers.obj26@051f909b
.obj17@051f909b.module := 

# .obj16@051f909b
.obj16@051f909b := MyFileName
.obj16@051f909b.__eContents := 
.obj16@051f909b.__eContainer := /files.obj17@051f909b
.obj16@051f909b.fileName := kernel_task.c

# .obj21@051f909b
.obj21@051f909b := MyDependsMember
.obj21@051f909b.__eContents := \
	annotations/.obj19@051f909b
.obj21@051f909b.__eContainer := /dependsMembers.obj26@051f909b
.obj21@051f909b.modules := \
	.obj20@051f909b./
.obj21@051f909b.module := 

# .obj19@051f909b
.obj19@051f909b := MyAnnotation
.obj19@051f909b.__eContents := 
.obj19@051f909b.__eContainer := target/annotations.obj21@051f909b
.obj19@051f909b.type := .obj18@051f909b./

# .obj18@051f909b
.obj18@051f909b := ELink
.obj18@051f909b.eSource := MyFile_Annotation_type.obj19@051f909b
.obj18@051f909b.eTarget := 
.obj18@051f909b.name := NoRuntime
.obj18@051f909b.origin := 14:3

# .obj20@051f909b
.obj20@051f909b := ELink
.obj20@051f909b.eSource := MyFile_DependsMember_modules.obj21@051f909b
.obj20@051f909b.eTarget := 
.obj20@051f909b.name := embox.kernel.task.api
.obj20@051f909b.origin := 14:21

# .obj23@051f909b
.obj23@051f909b := MyDependsMember
.obj23@051f909b.__eContents := 
.obj23@051f909b.__eContainer := /dependsMembers.obj26@051f909b
.obj23@051f909b.modules := \
	.obj22@051f909b./
.obj23@051f909b.module := 

# .obj22@051f909b
.obj22@051f909b := ELink
.obj22@051f909b.eSource := MyFile_DependsMember_modules.obj23@051f909b
.obj22@051f909b.eTarget := 
.obj22@051f909b.name := embox.kernel.task.task_resource
.obj22@051f909b.origin := 15:10

# .obj25@051f909b
.obj25@051f909b := MyDependsMember
.obj25@051f909b.__eContents := 
.obj25@051f909b.__eContainer := /dependsMembers.obj26@051f909b
.obj25@051f909b.modules := \
	.obj24@051f909b./
.obj25@051f909b.module := 

# .obj24@051f909b
.obj24@051f909b := ELink
.obj24@051f909b.eSource := MyFile_DependsMember_modules.obj25@051f909b
.obj24@051f909b.eTarget := 
.obj24@051f909b.name := embox.kernel.task.task_table_api
.obj24@051f909b.origin := 16:10

# .obj51@051f909b
.obj51@051f909b := MyModuleType
.obj51@051f909b.__eContents := \
	sourcesMembers/.obj30@051f909b \
	dependsMembers/.obj32@051f909b \
	dependsMembers/.obj34@051f909b \
	dependsMembers/.obj36@051f909b \
	dependsMembers/.obj38@051f909b \
	dependsMembers/.obj40@051f909b \
	dependsMembers/.obj42@051f909b \
	dependsMembers/.obj46@051f909b \
	dependsMembers/.obj50@051f909b
.obj51@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj51@051f909b.dependent := 
.obj51@051f909b.subTypes := 
.obj51@051f909b.modifiers := 
.obj51@051f909b.name := multi
.obj51@051f909b.origin := 19:8
.obj51@051f909b.superType := .obj27@051f909b./
.obj51@051f909b.customStorage := 

# .obj30@051f909b
.obj30@051f909b := MySourceMember
.obj30@051f909b.__eContents := \
	files/.obj28@051f909b \
	files/.obj29@051f909b
.obj30@051f909b.__eContainer := /sourcesMembers.obj51@051f909b
.obj30@051f909b.module := 

# .obj28@051f909b
.obj28@051f909b := MyFileName
.obj28@051f909b.__eContents := 
.obj28@051f909b.__eContainer := /files.obj30@051f909b
.obj28@051f909b.fileName := multi.c

# .obj29@051f909b
.obj29@051f909b := MyFileName
.obj29@051f909b.__eContents := 
.obj29@051f909b.__eContainer := /files.obj30@051f909b
.obj29@051f909b.fileName := multi.h

# .obj32@051f909b
.obj32@051f909b := MyDependsMember
.obj32@051f909b.__eContents := 
.obj32@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj32@051f909b.modules := \
	.obj31@051f909b./
.obj32@051f909b.module := 

# .obj31@051f909b
.obj31@051f909b := ELink
.obj31@051f909b.eSource := MyFile_DependsMember_modules.obj32@051f909b
.obj31@051f909b.eTarget := 
.obj31@051f909b.name := embox.kernel.task.kernel_task
.obj31@051f909b.origin := 22:10

# .obj34@051f909b
.obj34@051f909b := MyDependsMember
.obj34@051f909b.__eContents := 
.obj34@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj34@051f909b.modules := \
	.obj33@051f909b./
.obj34@051f909b.module := 

# .obj33@051f909b
.obj33@051f909b := ELink
.obj33@051f909b.eSource := MyFile_DependsMember_modules.obj34@051f909b
.obj33@051f909b.eTarget := 
.obj33@051f909b.name := embox.kernel.task.task_resource
.obj33@051f909b.origin := 23:10

# .obj36@051f909b
.obj36@051f909b := MyDependsMember
.obj36@051f909b.__eContents := 
.obj36@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj36@051f909b.modules := \
	.obj35@051f909b./
.obj36@051f909b.module := 

# .obj35@051f909b
.obj35@051f909b := ELink
.obj35@051f909b.eSource := MyFile_DependsMember_modules.obj36@051f909b
.obj35@051f909b.eTarget := 
.obj35@051f909b.name := embox.kernel.task.task_table
.obj35@051f909b.origin := 24:10

# .obj38@051f909b
.obj38@051f909b := MyDependsMember
.obj38@051f909b.__eContents := 
.obj38@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj38@051f909b.modules := \
	.obj37@051f909b./
.obj38@051f909b.module := 

# .obj37@051f909b
.obj37@051f909b := ELink
.obj37@051f909b.eSource := MyFile_DependsMember_modules.obj38@051f909b
.obj37@051f909b.eTarget := 
.obj37@051f909b.name := embox.compat.posix.proc.vfork
.obj37@051f909b.origin := 26:10

# .obj40@051f909b
.obj40@051f909b := MyDependsMember
.obj40@051f909b.__eContents := 
.obj40@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj40@051f909b.modules := \
	.obj39@051f909b./
.obj40@051f909b.module := 

# .obj39@051f909b
.obj39@051f909b := ELink
.obj39@051f909b.eSource := MyFile_DependsMember_modules.obj40@051f909b
.obj39@051f909b.eTarget := 
.obj39@051f909b.name := embox.kernel.thread.core
.obj39@051f909b.origin := 28:10

# .obj42@051f909b
.obj42@051f909b := MyDependsMember
.obj42@051f909b.__eContents := 
.obj42@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj42@051f909b.modules := \
	.obj41@051f909b./
.obj42@051f909b.module := 

# .obj41@051f909b
.obj41@051f909b := ELink
.obj41@051f909b.eSource := MyFile_DependsMember_modules.obj42@051f909b
.obj41@051f909b.eTarget := 
.obj41@051f909b.name := embox.kernel.sched.sched
.obj41@051f909b.origin := 29:10

# .obj46@051f909b
.obj46@051f909b := MyDependsMember
.obj46@051f909b.__eContents := \
	annotations/.obj44@051f909b
.obj46@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj46@051f909b.modules := \
	.obj45@051f909b./
.obj46@051f909b.module := 

# .obj44@051f909b
.obj44@051f909b := MyAnnotation
.obj44@051f909b.__eContents := 
.obj44@051f909b.__eContainer := target/annotations.obj46@051f909b
.obj44@051f909b.type := .obj43@051f909b./

# .obj43@051f909b
.obj43@051f909b := ELink
.obj43@051f909b.eSource := MyFile_Annotation_type.obj44@051f909b
.obj43@051f909b.eTarget := 
.obj43@051f909b.name := NoRuntime
.obj43@051f909b.origin := 36:3

# .obj45@051f909b
.obj45@051f909b := ELink
.obj45@051f909b.eSource := MyFile_DependsMember_modules.obj46@051f909b
.obj45@051f909b.eTarget := 
.obj45@051f909b.name := embox.compat.libc.assert
.obj45@051f909b.origin := 36:21

# .obj50@051f909b
.obj50@051f909b := MyDependsMember
.obj50@051f909b.__eContents := \
	annotations/.obj48@051f909b
.obj50@051f909b.__eContainer := /dependsMembers.obj51@051f909b
.obj50@051f909b.modules := \
	.obj49@051f909b./
.obj50@051f909b.module := 

# .obj48@051f909b
.obj48@051f909b := MyAnnotation
.obj48@051f909b.__eContents := 
.obj48@051f909b.__eContainer := target/annotations.obj50@051f909b
.obj48@051f909b.type := .obj47@051f909b./

# .obj47@051f909b
.obj47@051f909b := ELink
.obj47@051f909b.eSource := MyFile_Annotation_type.obj48@051f909b
.obj47@051f909b.eTarget := 
.obj47@051f909b.name := NoRuntime
.obj47@051f909b.origin := 37:3

# .obj49@051f909b
.obj49@051f909b := ELink
.obj49@051f909b.eSource := MyFile_DependsMember_modules.obj50@051f909b
.obj49@051f909b.eTarget := 
.obj49@051f909b.name := embox.compat.libc.str
.obj49@051f909b.origin := 37:21

# .obj27@051f909b
.obj27@051f909b := ELink
.obj27@051f909b.eSource := MyFile_ModuleType_superType.obj51@051f909b
.obj27@051f909b.eTarget := 
.obj27@051f909b.name := api
.obj27@051f909b.origin := 19:22

# .obj69@051f909b
.obj69@051f909b := MyModuleType
.obj69@051f909b.__eContents := \
	sourcesMembers/.obj54@051f909b \
	sourcesMembers/.obj56@051f909b \
	dependsMembers/.obj58@051f909b \
	dependsMembers/.obj60@051f909b \
	dependsMembers/.obj64@051f909b \
	dependsMembers/.obj68@051f909b
.obj69@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj69@051f909b.dependent := 
.obj69@051f909b.subTypes := 
.obj69@051f909b.modifiers := 
.obj69@051f909b.name := single
.obj69@051f909b.origin := 40:8
.obj69@051f909b.superType := .obj52@051f909b./
.obj69@051f909b.customStorage := 

# .obj54@051f909b
.obj54@051f909b := MySourceMember
.obj54@051f909b.__eContents := \
	files/.obj53@051f909b
.obj54@051f909b.__eContainer := /sourcesMembers.obj69@051f909b
.obj54@051f909b.module := 

# .obj53@051f909b
.obj53@051f909b := MyFileName
.obj53@051f909b.__eContents := 
.obj53@051f909b.__eContainer := /files.obj54@051f909b
.obj53@051f909b.fileName := single.c

# .obj56@051f909b
.obj56@051f909b := MySourceMember
.obj56@051f909b.__eContents := \
	files/.obj55@051f909b
.obj56@051f909b.__eContainer := /sourcesMembers.obj69@051f909b
.obj56@051f909b.module := 

# .obj55@051f909b
.obj55@051f909b := MyFileName
.obj55@051f909b.__eContents := 
.obj55@051f909b.__eContainer := /files.obj56@051f909b
.obj55@051f909b.fileName := single.h

# .obj58@051f909b
.obj58@051f909b := MyDependsMember
.obj58@051f909b.__eContents := 
.obj58@051f909b.__eContainer := /dependsMembers.obj69@051f909b
.obj58@051f909b.modules := \
	.obj57@051f909b./
.obj58@051f909b.module := 

# .obj57@051f909b
.obj57@051f909b := ELink
.obj57@051f909b.eSource := MyFile_DependsMember_modules.obj58@051f909b
.obj57@051f909b.eTarget := 
.obj57@051f909b.name := embox.kernel.task.kernel_task
.obj57@051f909b.origin := 44:10

# .obj60@051f909b
.obj60@051f909b := MyDependsMember
.obj60@051f909b.__eContents := 
.obj60@051f909b.__eContainer := /dependsMembers.obj69@051f909b
.obj60@051f909b.modules := \
	.obj59@051f909b./
.obj60@051f909b.module := 

# .obj59@051f909b
.obj59@051f909b := ELink
.obj59@051f909b.eSource := MyFile_DependsMember_modules.obj60@051f909b
.obj59@051f909b.eTarget := 
.obj59@051f909b.name := embox.kernel.task.task_resource
.obj59@051f909b.origin := 45:10

# .obj64@051f909b
.obj64@051f909b := MyDependsMember
.obj64@051f909b.__eContents := \
	annotations/.obj62@051f909b
.obj64@051f909b.__eContainer := /dependsMembers.obj69@051f909b
.obj64@051f909b.modules := \
	.obj63@051f909b./
.obj64@051f909b.module := 

# .obj62@051f909b
.obj62@051f909b := MyAnnotation
.obj62@051f909b.__eContents := 
.obj62@051f909b.__eContainer := target/annotations.obj64@051f909b
.obj62@051f909b.type := .obj61@051f909b./

# .obj61@051f909b
.obj61@051f909b := ELink
.obj61@051f909b.eSource := MyFile_Annotation_type.obj62@051f909b
.obj61@051f909b.eTarget := 
.obj61@051f909b.name := NoRuntime
.obj61@051f909b.origin := 46:3

# .obj63@051f909b
.obj63@051f909b := ELink
.obj63@051f909b.eSource := MyFile_DependsMember_modules.obj64@051f909b
.obj63@051f909b.eTarget := 
.obj63@051f909b.name := embox.compat.libc.assert
.obj63@051f909b.origin := 46:21

# .obj68@051f909b
.obj68@051f909b := MyDependsMember
.obj68@051f909b.__eContents := \
	annotations/.obj66@051f909b
.obj68@051f909b.__eContainer := /dependsMembers.obj69@051f909b
.obj68@051f909b.modules := \
	.obj67@051f909b./
.obj68@051f909b.module := 

# .obj66@051f909b
.obj66@051f909b := MyAnnotation
.obj66@051f909b.__eContents := 
.obj66@051f909b.__eContainer := target/annotations.obj68@051f909b
.obj66@051f909b.type := .obj65@051f909b./

# .obj65@051f909b
.obj65@051f909b := ELink
.obj65@051f909b.eSource := MyFile_Annotation_type.obj66@051f909b
.obj65@051f909b.eTarget := 
.obj65@051f909b.name := NoRuntime
.obj65@051f909b.origin := 47:3

# .obj67@051f909b
.obj67@051f909b := ELink
.obj67@051f909b.eSource := MyFile_DependsMember_modules.obj68@051f909b
.obj67@051f909b.eTarget := 
.obj67@051f909b.name := embox.compat.libc.str
.obj67@051f909b.origin := 47:21

# .obj52@051f909b
.obj52@051f909b := ELink
.obj52@051f909b.eSource := MyFile_ModuleType_superType.obj69@051f909b
.obj52@051f909b.eTarget := 
.obj52@051f909b.name := api
.obj52@051f909b.origin := 40:23

# .obj81@051f909b
.obj81@051f909b := MyModuleType
.obj81@051f909b.__eContents := \
	sourcesMembers/.obj72@051f909b \
	dependsMembers/.obj76@051f909b \
	dependsMembers/.obj80@051f909b
.obj81@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj81@051f909b.dependent := 
.obj81@051f909b.subTypes := 
.obj81@051f909b.modifiers := 
.obj81@051f909b.name := task_no_table
.obj81@051f909b.origin := 50:8
.obj81@051f909b.superType := .obj70@051f909b./
.obj81@051f909b.customStorage := 

# .obj72@051f909b
.obj72@051f909b := MySourceMember
.obj72@051f909b.__eContents := \
	files/.obj71@051f909b
.obj72@051f909b.__eContainer := /sourcesMembers.obj81@051f909b
.obj72@051f909b.module := 

# .obj71@051f909b
.obj71@051f909b := MyFileName
.obj71@051f909b.__eContents := 
.obj71@051f909b.__eContainer := /files.obj72@051f909b
.obj71@051f909b.fileName := task_no_table.h

# .obj76@051f909b
.obj76@051f909b := MyDependsMember
.obj76@051f909b.__eContents := \
	annotations/.obj74@051f909b
.obj76@051f909b.__eContainer := /dependsMembers.obj81@051f909b
.obj76@051f909b.modules := \
	.obj75@051f909b./
.obj76@051f909b.module := 

# .obj74@051f909b
.obj74@051f909b := MyAnnotation
.obj74@051f909b.__eContents := 
.obj74@051f909b.__eContainer := target/annotations.obj76@051f909b
.obj74@051f909b.type := .obj73@051f909b./

# .obj73@051f909b
.obj73@051f909b := ELink
.obj73@051f909b.eSource := MyFile_Annotation_type.obj74@051f909b
.obj73@051f909b.eTarget := 
.obj73@051f909b.name := NoRuntime
.obj73@051f909b.origin := 53:3

# .obj75@051f909b
.obj75@051f909b := ELink
.obj75@051f909b.eSource := MyFile_DependsMember_modules.obj76@051f909b
.obj75@051f909b.eTarget := 
.obj75@051f909b.name := embox.kernel.task.kernel_task
.obj75@051f909b.origin := 53:21

# .obj80@051f909b
.obj80@051f909b := MyDependsMember
.obj80@051f909b.__eContents := \
	annotations/.obj78@051f909b
.obj80@051f909b.__eContainer := /dependsMembers.obj81@051f909b
.obj80@051f909b.modules := \
	.obj79@051f909b./
.obj80@051f909b.module := 

# .obj78@051f909b
.obj78@051f909b := MyAnnotation
.obj78@051f909b.__eContents := 
.obj78@051f909b.__eContainer := target/annotations.obj80@051f909b
.obj78@051f909b.type := .obj77@051f909b./

# .obj77@051f909b
.obj77@051f909b := ELink
.obj77@051f909b.eSource := MyFile_Annotation_type.obj78@051f909b
.obj77@051f909b.eTarget := 
.obj77@051f909b.name := NoRuntime
.obj77@051f909b.origin := 54:3

# .obj79@051f909b
.obj79@051f909b := ELink
.obj79@051f909b.eSource := MyFile_DependsMember_modules.obj80@051f909b
.obj79@051f909b.eTarget := 
.obj79@051f909b.name := embox.compat.libc.assert
.obj79@051f909b.origin := 54:21

# .obj70@051f909b
.obj70@051f909b := ELink
.obj70@051f909b.eSource := MyFile_ModuleType_superType.obj81@051f909b
.obj70@051f909b.eTarget := 
.obj70@051f909b.name := task_table_api
.obj70@051f909b.origin := 50:30

# .obj93@051f909b
.obj93@051f909b := MyModuleType
.obj93@051f909b.__eContents := \
	sourcesMembers/.obj84@051f909b \
	dependsMembers/.obj88@051f909b \
	dependsMembers/.obj92@051f909b
.obj93@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj93@051f909b.dependent := 
.obj93@051f909b.subTypes := 
.obj93@051f909b.modifiers := 
.obj93@051f909b.name := task_resource
.obj93@051f909b.origin := 57:8
.obj93@051f909b.superType := 
.obj93@051f909b.customStorage := 

# .obj84@051f909b
.obj84@051f909b := MySourceMember
.obj84@051f909b.__eContents := \
	files/.obj82@051f909b \
	files/.obj83@051f909b
.obj84@051f909b.__eContainer := /sourcesMembers.obj93@051f909b
.obj84@051f909b.module := 

# .obj82@051f909b
.obj82@051f909b := MyFileName
.obj82@051f909b.__eContents := 
.obj82@051f909b.__eContainer := /files.obj84@051f909b
.obj82@051f909b.fileName := task_resource.c

# .obj83@051f909b
.obj83@051f909b := MyFileName
.obj83@051f909b.__eContents := 
.obj83@051f909b.__eContainer := /files.obj84@051f909b
.obj83@051f909b.fileName := task_resource.lds.S

# .obj88@051f909b
.obj88@051f909b := MyDependsMember
.obj88@051f909b.__eContents := \
	annotations/.obj86@051f909b
.obj88@051f909b.__eContainer := /dependsMembers.obj93@051f909b
.obj88@051f909b.modules := \
	.obj87@051f909b./
.obj88@051f909b.module := 

# .obj86@051f909b
.obj86@051f909b := MyAnnotation
.obj86@051f909b.__eContents := 
.obj86@051f909b.__eContainer := target/annotations.obj88@051f909b
.obj86@051f909b.type := .obj85@051f909b./

# .obj85@051f909b
.obj85@051f909b := ELink
.obj85@051f909b.eSource := MyFile_Annotation_type.obj86@051f909b
.obj85@051f909b.eTarget := 
.obj85@051f909b.name := NoRuntime
.obj85@051f909b.origin := 60:3

# .obj87@051f909b
.obj87@051f909b := ELink
.obj87@051f909b.eSource := MyFile_DependsMember_modules.obj88@051f909b
.obj87@051f909b.eTarget := 
.obj87@051f909b.name := embox.compat.libc.assert
.obj87@051f909b.origin := 60:21

# .obj92@051f909b
.obj92@051f909b := MyDependsMember
.obj92@051f909b.__eContents := \
	annotations/.obj90@051f909b
.obj92@051f909b.__eContainer := /dependsMembers.obj93@051f909b
.obj92@051f909b.modules := \
	.obj91@051f909b./
.obj92@051f909b.module := 

# .obj90@051f909b
.obj90@051f909b := MyAnnotation
.obj90@051f909b.__eContents := 
.obj90@051f909b.__eContainer := target/annotations.obj92@051f909b
.obj90@051f909b.type := .obj89@051f909b./

# .obj89@051f909b
.obj89@051f909b := ELink
.obj89@051f909b.eSource := MyFile_Annotation_type.obj90@051f909b
.obj89@051f909b.eTarget := 
.obj89@051f909b.name := NoRuntime
.obj89@051f909b.origin := 61:3

# .obj91@051f909b
.obj91@051f909b := ELink
.obj91@051f909b.eSource := MyFile_DependsMember_modules.obj92@051f909b
.obj91@051f909b.eTarget := 
.obj91@051f909b.name := embox.util.Array
.obj91@051f909b.origin := 61:21

# .obj104@051f909b
.obj104@051f909b := MyModuleType
.obj104@051f909b.__eContents := \
	sourcesMembers/.obj99@051f909b \
	optionsMembers/.obj97@051f909b \
	dependsMembers/.obj103@051f909b
.obj104@051f909b.__eContainer := fileContentRoot/types.obj105@051f909b
.obj104@051f909b.dependent := 
.obj104@051f909b.subTypes := 
.obj104@051f909b.modifiers := 
.obj104@051f909b.name := task_table
.obj104@051f909b.origin := 64:8
.obj104@051f909b.superType := .obj94@051f909b./
.obj104@051f909b.customStorage := 

# .obj99@051f909b
.obj99@051f909b := MySourceMember
.obj99@051f909b.__eContents := \
	files/.obj98@051f909b
.obj99@051f909b.__eContainer := /sourcesMembers.obj104@051f909b
.obj99@051f909b.module := 

# .obj98@051f909b
.obj98@051f909b := MyFileName
.obj98@051f909b.__eContents := 
.obj98@051f909b.__eContainer := /files.obj99@051f909b
.obj98@051f909b.fileName := task_table.c

# .obj97@051f909b
.obj97@051f909b := MyOptionMember
.obj97@051f909b.__eContents := \
	options/.obj95@051f909b
.obj97@051f909b.__eContainer := /optionsMembers.obj104@051f909b
.obj97@051f909b.module := 

# .obj95@051f909b
.obj95@051f909b := MyNumberOption
.obj95@051f909b.__eContents := \
	defaultValue/.obj96@051f909b
.obj95@051f909b.__eContainer := /options.obj97@051f909b
.obj95@051f909b.name := task_table_size
.obj95@051f909b.origin := 

# .obj96@051f909b
.obj96@051f909b := MyNumberLiteral
.obj96@051f909b.__eContents := 
.obj96@051f909b.__eContainer := /defaultValue.obj95@051f909b
.obj96@051f909b.value := 32

# .obj103@051f909b
.obj103@051f909b := MyDependsMember
.obj103@051f909b.__eContents := \
	annotations/.obj101@051f909b
.obj103@051f909b.__eContainer := /dependsMembers.obj104@051f909b
.obj103@051f909b.modules := \
	.obj102@051f909b./
.obj103@051f909b.module := 

# .obj101@051f909b
.obj101@051f909b := MyAnnotation
.obj101@051f909b.__eContents := 
.obj101@051f909b.__eContainer := target/annotations.obj103@051f909b
.obj101@051f909b.type := .obj100@051f909b./

# .obj100@051f909b
.obj100@051f909b := ELink
.obj100@051f909b.eSource := MyFile_Annotation_type.obj101@051f909b
.obj100@051f909b.eTarget := 
.obj100@051f909b.name := NoRuntime
.obj100@051f909b.origin := 68:3

# .obj102@051f909b
.obj102@051f909b := ELink
.obj102@051f909b.eSource := MyFile_DependsMember_modules.obj103@051f909b
.obj102@051f909b.eTarget := 
.obj102@051f909b.name := embox.compat.libc.assert
.obj102@051f909b.origin := 68:21

# .obj94@051f909b
.obj94@051f909b := ELink
.obj94@051f909b.eSource := MyFile_ModuleType_superType.obj104@051f909b
.obj94@051f909b.eTarget := 
.obj94@051f909b.name := task_table_api
.obj94@051f909b.origin := 64:27


__resource-mk/.cache/mybuild/files/src/kernel/task/Mybuild.mk := .obj1@051f909b
