# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@e99dd492

# .obj1@e99dd492
.obj1@e99dd492 := MyFileResource
.obj1@e99dd492.issues := 
.obj1@e99dd492.contentsRoot := .obj3@e99dd492
.obj1@e99dd492.resourceSet := 
.obj1@e99dd492.fileName := mk/mybuild/lang/App.my
.obj1@e99dd492.exports := \
	mybuild.lang \
	mybuild.lang.App
.obj1@e99dd492.exports.mybuild.lang := \
	.obj3@e99dd492
.obj1@e99dd492.exports.mybuild.lang.App := \
	.obj2@e99dd492

# .obj3@e99dd492
.obj3@e99dd492 := MyFileContentRoot
.obj3@e99dd492.__eContents := \
	types/.obj2@e99dd492
.obj3@e99dd492.__eContainer := .obj1@e99dd492
.obj3@e99dd492.imports := 
.obj3@e99dd492.name := mybuild.lang
.obj3@e99dd492.origin := 

# .obj2@e99dd492
.obj2@e99dd492 := MyAnnotationType
.obj2@e99dd492.__eContents := 
.obj2@e99dd492.__eContainer := fileContentRoot/types.obj3@e99dd492
.obj2@e99dd492.name := App
.obj2@e99dd492.origin := 3:12


__resource-mk/.cache/mybuild/files/mk/mybuild/lang/App.my.mk := .obj1@e99dd492
