# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@964e59ca

# .obj1@964e59ca
.obj1@964e59ca := MyFileResource
.obj1@964e59ca.issues := 
.obj1@964e59ca.contentsRoot := .obj5@964e59ca
.obj1@964e59ca.resourceSet := 
.obj1@964e59ca.fileName := mk/mybuild/lang/BuildDepends.my
.obj1@964e59ca.exports := \
	mybuild.lang \
	mybuild.lang.BuildDepends \
	mybuild.lang.BuildDepends.value
.obj1@964e59ca.exports.mybuild.lang := \
	.obj5@964e59ca
.obj1@964e59ca.exports.mybuild.lang.BuildDepends := \
	.obj4@964e59ca
.obj1@964e59ca.exports.mybuild.lang.BuildDepends.value := \
	.obj3@964e59ca

# .obj5@964e59ca
.obj5@964e59ca := MyFileContentRoot
.obj5@964e59ca.__eContents := \
	types/.obj4@964e59ca
.obj5@964e59ca.__eContainer := .obj1@964e59ca
.obj5@964e59ca.imports := 
.obj5@964e59ca.name := mybuild.lang
.obj5@964e59ca.origin := 

# .obj4@964e59ca
.obj4@964e59ca := MyAnnotationType
.obj4@964e59ca.__eContents := \
	options/.obj3@964e59ca
.obj4@964e59ca.__eContainer := fileContentRoot/types.obj5@964e59ca
.obj4@964e59ca.name := BuildDepends
.obj4@964e59ca.origin := 4:12

# .obj3@964e59ca
.obj3@964e59ca := MyTypeReferenceOption
.obj3@964e59ca.__eContents := 
.obj3@964e59ca.__eContainer := /options.obj4@964e59ca
.obj3@964e59ca.name := value
.obj3@964e59ca.origin := 
.obj3@964e59ca.type := 


__resource-mk/.cache/mybuild/files/mk/mybuild/lang/BuildDepends.my.mk := .obj1@964e59ca
