# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@4d472c16

# .obj1@4d472c16
.obj1@4d472c16 := MyFileResource
.obj1@4d472c16.issues := 
.obj1@4d472c16.contentsRoot := .obj6@4d472c16
.obj1@4d472c16.resourceSet := 
.obj1@4d472c16.fileName := mk/mybuild/lang/IncludePath.my
.obj1@4d472c16.exports := \
	mybuild.lang \
	mybuild.lang.IncludePath \
	mybuild.lang.IncludePath.value \
	mybuild.lang.IncludePathBefore \
	mybuild.lang.IncludePathBefore.value
.obj1@4d472c16.exports.mybuild.lang := \
	.obj6@4d472c16
.obj1@4d472c16.exports.mybuild.lang.IncludePath := \
	.obj3@4d472c16
.obj1@4d472c16.exports.mybuild.lang.IncludePath.value := \
	.obj2@4d472c16
.obj1@4d472c16.exports.mybuild.lang.IncludePathBefore := \
	.obj5@4d472c16
.obj1@4d472c16.exports.mybuild.lang.IncludePathBefore.value := \
	.obj4@4d472c16

# .obj6@4d472c16
.obj6@4d472c16 := MyFileContentRoot
.obj6@4d472c16.__eContents := \
	types/.obj3@4d472c16 \
	types/.obj5@4d472c16
.obj6@4d472c16.__eContainer := .obj1@4d472c16
.obj6@4d472c16.imports := 
.obj6@4d472c16.name := mybuild.lang
.obj6@4d472c16.origin := 

# .obj3@4d472c16
.obj3@4d472c16 := MyAnnotationType
.obj3@4d472c16.__eContents := \
	options/.obj2@4d472c16
.obj3@4d472c16.__eContainer := fileContentRoot/types.obj6@4d472c16
.obj3@4d472c16.name := IncludePath
.obj3@4d472c16.origin := 4:12

# .obj2@4d472c16
.obj2@4d472c16 := MyStringOption
.obj2@4d472c16.__eContents := 
.obj2@4d472c16.__eContainer := /options.obj3@4d472c16
.obj2@4d472c16.name := value
.obj2@4d472c16.origin := 

# .obj5@4d472c16
.obj5@4d472c16 := MyAnnotationType
.obj5@4d472c16.__eContents := \
	options/.obj4@4d472c16
.obj5@4d472c16.__eContainer := fileContentRoot/types.obj6@4d472c16
.obj5@4d472c16.name := IncludePathBefore
.obj5@4d472c16.origin := 8:12

# .obj4@4d472c16
.obj4@4d472c16 := MyStringOption
.obj4@4d472c16.__eContents := 
.obj4@4d472c16.__eContainer := /options.obj5@4d472c16
.obj4@4d472c16.name := value
.obj4@4d472c16.origin := 


__resource-mk/.cache/mybuild/files/mk/mybuild/lang/IncludePath.my.mk := .obj1@4d472c16
