# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@4047ffd6

# .obj1@4047ffd6
.obj1@4047ffd6 := MyFileResource
.obj1@4047ffd6.issues := 
.obj1@4047ffd6.contentsRoot := .obj5@4047ffd6
.obj1@4047ffd6.resourceSet := 
.obj1@4047ffd6.fileName := mk/mybuild/lang/IncludeExport.my
.obj1@4047ffd6.exports := \
	mybuild.lang \
	mybuild.lang.IncludeExport \
	mybuild.lang.IncludeExport.path \
	mybuild.lang.IncludeExport.target_name
.obj1@4047ffd6.exports.mybuild.lang := \
	.obj5@4047ffd6
.obj1@4047ffd6.exports.mybuild.lang.IncludeExport := \
	.obj4@4047ffd6
.obj1@4047ffd6.exports.mybuild.lang.IncludeExport.path := \
	.obj2@4047ffd6
.obj1@4047ffd6.exports.mybuild.lang.IncludeExport.target_name := \
	.obj3@4047ffd6

# .obj5@4047ffd6
.obj5@4047ffd6 := MyFileContentRoot
.obj5@4047ffd6.__eContents := \
	types/.obj4@4047ffd6
.obj5@4047ffd6.__eContainer := .obj1@4047ffd6
.obj5@4047ffd6.imports := 
.obj5@4047ffd6.name := mybuild.lang
.obj5@4047ffd6.origin := 

# .obj4@4047ffd6
.obj4@4047ffd6 := MyAnnotationType
.obj4@4047ffd6.__eContents := \
	options/.obj2@4047ffd6 \
	options/.obj3@4047ffd6
.obj4@4047ffd6.__eContainer := fileContentRoot/types.obj5@4047ffd6
.obj4@4047ffd6.name := IncludeExport
.obj4@4047ffd6.origin := 3:12

# .obj2@4047ffd6
.obj2@4047ffd6 := MyStringOption
.obj2@4047ffd6.__eContents := 
.obj2@4047ffd6.__eContainer := /options.obj4@4047ffd6
.obj2@4047ffd6.name := path
.obj2@4047ffd6.origin := 

# .obj3@4047ffd6
.obj3@4047ffd6 := MyStringOption
.obj3@4047ffd6.__eContents := 
.obj3@4047ffd6.__eContainer := /options.obj4@4047ffd6
.obj3@4047ffd6.name := target_name
.obj3@4047ffd6.origin := 


__resource-mk/.cache/mybuild/files/mk/mybuild/lang/IncludeExport.my.mk := .obj1@4047ffd6
