# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@8c316680

# .obj1@8c316680
.obj1@8c316680 := MyFileResource
.obj1@8c316680.issues := 
.obj1@8c316680.contentsRoot := .obj3@8c316680
.obj1@8c316680.resourceSet := 
.obj1@8c316680.fileName := mk/mybuild/lang/NoRuntime.my
.obj1@8c316680.exports := \
	mybuild.lang \
	mybuild.lang.NoRuntime
.obj1@8c316680.exports.mybuild.lang := \
	.obj3@8c316680
.obj1@8c316680.exports.mybuild.lang.NoRuntime := \
	.obj2@8c316680

# .obj3@8c316680
.obj3@8c316680 := MyFileContentRoot
.obj3@8c316680.__eContents := \
	types/.obj2@8c316680
.obj3@8c316680.__eContainer := .obj1@8c316680
.obj3@8c316680.imports := 
.obj3@8c316680.name := mybuild.lang
.obj3@8c316680.origin := 

# .obj2@8c316680
.obj2@8c316680 := MyAnnotationType
.obj2@8c316680.__eContents := 
.obj2@8c316680.__eContainer := fileContentRoot/types.obj3@8c316680
.obj2@8c316680.name := NoRuntime
.obj2@8c316680.origin := 3:12


__resource-mk/.cache/mybuild/files/mk/mybuild/lang/NoRuntime.my.mk := .obj1@8c316680
