# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@9f6c5bec

# .obj1@9f6c5bec
.obj1@9f6c5bec := MyFileResource
.obj1@9f6c5bec.issues := 
.obj1@9f6c5bec.contentsRoot := .obj7@9f6c5bec
.obj1@9f6c5bec.resourceSet := 
.obj1@9f6c5bec.fileName := src/tests/recursion/Mybuild
.obj1@9f6c5bec.exports := \
	embox.test \
	embox.test.recursion
.obj1@9f6c5bec.exports.embox.test := \
	.obj7@9f6c5bec
.obj1@9f6c5bec.exports.embox.test.recursion := \
	.obj6@9f6c5bec

# .obj7@9f6c5bec
.obj7@9f6c5bec := MyFileContentRoot
.obj7@9f6c5bec.__eContents := \
	types/.obj6@9f6c5bec
.obj7@9f6c5bec.__eContainer := .obj1@9f6c5bec
.obj7@9f6c5bec.imports := 
.obj7@9f6c5bec.name := embox.test
.obj7@9f6c5bec.origin := 

# .obj6@9f6c5bec
.obj6@9f6c5bec := MyModuleType
.obj6@9f6c5bec.__eContents := \
	sourcesMembers/.obj3@9f6c5bec \
	dependsMembers/.obj5@9f6c5bec
.obj6@9f6c5bec.__eContainer := fileContentRoot/types.obj7@9f6c5bec
.obj6@9f6c5bec.dependent := 
.obj6@9f6c5bec.subTypes := 
.obj6@9f6c5bec.modifiers := 
.obj6@9f6c5bec.name := recursion
.obj6@9f6c5bec.origin := 3:8
.obj6@9f6c5bec.superType := 
.obj6@9f6c5bec.customStorage := 

# .obj3@9f6c5bec
.obj3@9f6c5bec := MySourceMember
.obj3@9f6c5bec.__eContents := \
	files/.obj2@9f6c5bec
.obj3@9f6c5bec.__eContainer := /sourcesMembers.obj6@9f6c5bec
.obj3@9f6c5bec.module := 

# .obj2@9f6c5bec
.obj2@9f6c5bec := MyFileName
.obj2@9f6c5bec.__eContents := 
.obj2@9f6c5bec.__eContainer := /files.obj3@9f6c5bec
.obj2@9f6c5bec.fileName := stack_recursion.c

# .obj5@9f6c5bec
.obj5@9f6c5bec := MyDependsMember
.obj5@9f6c5bec.__eContents := 
.obj5@9f6c5bec.__eContainer := /dependsMembers.obj6@9f6c5bec
.obj5@9f6c5bec.modules := \
	.obj4@9f6c5bec./
.obj5@9f6c5bec.module := 

# .obj4@9f6c5bec
.obj4@9f6c5bec := ELink
.obj4@9f6c5bec.eSource := MyFile_DependsMember_modules.obj5@9f6c5bec
.obj4@9f6c5bec.eTarget := 
.obj4@9f6c5bec.name := embox.framework.LibFramework
.obj4@9f6c5bec.origin := 6:10


__resource-mk/.cache/mybuild/files/src/tests/recursion/Mybuild.mk := .obj1@9f6c5bec
