# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@df2d8df8

# .obj1@df2d8df8
.obj1@df2d8df8 := MyFileResource
.obj1@df2d8df8.issues := 
.obj1@df2d8df8.contentsRoot := .obj18@df2d8df8
.obj1@df2d8df8.resourceSet := 
.obj1@df2d8df8.fileName := src/drivers/mmc/host/pl181/Mybuild
.obj1@df2d8df8.exports := \
	embox.driver.mmc \
	embox.driver.mmc.pl181 \
	embox.driver.mmc.pl181.log_level \
	embox.driver.mmc.pl181.base_addr \
	embox.driver.mmc.pl181.irq0_num \
	embox.driver.mmc.pl181.irq1_num
.obj1@df2d8df8.exports.embox.driver.mmc := \
	.obj18@df2d8df8
.obj1@df2d8df8.exports.embox.driver.mmc.pl181 := \
	.obj17@df2d8df8
.obj1@df2d8df8.exports.embox.driver.mmc.pl181.log_level := \
	.obj2@df2d8df8
.obj1@df2d8df8.exports.embox.driver.mmc.pl181.base_addr := \
	.obj5@df2d8df8
.obj1@df2d8df8.exports.embox.driver.mmc.pl181.irq0_num := \
	.obj7@df2d8df8
.obj1@df2d8df8.exports.embox.driver.mmc.pl181.irq1_num := \
	.obj9@df2d8df8

# .obj18@df2d8df8
.obj18@df2d8df8 := MyFileContentRoot
.obj18@df2d8df8.__eContents := \
	types/.obj17@df2d8df8
.obj18@df2d8df8.__eContainer := .obj1@df2d8df8
.obj18@df2d8df8.imports := 
.obj18@df2d8df8.name := embox.driver.mmc
.obj18@df2d8df8.origin := 

# .obj17@df2d8df8
.obj17@df2d8df8 := MyModuleType
.obj17@df2d8df8.__eContents := \
	sourcesMembers/.obj12@df2d8df8 \
	optionsMembers/.obj4@df2d8df8 \
	optionsMembers/.obj6@df2d8df8 \
	optionsMembers/.obj8@df2d8df8 \
	optionsMembers/.obj10@df2d8df8 \
	dependsMembers/.obj14@df2d8df8 \
	dependsMembers/.obj16@df2d8df8
.obj17@df2d8df8.__eContainer := fileContentRoot/types.obj18@df2d8df8
.obj17@df2d8df8.dependent := 
.obj17@df2d8df8.subTypes := 
.obj17@df2d8df8.modifiers := 
.obj17@df2d8df8.name := pl181
.obj17@df2d8df8.origin := 3:8
.obj17@df2d8df8.superType := 
.obj17@df2d8df8.customStorage := 

# .obj12@df2d8df8
.obj12@df2d8df8 := MySourceMember
.obj12@df2d8df8.__eContents := \
	files/.obj11@df2d8df8
.obj12@df2d8df8.__eContainer := /sourcesMembers.obj17@df2d8df8
.obj12@df2d8df8.module := 

# .obj11@df2d8df8
.obj11@df2d8df8 := MyFileName
.obj11@df2d8df8.__eContents := 
.obj11@df2d8df8.__eContainer := /files.obj12@df2d8df8
.obj11@df2d8df8.fileName := pl181.c

# .obj4@df2d8df8
.obj4@df2d8df8 := MyOptionMember
.obj4@df2d8df8.__eContents := \
	options/.obj2@df2d8df8
.obj4@df2d8df8.__eContainer := /optionsMembers.obj17@df2d8df8
.obj4@df2d8df8.module := 

# .obj2@df2d8df8
.obj2@df2d8df8 := MyNumberOption
.obj2@df2d8df8.__eContents := \
	defaultValue/.obj3@df2d8df8
.obj2@df2d8df8.__eContainer := /options.obj4@df2d8df8
.obj2@df2d8df8.name := log_level
.obj2@df2d8df8.origin := 

# .obj3@df2d8df8
.obj3@df2d8df8 := MyNumberLiteral
.obj3@df2d8df8.__eContents := 
.obj3@df2d8df8.__eContainer := /defaultValue.obj2@df2d8df8
.obj3@df2d8df8.value := 1

# .obj6@df2d8df8
.obj6@df2d8df8 := MyOptionMember
.obj6@df2d8df8.__eContents := \
	options/.obj5@df2d8df8
.obj6@df2d8df8.__eContainer := /optionsMembers.obj17@df2d8df8
.obj6@df2d8df8.module := 

# .obj5@df2d8df8
.obj5@df2d8df8 := MyNumberOption
.obj5@df2d8df8.__eContents := 
.obj5@df2d8df8.__eContainer := /options.obj6@df2d8df8
.obj5@df2d8df8.name := base_addr
.obj5@df2d8df8.origin := 

# .obj8@df2d8df8
.obj8@df2d8df8 := MyOptionMember
.obj8@df2d8df8.__eContents := \
	options/.obj7@df2d8df8
.obj8@df2d8df8.__eContainer := /optionsMembers.obj17@df2d8df8
.obj8@df2d8df8.module := 

# .obj7@df2d8df8
.obj7@df2d8df8 := MyNumberOption
.obj7@df2d8df8.__eContents := 
.obj7@df2d8df8.__eContainer := /options.obj8@df2d8df8
.obj7@df2d8df8.name := irq0_num
.obj7@df2d8df8.origin := 

# .obj10@df2d8df8
.obj10@df2d8df8 := MyOptionMember
.obj10@df2d8df8.__eContents := \
	options/.obj9@df2d8df8
.obj10@df2d8df8.__eContainer := /optionsMembers.obj17@df2d8df8
.obj10@df2d8df8.module := 

# .obj9@df2d8df8
.obj9@df2d8df8 := MyNumberOption
.obj9@df2d8df8.__eContents := 
.obj9@df2d8df8.__eContainer := /options.obj10@df2d8df8
.obj9@df2d8df8.name := irq1_num
.obj9@df2d8df8.origin := 

# .obj14@df2d8df8
.obj14@df2d8df8 := MyDependsMember
.obj14@df2d8df8.__eContents := 
.obj14@df2d8df8.__eContainer := /dependsMembers.obj17@df2d8df8
.obj14@df2d8df8.modules := \
	.obj13@df2d8df8./
.obj14@df2d8df8.module := 

# .obj13@df2d8df8
.obj13@df2d8df8 := ELink
.obj13@df2d8df8.eSource := MyFile_DependsMember_modules.obj14@df2d8df8
.obj13@df2d8df8.eTarget := 
.obj13@df2d8df8.name := embox.driver.block_dev
.obj13@df2d8df8.origin := 12:10

# .obj16@df2d8df8
.obj16@df2d8df8 := MyDependsMember
.obj16@df2d8df8.__eContents := 
.obj16@df2d8df8.__eContainer := /dependsMembers.obj17@df2d8df8
.obj16@df2d8df8.modules := \
	.obj15@df2d8df8./
.obj16@df2d8df8.module := 

# .obj15@df2d8df8
.obj15@df2d8df8 := ELink
.obj15@df2d8df8.eSource := MyFile_DependsMember_modules.obj16@df2d8df8
.obj15@df2d8df8.eTarget := 
.obj15@df2d8df8.name := embox.driver.mmc.mmc_core
.obj15@df2d8df8.origin := 13:10


__resource-mk/.cache/mybuild/files/src/drivers/mmc/host/pl181/Mybuild.mk := .obj1@df2d8df8
