# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@5d7dceb3

# .obj1@5d7dceb3
.obj1@5d7dceb3 := MyFileResource
.obj1@5d7dceb3.issues := 
.obj1@5d7dceb3.contentsRoot := .obj28@5d7dceb3
.obj1@5d7dceb3.resourceSet := 
.obj1@5d7dceb3.fileName := src/cmds/net/Rlogin.my
.obj1@5d7dceb3.exports := \
	embox.cmd.net \
	embox.cmd.net.rlogin
.obj1@5d7dceb3.exports.embox.cmd.net := \
	.obj28@5d7dceb3
.obj1@5d7dceb3.exports.embox.cmd.net.rlogin := \
	.obj27@5d7dceb3

# .obj28@5d7dceb3
.obj28@5d7dceb3 := MyFileContentRoot
.obj28@5d7dceb3.__eContents := \
	types/.obj27@5d7dceb3
.obj28@5d7dceb3.__eContainer := .obj1@5d7dceb3
.obj28@5d7dceb3.imports := 
.obj28@5d7dceb3.name := embox.cmd.net
.obj28@5d7dceb3.origin := 

# .obj27@5d7dceb3
.obj27@5d7dceb3 := MyModuleType
.obj27@5d7dceb3.__eContents := \
	sourcesMembers/.obj16@5d7dceb3 \
	dependsMembers/.obj18@5d7dceb3 \
	dependsMembers/.obj20@5d7dceb3 \
	dependsMembers/.obj22@5d7dceb3 \
	dependsMembers/.obj24@5d7dceb3 \
	dependsMembers/.obj26@5d7dceb3 \
	annotations/.obj3@5d7dceb3 \
	annotations/.obj14@5d7dceb3
.obj27@5d7dceb3.__eContainer := fileContentRoot/types.obj28@5d7dceb3
.obj27@5d7dceb3.dependent := 
.obj27@5d7dceb3.subTypes := 
.obj27@5d7dceb3.modifiers := 
.obj27@5d7dceb3.name := rlogin
.obj27@5d7dceb3.origin := 17:8
.obj27@5d7dceb3.superType := 
.obj27@5d7dceb3.customStorage := 

# .obj16@5d7dceb3
.obj16@5d7dceb3 := MySourceMember
.obj16@5d7dceb3.__eContents := \
	files/.obj15@5d7dceb3
.obj16@5d7dceb3.__eContainer := /sourcesMembers.obj27@5d7dceb3
.obj16@5d7dceb3.module := 

# .obj15@5d7dceb3
.obj15@5d7dceb3 := MyFileName
.obj15@5d7dceb3.__eContents := 
.obj15@5d7dceb3.__eContainer := /files.obj16@5d7dceb3
.obj15@5d7dceb3.fileName := rlogin.c

# .obj18@5d7dceb3
.obj18@5d7dceb3 := MyDependsMember
.obj18@5d7dceb3.__eContents := 
.obj18@5d7dceb3.__eContainer := /dependsMembers.obj27@5d7dceb3
.obj18@5d7dceb3.modules := \
	.obj17@5d7dceb3./
.obj18@5d7dceb3.module := 

# .obj17@5d7dceb3
.obj17@5d7dceb3 := ELink
.obj17@5d7dceb3.eSource := MyFile_DependsMember_modules.obj18@5d7dceb3
.obj17@5d7dceb3.eTarget := 
.obj17@5d7dceb3.name := embox.compat.libc.all
.obj17@5d7dceb3.origin := 20:10

# .obj20@5d7dceb3
.obj20@5d7dceb3 := MyDependsMember
.obj20@5d7dceb3.__eContents := 
.obj20@5d7dceb3.__eContainer := /dependsMembers.obj27@5d7dceb3
.obj20@5d7dceb3.modules := \
	.obj19@5d7dceb3./
.obj20@5d7dceb3.module := 

# .obj19@5d7dceb3
.obj19@5d7dceb3 := ELink
.obj19@5d7dceb3.eSource := MyFile_DependsMember_modules.obj20@5d7dceb3
.obj19@5d7dceb3.eTarget := 
.obj19@5d7dceb3.name := embox.mem.heap_api
.obj19@5d7dceb3.origin := 21:10

# .obj22@5d7dceb3
.obj22@5d7dceb3 := MyDependsMember
.obj22@5d7dceb3.__eContents := 
.obj22@5d7dceb3.__eContainer := /dependsMembers.obj27@5d7dceb3
.obj22@5d7dceb3.modules := \
	.obj21@5d7dceb3./
.obj22@5d7dceb3.module := 

# .obj21@5d7dceb3
.obj21@5d7dceb3 := ELink
.obj21@5d7dceb3.eSource := MyFile_DependsMember_modules.obj22@5d7dceb3
.obj21@5d7dceb3.eTarget := 
.obj21@5d7dceb3.name := embox.compat.posix.net.socket
.obj21@5d7dceb3.origin := 22:10

# .obj24@5d7dceb3
.obj24@5d7dceb3 := MyDependsMember
.obj24@5d7dceb3.__eContents := 
.obj24@5d7dceb3.__eContainer := /dependsMembers.obj27@5d7dceb3
.obj24@5d7dceb3.modules := \
	.obj23@5d7dceb3./
.obj24@5d7dceb3.module := 

# .obj23@5d7dceb3
.obj23@5d7dceb3 := ELink
.obj23@5d7dceb3.eSource := MyFile_DependsMember_modules.obj24@5d7dceb3
.obj23@5d7dceb3.eTarget := 
.obj23@5d7dceb3.name := embox.compat.posix.LibPosix
.obj23@5d7dceb3.origin := 23:10

# .obj26@5d7dceb3
.obj26@5d7dceb3 := MyDependsMember
.obj26@5d7dceb3.__eContents := 
.obj26@5d7dceb3.__eContainer := /dependsMembers.obj27@5d7dceb3
.obj26@5d7dceb3.modules := \
	.obj25@5d7dceb3./
.obj26@5d7dceb3.module := 

# .obj25@5d7dceb3
.obj25@5d7dceb3 := ELink
.obj25@5d7dceb3.eSource := MyFile_DependsMember_modules.obj26@5d7dceb3
.obj25@5d7dceb3.eTarget := 
.obj25@5d7dceb3.name := embox.framework.LibFramework
.obj25@5d7dceb3.origin := 24:10

# .obj3@5d7dceb3
.obj3@5d7dceb3 := MyAnnotation
.obj3@5d7dceb3.__eContents := 
.obj3@5d7dceb3.__eContainer := target/annotations.obj27@5d7dceb3
.obj3@5d7dceb3.type := .obj2@5d7dceb3./

# .obj2@5d7dceb3
.obj2@5d7dceb3 := ELink
.obj2@5d7dceb3.eSource := MyFile_Annotation_type.obj3@5d7dceb3
.obj2@5d7dceb3.eTarget := 
.obj2@5d7dceb3.name := AutoCmd
.obj2@5d7dceb3.origin := 3:2

# .obj14@5d7dceb3
.obj14@5d7dceb3 := MyAnnotation
.obj14@5d7dceb3.__eContents := \
	bindings/.obj7@5d7dceb3 \
	bindings/.obj10@5d7dceb3 \
	bindings/.obj13@5d7dceb3
.obj14@5d7dceb3.__eContainer := target/annotations.obj27@5d7dceb3
.obj14@5d7dceb3.type := .obj4@5d7dceb3./

# .obj7@5d7dceb3
.obj7@5d7dceb3 := MyOptionBinding
.obj7@5d7dceb3.__eContents := \
	value/.obj6@5d7dceb3
.obj7@5d7dceb3.__eContainer := /bindings.obj14@5d7dceb3
.obj7@5d7dceb3.option := .obj5@5d7dceb3./

# .obj6@5d7dceb3
.obj6@5d7dceb3 := MyStringLiteral
.obj6@5d7dceb3.__eContents := 
.obj6@5d7dceb3.__eContainer := /value.obj7@5d7dceb3
.obj6@5d7dceb3.value := rlogin

# .obj5@5d7dceb3
.obj5@5d7dceb3 := ELink
.obj5@5d7dceb3.eSource := MyFile_OptionBinding_option.obj7@5d7dceb3
.obj5@5d7dceb3.eTarget := 
.obj5@5d7dceb3.name := name
.obj5@5d7dceb3.origin := 4:6

# .obj10@5d7dceb3
.obj10@5d7dceb3 := MyOptionBinding
.obj10@5d7dceb3.__eContents := \
	value/.obj9@5d7dceb3
.obj10@5d7dceb3.__eContainer := /bindings.obj14@5d7dceb3
.obj10@5d7dceb3.option := .obj8@5d7dceb3./

# .obj9@5d7dceb3
.obj9@5d7dceb3 := MyStringLiteral
.obj9@5d7dceb3.__eContents := 
.obj9@5d7dceb3.__eContainer := /value.obj10@5d7dceb3
.obj9@5d7dceb3.value := Rlogin client

# .obj8@5d7dceb3
.obj8@5d7dceb3 := ELink
.obj8@5d7dceb3.eSource := MyFile_OptionBinding_option.obj10@5d7dceb3
.obj8@5d7dceb3.eTarget := 
.obj8@5d7dceb3.name := help
.obj8@5d7dceb3.origin := 5:2

# .obj13@5d7dceb3
.obj13@5d7dceb3 := MyOptionBinding
.obj13@5d7dceb3.__eContents := \
	value/.obj12@5d7dceb3
.obj13@5d7dceb3.__eContainer := /bindings.obj14@5d7dceb3
.obj13@5d7dceb3.option := .obj11@5d7dceb3./

# .obj12@5d7dceb3
.obj12@5d7dceb3 := MyStringLiteral
.obj12@5d7dceb3.__eContents := 
.obj12@5d7dceb3.__eContainer := /value.obj13@5d7dceb3
.obj12@5d7dceb3.value := $(\0)$(\n)		NAME$(\n)			rlogin - Rlogin client$(\n)		SYNOPSIS$(\n)			rlogin [-l username] <server>$(\n)		DESCRIPTION$(\n)			Connect to remote rlogin server.$(\n)		AUTHORS$(\n)			Alexander Kalmuk$(\n)	

# .obj11@5d7dceb3
.obj11@5d7dceb3 := ELink
.obj11@5d7dceb3.eSource := MyFile_OptionBinding_option.obj13@5d7dceb3
.obj11@5d7dceb3.eTarget := 
.obj11@5d7dceb3.name := man
.obj11@5d7dceb3.origin := 6:2

# .obj4@5d7dceb3
.obj4@5d7dceb3 := ELink
.obj4@5d7dceb3.eSource := MyFile_Annotation_type.obj14@5d7dceb3
.obj4@5d7dceb3.eTarget := 
.obj4@5d7dceb3.name := Cmd
.obj4@5d7dceb3.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/net/Rlogin.my.mk := .obj1@5d7dceb3
