# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@85bd8108

# .obj1@85bd8108
.obj1@85bd8108 := MyFileResource
.obj1@85bd8108.issues := 
.obj1@85bd8108.contentsRoot := .obj42@85bd8108
.obj1@85bd8108.resourceSet := 
.obj1@85bd8108.fileName := platform/stm32f4_iocontrol/http_admin/Mybuild
.obj1@85bd8108.exports := \
	stm32f4_iocontrol \
	stm32f4_iocontrol.http_admin
.obj1@85bd8108.exports.stm32f4_iocontrol := \
	.obj42@85bd8108
.obj1@85bd8108.exports.stm32f4_iocontrol.http_admin := \
	.obj41@85bd8108

# .obj42@85bd8108
.obj42@85bd8108 := MyFileContentRoot
.obj42@85bd8108.__eContents := \
	types/.obj41@85bd8108
.obj42@85bd8108.__eContainer := .obj1@85bd8108
.obj42@85bd8108.imports := 
.obj42@85bd8108.name := stm32f4_iocontrol
.obj42@85bd8108.origin := 

# .obj41@85bd8108
.obj41@85bd8108 := MyModuleType
.obj41@85bd8108.__eContents := \
	sourcesMembers/.obj20@85bd8108 \
	sourcesMembers/.obj34@85bd8108 \
	dependsMembers/.obj36@85bd8108 \
	dependsMembers/.obj38@85bd8108 \
	dependsMembers/.obj40@85bd8108 \
	annotations/.obj12@85bd8108 \
	annotations/.obj18@85bd8108
.obj41@85bd8108.__eContainer := fileContentRoot/types.obj42@85bd8108
.obj41@85bd8108.dependent := 
.obj41@85bd8108.subTypes := 
.obj41@85bd8108.modifiers := 
.obj41@85bd8108.name := http_admin
.obj41@85bd8108.origin := 6:8
.obj41@85bd8108.superType := 
.obj41@85bd8108.customStorage := 

# .obj20@85bd8108
.obj20@85bd8108 := MySourceMember
.obj20@85bd8108.__eContents := \
	files/.obj19@85bd8108
.obj20@85bd8108.__eContainer := /sourcesMembers.obj41@85bd8108
.obj20@85bd8108.module := 

# .obj19@85bd8108
.obj19@85bd8108 := MyFileName
.obj19@85bd8108.__eContents := 
.obj19@85bd8108.__eContainer := /files.obj20@85bd8108
.obj19@85bd8108.fileName := http_admin_backend.c

# .obj34@85bd8108
.obj34@85bd8108 := MySourceMember
.obj34@85bd8108.__eContents := \
	files/.obj26@85bd8108 \
	files/.obj27@85bd8108 \
	files/.obj28@85bd8108 \
	files/.obj29@85bd8108 \
	files/.obj30@85bd8108 \
	files/.obj31@85bd8108 \
	files/.obj32@85bd8108 \
	files/.obj33@85bd8108 \
	annotations/.obj25@85bd8108
.obj34@85bd8108.__eContainer := /sourcesMembers.obj41@85bd8108
.obj34@85bd8108.module := 

# .obj26@85bd8108
.obj26@85bd8108 := MyFileName
.obj26@85bd8108.__eContents := 
.obj26@85bd8108.__eContainer := /files.obj34@85bd8108
.obj26@85bd8108.fileName := partials

# .obj27@85bd8108
.obj27@85bd8108 := MyFileName
.obj27@85bd8108.__eContents := 
.obj27@85bd8108.__eContainer := /files.obj34@85bd8108
.obj27@85bd8108.fileName := css

# .obj28@85bd8108
.obj28@85bd8108 := MyFileName
.obj28@85bd8108.__eContents := 
.obj28@85bd8108.__eContainer := /files.obj34@85bd8108
.obj28@85bd8108.fileName := index.html

# .obj29@85bd8108
.obj29@85bd8108 := MyFileName
.obj29@85bd8108.__eContents := 
.obj29@85bd8108.__eContainer := /files.obj34@85bd8108
.obj29@85bd8108.fileName := angular.min.js

# .obj30@85bd8108
.obj30@85bd8108 := MyFileName
.obj30@85bd8108.__eContents := 
.obj30@85bd8108.__eContainer := /files.obj34@85bd8108
.obj30@85bd8108.fileName := angular-route.min.js

# .obj31@85bd8108
.obj31@85bd8108 := MyFileName
.obj31@85bd8108.__eContents := 
.obj31@85bd8108.__eContainer := /files.obj34@85bd8108
.obj31@85bd8108.fileName := angular-translate.min.js

# .obj32@85bd8108
.obj32@85bd8108 := MyFileName
.obj32@85bd8108.__eContents := 
.obj32@85bd8108.__eContainer := /files.obj34@85bd8108
.obj32@85bd8108.fileName := ui-bootstrap-tpls-0.12.1.min.js

# .obj33@85bd8108
.obj33@85bd8108 := MyFileName
.obj33@85bd8108.__eContents := 
.obj33@85bd8108.__eContainer := /files.obj34@85bd8108
.obj33@85bd8108.fileName := app.js

# .obj25@85bd8108
.obj25@85bd8108 := MyAnnotation
.obj25@85bd8108.__eContents := \
	bindings/.obj24@85bd8108
.obj25@85bd8108.__eContainer := target/annotations.obj34@85bd8108
.obj25@85bd8108.type := .obj21@85bd8108./

# .obj24@85bd8108
.obj24@85bd8108 := MyOptionBinding
.obj24@85bd8108.__eContents := \
	value/.obj23@85bd8108
.obj24@85bd8108.__eContainer := /bindings.obj25@85bd8108
.obj24@85bd8108.option := .obj22@85bd8108./

# .obj23@85bd8108
.obj23@85bd8108 := MyStringLiteral
.obj23@85bd8108.__eContents := 
.obj23@85bd8108.__eContainer := /value.obj24@85bd8108
.obj23@85bd8108.value := http_admin

# .obj22@85bd8108
.obj22@85bd8108 := ELink
.obj22@85bd8108.eSource := MyFile_OptionBinding_option.obj24@85bd8108
.obj22@85bd8108.eTarget := 
.obj22@85bd8108.name := target_dir
.obj22@85bd8108.origin := 10:10

# .obj21@85bd8108
.obj21@85bd8108 := ELink
.obj21@85bd8108.eSource := MyFile_Annotation_type.obj25@85bd8108
.obj21@85bd8108.eTarget := 
.obj21@85bd8108.name := InitFS
.obj21@85bd8108.origin := 10:3

# .obj36@85bd8108
.obj36@85bd8108 := MyDependsMember
.obj36@85bd8108.__eContents := 
.obj36@85bd8108.__eContainer := /dependsMembers.obj41@85bd8108
.obj36@85bd8108.modules := \
	.obj35@85bd8108./
.obj36@85bd8108.module := 

# .obj35@85bd8108
.obj35@85bd8108 := ELink
.obj35@85bd8108.eSource := MyFile_DependsMember_modules.obj36@85bd8108
.obj35@85bd8108.eTarget := 
.obj35@85bd8108.name := third_party.lib.cjson
.obj35@85bd8108.origin := 20:10

# .obj38@85bd8108
.obj38@85bd8108 := MyDependsMember
.obj38@85bd8108.__eContents := 
.obj38@85bd8108.__eContainer := /dependsMembers.obj41@85bd8108
.obj38@85bd8108.modules := \
	.obj37@85bd8108./
.obj38@85bd8108.module := 

# .obj37@85bd8108
.obj37@85bd8108 := ELink
.obj37@85bd8108.eSource := MyFile_DependsMember_modules.obj38@85bd8108
.obj37@85bd8108.eTarget := 
.obj37@85bd8108.name := embox.compat.libc.stdlib.system
.obj37@85bd8108.origin := 21:10

# .obj40@85bd8108
.obj40@85bd8108 := MyDependsMember
.obj40@85bd8108.__eContents := 
.obj40@85bd8108.__eContainer := /dependsMembers.obj41@85bd8108
.obj40@85bd8108.modules := \
	.obj39@85bd8108./
.obj40@85bd8108.module := 

# .obj39@85bd8108
.obj39@85bd8108 := ELink
.obj39@85bd8108.eSource := MyFile_DependsMember_modules.obj40@85bd8108
.obj39@85bd8108.eTarget := 
.obj39@85bd8108.name := embox.compat.posix.util.environ
.obj39@85bd8108.origin := 22:10

# .obj12@85bd8108
.obj12@85bd8108 := MyAnnotation
.obj12@85bd8108.__eContents := \
	bindings/.obj5@85bd8108 \
	bindings/.obj8@85bd8108 \
	bindings/.obj11@85bd8108
.obj12@85bd8108.__eContainer := target/annotations.obj41@85bd8108
.obj12@85bd8108.type := .obj2@85bd8108./

# .obj5@85bd8108
.obj5@85bd8108 := MyOptionBinding
.obj5@85bd8108.__eContents := \
	value/.obj4@85bd8108
.obj5@85bd8108.__eContainer := /bindings.obj12@85bd8108
.obj5@85bd8108.option := .obj3@85bd8108./

# .obj4@85bd8108
.obj4@85bd8108 := MyStringLiteral
.obj4@85bd8108.__eContents := 
.obj4@85bd8108.__eContainer := /value.obj5@85bd8108
.obj4@85bd8108.value := http_admin_backend

# .obj3@85bd8108
.obj3@85bd8108 := ELink
.obj3@85bd8108.eSource := MyFile_OptionBinding_option.obj5@85bd8108
.obj3@85bd8108.eTarget := 
.obj3@85bd8108.name := name
.obj3@85bd8108.origin := 4:6

# .obj8@85bd8108
.obj8@85bd8108 := MyOptionBinding
.obj8@85bd8108.__eContents := \
	value/.obj7@85bd8108
.obj8@85bd8108.__eContainer := /bindings.obj12@85bd8108
.obj8@85bd8108.option := .obj6@85bd8108./

# .obj7@85bd8108
.obj7@85bd8108 := MyStringLiteral
.obj7@85bd8108.__eContents := 
.obj7@85bd8108.__eContainer := /value.obj8@85bd8108
.obj7@85bd8108.value := 

# .obj6@85bd8108
.obj6@85bd8108 := ELink
.obj6@85bd8108.eSource := MyFile_OptionBinding_option.obj8@85bd8108
.obj6@85bd8108.eTarget := 
.obj6@85bd8108.name := help
.obj6@85bd8108.origin := 4:33

# .obj11@85bd8108
.obj11@85bd8108 := MyOptionBinding
.obj11@85bd8108.__eContents := \
	value/.obj10@85bd8108
.obj11@85bd8108.__eContainer := /bindings.obj12@85bd8108
.obj11@85bd8108.option := .obj9@85bd8108./

# .obj10@85bd8108
.obj10@85bd8108 := MyStringLiteral
.obj10@85bd8108.__eContents := 
.obj10@85bd8108.__eContainer := /value.obj11@85bd8108
.obj10@85bd8108.value := 

# .obj9@85bd8108
.obj9@85bd8108 := ELink
.obj9@85bd8108.eSource := MyFile_OptionBinding_option.obj11@85bd8108
.obj9@85bd8108.eTarget := 
.obj9@85bd8108.name := man
.obj9@85bd8108.origin := 4:42

# .obj2@85bd8108
.obj2@85bd8108 := ELink
.obj2@85bd8108.eSource := MyFile_Annotation_type.obj12@85bd8108
.obj2@85bd8108.eTarget := 
.obj2@85bd8108.name := Cmd
.obj2@85bd8108.origin := 4:2

# .obj18@85bd8108
.obj18@85bd8108 := MyAnnotation
.obj18@85bd8108.__eContents := \
	bindings/.obj16@85bd8108
.obj18@85bd8108.__eContainer := target/annotations.obj41@85bd8108
.obj18@85bd8108.type := .obj13@85bd8108./

# .obj16@85bd8108
.obj16@85bd8108 := MyOptionBinding
.obj16@85bd8108.__eContents := \
	value/.obj15@85bd8108
.obj16@85bd8108.__eContainer := /bindings.obj18@85bd8108
.obj16@85bd8108.option := .obj17@85bd8108./

# .obj15@85bd8108
.obj15@85bd8108 := MyTypeReferenceLiteral
.obj15@85bd8108.__eContents := 
.obj15@85bd8108.__eContainer := /value.obj16@85bd8108
.obj15@85bd8108.value := .obj14@85bd8108./

# .obj14@85bd8108
.obj14@85bd8108 := ELink
.obj14@85bd8108.eSource := MyFile_TypeReferenceLiteral_value.obj15@85bd8108
.obj14@85bd8108.eTarget := 
.obj14@85bd8108.name := third_party.lib.cjson
.obj14@85bd8108.origin := 5:15

# .obj17@85bd8108
.obj17@85bd8108 := ELink
.obj17@85bd8108.eSource := MyFile_OptionBinding_option.obj16@85bd8108
.obj17@85bd8108.eTarget := 
.obj17@85bd8108.name := value
.obj17@85bd8108.origin := 5:14

# .obj13@85bd8108
.obj13@85bd8108 := ELink
.obj13@85bd8108.eSource := MyFile_Annotation_type.obj18@85bd8108
.obj13@85bd8108.eTarget := 
.obj13@85bd8108.name := BuildDepends
.obj13@85bd8108.origin := 5:2


__resource-mk/.cache/mybuild/files/platform/stm32f4_iocontrol/http_admin/Mybuild.mk := .obj1@85bd8108
