# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1hnd

# The following objects have been sealed to prevent further serialization.
.hnd1hnd.__serial_id__ := .hnd1hnd
.hnd2hnd.__serial_id__ := .hnd2hnd
.hnd3hnd.__serial_id__ := .hnd3hnd
.hnd4hnd.__serial_id__ := .hnd4hnd
.hnd5hnd.__serial_id__ := .hnd5hnd
.hnd6hnd.__serial_id__ := .hnd6hnd
.hnd7hnd.__serial_id__ := .hnd7hnd
.hnd8hnd.__serial_id__ := .hnd8hnd
# .obj1hnd
.hnd1hnd := AnnotationsCore
.hnd1hnd.avaibleAnnotations := \
	Build/mybuild.lang.IfNeed \
	Build/mybuild.lang.DefaultImpl \
	MyLink/mybuild.lang.DefaultImpl \
	Build/mybuild.lang.For \
	MyLink/mybuild.lang.TestFor \
	Build/mybuild.lang.TestFor \
	Build/mybuild.lang.WithTest
.hnd1hnd.avaibleAnnotations.Build/mybuild.lang.IfNeed := .hnd2hnd
.hnd1hnd.avaibleAnnotations.Build/mybuild.lang.DefaultImpl := .hnd3hnd
.hnd1hnd.avaibleAnnotations.MyLink/mybuild.lang.DefaultImpl := .hnd4hnd
.hnd1hnd.avaibleAnnotations.Build/mybuild.lang.For := .hnd5hnd
.hnd1hnd.avaibleAnnotations.MyLink/mybuild.lang.TestFor := .hnd6hnd
.hnd1hnd.avaibleAnnotations.Build/mybuild.lang.TestFor := .hnd7hnd
.hnd1hnd.avaibleAnnotations.Build/mybuild.lang.WithTest := .hnd8hnd

# .obj2hnd
.hnd2hnd := IfNeedAnnotationCallback
.hnd2hnd.annotationType := 
.hnd2hnd.target := 
.hnd2hnd.options := 

# .obj3hnd
.hnd3hnd := DefaultImplAnnotationCallback
.hnd3hnd.annotationType := 
.hnd3hnd.target := 
.hnd3hnd.options := 

# .obj4hnd
.hnd4hnd := DefaultImplAnnotationCallback
.hnd4hnd.annotationType := 
.hnd4hnd.target := 
.hnd4hnd.options := 

# .obj5hnd
.hnd5hnd := ForAnnotationCallback
.hnd5hnd.annotationType := 
.hnd5hnd.target := 
.hnd5hnd.options := 

# .obj6hnd
.hnd6hnd := TestForAnnotationCallback
.hnd6hnd.annotationType := 
.hnd6hnd.target := 
.hnd6hnd.options := 

# .obj7hnd
.hnd7hnd := TestForAnnotationCallback
.hnd7hnd.annotationType := 
.hnd7hnd.target := 
.hnd7hnd.options := 

# .obj8hnd
.hnd8hnd := WithTestAnnotationCallback
.hnd8hnd.annotationType := 
.hnd8hnd.target := 
.hnd8hnd.options := 


# List of objects requested to be serialized explicitly.
annotationsCore := \
	.hnd1hnd

