# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@1a58c717

# .obj1@1a58c717
.obj1@1a58c717 := MyFileResource
.obj1@1a58c717.issues := 
.obj1@1a58c717.contentsRoot := .obj8@1a58c717
.obj1@1a58c717.resourceSet := 
.obj1@1a58c717.fileName := src/arch/mips/subarch/p5600/Mybuild
.obj1@1a58c717.exports := \
	embox.arch.mips.subarch.p5600 \
	embox.arch.mips.subarch.p5600.arch
.obj1@1a58c717.exports.embox.arch.mips.subarch.p5600 := \
	.obj8@1a58c717
.obj1@1a58c717.exports.embox.arch.mips.subarch.p5600.arch := \
	.obj7@1a58c717

# .obj8@1a58c717
.obj8@1a58c717 := MyFileContentRoot
.obj8@1a58c717.__eContents := \
	types/.obj7@1a58c717
.obj8@1a58c717.__eContainer := .obj1@1a58c717
.obj8@1a58c717.imports := 
.obj8@1a58c717.name := embox.arch.mips.subarch.p5600
.obj8@1a58c717.origin := 

# .obj7@1a58c717
.obj7@1a58c717 := MyModuleType
.obj7@1a58c717.__eContents := \
	sourcesMembers/.obj4@1a58c717 \
	dependsMembers/.obj6@1a58c717
.obj7@1a58c717.__eContainer := fileContentRoot/types.obj8@1a58c717
.obj7@1a58c717.dependent := 
.obj7@1a58c717.subTypes := 
.obj7@1a58c717.modifiers := 
.obj7@1a58c717.name := arch
.obj7@1a58c717.origin := 3:8
.obj7@1a58c717.superType := .obj2@1a58c717./
.obj7@1a58c717.customStorage := 

# .obj4@1a58c717
.obj4@1a58c717 := MySourceMember
.obj4@1a58c717.__eContents := \
	files/.obj3@1a58c717
.obj4@1a58c717.__eContainer := /sourcesMembers.obj7@1a58c717
.obj4@1a58c717.module := 

# .obj3@1a58c717
.obj3@1a58c717 := MyFileName
.obj3@1a58c717.__eContents := 
.obj3@1a58c717.__eContainer := /files.obj4@1a58c717
.obj3@1a58c717.fileName := mips32_p5600_arch.c

# .obj6@1a58c717
.obj6@1a58c717 := MyDependsMember
.obj6@1a58c717.__eContents := 
.obj6@1a58c717.__eContainer := /dependsMembers.obj7@1a58c717
.obj6@1a58c717.modules := \
	.obj5@1a58c717./
.obj6@1a58c717.module := 

# .obj5@1a58c717
.obj5@1a58c717 := ELink
.obj5@1a58c717.eSource := MyFile_DependsMember_modules.obj6@1a58c717
.obj5@1a58c717.eTarget := 
.obj5@1a58c717.name := embox.arch.mips.subarch.p5600.global_control_block
.obj5@1a58c717.origin := 6:10

# .obj2@1a58c717
.obj2@1a58c717 := ELink
.obj2@1a58c717.eSource := MyFile_ModuleType_superType.obj7@1a58c717
.obj2@1a58c717.eTarget := 
.obj2@1a58c717.name := embox.arch.arch
.obj2@1a58c717.origin := 3:21


__resource-mk/.cache/mybuild/files/src/arch/mips/subarch/p5600/Mybuild.mk := .obj1@1a58c717
