# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@680771d8

# .obj1@680771d8
.obj1@680771d8 := MyFileResource
.obj1@680771d8.issues := 
.obj1@680771d8.contentsRoot := .obj14@680771d8
.obj1@680771d8.resourceSet := 
.obj1@680771d8.fileName := src/kernel/task/resource/task_heap/Mybuild
.obj1@680771d8.exports := \
	embox.kernel.task.resource \
	embox.kernel.task.resource.task_heap
.obj1@680771d8.exports.embox.kernel.task.resource := \
	.obj14@680771d8
.obj1@680771d8.exports.embox.kernel.task.resource.task_heap := \
	.obj13@680771d8

# .obj14@680771d8
.obj14@680771d8 := MyFileContentRoot
.obj14@680771d8.__eContents := \
	types/.obj13@680771d8
.obj14@680771d8.__eContainer := .obj1@680771d8
.obj14@680771d8.imports := 
.obj14@680771d8.name := embox.kernel.task.resource
.obj14@680771d8.origin := 

# .obj13@680771d8
.obj13@680771d8 := MyModuleType
.obj13@680771d8.__eContents := \
	sourcesMembers/.obj8@680771d8 \
	sourcesMembers/.obj10@680771d8 \
	dependsMembers/.obj12@680771d8
.obj13@680771d8.__eContainer := fileContentRoot/types.obj14@680771d8
.obj13@680771d8.dependent := 
.obj13@680771d8.subTypes := 
.obj13@680771d8.modifiers := 
.obj13@680771d8.name := task_heap
.obj13@680771d8.origin := 3:8
.obj13@680771d8.superType := 
.obj13@680771d8.customStorage := 

# .obj8@680771d8
.obj8@680771d8 := MySourceMember
.obj8@680771d8.__eContents := \
	files/.obj7@680771d8 \
	annotations/.obj6@680771d8
.obj8@680771d8.__eContainer := /sourcesMembers.obj13@680771d8
.obj8@680771d8.module := 

# .obj7@680771d8
.obj7@680771d8 := MyFileName
.obj7@680771d8.__eContents := 
.obj7@680771d8.__eContainer := /files.obj8@680771d8
.obj7@680771d8.fileName := task_heap.h

# .obj6@680771d8
.obj6@680771d8 := MyAnnotation
.obj6@680771d8.__eContents := \
	bindings/.obj5@680771d8
.obj6@680771d8.__eContainer := target/annotations.obj8@680771d8
.obj6@680771d8.type := .obj2@680771d8./

# .obj5@680771d8
.obj5@680771d8 := MyOptionBinding
.obj5@680771d8.__eContents := \
	value/.obj4@680771d8
.obj5@680771d8.__eContainer := /bindings.obj6@680771d8
.obj5@680771d8.option := .obj3@680771d8./

# .obj4@680771d8
.obj4@680771d8 := MyStringLiteral
.obj4@680771d8.__eContents := 
.obj4@680771d8.__eContainer := /value.obj5@680771d8
.obj4@680771d8.value := kernel/task/resource

# .obj3@680771d8
.obj3@680771d8 := ELink
.obj3@680771d8.eSource := MyFile_OptionBinding_option.obj5@680771d8
.obj3@680771d8.eTarget := 
.obj3@680771d8.name := path
.obj3@680771d8.origin := 4:17

# .obj2@680771d8
.obj2@680771d8 := ELink
.obj2@680771d8.eSource := MyFile_Annotation_type.obj6@680771d8
.obj2@680771d8.eTarget := 
.obj2@680771d8.name := IncludeExport
.obj2@680771d8.origin := 4:3

# .obj10@680771d8
.obj10@680771d8 := MySourceMember
.obj10@680771d8.__eContents := \
	files/.obj9@680771d8
.obj10@680771d8.__eContainer := /sourcesMembers.obj13@680771d8
.obj10@680771d8.module := 

# .obj9@680771d8
.obj9@680771d8 := MyFileName
.obj9@680771d8.__eContents := 
.obj9@680771d8.__eContainer := /files.obj10@680771d8
.obj9@680771d8.fileName := task_heap.c

# .obj12@680771d8
.obj12@680771d8 := MyDependsMember
.obj12@680771d8.__eContents := 
.obj12@680771d8.__eContainer := /dependsMembers.obj13@680771d8
.obj12@680771d8.modules := \
	.obj11@680771d8./
.obj12@680771d8.module := 

# .obj11@680771d8
.obj11@680771d8 := ELink
.obj11@680771d8.eSource := MyFile_DependsMember_modules.obj12@680771d8
.obj11@680771d8.eTarget := 
.obj11@680771d8.name := embox.kernel.task.task_resource
.obj11@680771d8.origin := 8:10


__resource-mk/.cache/mybuild/files/src/kernel/task/resource/task_heap/Mybuild.mk := .obj1@680771d8
