# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@764e3754

# .obj1@764e3754
.obj1@764e3754 := MyFileResource
.obj1@764e3754.issues := 
.obj1@764e3754.contentsRoot := .obj15@764e3754
.obj1@764e3754.resourceSet := 
.obj1@764e3754.fileName := src/drivers/net/usermode/Mybuild
.obj1@764e3754.exports := \
	embox.driver.net \
	embox.driver.net.usermode
.obj1@764e3754.exports.embox.driver.net := \
	.obj15@764e3754
.obj1@764e3754.exports.embox.driver.net.usermode := \
	.obj14@764e3754

# .obj15@764e3754
.obj15@764e3754 := MyFileContentRoot
.obj15@764e3754.__eContents := \
	types/.obj14@764e3754
.obj15@764e3754.__eContainer := .obj1@764e3754
.obj15@764e3754.imports := 
.obj15@764e3754.name := embox.driver.net
.obj15@764e3754.origin := 

# .obj14@764e3754
.obj14@764e3754 := MyModuleType
.obj14@764e3754.__eContents := \
	sourcesMembers/.obj3@764e3754 \
	dependsMembers/.obj5@764e3754 \
	dependsMembers/.obj7@764e3754 \
	dependsMembers/.obj9@764e3754 \
	dependsMembers/.obj11@764e3754 \
	dependsMembers/.obj13@764e3754
.obj14@764e3754.__eContainer := fileContentRoot/types.obj15@764e3754
.obj14@764e3754.dependent := 
.obj14@764e3754.subTypes := 
.obj14@764e3754.modifiers := 
.obj14@764e3754.name := usermode
.obj14@764e3754.origin := 3:8
.obj14@764e3754.superType := 
.obj14@764e3754.customStorage := 

# .obj3@764e3754
.obj3@764e3754 := MySourceMember
.obj3@764e3754.__eContents := \
	files/.obj2@764e3754
.obj3@764e3754.__eContainer := /sourcesMembers.obj14@764e3754
.obj3@764e3754.module := 

# .obj2@764e3754
.obj2@764e3754 := MyFileName
.obj2@764e3754.__eContents := 
.obj2@764e3754.__eContainer := /files.obj3@764e3754
.obj2@764e3754.fileName := usermode.c

# .obj5@764e3754
.obj5@764e3754 := MyDependsMember
.obj5@764e3754.__eContents := 
.obj5@764e3754.__eContainer := /dependsMembers.obj14@764e3754
.obj5@764e3754.modules := \
	.obj4@764e3754./
.obj5@764e3754.module := 

# .obj4@764e3754
.obj4@764e3754 := ELink
.obj4@764e3754.eSource := MyFile_DependsMember_modules.obj5@764e3754
.obj4@764e3754.eTarget := 
.obj4@764e3754.name := embox.net.skbuff
.obj4@764e3754.origin := 5:10

# .obj7@764e3754
.obj7@764e3754 := MyDependsMember
.obj7@764e3754.__eContents := 
.obj7@764e3754.__eContainer := /dependsMembers.obj14@764e3754
.obj7@764e3754.modules := \
	.obj6@764e3754./
.obj7@764e3754.module := 

# .obj6@764e3754
.obj6@764e3754 := ELink
.obj6@764e3754.eSource := MyFile_DependsMember_modules.obj7@764e3754
.obj6@764e3754.eTarget := 
.obj6@764e3754.name := embox.net.l2.ethernet
.obj6@764e3754.origin := 6:10

# .obj9@764e3754
.obj9@764e3754 := MyDependsMember
.obj9@764e3754.__eContents := 
.obj9@764e3754.__eContainer := /dependsMembers.obj14@764e3754
.obj9@764e3754.modules := \
	.obj8@764e3754./
.obj9@764e3754.module := 

# .obj8@764e3754
.obj8@764e3754 := ELink
.obj8@764e3754.eSource := MyFile_DependsMember_modules.obj9@764e3754
.obj8@764e3754.eTarget := 
.obj8@764e3754.name := embox.kernel.irq
.obj8@764e3754.origin := 7:10

# .obj11@764e3754
.obj11@764e3754 := MyDependsMember
.obj11@764e3754.__eContents := 
.obj11@764e3754.__eContainer := /dependsMembers.obj14@764e3754
.obj11@764e3754.modules := \
	.obj10@764e3754./
.obj11@764e3754.module := 

# .obj10@764e3754
.obj10@764e3754 := ELink
.obj10@764e3754.eSource := MyFile_DependsMember_modules.obj11@764e3754
.obj10@764e3754.eTarget := 
.obj10@764e3754.name := embox.net.dev
.obj10@764e3754.origin := 8:10

# .obj13@764e3754
.obj13@764e3754 := MyDependsMember
.obj13@764e3754.__eContents := 
.obj13@764e3754.__eContainer := /dependsMembers.obj14@764e3754
.obj13@764e3754.modules := \
	.obj12@764e3754./
.obj13@764e3754.module := 

# .obj12@764e3754
.obj12@764e3754 := ELink
.obj12@764e3754.eSource := MyFile_DependsMember_modules.obj13@764e3754
.obj12@764e3754.eTarget := 
.obj12@764e3754.name := embox.net.entry_api
.obj12@764e3754.origin := 9:10


__resource-mk/.cache/mybuild/files/src/drivers/net/usermode/Mybuild.mk := .obj1@764e3754
