# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@b2eceaa2

# .obj1@b2eceaa2
.obj1@b2eceaa2 := MyFileResource
.obj1@b2eceaa2.issues := 
.obj1@b2eceaa2.contentsRoot := .obj26@b2eceaa2
.obj1@b2eceaa2.resourceSet := 
.obj1@b2eceaa2.fileName := src/arch/x86/boot/Mybuild
.obj1@b2eceaa2.exports := \
	embox.arch.x86.boot \
	embox.arch.x86.boot.real_boot \
	embox.arch.x86.boot.multiboot \
	embox.arch.x86.boot.multiboot.video_mode_set \
	embox.arch.x86.boot.multiboot.video_width \
	embox.arch.x86.boot.multiboot.video_height \
	embox.arch.x86.boot.multiboot.video_depth
.obj1@b2eceaa2.exports.embox.arch.x86.boot := \
	.obj26@b2eceaa2
.obj1@b2eceaa2.exports.embox.arch.x86.boot.real_boot := \
	.obj4@b2eceaa2
.obj1@b2eceaa2.exports.embox.arch.x86.boot.multiboot := \
	.obj25@b2eceaa2
.obj1@b2eceaa2.exports.embox.arch.x86.boot.multiboot.video_mode_set := \
	.obj11@b2eceaa2
.obj1@b2eceaa2.exports.embox.arch.x86.boot.multiboot.video_width := \
	.obj14@b2eceaa2
.obj1@b2eceaa2.exports.embox.arch.x86.boot.multiboot.video_height := \
	.obj17@b2eceaa2
.obj1@b2eceaa2.exports.embox.arch.x86.boot.multiboot.video_depth := \
	.obj20@b2eceaa2

# .obj26@b2eceaa2
.obj26@b2eceaa2 := MyFileContentRoot
.obj26@b2eceaa2.__eContents := \
	types/.obj4@b2eceaa2 \
	types/.obj25@b2eceaa2
.obj26@b2eceaa2.__eContainer := .obj1@b2eceaa2
.obj26@b2eceaa2.imports := 
.obj26@b2eceaa2.name := embox.arch.x86.boot
.obj26@b2eceaa2.origin := 

# .obj4@b2eceaa2
.obj4@b2eceaa2 := MyModuleType
.obj4@b2eceaa2.__eContents := \
	sourcesMembers/.obj3@b2eceaa2
.obj4@b2eceaa2.__eContainer := fileContentRoot/types.obj26@b2eceaa2
.obj4@b2eceaa2.dependent := 
.obj4@b2eceaa2.subTypes := 
.obj4@b2eceaa2.modifiers := 
.obj4@b2eceaa2.name := real_boot
.obj4@b2eceaa2.origin := 3:8
.obj4@b2eceaa2.superType := 
.obj4@b2eceaa2.customStorage := 

# .obj3@b2eceaa2
.obj3@b2eceaa2 := MySourceMember
.obj3@b2eceaa2.__eContents := \
	files/.obj2@b2eceaa2
.obj3@b2eceaa2.__eContainer := /sourcesMembers.obj4@b2eceaa2
.obj3@b2eceaa2.module := 

# .obj2@b2eceaa2
.obj2@b2eceaa2 := MyFileName
.obj2@b2eceaa2.__eContents := 
.obj2@b2eceaa2.__eContainer := /files.obj3@b2eceaa2
.obj2@b2eceaa2.fileName := realmode_boot.S

# .obj25@b2eceaa2
.obj25@b2eceaa2 := MyModuleType
.obj25@b2eceaa2.__eContents := \
	sourcesMembers/.obj6@b2eceaa2 \
	sourcesMembers/.obj8@b2eceaa2 \
	sourcesMembers/.obj10@b2eceaa2 \
	optionsMembers/.obj13@b2eceaa2 \
	optionsMembers/.obj16@b2eceaa2 \
	optionsMembers/.obj19@b2eceaa2 \
	optionsMembers/.obj22@b2eceaa2 \
	dependsMembers/.obj24@b2eceaa2
.obj25@b2eceaa2.__eContainer := fileContentRoot/types.obj26@b2eceaa2
.obj25@b2eceaa2.dependent := 
.obj25@b2eceaa2.subTypes := 
.obj25@b2eceaa2.modifiers := 
.obj25@b2eceaa2.name := multiboot
.obj25@b2eceaa2.origin := 7:8
.obj25@b2eceaa2.superType := 
.obj25@b2eceaa2.customStorage := 

# .obj6@b2eceaa2
.obj6@b2eceaa2 := MySourceMember
.obj6@b2eceaa2.__eContents := \
	files/.obj5@b2eceaa2
.obj6@b2eceaa2.__eContainer := /sourcesMembers.obj25@b2eceaa2
.obj6@b2eceaa2.module := 

# .obj5@b2eceaa2
.obj5@b2eceaa2 := MyFileName
.obj5@b2eceaa2.__eContents := 
.obj5@b2eceaa2.__eContainer := /files.obj6@b2eceaa2
.obj5@b2eceaa2.fileName := boot.S

# .obj8@b2eceaa2
.obj8@b2eceaa2 := MySourceMember
.obj8@b2eceaa2.__eContents := \
	files/.obj7@b2eceaa2
.obj8@b2eceaa2.__eContainer := /sourcesMembers.obj25@b2eceaa2
.obj8@b2eceaa2.module := 

# .obj7@b2eceaa2
.obj7@b2eceaa2 := MyFileName
.obj7@b2eceaa2.__eContents := 
.obj7@b2eceaa2.__eContainer := /files.obj8@b2eceaa2
.obj7@b2eceaa2.fileName := multiboot_header.S

# .obj10@b2eceaa2
.obj10@b2eceaa2 := MySourceMember
.obj10@b2eceaa2.__eContents := \
	files/.obj9@b2eceaa2
.obj10@b2eceaa2.__eContainer := /sourcesMembers.obj25@b2eceaa2
.obj10@b2eceaa2.module := 

# .obj9@b2eceaa2
.obj9@b2eceaa2 := MyFileName
.obj9@b2eceaa2.__eContents := 
.obj9@b2eceaa2.__eContainer := /files.obj10@b2eceaa2
.obj9@b2eceaa2.fileName := multiboot.c

# .obj13@b2eceaa2
.obj13@b2eceaa2 := MyOptionMember
.obj13@b2eceaa2.__eContents := \
	options/.obj11@b2eceaa2
.obj13@b2eceaa2.__eContainer := /optionsMembers.obj25@b2eceaa2
.obj13@b2eceaa2.module := 

# .obj11@b2eceaa2
.obj11@b2eceaa2 := MyNumberOption
.obj11@b2eceaa2.__eContents := \
	defaultValue/.obj12@b2eceaa2
.obj11@b2eceaa2.__eContainer := /options.obj13@b2eceaa2
.obj11@b2eceaa2.name := video_mode_set
.obj11@b2eceaa2.origin := 

# .obj12@b2eceaa2
.obj12@b2eceaa2 := MyNumberLiteral
.obj12@b2eceaa2.__eContents := 
.obj12@b2eceaa2.__eContainer := /defaultValue.obj11@b2eceaa2
.obj12@b2eceaa2.value := 0

# .obj16@b2eceaa2
.obj16@b2eceaa2 := MyOptionMember
.obj16@b2eceaa2.__eContents := \
	options/.obj14@b2eceaa2
.obj16@b2eceaa2.__eContainer := /optionsMembers.obj25@b2eceaa2
.obj16@b2eceaa2.module := 

# .obj14@b2eceaa2
.obj14@b2eceaa2 := MyNumberOption
.obj14@b2eceaa2.__eContents := \
	defaultValue/.obj15@b2eceaa2
.obj14@b2eceaa2.__eContainer := /options.obj16@b2eceaa2
.obj14@b2eceaa2.name := video_width
.obj14@b2eceaa2.origin := 

# .obj15@b2eceaa2
.obj15@b2eceaa2 := MyNumberLiteral
.obj15@b2eceaa2.__eContents := 
.obj15@b2eceaa2.__eContainer := /defaultValue.obj14@b2eceaa2
.obj15@b2eceaa2.value := 800

# .obj19@b2eceaa2
.obj19@b2eceaa2 := MyOptionMember
.obj19@b2eceaa2.__eContents := \
	options/.obj17@b2eceaa2
.obj19@b2eceaa2.__eContainer := /optionsMembers.obj25@b2eceaa2
.obj19@b2eceaa2.module := 

# .obj17@b2eceaa2
.obj17@b2eceaa2 := MyNumberOption
.obj17@b2eceaa2.__eContents := \
	defaultValue/.obj18@b2eceaa2
.obj17@b2eceaa2.__eContainer := /options.obj19@b2eceaa2
.obj17@b2eceaa2.name := video_height
.obj17@b2eceaa2.origin := 

# .obj18@b2eceaa2
.obj18@b2eceaa2 := MyNumberLiteral
.obj18@b2eceaa2.__eContents := 
.obj18@b2eceaa2.__eContainer := /defaultValue.obj17@b2eceaa2
.obj18@b2eceaa2.value := 600

# .obj22@b2eceaa2
.obj22@b2eceaa2 := MyOptionMember
.obj22@b2eceaa2.__eContents := \
	options/.obj20@b2eceaa2
.obj22@b2eceaa2.__eContainer := /optionsMembers.obj25@b2eceaa2
.obj22@b2eceaa2.module := 

# .obj20@b2eceaa2
.obj20@b2eceaa2 := MyNumberOption
.obj20@b2eceaa2.__eContents := \
	defaultValue/.obj21@b2eceaa2
.obj20@b2eceaa2.__eContainer := /options.obj22@b2eceaa2
.obj20@b2eceaa2.name := video_depth
.obj20@b2eceaa2.origin := 

# .obj21@b2eceaa2
.obj21@b2eceaa2 := MyNumberLiteral
.obj21@b2eceaa2.__eContents := 
.obj21@b2eceaa2.__eContainer := /defaultValue.obj20@b2eceaa2
.obj21@b2eceaa2.value := 24

# .obj24@b2eceaa2
.obj24@b2eceaa2 := MyDependsMember
.obj24@b2eceaa2.__eContents := 
.obj24@b2eceaa2.__eContainer := /dependsMembers.obj25@b2eceaa2
.obj24@b2eceaa2.modules := \
	.obj23@b2eceaa2./
.obj24@b2eceaa2.module := 

# .obj23@b2eceaa2
.obj23@b2eceaa2 := ELink
.obj23@b2eceaa2.eSource := MyFile_DependsMember_modules.obj24@b2eceaa2
.obj23@b2eceaa2.eTarget := 
.obj23@b2eceaa2.name := embox.arch.x86.kernel.arch
.obj23@b2eceaa2.origin := 17:10


__resource-mk/.cache/mybuild/files/src/arch/x86/boot/Mybuild.mk := .obj1@b2eceaa2
