# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@906415a1

# .obj1@906415a1
.obj1@906415a1 := MyFileResource
.obj1@906415a1.issues := 
.obj1@906415a1.contentsRoot := .obj16@906415a1
.obj1@906415a1.resourceSet := 
.obj1@906415a1.fileName := src/arch/microblaze/mmu/Mybuild
.obj1@906415a1.exports := \
	embox.arch.microblaze \
	embox.arch.microblaze.mmu \
	embox.arch.microblaze.mmuinfo
.obj1@906415a1.exports.embox.arch.microblaze := \
	.obj16@906415a1
.obj1@906415a1.exports.embox.arch.microblaze.mmu := \
	.obj11@906415a1
.obj1@906415a1.exports.embox.arch.microblaze.mmuinfo := \
	.obj15@906415a1

# .obj16@906415a1
.obj16@906415a1 := MyFileContentRoot
.obj16@906415a1.__eContents := \
	types/.obj11@906415a1 \
	types/.obj15@906415a1
.obj16@906415a1.__eContainer := .obj1@906415a1
.obj16@906415a1.imports := 
.obj16@906415a1.name := embox.arch.microblaze
.obj16@906415a1.origin := 

# .obj11@906415a1
.obj11@906415a1 := MyModuleType
.obj11@906415a1.__eContents := \
	sourcesMembers/.obj4@906415a1 \
	sourcesMembers/.obj6@906415a1 \
	sourcesMembers/.obj8@906415a1 \
	dependsMembers/.obj10@906415a1
.obj11@906415a1.__eContainer := fileContentRoot/types.obj16@906415a1
.obj11@906415a1.dependent := 
.obj11@906415a1.subTypes := 
.obj11@906415a1.modifiers := 
.obj11@906415a1.name := mmu
.obj11@906415a1.origin := 3:8
.obj11@906415a1.superType := .obj2@906415a1./
.obj11@906415a1.customStorage := 

# .obj4@906415a1
.obj4@906415a1 := MySourceMember
.obj4@906415a1.__eContents := \
	files/.obj3@906415a1
.obj4@906415a1.__eContainer := /sourcesMembers.obj11@906415a1
.obj4@906415a1.module := 

# .obj3@906415a1
.obj3@906415a1 := MyFileName
.obj3@906415a1.__eContents := 
.obj3@906415a1.__eContainer := /files.obj4@906415a1
.obj3@906415a1.fileName := mmu_core.c

# .obj6@906415a1
.obj6@906415a1 := MySourceMember
.obj6@906415a1.__eContents := \
	files/.obj5@906415a1
.obj6@906415a1.__eContainer := /sourcesMembers.obj11@906415a1
.obj6@906415a1.module := 

# .obj5@906415a1
.obj5@906415a1 := MyFileName
.obj5@906415a1.__eContents := 
.obj5@906415a1.__eContainer := /files.obj6@906415a1
.obj5@906415a1.fileName := mmu.c

# .obj8@906415a1
.obj8@906415a1 := MySourceMember
.obj8@906415a1.__eContents := \
	files/.obj7@906415a1
.obj8@906415a1.__eContainer := /sourcesMembers.obj11@906415a1
.obj8@906415a1.module := 

# .obj7@906415a1
.obj7@906415a1 := MyFileName
.obj7@906415a1.__eContents := 
.obj7@906415a1.__eContainer := /files.obj8@906415a1
.obj7@906415a1.fileName := mmu.h

# .obj10@906415a1
.obj10@906415a1 := MyDependsMember
.obj10@906415a1.__eContents := 
.obj10@906415a1.__eContainer := /dependsMembers.obj11@906415a1
.obj10@906415a1.modules := \
	.obj9@906415a1./
.obj10@906415a1.module := 

# .obj9@906415a1
.obj9@906415a1 := ELink
.obj9@906415a1.eSource := MyFile_DependsMember_modules.obj10@906415a1
.obj9@906415a1.eTarget := 
.obj9@906415a1.name := embox.mem.vmem_depends
.obj9@906415a1.origin := 8:10

# .obj2@906415a1
.obj2@906415a1 := ELink
.obj2@906415a1.eSource := MyFile_ModuleType_superType.obj11@906415a1
.obj2@906415a1.eTarget := 
.obj2@906415a1.name := embox.mem.vmem
.obj2@906415a1.origin := 3:20

# .obj15@906415a1
.obj15@906415a1 := MyModuleType
.obj15@906415a1.__eContents := \
	sourcesMembers/.obj14@906415a1
.obj15@906415a1.__eContainer := fileContentRoot/types.obj16@906415a1
.obj15@906415a1.dependent := 
.obj15@906415a1.subTypes := 
.obj15@906415a1.modifiers := 
.obj15@906415a1.name := mmuinfo
.obj15@906415a1.origin := 11:8
.obj15@906415a1.superType := .obj12@906415a1./
.obj15@906415a1.customStorage := 

# .obj14@906415a1
.obj14@906415a1 := MySourceMember
.obj14@906415a1.__eContents := \
	files/.obj13@906415a1
.obj14@906415a1.__eContainer := /sourcesMembers.obj15@906415a1
.obj14@906415a1.module := 

# .obj13@906415a1
.obj13@906415a1 := MyFileName
.obj13@906415a1.__eContents := 
.obj13@906415a1.__eContainer := /files.obj14@906415a1
.obj13@906415a1.fileName := mmuinfo.c

# .obj12@906415a1
.obj12@906415a1 := ELink
.obj12@906415a1.eSource := MyFile_ModuleType_superType.obj15@906415a1
.obj12@906415a1.eTarget := 
.obj12@906415a1.name := embox.arch.mmuinfo
.obj12@906415a1.origin := 11:24


__resource-mk/.cache/mybuild/files/src/arch/microblaze/mmu/Mybuild.mk := .obj1@906415a1
