# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@edac1ce5

# .obj1@edac1ce5
.obj1@edac1ce5 := MyFileResource
.obj1@edac1ce5.issues := 
.obj1@edac1ce5.contentsRoot := .obj39@edac1ce5
.obj1@edac1ce5.resourceSet := 
.obj1@edac1ce5.fileName := src/service/http_admin/Mybuild
.obj1@edac1ce5.exports := \
	embox.service \
	embox.service.http_admin \
	embox.service.http_admin.log_level
.obj1@edac1ce5.exports.embox.service := \
	.obj39@edac1ce5
.obj1@edac1ce5.exports.embox.service.http_admin := \
	.obj38@edac1ce5
.obj1@edac1ce5.exports.embox.service.http_admin.log_level := \
	.obj21@edac1ce5

# .obj39@edac1ce5
.obj39@edac1ce5 := MyFileContentRoot
.obj39@edac1ce5.__eContents := \
	types/.obj38@edac1ce5
.obj39@edac1ce5.__eContainer := .obj1@edac1ce5
.obj39@edac1ce5.imports := 
.obj39@edac1ce5.name := embox.service
.obj39@edac1ce5.origin := 

# .obj38@edac1ce5
.obj38@edac1ce5 := MyModuleType
.obj38@edac1ce5.__eContents := \
	sourcesMembers/.obj25@edac1ce5 \
	sourcesMembers/.obj33@edac1ce5 \
	optionsMembers/.obj23@edac1ce5 \
	dependsMembers/.obj35@edac1ce5 \
	dependsMembers/.obj37@edac1ce5 \
	annotations/.obj3@edac1ce5 \
	annotations/.obj14@edac1ce5 \
	annotations/.obj20@edac1ce5
.obj38@edac1ce5.__eContainer := fileContentRoot/types.obj39@edac1ce5
.obj38@edac1ce5.dependent := 
.obj38@edac1ce5.subTypes := 
.obj38@edac1ce5.modifiers := 
.obj38@edac1ce5.name := http_admin
.obj38@edac1ce5.origin := 7:8
.obj38@edac1ce5.superType := 
.obj38@edac1ce5.customStorage := 

# .obj25@edac1ce5
.obj25@edac1ce5 := MySourceMember
.obj25@edac1ce5.__eContents := \
	files/.obj24@edac1ce5
.obj25@edac1ce5.__eContainer := /sourcesMembers.obj38@edac1ce5
.obj25@edac1ce5.module := 

# .obj24@edac1ce5
.obj24@edac1ce5 := MyFileName
.obj24@edac1ce5.__eContents := 
.obj24@edac1ce5.__eContainer := /files.obj25@edac1ce5
.obj24@edac1ce5.fileName := http_admin_backend.c

# .obj33@edac1ce5
.obj33@edac1ce5 := MySourceMember
.obj33@edac1ce5.__eContents := \
	files/.obj31@edac1ce5 \
	files/.obj32@edac1ce5 \
	annotations/.obj30@edac1ce5
.obj33@edac1ce5.__eContainer := /sourcesMembers.obj38@edac1ce5
.obj33@edac1ce5.module := 

# .obj31@edac1ce5
.obj31@edac1ce5 := MyFileName
.obj31@edac1ce5.__eContents := 
.obj31@edac1ce5.__eContainer := /files.obj33@edac1ce5
.obj31@edac1ce5.fileName := index.html

# .obj32@edac1ce5
.obj32@edac1ce5 := MyFileName
.obj32@edac1ce5.__eContents := 
.obj32@edac1ce5.__eContainer := /files.obj33@edac1ce5
.obj32@edac1ce5.fileName := app.js

# .obj30@edac1ce5
.obj30@edac1ce5 := MyAnnotation
.obj30@edac1ce5.__eContents := \
	bindings/.obj29@edac1ce5
.obj30@edac1ce5.__eContainer := target/annotations.obj33@edac1ce5
.obj30@edac1ce5.type := .obj26@edac1ce5./

# .obj29@edac1ce5
.obj29@edac1ce5 := MyOptionBinding
.obj29@edac1ce5.__eContents := \
	value/.obj28@edac1ce5
.obj29@edac1ce5.__eContainer := /bindings.obj30@edac1ce5
.obj29@edac1ce5.option := .obj27@edac1ce5./

# .obj28@edac1ce5
.obj28@edac1ce5 := MyStringLiteral
.obj28@edac1ce5.__eContents := 
.obj28@edac1ce5.__eContainer := /value.obj29@edac1ce5
.obj28@edac1ce5.value := http_admin

# .obj27@edac1ce5
.obj27@edac1ce5 := ELink
.obj27@edac1ce5.eSource := MyFile_OptionBinding_option.obj29@edac1ce5
.obj27@edac1ce5.eTarget := 
.obj27@edac1ce5.name := target_dir
.obj27@edac1ce5.origin := 11:10

# .obj26@edac1ce5
.obj26@edac1ce5 := ELink
.obj26@edac1ce5.eSource := MyFile_Annotation_type.obj30@edac1ce5
.obj26@edac1ce5.eTarget := 
.obj26@edac1ce5.name := InitFS
.obj26@edac1ce5.origin := 11:3

# .obj23@edac1ce5
.obj23@edac1ce5 := MyOptionMember
.obj23@edac1ce5.__eContents := \
	options/.obj21@edac1ce5
.obj23@edac1ce5.__eContainer := /optionsMembers.obj38@edac1ce5
.obj23@edac1ce5.module := 

# .obj21@edac1ce5
.obj21@edac1ce5 := MyNumberOption
.obj21@edac1ce5.__eContents := \
	defaultValue/.obj22@edac1ce5
.obj21@edac1ce5.__eContainer := /options.obj23@edac1ce5
.obj21@edac1ce5.name := log_level
.obj21@edac1ce5.origin := 

# .obj22@edac1ce5
.obj22@edac1ce5 := MyNumberLiteral
.obj22@edac1ce5.__eContents := 
.obj22@edac1ce5.__eContainer := /defaultValue.obj21@edac1ce5
.obj22@edac1ce5.value := 1

# .obj35@edac1ce5
.obj35@edac1ce5 := MyDependsMember
.obj35@edac1ce5.__eContents := 
.obj35@edac1ce5.__eContainer := /dependsMembers.obj38@edac1ce5
.obj35@edac1ce5.modules := \
	.obj34@edac1ce5./
.obj35@edac1ce5.module := 

# .obj34@edac1ce5
.obj34@edac1ce5 := ELink
.obj34@edac1ce5.eSource := MyFile_DependsMember_modules.obj35@edac1ce5
.obj34@edac1ce5.eTarget := 
.obj34@edac1ce5.name := third_party.lib.cjson
.obj34@edac1ce5.origin := 15:10

# .obj37@edac1ce5
.obj37@edac1ce5 := MyDependsMember
.obj37@edac1ce5.__eContents := 
.obj37@edac1ce5.__eContainer := /dependsMembers.obj38@edac1ce5
.obj37@edac1ce5.modules := \
	.obj36@edac1ce5./
.obj37@edac1ce5.module := 

# .obj36@edac1ce5
.obj36@edac1ce5 := ELink
.obj36@edac1ce5.eSource := MyFile_DependsMember_modules.obj37@edac1ce5
.obj36@edac1ce5.eTarget := 
.obj36@edac1ce5.name := embox.compat.libc.stdlib.system
.obj36@edac1ce5.origin := 16:10

# .obj3@edac1ce5
.obj3@edac1ce5 := MyAnnotation
.obj3@edac1ce5.__eContents := 
.obj3@edac1ce5.__eContainer := target/annotations.obj38@edac1ce5
.obj3@edac1ce5.type := .obj2@edac1ce5./

# .obj2@edac1ce5
.obj2@edac1ce5 := ELink
.obj2@edac1ce5.eSource := MyFile_Annotation_type.obj3@edac1ce5
.obj2@edac1ce5.eTarget := 
.obj2@edac1ce5.name := AutoCmd
.obj2@edac1ce5.origin := 4:2

# .obj14@edac1ce5
.obj14@edac1ce5 := MyAnnotation
.obj14@edac1ce5.__eContents := \
	bindings/.obj7@edac1ce5 \
	bindings/.obj10@edac1ce5 \
	bindings/.obj13@edac1ce5
.obj14@edac1ce5.__eContainer := target/annotations.obj38@edac1ce5
.obj14@edac1ce5.type := .obj4@edac1ce5./

# .obj7@edac1ce5
.obj7@edac1ce5 := MyOptionBinding
.obj7@edac1ce5.__eContents := \
	value/.obj6@edac1ce5
.obj7@edac1ce5.__eContainer := /bindings.obj14@edac1ce5
.obj7@edac1ce5.option := .obj5@edac1ce5./

# .obj6@edac1ce5
.obj6@edac1ce5 := MyStringLiteral
.obj6@edac1ce5.__eContents := 
.obj6@edac1ce5.__eContainer := /value.obj7@edac1ce5
.obj6@edac1ce5.value := http_admin_backend

# .obj5@edac1ce5
.obj5@edac1ce5 := ELink
.obj5@edac1ce5.eSource := MyFile_OptionBinding_option.obj7@edac1ce5
.obj5@edac1ce5.eTarget := 
.obj5@edac1ce5.name := name
.obj5@edac1ce5.origin := 5:6

# .obj10@edac1ce5
.obj10@edac1ce5 := MyOptionBinding
.obj10@edac1ce5.__eContents := \
	value/.obj9@edac1ce5
.obj10@edac1ce5.__eContainer := /bindings.obj14@edac1ce5
.obj10@edac1ce5.option := .obj8@edac1ce5./

# .obj9@edac1ce5
.obj9@edac1ce5 := MyStringLiteral
.obj9@edac1ce5.__eContents := 
.obj9@edac1ce5.__eContainer := /value.obj10@edac1ce5
.obj9@edac1ce5.value := 

# .obj8@edac1ce5
.obj8@edac1ce5 := ELink
.obj8@edac1ce5.eSource := MyFile_OptionBinding_option.obj10@edac1ce5
.obj8@edac1ce5.eTarget := 
.obj8@edac1ce5.name := help
.obj8@edac1ce5.origin := 5:33

# .obj13@edac1ce5
.obj13@edac1ce5 := MyOptionBinding
.obj13@edac1ce5.__eContents := \
	value/.obj12@edac1ce5
.obj13@edac1ce5.__eContainer := /bindings.obj14@edac1ce5
.obj13@edac1ce5.option := .obj11@edac1ce5./

# .obj12@edac1ce5
.obj12@edac1ce5 := MyStringLiteral
.obj12@edac1ce5.__eContents := 
.obj12@edac1ce5.__eContainer := /value.obj13@edac1ce5
.obj12@edac1ce5.value := 

# .obj11@edac1ce5
.obj11@edac1ce5 := ELink
.obj11@edac1ce5.eSource := MyFile_OptionBinding_option.obj13@edac1ce5
.obj11@edac1ce5.eTarget := 
.obj11@edac1ce5.name := man
.obj11@edac1ce5.origin := 5:42

# .obj4@edac1ce5
.obj4@edac1ce5 := ELink
.obj4@edac1ce5.eSource := MyFile_Annotation_type.obj14@edac1ce5
.obj4@edac1ce5.eTarget := 
.obj4@edac1ce5.name := Cmd
.obj4@edac1ce5.origin := 5:2

# .obj20@edac1ce5
.obj20@edac1ce5 := MyAnnotation
.obj20@edac1ce5.__eContents := \
	bindings/.obj18@edac1ce5
.obj20@edac1ce5.__eContainer := target/annotations.obj38@edac1ce5
.obj20@edac1ce5.type := .obj15@edac1ce5./

# .obj18@edac1ce5
.obj18@edac1ce5 := MyOptionBinding
.obj18@edac1ce5.__eContents := \
	value/.obj17@edac1ce5
.obj18@edac1ce5.__eContainer := /bindings.obj20@edac1ce5
.obj18@edac1ce5.option := .obj19@edac1ce5./

# .obj17@edac1ce5
.obj17@edac1ce5 := MyTypeReferenceLiteral
.obj17@edac1ce5.__eContents := 
.obj17@edac1ce5.__eContainer := /value.obj18@edac1ce5
.obj17@edac1ce5.value := .obj16@edac1ce5./

# .obj16@edac1ce5
.obj16@edac1ce5 := ELink
.obj16@edac1ce5.eSource := MyFile_TypeReferenceLiteral_value.obj17@edac1ce5
.obj16@edac1ce5.eTarget := 
.obj16@edac1ce5.name := third_party.lib.cjson
.obj16@edac1ce5.origin := 6:15

# .obj19@edac1ce5
.obj19@edac1ce5 := ELink
.obj19@edac1ce5.eSource := MyFile_OptionBinding_option.obj18@edac1ce5
.obj19@edac1ce5.eTarget := 
.obj19@edac1ce5.name := value
.obj19@edac1ce5.origin := 6:14

# .obj15@edac1ce5
.obj15@edac1ce5 := ELink
.obj15@edac1ce5.eSource := MyFile_Annotation_type.obj20@edac1ce5
.obj15@edac1ce5.eTarget := 
.obj15@edac1ce5.name := BuildDepends
.obj15@edac1ce5.origin := 6:2


__resource-mk/.cache/mybuild/files/src/service/http_admin/Mybuild.mk := .obj1@edac1ce5
