# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@5807b285

# .obj1@5807b285
.obj1@5807b285 := MyFileResource
.obj1@5807b285.issues := 
.obj1@5807b285.contentsRoot := .obj17@5807b285
.obj1@5807b285.resourceSet := 
.obj1@5807b285.fileName := src/drivers/net/usbnet/Mybuild
.obj1@5807b285.exports := \
	embox.driver.net \
	embox.driver.net.usbnet
.obj1@5807b285.exports.embox.driver.net := \
	.obj17@5807b285
.obj1@5807b285.exports.embox.driver.net.usbnet := \
	.obj16@5807b285

# .obj17@5807b285
.obj17@5807b285 := MyFileContentRoot
.obj17@5807b285.__eContents := \
	types/.obj16@5807b285
.obj17@5807b285.__eContainer := .obj1@5807b285
.obj17@5807b285.imports := 
.obj17@5807b285.name := embox.driver.net
.obj17@5807b285.origin := 

# .obj16@5807b285
.obj16@5807b285 := MyModuleType
.obj16@5807b285.__eContents := \
	sourcesMembers/.obj3@5807b285 \
	dependsMembers/.obj5@5807b285 \
	dependsMembers/.obj7@5807b285 \
	dependsMembers/.obj9@5807b285 \
	dependsMembers/.obj11@5807b285 \
	dependsMembers/.obj13@5807b285 \
	dependsMembers/.obj15@5807b285
.obj16@5807b285.__eContainer := fileContentRoot/types.obj17@5807b285
.obj16@5807b285.dependent := 
.obj16@5807b285.subTypes := 
.obj16@5807b285.modifiers := 
.obj16@5807b285.name := usbnet
.obj16@5807b285.origin := 3:8
.obj16@5807b285.superType := 
.obj16@5807b285.customStorage := 

# .obj3@5807b285
.obj3@5807b285 := MySourceMember
.obj3@5807b285.__eContents := \
	files/.obj2@5807b285
.obj3@5807b285.__eContainer := /sourcesMembers.obj16@5807b285
.obj3@5807b285.module := 

# .obj2@5807b285
.obj2@5807b285 := MyFileName
.obj2@5807b285.__eContents := 
.obj2@5807b285.__eContainer := /files.obj3@5807b285
.obj2@5807b285.fileName := usbnet.c

# .obj5@5807b285
.obj5@5807b285 := MyDependsMember
.obj5@5807b285.__eContents := 
.obj5@5807b285.__eContainer := /dependsMembers.obj16@5807b285
.obj5@5807b285.modules := \
	.obj4@5807b285./
.obj5@5807b285.module := 

# .obj4@5807b285
.obj4@5807b285 := ELink
.obj4@5807b285.eSource := MyFile_DependsMember_modules.obj5@5807b285
.obj4@5807b285.eTarget := 
.obj4@5807b285.name := embox.driver.usb.class.cdc
.obj4@5807b285.origin := 6:10

# .obj7@5807b285
.obj7@5807b285 := MyDependsMember
.obj7@5807b285.__eContents := 
.obj7@5807b285.__eContainer := /dependsMembers.obj16@5807b285
.obj7@5807b285.modules := \
	.obj6@5807b285./
.obj7@5807b285.module := 

# .obj6@5807b285
.obj6@5807b285 := ELink
.obj6@5807b285.eSource := MyFile_DependsMember_modules.obj7@5807b285
.obj6@5807b285.eTarget := 
.obj6@5807b285.name := embox.net.skbuff
.obj6@5807b285.origin := 7:10

# .obj9@5807b285
.obj9@5807b285 := MyDependsMember
.obj9@5807b285.__eContents := 
.obj9@5807b285.__eContainer := /dependsMembers.obj16@5807b285
.obj9@5807b285.modules := \
	.obj8@5807b285./
.obj9@5807b285.module := 

# .obj8@5807b285
.obj8@5807b285 := ELink
.obj8@5807b285.eSource := MyFile_DependsMember_modules.obj9@5807b285
.obj8@5807b285.eTarget := 
.obj8@5807b285.name := embox.net.l2.ethernet
.obj8@5807b285.origin := 8:10

# .obj11@5807b285
.obj11@5807b285 := MyDependsMember
.obj11@5807b285.__eContents := 
.obj11@5807b285.__eContainer := /dependsMembers.obj16@5807b285
.obj11@5807b285.modules := \
	.obj10@5807b285./
.obj11@5807b285.module := 

# .obj10@5807b285
.obj10@5807b285 := ELink
.obj10@5807b285.eSource := MyFile_DependsMember_modules.obj11@5807b285
.obj10@5807b285.eTarget := 
.obj10@5807b285.name := embox.net.dev
.obj10@5807b285.origin := 9:10

# .obj13@5807b285
.obj13@5807b285 := MyDependsMember
.obj13@5807b285.__eContents := 
.obj13@5807b285.__eContainer := /dependsMembers.obj16@5807b285
.obj13@5807b285.modules := \
	.obj12@5807b285./
.obj13@5807b285.module := 

# .obj12@5807b285
.obj12@5807b285 := ELink
.obj12@5807b285.eSource := MyFile_DependsMember_modules.obj13@5807b285
.obj12@5807b285.eTarget := 
.obj12@5807b285.name := embox.net.entry_api
.obj12@5807b285.origin := 10:10

# .obj15@5807b285
.obj15@5807b285 := MyDependsMember
.obj15@5807b285.__eContents := 
.obj15@5807b285.__eContainer := /dependsMembers.obj16@5807b285
.obj15@5807b285.modules := \
	.obj14@5807b285./
.obj15@5807b285.module := 

# .obj14@5807b285
.obj14@5807b285 := ELink
.obj14@5807b285.eSource := MyFile_DependsMember_modules.obj15@5807b285
.obj14@5807b285.eTarget := 
.obj14@5807b285.name := embox.net.core
.obj14@5807b285.origin := 11:10


__resource-mk/.cache/mybuild/files/src/drivers/net/usbnet/Mybuild.mk := .obj1@5807b285
