# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@8b44bb85

# .obj1@8b44bb85
.obj1@8b44bb85 := MyFileResource
.obj1@8b44bb85.issues := 
.obj1@8b44bb85.contentsRoot := .obj24@8b44bb85
.obj1@8b44bb85.resourceSet := 
.obj1@8b44bb85.fileName := src/cmds/bootloader/Boot.my
.obj1@8b44bb85.exports := \
	embox.cmd \
	embox.cmd.boot
.obj1@8b44bb85.exports.embox.cmd := \
	.obj24@8b44bb85
.obj1@8b44bb85.exports.embox.cmd.boot := \
	.obj23@8b44bb85

# .obj24@8b44bb85
.obj24@8b44bb85 := MyFileContentRoot
.obj24@8b44bb85.__eContents := \
	types/.obj23@8b44bb85
.obj24@8b44bb85.__eContainer := .obj1@8b44bb85
.obj24@8b44bb85.imports := 
.obj24@8b44bb85.name := embox.cmd
.obj24@8b44bb85.origin := 

# .obj23@8b44bb85
.obj23@8b44bb85 := MyModuleType
.obj23@8b44bb85.__eContents := \
	sourcesMembers/.obj16@8b44bb85 \
	dependsMembers/.obj18@8b44bb85 \
	dependsMembers/.obj20@8b44bb85 \
	dependsMembers/.obj22@8b44bb85 \
	annotations/.obj3@8b44bb85 \
	annotations/.obj14@8b44bb85
.obj23@8b44bb85.__eContainer := fileContentRoot/types.obj24@8b44bb85
.obj23@8b44bb85.dependent := 
.obj23@8b44bb85.subTypes := 
.obj23@8b44bb85.modifiers := 
.obj23@8b44bb85.name := boot
.obj23@8b44bb85.origin := 27:8
.obj23@8b44bb85.superType := 
.obj23@8b44bb85.customStorage := 

# .obj16@8b44bb85
.obj16@8b44bb85 := MySourceMember
.obj16@8b44bb85.__eContents := \
	files/.obj15@8b44bb85
.obj16@8b44bb85.__eContainer := /sourcesMembers.obj23@8b44bb85
.obj16@8b44bb85.module := 

# .obj15@8b44bb85
.obj15@8b44bb85 := MyFileName
.obj15@8b44bb85.__eContents := 
.obj15@8b44bb85.__eContainer := /files.obj16@8b44bb85
.obj15@8b44bb85.fileName := boot.c

# .obj18@8b44bb85
.obj18@8b44bb85 := MyDependsMember
.obj18@8b44bb85.__eContents := 
.obj18@8b44bb85.__eContainer := /dependsMembers.obj23@8b44bb85
.obj18@8b44bb85.modules := \
	.obj17@8b44bb85./
.obj18@8b44bb85.module := 

# .obj17@8b44bb85
.obj17@8b44bb85 := ELink
.obj17@8b44bb85.eSource := MyFile_DependsMember_modules.obj18@8b44bb85
.obj17@8b44bb85.eTarget := 
.obj17@8b44bb85.name := embox.compat.libc.all
.obj17@8b44bb85.origin := 30:10

# .obj20@8b44bb85
.obj20@8b44bb85 := MyDependsMember
.obj20@8b44bb85.__eContents := 
.obj20@8b44bb85.__eContainer := /dependsMembers.obj23@8b44bb85
.obj20@8b44bb85.modules := \
	.obj19@8b44bb85./
.obj20@8b44bb85.module := 

# .obj19@8b44bb85
.obj19@8b44bb85 := ELink
.obj19@8b44bb85.eSource := MyFile_DependsMember_modules.obj20@8b44bb85
.obj19@8b44bb85.eTarget := 
.obj19@8b44bb85.name := embox.compat.posix.LibPosix
.obj19@8b44bb85.origin := 31:10

# .obj22@8b44bb85
.obj22@8b44bb85 := MyDependsMember
.obj22@8b44bb85.__eContents := 
.obj22@8b44bb85.__eContainer := /dependsMembers.obj23@8b44bb85
.obj22@8b44bb85.modules := \
	.obj21@8b44bb85./
.obj22@8b44bb85.module := 

# .obj21@8b44bb85
.obj21@8b44bb85 := ELink
.obj21@8b44bb85.eSource := MyFile_DependsMember_modules.obj22@8b44bb85
.obj21@8b44bb85.eTarget := 
.obj21@8b44bb85.name := embox.framework.LibFramework
.obj21@8b44bb85.origin := 32:10

# .obj3@8b44bb85
.obj3@8b44bb85 := MyAnnotation
.obj3@8b44bb85.__eContents := 
.obj3@8b44bb85.__eContainer := target/annotations.obj23@8b44bb85
.obj3@8b44bb85.type := .obj2@8b44bb85./

# .obj2@8b44bb85
.obj2@8b44bb85 := ELink
.obj2@8b44bb85.eSource := MyFile_Annotation_type.obj3@8b44bb85
.obj2@8b44bb85.eTarget := 
.obj2@8b44bb85.name := AutoCmd
.obj2@8b44bb85.origin := 3:2

# .obj14@8b44bb85
.obj14@8b44bb85 := MyAnnotation
.obj14@8b44bb85.__eContents := \
	bindings/.obj7@8b44bb85 \
	bindings/.obj10@8b44bb85 \
	bindings/.obj13@8b44bb85
.obj14@8b44bb85.__eContainer := target/annotations.obj23@8b44bb85
.obj14@8b44bb85.type := .obj4@8b44bb85./

# .obj7@8b44bb85
.obj7@8b44bb85 := MyOptionBinding
.obj7@8b44bb85.__eContents := \
	value/.obj6@8b44bb85
.obj7@8b44bb85.__eContainer := /bindings.obj14@8b44bb85
.obj7@8b44bb85.option := .obj5@8b44bb85./

# .obj6@8b44bb85
.obj6@8b44bb85 := MyStringLiteral
.obj6@8b44bb85.__eContents := 
.obj6@8b44bb85.__eContainer := /value.obj7@8b44bb85
.obj6@8b44bb85.value := boot

# .obj5@8b44bb85
.obj5@8b44bb85 := ELink
.obj5@8b44bb85.eSource := MyFile_OptionBinding_option.obj7@8b44bb85
.obj5@8b44bb85.eTarget := 
.obj5@8b44bb85.name := name
.obj5@8b44bb85.origin := 4:6

# .obj10@8b44bb85
.obj10@8b44bb85 := MyOptionBinding
.obj10@8b44bb85.__eContents := \
	value/.obj9@8b44bb85
.obj10@8b44bb85.__eContainer := /bindings.obj14@8b44bb85
.obj10@8b44bb85.option := .obj8@8b44bb85./

# .obj9@8b44bb85
.obj9@8b44bb85 := MyStringLiteral
.obj9@8b44bb85.__eContents := 
.obj9@8b44bb85.__eContainer := /value.obj10@8b44bb85
.obj9@8b44bb85.value := Boot application image from memory

# .obj8@8b44bb85
.obj8@8b44bb85 := ELink
.obj8@8b44bb85.eSource := MyFile_OptionBinding_option.obj10@8b44bb85
.obj8@8b44bb85.eTarget := 
.obj8@8b44bb85.name := help
.obj8@8b44bb85.origin := 5:2

# .obj13@8b44bb85
.obj13@8b44bb85 := MyOptionBinding
.obj13@8b44bb85.__eContents := \
	value/.obj12@8b44bb85
.obj13@8b44bb85.__eContainer := /bindings.obj14@8b44bb85
.obj13@8b44bb85.option := .obj11@8b44bb85./

# .obj12@8b44bb85
.obj12@8b44bb85 := MyStringLiteral
.obj12@8b44bb85.__eContents := 
.obj12@8b44bb85.__eContainer := /value.obj13@8b44bb85
.obj12@8b44bb85.value := $(\0)$(\n)		NAME$(\n)			boot - boot application image from memory$(\n)		SYNOPSIS$(\n)			boot [-f format] -a addr$(\n)		DESCRIPTION$(\n)			-f format - image format$(\n)				u - Das U-Boot format$(\n)				r - raw format (default)$(\n)			-a addr   - entry point address$(\n)		EXAMPLES$(\n)			For sparc:$(\n)			boot -a 0x40004000$(\n)			boot -f u -a 0x40003FC0$(\n)			For microblaze:$(\n)			boot -f u -a 0x45000000$(\n)		SEE ALSO$(\n)			tftp, goto$(\n)		AUTHORS$(\n)			Nikolay Korotky$(\n)	

# .obj11@8b44bb85
.obj11@8b44bb85 := ELink
.obj11@8b44bb85.eSource := MyFile_OptionBinding_option.obj13@8b44bb85
.obj11@8b44bb85.eTarget := 
.obj11@8b44bb85.name := man
.obj11@8b44bb85.origin := 6:2

# .obj4@8b44bb85
.obj4@8b44bb85 := ELink
.obj4@8b44bb85.eSource := MyFile_Annotation_type.obj14@8b44bb85
.obj4@8b44bb85.eTarget := 
.obj4@8b44bb85.name := Cmd
.obj4@8b44bb85.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/bootloader/Boot.my.mk := .obj1@8b44bb85
