# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@f2c34ddc

# .obj1@f2c34ddc
.obj1@f2c34ddc := MyFileResource
.obj1@f2c34ddc.issues := 
.obj1@f2c34ddc.contentsRoot := .obj18@f2c34ddc
.obj1@f2c34ddc.resourceSet := 
.obj1@f2c34ddc.fileName := src/kernel/sched/priority/Mybuild
.obj1@f2c34ddc.exports := \
	embox.kernel.sched.priority \
	embox.kernel.sched.priority.priority \
	embox.kernel.sched.priority.inherit \
	embox.kernel.sched.priority.none
.obj1@f2c34ddc.exports.embox.kernel.sched.priority := \
	.obj18@f2c34ddc
.obj1@f2c34ddc.exports.embox.kernel.sched.priority.priority := \
	.obj8@f2c34ddc
.obj1@f2c34ddc.exports.embox.kernel.sched.priority.inherit := \
	.obj13@f2c34ddc
.obj1@f2c34ddc.exports.embox.kernel.sched.priority.none := \
	.obj17@f2c34ddc

# .obj18@f2c34ddc
.obj18@f2c34ddc := MyFileContentRoot
.obj18@f2c34ddc.__eContents := \
	types/.obj8@f2c34ddc \
	types/.obj13@f2c34ddc \
	types/.obj17@f2c34ddc
.obj18@f2c34ddc.__eContainer := .obj1@f2c34ddc
.obj18@f2c34ddc.imports := 
.obj18@f2c34ddc.name := embox.kernel.sched.priority
.obj18@f2c34ddc.origin := 

# .obj8@f2c34ddc
.obj8@f2c34ddc := MyModuleType
.obj8@f2c34ddc.__eContents := \
	annotations/.obj7@f2c34ddc
.obj8@f2c34ddc.__eContainer := fileContentRoot/types.obj18@f2c34ddc
.obj8@f2c34ddc.dependent := 
.obj8@f2c34ddc.subTypes := 
.obj8@f2c34ddc.modifiers := abstract
.obj8@f2c34ddc.name := priority
.obj8@f2c34ddc.origin := 4:17
.obj8@f2c34ddc.superType := 
.obj8@f2c34ddc.customStorage := 

# .obj7@f2c34ddc
.obj7@f2c34ddc := MyAnnotation
.obj7@f2c34ddc.__eContents := \
	bindings/.obj5@f2c34ddc
.obj7@f2c34ddc.__eContainer := target/annotations.obj8@f2c34ddc
.obj7@f2c34ddc.type := .obj2@f2c34ddc./

# .obj5@f2c34ddc
.obj5@f2c34ddc := MyOptionBinding
.obj5@f2c34ddc.__eContents := \
	value/.obj4@f2c34ddc
.obj5@f2c34ddc.__eContainer := /bindings.obj7@f2c34ddc
.obj5@f2c34ddc.option := .obj6@f2c34ddc./

# .obj4@f2c34ddc
.obj4@f2c34ddc := MyTypeReferenceLiteral
.obj4@f2c34ddc.__eContents := 
.obj4@f2c34ddc.__eContainer := /value.obj5@f2c34ddc
.obj4@f2c34ddc.value := .obj3@f2c34ddc./

# .obj3@f2c34ddc
.obj3@f2c34ddc := ELink
.obj3@f2c34ddc.eSource := MyFile_TypeReferenceLiteral_value.obj4@f2c34ddc
.obj3@f2c34ddc.eTarget := 
.obj3@f2c34ddc.name := inherit
.obj3@f2c34ddc.origin := 3:14

# .obj6@f2c34ddc
.obj6@f2c34ddc := ELink
.obj6@f2c34ddc.eSource := MyFile_OptionBinding_option.obj5@f2c34ddc
.obj6@f2c34ddc.eTarget := 
.obj6@f2c34ddc.name := value
.obj6@f2c34ddc.origin := 3:13

# .obj2@f2c34ddc
.obj2@f2c34ddc := ELink
.obj2@f2c34ddc.eSource := MyFile_Annotation_type.obj7@f2c34ddc
.obj2@f2c34ddc.eTarget := 
.obj2@f2c34ddc.name := DefaultImpl
.obj2@f2c34ddc.origin := 3:2

# .obj13@f2c34ddc
.obj13@f2c34ddc := MyModuleType
.obj13@f2c34ddc.__eContents := \
	sourcesMembers/.obj12@f2c34ddc
.obj13@f2c34ddc.__eContainer := fileContentRoot/types.obj18@f2c34ddc
.obj13@f2c34ddc.dependent := 
.obj13@f2c34ddc.subTypes := 
.obj13@f2c34ddc.modifiers := 
.obj13@f2c34ddc.name := inherit
.obj13@f2c34ddc.origin := 6:8
.obj13@f2c34ddc.superType := .obj9@f2c34ddc./
.obj13@f2c34ddc.customStorage := 

# .obj12@f2c34ddc
.obj12@f2c34ddc := MySourceMember
.obj12@f2c34ddc.__eContents := \
	files/.obj10@f2c34ddc \
	files/.obj11@f2c34ddc
.obj12@f2c34ddc.__eContainer := /sourcesMembers.obj13@f2c34ddc
.obj12@f2c34ddc.module := 

# .obj10@f2c34ddc
.obj10@f2c34ddc := MyFileName
.obj10@f2c34ddc.__eContents := 
.obj10@f2c34ddc.__eContainer := /files.obj12@f2c34ddc
.obj10@f2c34ddc.fileName := inherit.h

# .obj11@f2c34ddc
.obj11@f2c34ddc := MyFileName
.obj11@f2c34ddc.__eContents := 
.obj11@f2c34ddc.__eContainer := /files.obj12@f2c34ddc
.obj11@f2c34ddc.fileName := inherit.c

# .obj9@f2c34ddc
.obj9@f2c34ddc := ELink
.obj9@f2c34ddc.eSource := MyFile_ModuleType_superType.obj13@f2c34ddc
.obj9@f2c34ddc.eTarget := 
.obj9@f2c34ddc.name := priority
.obj9@f2c34ddc.origin := 6:24

# .obj17@f2c34ddc
.obj17@f2c34ddc := MyModuleType
.obj17@f2c34ddc.__eContents := \
	sourcesMembers/.obj16@f2c34ddc
.obj17@f2c34ddc.__eContainer := fileContentRoot/types.obj18@f2c34ddc
.obj17@f2c34ddc.dependent := 
.obj17@f2c34ddc.subTypes := 
.obj17@f2c34ddc.modifiers := 
.obj17@f2c34ddc.name := none
.obj17@f2c34ddc.origin := 10:8
.obj17@f2c34ddc.superType := .obj14@f2c34ddc./
.obj17@f2c34ddc.customStorage := 

# .obj16@f2c34ddc
.obj16@f2c34ddc := MySourceMember
.obj16@f2c34ddc.__eContents := \
	files/.obj15@f2c34ddc
.obj16@f2c34ddc.__eContainer := /sourcesMembers.obj17@f2c34ddc
.obj16@f2c34ddc.module := 

# .obj15@f2c34ddc
.obj15@f2c34ddc := MyFileName
.obj15@f2c34ddc.__eContents := 
.obj15@f2c34ddc.__eContainer := /files.obj16@f2c34ddc
.obj15@f2c34ddc.fileName := none.h

# .obj14@f2c34ddc
.obj14@f2c34ddc := ELink
.obj14@f2c34ddc.eSource := MyFile_ModuleType_superType.obj17@f2c34ddc
.obj14@f2c34ddc.eTarget := 
.obj14@f2c34ddc.name := priority
.obj14@f2c34ddc.origin := 10:21


__resource-mk/.cache/mybuild/files/src/kernel/sched/priority/Mybuild.mk := .obj1@f2c34ddc
