# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@7a1b63a5

# .obj1@7a1b63a5
.obj1@7a1b63a5 := MyFileResource
.obj1@7a1b63a5.issues := 
.obj1@7a1b63a5.contentsRoot := .obj5@7a1b63a5
.obj1@7a1b63a5.resourceSet := 
.obj1@7a1b63a5.fileName := src/compat/posix/sys/timerfd/Mybuild
.obj1@7a1b63a5.exports := \
	embox.compat.posix \
	embox.compat.posix.timerfd
.obj1@7a1b63a5.exports.embox.compat.posix := \
	.obj5@7a1b63a5
.obj1@7a1b63a5.exports.embox.compat.posix.timerfd := \
	.obj4@7a1b63a5

# .obj5@7a1b63a5
.obj5@7a1b63a5 := MyFileContentRoot
.obj5@7a1b63a5.__eContents := \
	types/.obj4@7a1b63a5
.obj5@7a1b63a5.__eContainer := .obj1@7a1b63a5
.obj5@7a1b63a5.imports := 
.obj5@7a1b63a5.name := embox.compat.posix
.obj5@7a1b63a5.origin := 

# .obj4@7a1b63a5
.obj4@7a1b63a5 := MyModuleType
.obj4@7a1b63a5.__eContents := \
	sourcesMembers/.obj3@7a1b63a5
.obj4@7a1b63a5.__eContainer := fileContentRoot/types.obj5@7a1b63a5
.obj4@7a1b63a5.dependent := 
.obj4@7a1b63a5.subTypes := 
.obj4@7a1b63a5.modifiers := 
.obj4@7a1b63a5.name := timerfd
.obj4@7a1b63a5.origin := 3:8
.obj4@7a1b63a5.superType := 
.obj4@7a1b63a5.customStorage := 

# .obj3@7a1b63a5
.obj3@7a1b63a5 := MySourceMember
.obj3@7a1b63a5.__eContents := \
	files/.obj2@7a1b63a5
.obj3@7a1b63a5.__eContainer := /sourcesMembers.obj4@7a1b63a5
.obj3@7a1b63a5.module := 

# .obj2@7a1b63a5
.obj2@7a1b63a5 := MyFileName
.obj2@7a1b63a5.__eContents := 
.obj2@7a1b63a5.__eContainer := /files.obj3@7a1b63a5
.obj2@7a1b63a5.fileName := timerfd.c


__resource-mk/.cache/mybuild/files/src/compat/posix/sys/timerfd/Mybuild.mk := .obj1@7a1b63a5
