# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@471e891d

# .obj1@471e891d
.obj1@471e891d := MyFileResource
.obj1@471e891d.issues := 
.obj1@471e891d.contentsRoot := .obj30@471e891d
.obj1@471e891d.resourceSet := 
.obj1@471e891d.fileName := src/fs/driver/ntfs/Mybuild
.obj1@471e891d.exports := \
	embox.fs.driver \
	embox.fs.driver.ntfs \
	embox.fs.driver.ntfs.ntfs_desc_quantity \
	embox.fs.driver.ntfs.ntfs_inode_quantity \
	embox.fs.driver.ntfs.ntfs_descriptor_quantity
.obj1@471e891d.exports.embox.fs.driver := \
	.obj30@471e891d
.obj1@471e891d.exports.embox.fs.driver.ntfs := \
	.obj29@471e891d
.obj1@471e891d.exports.embox.fs.driver.ntfs.ntfs_desc_quantity := \
	.obj16@471e891d
.obj1@471e891d.exports.embox.fs.driver.ntfs.ntfs_inode_quantity := \
	.obj19@471e891d
.obj1@471e891d.exports.embox.fs.driver.ntfs.ntfs_descriptor_quantity := \
	.obj22@471e891d

# .obj30@471e891d
.obj30@471e891d := MyFileContentRoot
.obj30@471e891d.__eContents := \
	types/.obj29@471e891d
.obj30@471e891d.__eContainer := .obj1@471e891d
.obj30@471e891d.imports := 
.obj30@471e891d.name := embox.fs.driver
.obj30@471e891d.origin := 

# .obj29@471e891d
.obj29@471e891d := MyModuleType
.obj29@471e891d.__eContents := \
	sourcesMembers/.obj26@471e891d \
	optionsMembers/.obj18@471e891d \
	optionsMembers/.obj21@471e891d \
	optionsMembers/.obj24@471e891d \
	dependsMembers/.obj28@471e891d \
	annotations/.obj9@471e891d \
	annotations/.obj15@471e891d
.obj29@471e891d.__eContainer := fileContentRoot/types.obj30@471e891d
.obj29@471e891d.dependent := 
.obj29@471e891d.subTypes := 
.obj29@471e891d.modifiers := 
.obj29@471e891d.name := ntfs
.obj29@471e891d.origin := 5:8
.obj29@471e891d.superType := 
.obj29@471e891d.customStorage := 

# .obj26@471e891d
.obj26@471e891d := MySourceMember
.obj26@471e891d.__eContents := \
	files/.obj25@471e891d
.obj26@471e891d.__eContainer := /sourcesMembers.obj29@471e891d
.obj26@471e891d.module := 

# .obj25@471e891d
.obj25@471e891d := MyFileName
.obj25@471e891d.__eContents := 
.obj25@471e891d.__eContainer := /files.obj26@471e891d
.obj25@471e891d.fileName := ntfs.c

# .obj18@471e891d
.obj18@471e891d := MyOptionMember
.obj18@471e891d.__eContents := \
	options/.obj16@471e891d
.obj18@471e891d.__eContainer := /optionsMembers.obj29@471e891d
.obj18@471e891d.module := 

# .obj16@471e891d
.obj16@471e891d := MyNumberOption
.obj16@471e891d.__eContents := \
	defaultValue/.obj17@471e891d
.obj16@471e891d.__eContainer := /options.obj18@471e891d
.obj16@471e891d.name := ntfs_desc_quantity
.obj16@471e891d.origin := 

# .obj17@471e891d
.obj17@471e891d := MyNumberLiteral
.obj17@471e891d.__eContents := 
.obj17@471e891d.__eContainer := /defaultValue.obj16@471e891d
.obj17@471e891d.value := 8

# .obj21@471e891d
.obj21@471e891d := MyOptionMember
.obj21@471e891d.__eContents := \
	options/.obj19@471e891d
.obj21@471e891d.__eContainer := /optionsMembers.obj29@471e891d
.obj21@471e891d.module := 

# .obj19@471e891d
.obj19@471e891d := MyNumberOption
.obj19@471e891d.__eContents := \
	defaultValue/.obj20@471e891d
.obj19@471e891d.__eContainer := /options.obj21@471e891d
.obj19@471e891d.name := ntfs_inode_quantity
.obj19@471e891d.origin := 

# .obj20@471e891d
.obj20@471e891d := MyNumberLiteral
.obj20@471e891d.__eContents := 
.obj20@471e891d.__eContainer := /defaultValue.obj19@471e891d
.obj20@471e891d.value := 64

# .obj24@471e891d
.obj24@471e891d := MyOptionMember
.obj24@471e891d.__eContents := \
	options/.obj22@471e891d
.obj24@471e891d.__eContainer := /optionsMembers.obj29@471e891d
.obj24@471e891d.module := 

# .obj22@471e891d
.obj22@471e891d := MyNumberOption
.obj22@471e891d.__eContents := \
	defaultValue/.obj23@471e891d
.obj22@471e891d.__eContainer := /options.obj24@471e891d
.obj22@471e891d.name := ntfs_descriptor_quantity
.obj22@471e891d.origin := 

# .obj23@471e891d
.obj23@471e891d := MyNumberLiteral
.obj23@471e891d.__eContents := 
.obj23@471e891d.__eContainer := /defaultValue.obj22@471e891d
.obj23@471e891d.value := 4

# .obj28@471e891d
.obj28@471e891d := MyDependsMember
.obj28@471e891d.__eContents := 
.obj28@471e891d.__eContainer := /dependsMembers.obj29@471e891d
.obj28@471e891d.modules := \
	.obj27@471e891d./
.obj28@471e891d.module := 

# .obj27@471e891d
.obj27@471e891d := ELink
.obj27@471e891d.eSource := MyFile_DependsMember_modules.obj28@471e891d
.obj27@471e891d.eTarget := 
.obj27@471e891d.name := third_party.ntfs_3g.core
.obj27@471e891d.origin := 12:10

# .obj9@471e891d
.obj9@471e891d := MyAnnotation
.obj9@471e891d.__eContents := \
	bindings/.obj5@471e891d \
	bindings/.obj8@471e891d
.obj9@471e891d.__eContainer := target/annotations.obj29@471e891d
.obj9@471e891d.type := .obj2@471e891d./

# .obj5@471e891d
.obj5@471e891d := MyOptionBinding
.obj5@471e891d.__eContents := \
	value/.obj4@471e891d
.obj5@471e891d.__eContainer := /bindings.obj9@471e891d
.obj5@471e891d.option := .obj3@471e891d./

# .obj4@471e891d
.obj4@471e891d := MyNumberLiteral
.obj4@471e891d.__eContents := 
.obj4@471e891d.__eContainer := /value.obj5@471e891d
.obj4@471e891d.value := 2

# .obj3@471e891d
.obj3@471e891d := ELink
.obj3@471e891d.eSource := MyFile_OptionBinding_option.obj5@471e891d
.obj3@471e891d.eTarget := 
.obj3@471e891d.name := stage
.obj3@471e891d.origin := 3:8

# .obj8@471e891d
.obj8@471e891d := MyOptionBinding
.obj8@471e891d.__eContents := \
	value/.obj7@471e891d
.obj8@471e891d.__eContainer := /bindings.obj9@471e891d
.obj8@471e891d.option := .obj6@471e891d./

# .obj7@471e891d
.obj7@471e891d := MyStringLiteral
.obj7@471e891d.__eContents := 
.obj7@471e891d.__eContainer := /value.obj8@471e891d
.obj7@471e891d.value := true

# .obj6@471e891d
.obj6@471e891d := ELink
.obj6@471e891d.eSource := MyFile_OptionBinding_option.obj8@471e891d
.obj6@471e891d.eTarget := 
.obj6@471e891d.name := script
.obj6@471e891d.origin := 3:16

# .obj2@471e891d
.obj2@471e891d := ELink
.obj2@471e891d.eSource := MyFile_Annotation_type.obj9@471e891d
.obj2@471e891d.eTarget := 
.obj2@471e891d.name := Build
.obj2@471e891d.origin := 3:2

# .obj15@471e891d
.obj15@471e891d := MyAnnotation
.obj15@471e891d.__eContents := \
	bindings/.obj13@471e891d
.obj15@471e891d.__eContainer := target/annotations.obj29@471e891d
.obj15@471e891d.type := .obj10@471e891d./

# .obj13@471e891d
.obj13@471e891d := MyOptionBinding
.obj13@471e891d.__eContents := \
	value/.obj12@471e891d
.obj13@471e891d.__eContainer := /bindings.obj15@471e891d
.obj13@471e891d.option := .obj14@471e891d./

# .obj12@471e891d
.obj12@471e891d := MyTypeReferenceLiteral
.obj12@471e891d.__eContents := 
.obj12@471e891d.__eContainer := /value.obj13@471e891d
.obj12@471e891d.value := .obj11@471e891d./

# .obj11@471e891d
.obj11@471e891d := ELink
.obj11@471e891d.eSource := MyFile_TypeReferenceLiteral_value.obj12@471e891d
.obj11@471e891d.eTarget := 
.obj11@471e891d.name := third_party.ntfs_3g.core
.obj11@471e891d.origin := 4:15

# .obj14@471e891d
.obj14@471e891d := ELink
.obj14@471e891d.eSource := MyFile_OptionBinding_option.obj13@471e891d
.obj14@471e891d.eTarget := 
.obj14@471e891d.name := value
.obj14@471e891d.origin := 4:14

# .obj10@471e891d
.obj10@471e891d := ELink
.obj10@471e891d.eSource := MyFile_Annotation_type.obj15@471e891d
.obj10@471e891d.eTarget := 
.obj10@471e891d.name := BuildDepends
.obj10@471e891d.origin := 4:2


__resource-mk/.cache/mybuild/files/src/fs/driver/ntfs/Mybuild.mk := .obj1@471e891d
