# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@306e4503

# .obj1@306e4503
.obj1@306e4503 := MyFileResource
.obj1@306e4503.issues := 
.obj1@306e4503.contentsRoot := .obj126@306e4503
.obj1@306e4503.resourceSet := 
.obj1@306e4503.fileName := src/net/Mybuild
.obj1@306e4503.exports := \
	embox.net \
	embox.net.dev \
	embox.net.dev.netdev_table_sz \
	embox.net.dev.netdev_quantity \
	embox.net.core \
	embox.net.core.amount_interface \
	embox.net.sock \
	embox.net.sock_xattr_api \
	embox.net.sock_xattr \
	embox.net.sock_noxattr \
	embox.net.neighbour \
	embox.net.neighbour.log_level \
	embox.net.neighbour.neighbour_amount \
	embox.net.neighbour.neighbour_attempt \
	embox.net.neighbour.neighbour_expire \
	embox.net.neighbour.neighbour_resend \
	embox.net.neighbour.neighbour_tmr_freq \
	embox.net.packet \
	embox.net.net_pack
.obj1@306e4503.exports.embox.net := \
	.obj126@306e4503
.obj1@306e4503.exports.embox.net.dev := \
	.obj16@306e4503
.obj1@306e4503.exports.embox.net.dev.netdev_table_sz := \
	.obj2@306e4503
.obj1@306e4503.exports.embox.net.dev.netdev_quantity := \
	.obj5@306e4503
.obj1@306e4503.exports.embox.net.core := \
	.obj28@306e4503
.obj1@306e4503.exports.embox.net.core.amount_interface := \
	.obj17@306e4503
.obj1@306e4503.exports.embox.net.sock := \
	.obj63@306e4503
.obj1@306e4503.exports.embox.net.sock_xattr_api := \
	.obj70@306e4503
.obj1@306e4503.exports.embox.net.sock_xattr := \
	.obj80@306e4503
.obj1@306e4503.exports.embox.net.sock_noxattr := \
	.obj84@306e4503
.obj1@306e4503.exports.embox.net.neighbour := \
	.obj117@306e4503
.obj1@306e4503.exports.embox.net.neighbour.log_level := \
	.obj85@306e4503
.obj1@306e4503.exports.embox.net.neighbour.neighbour_amount := \
	.obj88@306e4503
.obj1@306e4503.exports.embox.net.neighbour.neighbour_attempt := \
	.obj91@306e4503
.obj1@306e4503.exports.embox.net.neighbour.neighbour_expire := \
	.obj94@306e4503
.obj1@306e4503.exports.embox.net.neighbour.neighbour_resend := \
	.obj97@306e4503
.obj1@306e4503.exports.embox.net.neighbour.neighbour_tmr_freq := \
	.obj100@306e4503
.obj1@306e4503.exports.embox.net.packet := \
	.obj120@306e4503
.obj1@306e4503.exports.embox.net.net_pack := \
	.obj125@306e4503

# .obj126@306e4503
.obj126@306e4503 := MyFileContentRoot
.obj126@306e4503.__eContents := \
	types/.obj16@306e4503 \
	types/.obj28@306e4503 \
	types/.obj63@306e4503 \
	types/.obj70@306e4503 \
	types/.obj80@306e4503 \
	types/.obj84@306e4503 \
	types/.obj117@306e4503 \
	types/.obj120@306e4503 \
	types/.obj125@306e4503
.obj126@306e4503.__eContainer := .obj1@306e4503
.obj126@306e4503.imports := 
.obj126@306e4503.name := embox.net
.obj126@306e4503.origin := 

# .obj16@306e4503
.obj16@306e4503 := MyModuleType
.obj16@306e4503.__eContents := \
	sourcesMembers/.obj9@306e4503 \
	optionsMembers/.obj4@306e4503 \
	optionsMembers/.obj7@306e4503 \
	dependsMembers/.obj11@306e4503 \
	dependsMembers/.obj13@306e4503 \
	dependsMembers/.obj15@306e4503
.obj16@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj16@306e4503.dependent := 
.obj16@306e4503.subTypes := 
.obj16@306e4503.modifiers := 
.obj16@306e4503.name := dev
.obj16@306e4503.origin := 3:8
.obj16@306e4503.superType := 
.obj16@306e4503.customStorage := 

# .obj9@306e4503
.obj9@306e4503 := MySourceMember
.obj9@306e4503.__eContents := \
	files/.obj8@306e4503
.obj9@306e4503.__eContainer := /sourcesMembers.obj16@306e4503
.obj9@306e4503.module := 

# .obj8@306e4503
.obj8@306e4503 := MyFileName
.obj8@306e4503.__eContents := 
.obj8@306e4503.__eContainer := /files.obj9@306e4503
.obj8@306e4503.fileName := netdev.c

# .obj4@306e4503
.obj4@306e4503 := MyOptionMember
.obj4@306e4503.__eContents := \
	options/.obj2@306e4503
.obj4@306e4503.__eContainer := /optionsMembers.obj16@306e4503
.obj4@306e4503.module := 

# .obj2@306e4503
.obj2@306e4503 := MyNumberOption
.obj2@306e4503.__eContents := \
	defaultValue/.obj3@306e4503
.obj2@306e4503.__eContainer := /options.obj4@306e4503
.obj2@306e4503.name := netdev_table_sz
.obj2@306e4503.origin := 

# .obj3@306e4503
.obj3@306e4503 := MyNumberLiteral
.obj3@306e4503.__eContents := 
.obj3@306e4503.__eContainer := /defaultValue.obj2@306e4503
.obj3@306e4503.value := 3

# .obj7@306e4503
.obj7@306e4503 := MyOptionMember
.obj7@306e4503.__eContents := \
	options/.obj5@306e4503
.obj7@306e4503.__eContainer := /optionsMembers.obj16@306e4503
.obj7@306e4503.module := 

# .obj5@306e4503
.obj5@306e4503 := MyNumberOption
.obj5@306e4503.__eContents := \
	defaultValue/.obj6@306e4503
.obj5@306e4503.__eContainer := /options.obj7@306e4503
.obj5@306e4503.name := netdev_quantity
.obj5@306e4503.origin := 

# .obj6@306e4503
.obj6@306e4503 := MyNumberLiteral
.obj6@306e4503.__eContents := 
.obj6@306e4503.__eContainer := /defaultValue.obj5@306e4503
.obj6@306e4503.value := 8

# .obj11@306e4503
.obj11@306e4503 := MyDependsMember
.obj11@306e4503.__eContents := 
.obj11@306e4503.__eContainer := /dependsMembers.obj16@306e4503
.obj11@306e4503.modules := \
	.obj10@306e4503./
.obj11@306e4503.module := 

# .obj10@306e4503
.obj10@306e4503 := ELink
.obj10@306e4503.eSource := MyFile_DependsMember_modules.obj11@306e4503
.obj10@306e4503.eTarget := 
.obj10@306e4503.name := embox.mem.sysmalloc_api
.obj10@306e4503.origin := 9:10

# .obj13@306e4503
.obj13@306e4503 := MyDependsMember
.obj13@306e4503.__eContents := 
.obj13@306e4503.__eContainer := /dependsMembers.obj16@306e4503
.obj13@306e4503.modules := \
	.obj12@306e4503./
.obj13@306e4503.module := 

# .obj12@306e4503
.obj12@306e4503 := ELink
.obj12@306e4503.eSource := MyFile_DependsMember_modules.obj13@306e4503
.obj12@306e4503.eTarget := 
.obj12@306e4503.name := embox.util.dlist
.obj12@306e4503.origin := 10:10

# .obj15@306e4503
.obj15@306e4503 := MyDependsMember
.obj15@306e4503.__eContents := 
.obj15@306e4503.__eContainer := /dependsMembers.obj16@306e4503
.obj15@306e4503.modules := \
	.obj14@306e4503./
.obj15@306e4503.module := 

# .obj14@306e4503
.obj14@306e4503 := ELink
.obj14@306e4503.eSource := MyFile_DependsMember_modules.obj15@306e4503
.obj14@306e4503.eTarget := 
.obj14@306e4503.name := embox.util.hashtable
.obj14@306e4503.origin := 11:10

# .obj28@306e4503
.obj28@306e4503 := MyModuleType
.obj28@306e4503.__eContents := \
	sourcesMembers/.obj21@306e4503 \
	optionsMembers/.obj19@306e4503 \
	dependsMembers/.obj23@306e4503 \
	dependsMembers/.obj25@306e4503 \
	dependsMembers/.obj27@306e4503
.obj28@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj28@306e4503.dependent := 
.obj28@306e4503.subTypes := 
.obj28@306e4503.modifiers := 
.obj28@306e4503.name := core
.obj28@306e4503.origin := 14:8
.obj28@306e4503.superType := 
.obj28@306e4503.customStorage := 

# .obj21@306e4503
.obj21@306e4503 := MySourceMember
.obj21@306e4503.__eContents := \
	files/.obj20@306e4503
.obj21@306e4503.__eContainer := /sourcesMembers.obj28@306e4503
.obj21@306e4503.module := 

# .obj20@306e4503
.obj20@306e4503 := MyFileName
.obj20@306e4503.__eContents := 
.obj20@306e4503.__eContainer := /files.obj21@306e4503
.obj20@306e4503.fileName := inetdev.c

# .obj19@306e4503
.obj19@306e4503 := MyOptionMember
.obj19@306e4503.__eContents := \
	options/.obj17@306e4503
.obj19@306e4503.__eContainer := /optionsMembers.obj28@306e4503
.obj19@306e4503.module := 

# .obj17@306e4503
.obj17@306e4503 := MyNumberOption
.obj17@306e4503.__eContents := \
	defaultValue/.obj18@306e4503
.obj17@306e4503.__eContainer := /options.obj19@306e4503
.obj17@306e4503.name := amount_interface
.obj17@306e4503.origin := 

# .obj18@306e4503
.obj18@306e4503 := MyNumberLiteral
.obj18@306e4503.__eContents := 
.obj18@306e4503.__eContainer := /defaultValue.obj17@306e4503
.obj18@306e4503.value := 4

# .obj23@306e4503
.obj23@306e4503 := MyDependsMember
.obj23@306e4503.__eContents := 
.obj23@306e4503.__eContainer := /dependsMembers.obj28@306e4503
.obj23@306e4503.modules := \
	.obj22@306e4503./
.obj23@306e4503.module := 

# .obj22@306e4503
.obj22@306e4503 := ELink
.obj22@306e4503.eSource := MyFile_DependsMember_modules.obj23@306e4503
.obj22@306e4503.eTarget := 
.obj22@306e4503.name := dev
.obj22@306e4503.origin := 18:10

# .obj25@306e4503
.obj25@306e4503 := MyDependsMember
.obj25@306e4503.__eContents := 
.obj25@306e4503.__eContainer := /dependsMembers.obj28@306e4503
.obj25@306e4503.modules := \
	.obj24@306e4503./
.obj25@306e4503.module := 

# .obj24@306e4503
.obj24@306e4503 := ELink
.obj24@306e4503.eSource := MyFile_DependsMember_modules.obj25@306e4503
.obj24@306e4503.eTarget := 
.obj24@306e4503.name := embox.util.dlist
.obj24@306e4503.origin := 19:10

# .obj27@306e4503
.obj27@306e4503 := MyDependsMember
.obj27@306e4503.__eContents := 
.obj27@306e4503.__eContainer := /dependsMembers.obj28@306e4503
.obj27@306e4503.modules := \
	.obj26@306e4503./
.obj27@306e4503.module := 

# .obj26@306e4503
.obj26@306e4503 := ELink
.obj26@306e4503.eSource := MyFile_DependsMember_modules.obj27@306e4503
.obj26@306e4503.eTarget := 
.obj26@306e4503.name := embox.mem.pool
.obj26@306e4503.origin := 20:10

# .obj63@306e4503
.obj63@306e4503 := MyModuleType
.obj63@306e4503.__eContents := \
	sourcesMembers/.obj30@306e4503 \
	sourcesMembers/.obj32@306e4503 \
	sourcesMembers/.obj34@306e4503 \
	sourcesMembers/.obj36@306e4503 \
	sourcesMembers/.obj38@306e4503 \
	dependsMembers/.obj40@306e4503 \
	dependsMembers/.obj42@306e4503 \
	dependsMembers/.obj44@306e4503 \
	dependsMembers/.obj46@306e4503 \
	dependsMembers/.obj48@306e4503 \
	dependsMembers/.obj50@306e4503 \
	dependsMembers/.obj52@306e4503 \
	dependsMembers/.obj54@306e4503 \
	dependsMembers/.obj58@306e4503 \
	dependsMembers/.obj62@306e4503
.obj63@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj63@306e4503.dependent := 
.obj63@306e4503.subTypes := 
.obj63@306e4503.modifiers := 
.obj63@306e4503.name := sock
.obj63@306e4503.origin := 23:8
.obj63@306e4503.superType := 
.obj63@306e4503.customStorage := 

# .obj30@306e4503
.obj30@306e4503 := MySourceMember
.obj30@306e4503.__eContents := \
	files/.obj29@306e4503
.obj30@306e4503.__eContainer := /sourcesMembers.obj63@306e4503
.obj30@306e4503.module := 

# .obj29@306e4503
.obj29@306e4503 := MyFileName
.obj29@306e4503.__eContents := 
.obj29@306e4503.__eContainer := /files.obj30@306e4503
.obj29@306e4503.fileName := sock.c

# .obj32@306e4503
.obj32@306e4503 := MySourceMember
.obj32@306e4503.__eContents := \
	files/.obj31@306e4503
.obj32@306e4503.__eContainer := /sourcesMembers.obj63@306e4503
.obj32@306e4503.module := 

# .obj31@306e4503
.obj31@306e4503 := MyFileName
.obj31@306e4503.__eContents := 
.obj31@306e4503.__eContainer := /files.obj32@306e4503
.obj31@306e4503.fileName := socket/sock_hash.c

# .obj34@306e4503
.obj34@306e4503 := MySourceMember
.obj34@306e4503.__eContents := \
	files/.obj33@306e4503
.obj34@306e4503.__eContainer := /sourcesMembers.obj63@306e4503
.obj34@306e4503.module := 

# .obj33@306e4503
.obj33@306e4503 := MyFileName
.obj33@306e4503.__eContents := 
.obj33@306e4503.__eContainer := /files.obj34@306e4503
.obj33@306e4503.fileName := socket/sock_repo.c

# .obj36@306e4503
.obj36@306e4503 := MySourceMember
.obj36@306e4503.__eContents := \
	files/.obj35@306e4503
.obj36@306e4503.__eContainer := /sourcesMembers.obj63@306e4503
.obj36@306e4503.module := 

# .obj35@306e4503
.obj35@306e4503 := MyFileName
.obj35@306e4503.__eContents := 
.obj35@306e4503.__eContainer := /files.obj36@306e4503
.obj35@306e4503.fileName := socket/sock_factory.c

# .obj38@306e4503
.obj38@306e4503 := MySourceMember
.obj38@306e4503.__eContents := \
	files/.obj37@306e4503
.obj38@306e4503.__eContainer := /sourcesMembers.obj63@306e4503
.obj38@306e4503.module := 

# .obj37@306e4503
.obj37@306e4503 := MyFileName
.obj37@306e4503.__eContents := 
.obj37@306e4503.__eContainer := /files.obj38@306e4503
.obj37@306e4503.fileName := socket/sock_wait.c

# .obj40@306e4503
.obj40@306e4503 := MyDependsMember
.obj40@306e4503.__eContents := 
.obj40@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj40@306e4503.modules := \
	.obj39@306e4503./
.obj40@306e4503.module := 

# .obj39@306e4503
.obj39@306e4503 := ELink
.obj39@306e4503.eSource := MyFile_DependsMember_modules.obj40@306e4503
.obj39@306e4503.eTarget := 
.obj39@306e4503.name := embox.net.skbuff
.obj39@306e4503.origin := 30:10

# .obj42@306e4503
.obj42@306e4503 := MyDependsMember
.obj42@306e4503.__eContents := 
.obj42@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj42@306e4503.modules := \
	.obj41@306e4503./
.obj42@306e4503.module := 

# .obj41@306e4503
.obj41@306e4503 := ELink
.obj41@306e4503.eSource := MyFile_DependsMember_modules.obj42@306e4503
.obj41@306e4503.eTarget := 
.obj41@306e4503.name := embox.fs.idesc
.obj41@306e4503.origin := 31:10

# .obj44@306e4503
.obj44@306e4503 := MyDependsMember
.obj44@306e4503.__eContents := 
.obj44@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj44@306e4503.modules := \
	.obj43@306e4503./
.obj44@306e4503.module := 

# .obj43@306e4503
.obj43@306e4503 := ELink
.obj43@306e4503.eSource := MyFile_DependsMember_modules.obj44@306e4503
.obj43@306e4503.eTarget := 
.obj43@306e4503.name := embox.fs.idesc_event
.obj43@306e4503.origin := 32:10

# .obj46@306e4503
.obj46@306e4503 := MyDependsMember
.obj46@306e4503.__eContents := 
.obj46@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj46@306e4503.modules := \
	.obj45@306e4503./
.obj46@306e4503.module := 

# .obj45@306e4503
.obj45@306e4503 := ELink
.obj45@306e4503.eSource := MyFile_DependsMember_modules.obj46@306e4503
.obj45@306e4503.eTarget := 
.obj45@306e4503.name := embox.arch.interrupt
.obj45@306e4503.origin := 33:10

# .obj48@306e4503
.obj48@306e4503 := MyDependsMember
.obj48@306e4503.__eContents := 
.obj48@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj48@306e4503.modules := \
	.obj47@306e4503./
.obj48@306e4503.module := 

# .obj47@306e4503
.obj47@306e4503 := ELink
.obj47@306e4503.eSource := MyFile_DependsMember_modules.obj48@306e4503
.obj47@306e4503.eTarget := 
.obj47@306e4503.name := embox.mem.pool
.obj47@306e4503.origin := 34:10

# .obj50@306e4503
.obj50@306e4503 := MyDependsMember
.obj50@306e4503.__eContents := 
.obj50@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj50@306e4503.modules := \
	.obj49@306e4503./
.obj50@306e4503.module := 

# .obj49@306e4503
.obj49@306e4503 := ELink
.obj49@306e4503.eSource := MyFile_DependsMember_modules.obj50@306e4503
.obj49@306e4503.eTarget := 
.obj49@306e4503.name := family
.obj49@306e4503.origin := 35:10

# .obj52@306e4503
.obj52@306e4503 := MyDependsMember
.obj52@306e4503.__eContents := 
.obj52@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj52@306e4503.modules := \
	.obj51@306e4503./
.obj52@306e4503.module := 

# .obj51@306e4503
.obj51@306e4503 := ELink
.obj51@306e4503.eSource := MyFile_DependsMember_modules.obj52@306e4503
.obj51@306e4503.eTarget := 
.obj51@306e4503.name := net_sock
.obj51@306e4503.origin := 36:10

# .obj54@306e4503
.obj54@306e4503 := MyDependsMember
.obj54@306e4503.__eContents := 
.obj54@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj54@306e4503.modules := \
	.obj53@306e4503./
.obj54@306e4503.module := 

# .obj53@306e4503
.obj53@306e4503 := ELink
.obj53@306e4503.eSource := MyFile_DependsMember_modules.obj54@306e4503
.obj53@306e4503.eTarget := 
.obj53@306e4503.name := sock_xattr_api
.obj53@306e4503.origin := 38:10

# .obj58@306e4503
.obj58@306e4503 := MyDependsMember
.obj58@306e4503.__eContents := \
	annotations/.obj56@306e4503
.obj58@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj58@306e4503.modules := \
	.obj57@306e4503./
.obj58@306e4503.module := 

# .obj56@306e4503
.obj56@306e4503 := MyAnnotation
.obj56@306e4503.__eContents := 
.obj56@306e4503.__eContainer := target/annotations.obj58@306e4503
.obj56@306e4503.type := .obj55@306e4503./

# .obj55@306e4503
.obj55@306e4503 := ELink
.obj55@306e4503.eSource := MyFile_Annotation_type.obj56@306e4503
.obj55@306e4503.eTarget := 
.obj55@306e4503.name := NoRuntime
.obj55@306e4503.origin := 39:3

# .obj57@306e4503
.obj57@306e4503 := ELink
.obj57@306e4503.eSource := MyFile_DependsMember_modules.obj58@306e4503
.obj57@306e4503.eTarget := 
.obj57@306e4503.name := embox.security.api
.obj57@306e4503.origin := 39:21

# .obj62@306e4503
.obj62@306e4503 := MyDependsMember
.obj62@306e4503.__eContents := \
	annotations/.obj60@306e4503
.obj62@306e4503.__eContainer := /dependsMembers.obj63@306e4503
.obj62@306e4503.modules := \
	.obj61@306e4503./
.obj62@306e4503.module := 

# .obj60@306e4503
.obj60@306e4503 := MyAnnotation
.obj60@306e4503.__eContents := 
.obj60@306e4503.__eContainer := target/annotations.obj62@306e4503
.obj60@306e4503.type := .obj59@306e4503./

# .obj59@306e4503
.obj59@306e4503 := ELink
.obj59@306e4503.eSource := MyFile_Annotation_type.obj60@306e4503
.obj59@306e4503.eTarget := 
.obj59@306e4503.name := NoRuntime
.obj59@306e4503.origin := 40:3

# .obj61@306e4503
.obj61@306e4503 := ELink
.obj61@306e4503.eSource := MyFile_DependsMember_modules.obj62@306e4503
.obj61@306e4503.eTarget := 
.obj61@306e4503.name := embox.compat.posix.net.socket
.obj61@306e4503.origin := 40:21

# .obj70@306e4503
.obj70@306e4503 := MyModuleType
.obj70@306e4503.__eContents := \
	annotations/.obj69@306e4503
.obj70@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj70@306e4503.dependent := 
.obj70@306e4503.subTypes := 
.obj70@306e4503.modifiers := abstract
.obj70@306e4503.name := sock_xattr_api
.obj70@306e4503.origin := 44:17
.obj70@306e4503.superType := 
.obj70@306e4503.customStorage := 

# .obj69@306e4503
.obj69@306e4503 := MyAnnotation
.obj69@306e4503.__eContents := \
	bindings/.obj67@306e4503
.obj69@306e4503.__eContainer := target/annotations.obj70@306e4503
.obj69@306e4503.type := .obj64@306e4503./

# .obj67@306e4503
.obj67@306e4503 := MyOptionBinding
.obj67@306e4503.__eContents := \
	value/.obj66@306e4503
.obj67@306e4503.__eContainer := /bindings.obj69@306e4503
.obj67@306e4503.option := .obj68@306e4503./

# .obj66@306e4503
.obj66@306e4503 := MyTypeReferenceLiteral
.obj66@306e4503.__eContents := 
.obj66@306e4503.__eContainer := /value.obj67@306e4503
.obj66@306e4503.value := .obj65@306e4503./

# .obj65@306e4503
.obj65@306e4503 := ELink
.obj65@306e4503.eSource := MyFile_TypeReferenceLiteral_value.obj66@306e4503
.obj65@306e4503.eTarget := 
.obj65@306e4503.name := sock_noxattr
.obj65@306e4503.origin := 43:14

# .obj68@306e4503
.obj68@306e4503 := ELink
.obj68@306e4503.eSource := MyFile_OptionBinding_option.obj67@306e4503
.obj68@306e4503.eTarget := 
.obj68@306e4503.name := value
.obj68@306e4503.origin := 43:13

# .obj64@306e4503
.obj64@306e4503 := ELink
.obj64@306e4503.eSource := MyFile_Annotation_type.obj69@306e4503
.obj64@306e4503.eTarget := 
.obj64@306e4503.name := DefaultImpl
.obj64@306e4503.origin := 43:2

# .obj80@306e4503
.obj80@306e4503 := MyModuleType
.obj80@306e4503.__eContents := \
	sourcesMembers/.obj73@306e4503 \
	sourcesMembers/.obj75@306e4503 \
	dependsMembers/.obj77@306e4503 \
	dependsMembers/.obj79@306e4503
.obj80@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj80@306e4503.dependent := 
.obj80@306e4503.subTypes := 
.obj80@306e4503.modifiers := 
.obj80@306e4503.name := sock_xattr
.obj80@306e4503.origin := 46:8
.obj80@306e4503.superType := .obj71@306e4503./
.obj80@306e4503.customStorage := 

# .obj73@306e4503
.obj73@306e4503 := MySourceMember
.obj73@306e4503.__eContents := \
	files/.obj72@306e4503
.obj73@306e4503.__eContainer := /sourcesMembers.obj80@306e4503
.obj73@306e4503.module := 

# .obj72@306e4503
.obj72@306e4503 := MyFileName
.obj72@306e4503.__eContents := 
.obj72@306e4503.__eContainer := /files.obj73@306e4503
.obj72@306e4503.fileName := socket/sock_xattr.c

# .obj75@306e4503
.obj75@306e4503 := MySourceMember
.obj75@306e4503.__eContents := \
	files/.obj74@306e4503
.obj75@306e4503.__eContainer := /sourcesMembers.obj80@306e4503
.obj75@306e4503.module := 

# .obj74@306e4503
.obj74@306e4503 := MyFileName
.obj74@306e4503.__eContents := 
.obj74@306e4503.__eContainer := /files.obj75@306e4503
.obj74@306e4503.fileName := socket/sock_xattr.h

# .obj77@306e4503
.obj77@306e4503 := MyDependsMember
.obj77@306e4503.__eContents := 
.obj77@306e4503.__eContainer := /dependsMembers.obj80@306e4503
.obj77@306e4503.modules := \
	.obj76@306e4503./
.obj77@306e4503.module := 

# .obj76@306e4503
.obj76@306e4503 := ELink
.obj76@306e4503.eSource := MyFile_DependsMember_modules.obj77@306e4503
.obj76@306e4503.eTarget := 
.obj76@306e4503.name := embox.fs.xattr_list
.obj76@306e4503.origin := 50:10

# .obj79@306e4503
.obj79@306e4503 := MyDependsMember
.obj79@306e4503.__eContents := 
.obj79@306e4503.__eContainer := /dependsMembers.obj80@306e4503
.obj79@306e4503.modules := \
	.obj78@306e4503./
.obj79@306e4503.module := 

# .obj78@306e4503
.obj78@306e4503 := ELink
.obj78@306e4503.eSource := MyFile_DependsMember_modules.obj79@306e4503
.obj78@306e4503.eTarget := 
.obj78@306e4503.name := embox.security.smac
.obj78@306e4503.origin := 51:10

# .obj71@306e4503
.obj71@306e4503 := ELink
.obj71@306e4503.eSource := MyFile_ModuleType_superType.obj80@306e4503
.obj71@306e4503.eTarget := 
.obj71@306e4503.name := sock_xattr_api
.obj71@306e4503.origin := 46:27

# .obj84@306e4503
.obj84@306e4503 := MyModuleType
.obj84@306e4503.__eContents := \
	sourcesMembers/.obj83@306e4503
.obj84@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj84@306e4503.dependent := 
.obj84@306e4503.subTypes := 
.obj84@306e4503.modifiers := 
.obj84@306e4503.name := sock_noxattr
.obj84@306e4503.origin := 54:8
.obj84@306e4503.superType := .obj81@306e4503./
.obj84@306e4503.customStorage := 

# .obj83@306e4503
.obj83@306e4503 := MySourceMember
.obj83@306e4503.__eContents := \
	files/.obj82@306e4503
.obj83@306e4503.__eContainer := /sourcesMembers.obj84@306e4503
.obj83@306e4503.module := 

# .obj82@306e4503
.obj82@306e4503 := MyFileName
.obj82@306e4503.__eContents := 
.obj82@306e4503.__eContainer := /files.obj83@306e4503
.obj82@306e4503.fileName := socket/sock_noxattr.h

# .obj81@306e4503
.obj81@306e4503 := ELink
.obj81@306e4503.eSource := MyFile_ModuleType_superType.obj84@306e4503
.obj81@306e4503.eTarget := 
.obj81@306e4503.name := sock_xattr_api
.obj81@306e4503.origin := 54:29

# .obj117@306e4503
.obj117@306e4503 := MyModuleType
.obj117@306e4503.__eContents := \
	sourcesMembers/.obj104@306e4503 \
	optionsMembers/.obj87@306e4503 \
	optionsMembers/.obj90@306e4503 \
	optionsMembers/.obj93@306e4503 \
	optionsMembers/.obj96@306e4503 \
	optionsMembers/.obj99@306e4503 \
	optionsMembers/.obj102@306e4503 \
	dependsMembers/.obj106@306e4503 \
	dependsMembers/.obj108@306e4503 \
	dependsMembers/.obj112@306e4503 \
	dependsMembers/.obj116@306e4503
.obj117@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj117@306e4503.dependent := 
.obj117@306e4503.subTypes := 
.obj117@306e4503.modifiers := 
.obj117@306e4503.name := neighbour
.obj117@306e4503.origin := 58:8
.obj117@306e4503.superType := 
.obj117@306e4503.customStorage := 

# .obj104@306e4503
.obj104@306e4503 := MySourceMember
.obj104@306e4503.__eContents := \
	files/.obj103@306e4503
.obj104@306e4503.__eContainer := /sourcesMembers.obj117@306e4503
.obj104@306e4503.module := 

# .obj103@306e4503
.obj103@306e4503 := MyFileName
.obj103@306e4503.__eContents := 
.obj103@306e4503.__eContainer := /files.obj104@306e4503
.obj103@306e4503.fileName := neighbour.c

# .obj87@306e4503
.obj87@306e4503 := MyOptionMember
.obj87@306e4503.__eContents := \
	options/.obj85@306e4503
.obj87@306e4503.__eContainer := /optionsMembers.obj117@306e4503
.obj87@306e4503.module := 

# .obj85@306e4503
.obj85@306e4503 := MyNumberOption
.obj85@306e4503.__eContents := \
	defaultValue/.obj86@306e4503
.obj85@306e4503.__eContainer := /options.obj87@306e4503
.obj85@306e4503.name := log_level
.obj85@306e4503.origin := 

# .obj86@306e4503
.obj86@306e4503 := MyNumberLiteral
.obj86@306e4503.__eContents := 
.obj86@306e4503.__eContainer := /defaultValue.obj85@306e4503
.obj86@306e4503.value := 0

# .obj90@306e4503
.obj90@306e4503 := MyOptionMember
.obj90@306e4503.__eContents := \
	options/.obj88@306e4503
.obj90@306e4503.__eContainer := /optionsMembers.obj117@306e4503
.obj90@306e4503.module := 

# .obj88@306e4503
.obj88@306e4503 := MyNumberOption
.obj88@306e4503.__eContents := \
	defaultValue/.obj89@306e4503
.obj88@306e4503.__eContainer := /options.obj90@306e4503
.obj88@306e4503.name := neighbour_amount
.obj88@306e4503.origin := 

# .obj89@306e4503
.obj89@306e4503 := MyNumberLiteral
.obj89@306e4503.__eContents := 
.obj89@306e4503.__eContainer := /defaultValue.obj88@306e4503
.obj89@306e4503.value := 10

# .obj93@306e4503
.obj93@306e4503 := MyOptionMember
.obj93@306e4503.__eContents := \
	options/.obj91@306e4503
.obj93@306e4503.__eContainer := /optionsMembers.obj117@306e4503
.obj93@306e4503.module := 

# .obj91@306e4503
.obj91@306e4503 := MyNumberOption
.obj91@306e4503.__eContents := \
	defaultValue/.obj92@306e4503
.obj91@306e4503.__eContainer := /options.obj93@306e4503
.obj91@306e4503.name := neighbour_attempt
.obj91@306e4503.origin := 

# .obj92@306e4503
.obj92@306e4503 := MyNumberLiteral
.obj92@306e4503.__eContents := 
.obj92@306e4503.__eContainer := /defaultValue.obj91@306e4503
.obj92@306e4503.value := 3

# .obj96@306e4503
.obj96@306e4503 := MyOptionMember
.obj96@306e4503.__eContents := \
	options/.obj94@306e4503
.obj96@306e4503.__eContainer := /optionsMembers.obj117@306e4503
.obj96@306e4503.module := 

# .obj94@306e4503
.obj94@306e4503 := MyNumberOption
.obj94@306e4503.__eContents := \
	defaultValue/.obj95@306e4503
.obj94@306e4503.__eContainer := /options.obj96@306e4503
.obj94@306e4503.name := neighbour_expire
.obj94@306e4503.origin := 

# .obj95@306e4503
.obj95@306e4503 := MyNumberLiteral
.obj95@306e4503.__eContents := 
.obj95@306e4503.__eContainer := /defaultValue.obj94@306e4503
.obj95@306e4503.value := 60000

# .obj99@306e4503
.obj99@306e4503 := MyOptionMember
.obj99@306e4503.__eContents := \
	options/.obj97@306e4503
.obj99@306e4503.__eContainer := /optionsMembers.obj117@306e4503
.obj99@306e4503.module := 

# .obj97@306e4503
.obj97@306e4503 := MyNumberOption
.obj97@306e4503.__eContents := \
	defaultValue/.obj98@306e4503
.obj97@306e4503.__eContainer := /options.obj99@306e4503
.obj97@306e4503.name := neighbour_resend
.obj97@306e4503.origin := 

# .obj98@306e4503
.obj98@306e4503 := MyNumberLiteral
.obj98@306e4503.__eContents := 
.obj98@306e4503.__eContainer := /defaultValue.obj97@306e4503
.obj98@306e4503.value := 1000

# .obj102@306e4503
.obj102@306e4503 := MyOptionMember
.obj102@306e4503.__eContents := \
	options/.obj100@306e4503
.obj102@306e4503.__eContainer := /optionsMembers.obj117@306e4503
.obj102@306e4503.module := 

# .obj100@306e4503
.obj100@306e4503 := MyNumberOption
.obj100@306e4503.__eContents := \
	defaultValue/.obj101@306e4503
.obj100@306e4503.__eContainer := /options.obj102@306e4503
.obj100@306e4503.name := neighbour_tmr_freq
.obj100@306e4503.origin := 

# .obj101@306e4503
.obj101@306e4503 := MyNumberLiteral
.obj101@306e4503.__eContents := 
.obj101@306e4503.__eContainer := /defaultValue.obj100@306e4503
.obj101@306e4503.value := 1000

# .obj106@306e4503
.obj106@306e4503 := MyDependsMember
.obj106@306e4503.__eContents := 
.obj106@306e4503.__eContainer := /dependsMembers.obj117@306e4503
.obj106@306e4503.modules := \
	.obj105@306e4503./
.obj106@306e4503.module := 

# .obj105@306e4503
.obj105@306e4503 := ELink
.obj105@306e4503.eSource := MyFile_DependsMember_modules.obj106@306e4503
.obj105@306e4503.eTarget := 
.obj105@306e4503.name := embox.compat.posix.util.time
.obj105@306e4503.origin := 68:10

# .obj108@306e4503
.obj108@306e4503 := MyDependsMember
.obj108@306e4503.__eContents := 
.obj108@306e4503.__eContainer := /dependsMembers.obj117@306e4503
.obj108@306e4503.modules := \
	.obj107@306e4503./
.obj108@306e4503.module := 

# .obj107@306e4503
.obj107@306e4503 := ELink
.obj107@306e4503.eSource := MyFile_DependsMember_modules.obj108@306e4503
.obj107@306e4503.eTarget := 
.obj107@306e4503.name := embox.mem.pool
.obj107@306e4503.origin := 69:10

# .obj112@306e4503
.obj112@306e4503 := MyDependsMember
.obj112@306e4503.__eContents := \
	annotations/.obj110@306e4503
.obj112@306e4503.__eContainer := /dependsMembers.obj117@306e4503
.obj112@306e4503.modules := \
	.obj111@306e4503./
.obj112@306e4503.module := 

# .obj110@306e4503
.obj110@306e4503 := MyAnnotation
.obj110@306e4503.__eContents := 
.obj110@306e4503.__eContainer := target/annotations.obj112@306e4503
.obj110@306e4503.type := .obj109@306e4503./

# .obj109@306e4503
.obj109@306e4503 := ELink
.obj109@306e4503.eSource := MyFile_Annotation_type.obj110@306e4503
.obj109@306e4503.eTarget := 
.obj109@306e4503.name := NoRuntime
.obj109@306e4503.origin := 70:3

# .obj111@306e4503
.obj111@306e4503 := ELink
.obj111@306e4503.eSource := MyFile_DependsMember_modules.obj112@306e4503
.obj111@306e4503.eTarget := 
.obj111@306e4503.name := embox.net.arp
.obj111@306e4503.origin := 70:21

# .obj116@306e4503
.obj116@306e4503 := MyDependsMember
.obj116@306e4503.__eContents := \
	annotations/.obj114@306e4503
.obj116@306e4503.__eContainer := /dependsMembers.obj117@306e4503
.obj116@306e4503.modules := \
	.obj115@306e4503./
.obj116@306e4503.module := 

# .obj114@306e4503
.obj114@306e4503 := MyAnnotation
.obj114@306e4503.__eContents := 
.obj114@306e4503.__eContainer := target/annotations.obj116@306e4503
.obj114@306e4503.type := .obj113@306e4503./

# .obj113@306e4503
.obj113@306e4503 := ELink
.obj113@306e4503.eSource := MyFile_Annotation_type.obj114@306e4503
.obj113@306e4503.eTarget := 
.obj113@306e4503.name := NoRuntime
.obj113@306e4503.origin := 71:3

# .obj115@306e4503
.obj115@306e4503 := ELink
.obj115@306e4503.eSource := MyFile_DependsMember_modules.obj116@306e4503
.obj115@306e4503.eTarget := 
.obj115@306e4503.name := embox.net.ndp
.obj115@306e4503.origin := 71:21

# .obj120@306e4503
.obj120@306e4503 := MyModuleType
.obj120@306e4503.__eContents := \
	sourcesMembers/.obj119@306e4503
.obj120@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj120@306e4503.dependent := 
.obj120@306e4503.subTypes := 
.obj120@306e4503.modifiers := 
.obj120@306e4503.name := packet
.obj120@306e4503.origin := 74:8
.obj120@306e4503.superType := 
.obj120@306e4503.customStorage := 

# .obj119@306e4503
.obj119@306e4503 := MySourceMember
.obj119@306e4503.__eContents := \
	files/.obj118@306e4503
.obj119@306e4503.__eContainer := /sourcesMembers.obj120@306e4503
.obj119@306e4503.module := 

# .obj118@306e4503
.obj118@306e4503 := MyFileName
.obj118@306e4503.__eContents := 
.obj118@306e4503.__eContainer := /files.obj119@306e4503
.obj118@306e4503.fileName := packet.c

# .obj125@306e4503
.obj125@306e4503 := MyModuleType
.obj125@306e4503.__eContents := \
	sourcesMembers/.obj122@306e4503 \
	dependsMembers/.obj124@306e4503
.obj125@306e4503.__eContainer := fileContentRoot/types.obj126@306e4503
.obj125@306e4503.dependent := 
.obj125@306e4503.subTypes := 
.obj125@306e4503.modifiers := 
.obj125@306e4503.name := net_pack
.obj125@306e4503.origin := 78:8
.obj125@306e4503.superType := 
.obj125@306e4503.customStorage := 

# .obj122@306e4503
.obj122@306e4503 := MySourceMember
.obj122@306e4503.__eContents := \
	files/.obj121@306e4503
.obj122@306e4503.__eContainer := /sourcesMembers.obj125@306e4503
.obj122@306e4503.module := 

# .obj121@306e4503
.obj121@306e4503 := MyFileName
.obj121@306e4503.__eContents := 
.obj121@306e4503.__eContainer := /files.obj122@306e4503
.obj121@306e4503.fileName := net_pack.c

# .obj124@306e4503
.obj124@306e4503 := MyDependsMember
.obj124@306e4503.__eContents := 
.obj124@306e4503.__eContainer := /dependsMembers.obj125@306e4503
.obj124@306e4503.modules := \
	.obj123@306e4503./
.obj124@306e4503.module := 

# .obj123@306e4503
.obj123@306e4503 := ELink
.obj123@306e4503.eSource := MyFile_DependsMember_modules.obj124@306e4503
.obj123@306e4503.eTarget := 
.obj123@306e4503.name := embox.util.Array
.obj123@306e4503.origin := 81:10


__resource-mk/.cache/mybuild/files/src/net/Mybuild.mk := .obj1@306e4503
