# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@dece22d1

# .obj1@dece22d1
.obj1@dece22d1 := MyFileResource
.obj1@dece22d1.issues := 
.obj1@dece22d1.contentsRoot := .obj12@dece22d1
.obj1@dece22d1.resourceSet := 
.obj1@dece22d1.fileName := src/net/netfilter/Mybuild
.obj1@dece22d1.exports := \
	embox.net \
	embox.net.netfilter \
	embox.net.netfilter.amount_rules
.obj1@dece22d1.exports.embox.net := \
	.obj12@dece22d1
.obj1@dece22d1.exports.embox.net.netfilter := \
	.obj11@dece22d1
.obj1@dece22d1.exports.embox.net.netfilter.amount_rules := \
	.obj4@dece22d1

# .obj12@dece22d1
.obj12@dece22d1 := MyFileContentRoot
.obj12@dece22d1.__eContents := \
	types/.obj11@dece22d1
.obj12@dece22d1.__eContainer := .obj1@dece22d1
.obj12@dece22d1.imports := 
.obj12@dece22d1.name := embox.net
.obj12@dece22d1.origin := 

# .obj11@dece22d1
.obj11@dece22d1 := MyModuleType
.obj11@dece22d1.__eContents := \
	sourcesMembers/.obj3@dece22d1 \
	optionsMembers/.obj6@dece22d1 \
	dependsMembers/.obj8@dece22d1 \
	dependsMembers/.obj10@dece22d1
.obj11@dece22d1.__eContainer := fileContentRoot/types.obj12@dece22d1
.obj11@dece22d1.dependent := 
.obj11@dece22d1.subTypes := 
.obj11@dece22d1.modifiers := 
.obj11@dece22d1.name := netfilter
.obj11@dece22d1.origin := 3:8
.obj11@dece22d1.superType := 
.obj11@dece22d1.customStorage := 

# .obj3@dece22d1
.obj3@dece22d1 := MySourceMember
.obj3@dece22d1.__eContents := \
	files/.obj2@dece22d1
.obj3@dece22d1.__eContainer := /sourcesMembers.obj11@dece22d1
.obj3@dece22d1.module := 

# .obj2@dece22d1
.obj2@dece22d1 := MyFileName
.obj2@dece22d1.__eContents := 
.obj2@dece22d1.__eContainer := /files.obj3@dece22d1
.obj2@dece22d1.fileName := netfilter.c

# .obj6@dece22d1
.obj6@dece22d1 := MyOptionMember
.obj6@dece22d1.__eContents := \
	options/.obj4@dece22d1
.obj6@dece22d1.__eContainer := /optionsMembers.obj11@dece22d1
.obj6@dece22d1.module := 

# .obj4@dece22d1
.obj4@dece22d1 := MyNumberOption
.obj4@dece22d1.__eContents := \
	defaultValue/.obj5@dece22d1
.obj4@dece22d1.__eContainer := /options.obj6@dece22d1
.obj4@dece22d1.name := amount_rules
.obj4@dece22d1.origin := 

# .obj5@dece22d1
.obj5@dece22d1 := MyNumberLiteral
.obj5@dece22d1.__eContents := 
.obj5@dece22d1.__eContainer := /defaultValue.obj4@dece22d1
.obj5@dece22d1.value := 10

# .obj8@dece22d1
.obj8@dece22d1 := MyDependsMember
.obj8@dece22d1.__eContents := 
.obj8@dece22d1.__eContainer := /dependsMembers.obj11@dece22d1
.obj8@dece22d1.modules := \
	.obj7@dece22d1./
.obj8@dece22d1.module := 

# .obj7@dece22d1
.obj7@dece22d1 := ELink
.obj7@dece22d1.eSource := MyFile_DependsMember_modules.obj8@dece22d1
.obj7@dece22d1.eTarget := 
.obj7@dece22d1.name := embox.mem.pool
.obj7@dece22d1.origin := 7:10

# .obj10@dece22d1
.obj10@dece22d1 := MyDependsMember
.obj10@dece22d1.__eContents := 
.obj10@dece22d1.__eContainer := /dependsMembers.obj11@dece22d1
.obj10@dece22d1.modules := \
	.obj9@dece22d1./
.obj10@dece22d1.module := 

# .obj9@dece22d1
.obj9@dece22d1 := ELink
.obj9@dece22d1.eSource := MyFile_DependsMember_modules.obj10@dece22d1
.obj9@dece22d1.eTarget := 
.obj9@dece22d1.name := embox.util.dlist
.obj9@dece22d1.origin := 8:10


__resource-mk/.cache/mybuild/files/src/net/netfilter/Mybuild.mk := .obj1@dece22d1
