# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@3c1e350b

# .obj1@3c1e350b
.obj1@3c1e350b := MyFileResource
.obj1@3c1e350b.issues := 
.obj1@3c1e350b.contentsRoot := .obj51@3c1e350b
.obj1@3c1e350b.resourceSet := 
.obj1@3c1e350b.fileName := src/kernel/thread/sync/Mybuild
.obj1@3c1e350b.exports := \
	embox.kernel.thread \
	embox.kernel.thread.sync \
	embox.kernel.thread.mutex \
	embox.kernel.thread.sem \
	embox.kernel.thread.barrier \
	embox.kernel.thread.cond \
	embox.kernel.thread.rwlock \
	embox.kernel.thread.mqueue
.obj1@3c1e350b.exports.embox.kernel.thread := \
	.obj51@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.sync := \
	.obj12@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.mutex := \
	.obj23@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.sem := \
	.obj28@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.barrier := \
	.obj33@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.cond := \
	.obj40@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.rwlock := \
	.obj45@3c1e350b
.obj1@3c1e350b.exports.embox.kernel.thread.mqueue := \
	.obj50@3c1e350b

# .obj51@3c1e350b
.obj51@3c1e350b := MyFileContentRoot
.obj51@3c1e350b.__eContents := \
	types/.obj12@3c1e350b \
	types/.obj23@3c1e350b \
	types/.obj28@3c1e350b \
	types/.obj33@3c1e350b \
	types/.obj40@3c1e350b \
	types/.obj45@3c1e350b \
	types/.obj50@3c1e350b
.obj51@3c1e350b.__eContainer := .obj1@3c1e350b
.obj51@3c1e350b.imports := 
.obj51@3c1e350b.name := embox.kernel.thread
.obj51@3c1e350b.origin := 

# .obj12@3c1e350b
.obj12@3c1e350b := MyModuleType
.obj12@3c1e350b.__eContents := \
	dependsMembers/.obj3@3c1e350b \
	dependsMembers/.obj5@3c1e350b \
	dependsMembers/.obj7@3c1e350b \
	dependsMembers/.obj9@3c1e350b \
	dependsMembers/.obj11@3c1e350b
.obj12@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj12@3c1e350b.dependent := 
.obj12@3c1e350b.subTypes := 
.obj12@3c1e350b.modifiers := 
.obj12@3c1e350b.name := sync
.obj12@3c1e350b.origin := 3:8
.obj12@3c1e350b.superType := 
.obj12@3c1e350b.customStorage := 

# .obj3@3c1e350b
.obj3@3c1e350b := MyDependsMember
.obj3@3c1e350b.__eContents := 
.obj3@3c1e350b.__eContainer := /dependsMembers.obj12@3c1e350b
.obj3@3c1e350b.modules := \
	.obj2@3c1e350b./
.obj3@3c1e350b.module := 

# .obj2@3c1e350b
.obj2@3c1e350b := ELink
.obj2@3c1e350b.eSource := MyFile_DependsMember_modules.obj3@3c1e350b
.obj2@3c1e350b.eTarget := 
.obj2@3c1e350b.name := mutex
.obj2@3c1e350b.origin := 4:10

# .obj5@3c1e350b
.obj5@3c1e350b := MyDependsMember
.obj5@3c1e350b.__eContents := 
.obj5@3c1e350b.__eContainer := /dependsMembers.obj12@3c1e350b
.obj5@3c1e350b.modules := \
	.obj4@3c1e350b./
.obj5@3c1e350b.module := 

# .obj4@3c1e350b
.obj4@3c1e350b := ELink
.obj4@3c1e350b.eSource := MyFile_DependsMember_modules.obj5@3c1e350b
.obj4@3c1e350b.eTarget := 
.obj4@3c1e350b.name := sem
.obj4@3c1e350b.origin := 5:10

# .obj7@3c1e350b
.obj7@3c1e350b := MyDependsMember
.obj7@3c1e350b.__eContents := 
.obj7@3c1e350b.__eContainer := /dependsMembers.obj12@3c1e350b
.obj7@3c1e350b.modules := \
	.obj6@3c1e350b./
.obj7@3c1e350b.module := 

# .obj6@3c1e350b
.obj6@3c1e350b := ELink
.obj6@3c1e350b.eSource := MyFile_DependsMember_modules.obj7@3c1e350b
.obj6@3c1e350b.eTarget := 
.obj6@3c1e350b.name := barrier
.obj6@3c1e350b.origin := 6:10

# .obj9@3c1e350b
.obj9@3c1e350b := MyDependsMember
.obj9@3c1e350b.__eContents := 
.obj9@3c1e350b.__eContainer := /dependsMembers.obj12@3c1e350b
.obj9@3c1e350b.modules := \
	.obj8@3c1e350b./
.obj9@3c1e350b.module := 

# .obj8@3c1e350b
.obj8@3c1e350b := ELink
.obj8@3c1e350b.eSource := MyFile_DependsMember_modules.obj9@3c1e350b
.obj8@3c1e350b.eTarget := 
.obj8@3c1e350b.name := cond
.obj8@3c1e350b.origin := 7:10

# .obj11@3c1e350b
.obj11@3c1e350b := MyDependsMember
.obj11@3c1e350b.__eContents := 
.obj11@3c1e350b.__eContainer := /dependsMembers.obj12@3c1e350b
.obj11@3c1e350b.modules := \
	.obj10@3c1e350b./
.obj11@3c1e350b.module := 

# .obj10@3c1e350b
.obj10@3c1e350b := ELink
.obj10@3c1e350b.eSource := MyFile_DependsMember_modules.obj11@3c1e350b
.obj10@3c1e350b.eTarget := 
.obj10@3c1e350b.name := rwlock
.obj10@3c1e350b.origin := 8:10

# .obj23@3c1e350b
.obj23@3c1e350b := MyModuleType
.obj23@3c1e350b.__eContents := \
	sourcesMembers/.obj14@3c1e350b \
	dependsMembers/.obj16@3c1e350b \
	dependsMembers/.obj18@3c1e350b \
	dependsMembers/.obj20@3c1e350b \
	dependsMembers/.obj22@3c1e350b
.obj23@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj23@3c1e350b.dependent := 
.obj23@3c1e350b.subTypes := 
.obj23@3c1e350b.modifiers := 
.obj23@3c1e350b.name := mutex
.obj23@3c1e350b.origin := 12:8
.obj23@3c1e350b.superType := 
.obj23@3c1e350b.customStorage := 

# .obj14@3c1e350b
.obj14@3c1e350b := MySourceMember
.obj14@3c1e350b.__eContents := \
	files/.obj13@3c1e350b
.obj14@3c1e350b.__eContainer := /sourcesMembers.obj23@3c1e350b
.obj14@3c1e350b.module := 

# .obj13@3c1e350b
.obj13@3c1e350b := MyFileName
.obj13@3c1e350b.__eContents := 
.obj13@3c1e350b.__eContainer := /files.obj14@3c1e350b
.obj13@3c1e350b.fileName := mutex.c

# .obj16@3c1e350b
.obj16@3c1e350b := MyDependsMember
.obj16@3c1e350b.__eContents := 
.obj16@3c1e350b.__eContainer := /dependsMembers.obj23@3c1e350b
.obj16@3c1e350b.modules := \
	.obj15@3c1e350b./
.obj16@3c1e350b.module := 

# .obj15@3c1e350b
.obj15@3c1e350b := ELink
.obj15@3c1e350b.eSource := MyFile_DependsMember_modules.obj16@3c1e350b
.obj15@3c1e350b.eTarget := 
.obj15@3c1e350b.name := embox.kernel.sched.priority.priority
.obj15@3c1e350b.origin := 15:10

# .obj18@3c1e350b
.obj18@3c1e350b := MyDependsMember
.obj18@3c1e350b.__eContents := 
.obj18@3c1e350b.__eContainer := /dependsMembers.obj23@3c1e350b
.obj18@3c1e350b.modules := \
	.obj17@3c1e350b./
.obj18@3c1e350b.module := 

# .obj17@3c1e350b
.obj17@3c1e350b := ELink
.obj17@3c1e350b.eSource := MyFile_DependsMember_modules.obj18@3c1e350b
.obj17@3c1e350b.eTarget := 
.obj17@3c1e350b.name := embox.kernel.sched.wait_queue
.obj17@3c1e350b.origin := 16:10

# .obj20@3c1e350b
.obj20@3c1e350b := MyDependsMember
.obj20@3c1e350b.__eContents := 
.obj20@3c1e350b.__eContainer := /dependsMembers.obj23@3c1e350b
.obj20@3c1e350b.modules := \
	.obj19@3c1e350b./
.obj20@3c1e350b.module := 

# .obj19@3c1e350b
.obj19@3c1e350b := ELink
.obj19@3c1e350b.eSource := MyFile_DependsMember_modules.obj20@3c1e350b
.obj19@3c1e350b.eTarget := 
.obj19@3c1e350b.name := embox.kernel.sched.mutex
.obj19@3c1e350b.origin := 18:10

# .obj22@3c1e350b
.obj22@3c1e350b := MyDependsMember
.obj22@3c1e350b.__eContents := 
.obj22@3c1e350b.__eContainer := /dependsMembers.obj23@3c1e350b
.obj22@3c1e350b.modules := \
	.obj21@3c1e350b./
.obj22@3c1e350b.module := 

# .obj21@3c1e350b
.obj21@3c1e350b := ELink
.obj21@3c1e350b.eSource := MyFile_DependsMember_modules.obj22@3c1e350b
.obj21@3c1e350b.eTarget := 
.obj21@3c1e350b.name := embox.kernel.sched.sched
.obj21@3c1e350b.origin := 19:10

# .obj28@3c1e350b
.obj28@3c1e350b := MyModuleType
.obj28@3c1e350b.__eContents := \
	sourcesMembers/.obj25@3c1e350b \
	dependsMembers/.obj27@3c1e350b
.obj28@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj28@3c1e350b.dependent := 
.obj28@3c1e350b.subTypes := 
.obj28@3c1e350b.modifiers := 
.obj28@3c1e350b.name := sem
.obj28@3c1e350b.origin := 22:8
.obj28@3c1e350b.superType := 
.obj28@3c1e350b.customStorage := 

# .obj25@3c1e350b
.obj25@3c1e350b := MySourceMember
.obj25@3c1e350b.__eContents := \
	files/.obj24@3c1e350b
.obj25@3c1e350b.__eContainer := /sourcesMembers.obj28@3c1e350b
.obj25@3c1e350b.module := 

# .obj24@3c1e350b
.obj24@3c1e350b := MyFileName
.obj24@3c1e350b.__eContents := 
.obj24@3c1e350b.__eContainer := /files.obj25@3c1e350b
.obj24@3c1e350b.fileName := semaphore.c

# .obj27@3c1e350b
.obj27@3c1e350b := MyDependsMember
.obj27@3c1e350b.__eContents := 
.obj27@3c1e350b.__eContainer := /dependsMembers.obj28@3c1e350b
.obj27@3c1e350b.modules := \
	.obj26@3c1e350b./
.obj27@3c1e350b.module := 

# .obj26@3c1e350b
.obj26@3c1e350b := ELink
.obj26@3c1e350b.eSource := MyFile_DependsMember_modules.obj27@3c1e350b
.obj26@3c1e350b.eTarget := 
.obj26@3c1e350b.name := embox.kernel.sched.sched
.obj26@3c1e350b.origin := 25:10

# .obj33@3c1e350b
.obj33@3c1e350b := MyModuleType
.obj33@3c1e350b.__eContents := \
	sourcesMembers/.obj30@3c1e350b \
	dependsMembers/.obj32@3c1e350b
.obj33@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj33@3c1e350b.dependent := 
.obj33@3c1e350b.subTypes := 
.obj33@3c1e350b.modifiers := 
.obj33@3c1e350b.name := barrier
.obj33@3c1e350b.origin := 28:8
.obj33@3c1e350b.superType := 
.obj33@3c1e350b.customStorage := 

# .obj30@3c1e350b
.obj30@3c1e350b := MySourceMember
.obj30@3c1e350b.__eContents := \
	files/.obj29@3c1e350b
.obj30@3c1e350b.__eContainer := /sourcesMembers.obj33@3c1e350b
.obj30@3c1e350b.module := 

# .obj29@3c1e350b
.obj29@3c1e350b := MyFileName
.obj29@3c1e350b.__eContents := 
.obj29@3c1e350b.__eContainer := /files.obj30@3c1e350b
.obj29@3c1e350b.fileName := barrier.c

# .obj32@3c1e350b
.obj32@3c1e350b := MyDependsMember
.obj32@3c1e350b.__eContents := 
.obj32@3c1e350b.__eContainer := /dependsMembers.obj33@3c1e350b
.obj32@3c1e350b.modules := \
	.obj31@3c1e350b./
.obj32@3c1e350b.module := 

# .obj31@3c1e350b
.obj31@3c1e350b := ELink
.obj31@3c1e350b.eSource := MyFile_DependsMember_modules.obj32@3c1e350b
.obj31@3c1e350b.eTarget := 
.obj31@3c1e350b.name := embox.kernel.sched.sched
.obj31@3c1e350b.origin := 31:10

# .obj40@3c1e350b
.obj40@3c1e350b := MyModuleType
.obj40@3c1e350b.__eContents := \
	sourcesMembers/.obj35@3c1e350b \
	dependsMembers/.obj37@3c1e350b \
	dependsMembers/.obj39@3c1e350b
.obj40@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj40@3c1e350b.dependent := 
.obj40@3c1e350b.subTypes := 
.obj40@3c1e350b.modifiers := 
.obj40@3c1e350b.name := cond
.obj40@3c1e350b.origin := 34:8
.obj40@3c1e350b.superType := 
.obj40@3c1e350b.customStorage := 

# .obj35@3c1e350b
.obj35@3c1e350b := MySourceMember
.obj35@3c1e350b.__eContents := \
	files/.obj34@3c1e350b
.obj35@3c1e350b.__eContainer := /sourcesMembers.obj40@3c1e350b
.obj35@3c1e350b.module := 

# .obj34@3c1e350b
.obj34@3c1e350b := MyFileName
.obj34@3c1e350b.__eContents := 
.obj34@3c1e350b.__eContainer := /files.obj35@3c1e350b
.obj34@3c1e350b.fileName := cond.c

# .obj37@3c1e350b
.obj37@3c1e350b := MyDependsMember
.obj37@3c1e350b.__eContents := 
.obj37@3c1e350b.__eContainer := /dependsMembers.obj40@3c1e350b
.obj37@3c1e350b.modules := \
	.obj36@3c1e350b./
.obj37@3c1e350b.module := 

# .obj36@3c1e350b
.obj36@3c1e350b := ELink
.obj36@3c1e350b.eSource := MyFile_DependsMember_modules.obj37@3c1e350b
.obj36@3c1e350b.eTarget := 
.obj36@3c1e350b.name := mutex
.obj36@3c1e350b.origin := 37:10

# .obj39@3c1e350b
.obj39@3c1e350b := MyDependsMember
.obj39@3c1e350b.__eContents := 
.obj39@3c1e350b.__eContainer := /dependsMembers.obj40@3c1e350b
.obj39@3c1e350b.modules := \
	.obj38@3c1e350b./
.obj39@3c1e350b.module := 

# .obj38@3c1e350b
.obj38@3c1e350b := ELink
.obj38@3c1e350b.eSource := MyFile_DependsMember_modules.obj39@3c1e350b
.obj38@3c1e350b.eTarget := 
.obj38@3c1e350b.name := embox.kernel.sched.sched
.obj38@3c1e350b.origin := 39:10

# .obj45@3c1e350b
.obj45@3c1e350b := MyModuleType
.obj45@3c1e350b.__eContents := \
	sourcesMembers/.obj42@3c1e350b \
	dependsMembers/.obj44@3c1e350b
.obj45@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj45@3c1e350b.dependent := 
.obj45@3c1e350b.subTypes := 
.obj45@3c1e350b.modifiers := 
.obj45@3c1e350b.name := rwlock
.obj45@3c1e350b.origin := 42:8
.obj45@3c1e350b.superType := 
.obj45@3c1e350b.customStorage := 

# .obj42@3c1e350b
.obj42@3c1e350b := MySourceMember
.obj42@3c1e350b.__eContents := \
	files/.obj41@3c1e350b
.obj42@3c1e350b.__eContainer := /sourcesMembers.obj45@3c1e350b
.obj42@3c1e350b.module := 

# .obj41@3c1e350b
.obj41@3c1e350b := MyFileName
.obj41@3c1e350b.__eContents := 
.obj41@3c1e350b.__eContainer := /files.obj42@3c1e350b
.obj41@3c1e350b.fileName := rwlock.c

# .obj44@3c1e350b
.obj44@3c1e350b := MyDependsMember
.obj44@3c1e350b.__eContents := 
.obj44@3c1e350b.__eContainer := /dependsMembers.obj45@3c1e350b
.obj44@3c1e350b.modules := \
	.obj43@3c1e350b./
.obj44@3c1e350b.module := 

# .obj43@3c1e350b
.obj43@3c1e350b := ELink
.obj43@3c1e350b.eSource := MyFile_DependsMember_modules.obj44@3c1e350b
.obj43@3c1e350b.eTarget := 
.obj43@3c1e350b.name := embox.kernel.sched.sched
.obj43@3c1e350b.origin := 45:10

# .obj50@3c1e350b
.obj50@3c1e350b := MyModuleType
.obj50@3c1e350b.__eContents := \
	sourcesMembers/.obj47@3c1e350b \
	dependsMembers/.obj49@3c1e350b
.obj50@3c1e350b.__eContainer := fileContentRoot/types.obj51@3c1e350b
.obj50@3c1e350b.dependent := 
.obj50@3c1e350b.subTypes := 
.obj50@3c1e350b.modifiers := 
.obj50@3c1e350b.name := mqueue
.obj50@3c1e350b.origin := 48:8
.obj50@3c1e350b.superType := 
.obj50@3c1e350b.customStorage := 

# .obj47@3c1e350b
.obj47@3c1e350b := MySourceMember
.obj47@3c1e350b.__eContents := \
	files/.obj46@3c1e350b
.obj47@3c1e350b.__eContainer := /sourcesMembers.obj50@3c1e350b
.obj47@3c1e350b.module := 

# .obj46@3c1e350b
.obj46@3c1e350b := MyFileName
.obj46@3c1e350b.__eContents := 
.obj46@3c1e350b.__eContainer := /files.obj47@3c1e350b
.obj46@3c1e350b.fileName := mqueue.c

# .obj49@3c1e350b
.obj49@3c1e350b := MyDependsMember
.obj49@3c1e350b.__eContents := 
.obj49@3c1e350b.__eContainer := /dependsMembers.obj50@3c1e350b
.obj49@3c1e350b.modules := \
	.obj48@3c1e350b./
.obj49@3c1e350b.module := 

# .obj48@3c1e350b
.obj48@3c1e350b := ELink
.obj48@3c1e350b.eSource := MyFile_DependsMember_modules.obj49@3c1e350b
.obj48@3c1e350b.eTarget := 
.obj48@3c1e350b.name := embox.kernel.sched.sched
.obj48@3c1e350b.origin := 51:10


__resource-mk/.cache/mybuild/files/src/kernel/thread/sync/Mybuild.mk := .obj1@3c1e350b
