# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@6a5beb0a

# .obj1@6a5beb0a
.obj1@6a5beb0a := MyFileResource
.obj1@6a5beb0a.issues := 
.obj1@6a5beb0a.contentsRoot := .obj21@6a5beb0a
.obj1@6a5beb0a.resourceSet := 
.obj1@6a5beb0a.fileName := src/tests/mmu/Mybuild
.obj1@6a5beb0a.exports := \
	embox.test \
	embox.test.mmu_core \
	embox.test.mmu_double_map \
	embox.test.mmu_double_map.vaddr_offset
.obj1@6a5beb0a.exports.embox.test := \
	.obj21@6a5beb0a
.obj1@6a5beb0a.exports.embox.test.mmu_core := \
	.obj10@6a5beb0a
.obj1@6a5beb0a.exports.embox.test.mmu_double_map := \
	.obj20@6a5beb0a
.obj1@6a5beb0a.exports.embox.test.mmu_double_map.vaddr_offset := \
	.obj11@6a5beb0a

# .obj21@6a5beb0a
.obj21@6a5beb0a := MyFileContentRoot
.obj21@6a5beb0a.__eContents := \
	types/.obj10@6a5beb0a \
	types/.obj20@6a5beb0a
.obj21@6a5beb0a.__eContainer := .obj1@6a5beb0a
.obj21@6a5beb0a.imports := 
.obj21@6a5beb0a.name := embox.test
.obj21@6a5beb0a.origin := 

# .obj10@6a5beb0a
.obj10@6a5beb0a := MyModuleType
.obj10@6a5beb0a.__eContents := \
	sourcesMembers/.obj3@6a5beb0a \
	dependsMembers/.obj5@6a5beb0a \
	dependsMembers/.obj7@6a5beb0a \
	dependsMembers/.obj9@6a5beb0a
.obj10@6a5beb0a.__eContainer := fileContentRoot/types.obj21@6a5beb0a
.obj10@6a5beb0a.dependent := 
.obj10@6a5beb0a.subTypes := 
.obj10@6a5beb0a.modifiers := 
.obj10@6a5beb0a.name := mmu_core
.obj10@6a5beb0a.origin := 3:8
.obj10@6a5beb0a.superType := 
.obj10@6a5beb0a.customStorage := 

# .obj3@6a5beb0a
.obj3@6a5beb0a := MySourceMember
.obj3@6a5beb0a.__eContents := \
	files/.obj2@6a5beb0a
.obj3@6a5beb0a.__eContainer := /sourcesMembers.obj10@6a5beb0a
.obj3@6a5beb0a.module := 

# .obj2@6a5beb0a
.obj2@6a5beb0a := MyFileName
.obj2@6a5beb0a.__eContents := 
.obj2@6a5beb0a.__eContainer := /files.obj3@6a5beb0a
.obj2@6a5beb0a.fileName := mmu_core.c

# .obj5@6a5beb0a
.obj5@6a5beb0a := MyDependsMember
.obj5@6a5beb0a.__eContents := 
.obj5@6a5beb0a.__eContainer := /dependsMembers.obj10@6a5beb0a
.obj5@6a5beb0a.modules := \
	.obj4@6a5beb0a./
.obj5@6a5beb0a.module := 

# .obj4@6a5beb0a
.obj4@6a5beb0a := ELink
.obj4@6a5beb0a.eSource := MyFile_DependsMember_modules.obj5@6a5beb0a
.obj4@6a5beb0a.eTarget := 
.obj4@6a5beb0a.name := embox.framework.LibFramework
.obj4@6a5beb0a.origin := 6:10

# .obj7@6a5beb0a
.obj7@6a5beb0a := MyDependsMember
.obj7@6a5beb0a.__eContents := 
.obj7@6a5beb0a.__eContainer := /dependsMembers.obj10@6a5beb0a
.obj7@6a5beb0a.modules := \
	.obj6@6a5beb0a./
.obj7@6a5beb0a.module := 

# .obj6@6a5beb0a
.obj6@6a5beb0a := ELink
.obj6@6a5beb0a.eSource := MyFile_DependsMember_modules.obj7@6a5beb0a
.obj6@6a5beb0a.eTarget := 
.obj6@6a5beb0a.name := embox.arch.mmu
.obj6@6a5beb0a.origin := 8:10

# .obj9@6a5beb0a
.obj9@6a5beb0a := MyDependsMember
.obj9@6a5beb0a.__eContents := 
.obj9@6a5beb0a.__eContainer := /dependsMembers.obj10@6a5beb0a
.obj9@6a5beb0a.modules := \
	.obj8@6a5beb0a./
.obj9@6a5beb0a.module := 

# .obj8@6a5beb0a
.obj8@6a5beb0a := ELink
.obj8@6a5beb0a.eSource := MyFile_DependsMember_modules.obj9@6a5beb0a
.obj8@6a5beb0a.eTarget := 
.obj8@6a5beb0a.name := embox.arch.testtrap
.obj8@6a5beb0a.origin := 9:10

# .obj20@6a5beb0a
.obj20@6a5beb0a := MyModuleType
.obj20@6a5beb0a.__eContents := \
	sourcesMembers/.obj15@6a5beb0a \
	optionsMembers/.obj13@6a5beb0a \
	dependsMembers/.obj17@6a5beb0a \
	dependsMembers/.obj19@6a5beb0a
.obj20@6a5beb0a.__eContainer := fileContentRoot/types.obj21@6a5beb0a
.obj20@6a5beb0a.dependent := 
.obj20@6a5beb0a.subTypes := 
.obj20@6a5beb0a.modifiers := 
.obj20@6a5beb0a.name := mmu_double_map
.obj20@6a5beb0a.origin := 12:8
.obj20@6a5beb0a.superType := 
.obj20@6a5beb0a.customStorage := 

# .obj15@6a5beb0a
.obj15@6a5beb0a := MySourceMember
.obj15@6a5beb0a.__eContents := \
	files/.obj14@6a5beb0a
.obj15@6a5beb0a.__eContainer := /sourcesMembers.obj20@6a5beb0a
.obj15@6a5beb0a.module := 

# .obj14@6a5beb0a
.obj14@6a5beb0a := MyFileName
.obj14@6a5beb0a.__eContents := 
.obj14@6a5beb0a.__eContainer := /files.obj15@6a5beb0a
.obj14@6a5beb0a.fileName := mmu_double_map.c

# .obj13@6a5beb0a
.obj13@6a5beb0a := MyOptionMember
.obj13@6a5beb0a.__eContents := \
	options/.obj11@6a5beb0a
.obj13@6a5beb0a.__eContainer := /optionsMembers.obj20@6a5beb0a
.obj13@6a5beb0a.module := 

# .obj11@6a5beb0a
.obj11@6a5beb0a := MyNumberOption
.obj11@6a5beb0a.__eContents := \
	defaultValue/.obj12@6a5beb0a
.obj11@6a5beb0a.__eContainer := /options.obj13@6a5beb0a
.obj11@6a5beb0a.name := vaddr_offset
.obj11@6a5beb0a.origin := 

# .obj12@6a5beb0a
.obj12@6a5beb0a := MyNumberLiteral
.obj12@6a5beb0a.__eContents := 
.obj12@6a5beb0a.__eContainer := /defaultValue.obj11@6a5beb0a
.obj12@6a5beb0a.value := 2147483648

# .obj17@6a5beb0a
.obj17@6a5beb0a := MyDependsMember
.obj17@6a5beb0a.__eContents := 
.obj17@6a5beb0a.__eContainer := /dependsMembers.obj20@6a5beb0a
.obj17@6a5beb0a.modules := \
	.obj16@6a5beb0a./
.obj17@6a5beb0a.module := 

# .obj16@6a5beb0a
.obj16@6a5beb0a := ELink
.obj16@6a5beb0a.eSource := MyFile_DependsMember_modules.obj17@6a5beb0a
.obj16@6a5beb0a.eTarget := 
.obj16@6a5beb0a.name := embox.arch.mmu
.obj16@6a5beb0a.origin := 17:10

# .obj19@6a5beb0a
.obj19@6a5beb0a := MyDependsMember
.obj19@6a5beb0a.__eContents := 
.obj19@6a5beb0a.__eContainer := /dependsMembers.obj20@6a5beb0a
.obj19@6a5beb0a.modules := \
	.obj18@6a5beb0a./
.obj19@6a5beb0a.module := 

# .obj18@6a5beb0a
.obj18@6a5beb0a := ELink
.obj18@6a5beb0a.eSource := MyFile_DependsMember_modules.obj19@6a5beb0a
.obj18@6a5beb0a.eTarget := 
.obj18@6a5beb0a.name := embox.arch.testtrap
.obj18@6a5beb0a.origin := 18:10


__resource-mk/.cache/mybuild/files/src/tests/mmu/Mybuild.mk := .obj1@6a5beb0a
