# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@40098c07

# .obj1@40098c07
.obj1@40098c07 := MyFileResource
.obj1@40098c07.issues := 
.obj1@40098c07.contentsRoot := .obj57@40098c07
.obj1@40098c07.resourceSet := 
.obj1@40098c07.fileName := src/tests/util/Mybuild
.obj1@40098c07.exports := \
	embox.test.util \
	embox.test.util.array_test \
	embox.test.util.bit_test \
	embox.test.util.bitmap_test \
	embox.test.util.slist_test \
	embox.test.util.tree_test \
	embox.test.util.ring_buff_test \
	embox.test.util.hashtable_test \
	embox.test.util.dlist_test \
	embox.test.util.indexator_test
.obj1@40098c07.exports.embox.test.util := \
	.obj57@40098c07
.obj1@40098c07.exports.embox.test.util.array_test := \
	.obj6@40098c07
.obj1@40098c07.exports.embox.test.util.bit_test := \
	.obj11@40098c07
.obj1@40098c07.exports.embox.test.util.bitmap_test := \
	.obj18@40098c07
.obj1@40098c07.exports.embox.test.util.slist_test := \
	.obj25@40098c07
.obj1@40098c07.exports.embox.test.util.tree_test := \
	.obj30@40098c07
.obj1@40098c07.exports.embox.test.util.ring_buff_test := \
	.obj37@40098c07
.obj1@40098c07.exports.embox.test.util.hashtable_test := \
	.obj44@40098c07
.obj1@40098c07.exports.embox.test.util.dlist_test := \
	.obj49@40098c07
.obj1@40098c07.exports.embox.test.util.indexator_test := \
	.obj56@40098c07

# .obj57@40098c07
.obj57@40098c07 := MyFileContentRoot
.obj57@40098c07.__eContents := \
	types/.obj6@40098c07 \
	types/.obj11@40098c07 \
	types/.obj18@40098c07 \
	types/.obj25@40098c07 \
	types/.obj30@40098c07 \
	types/.obj37@40098c07 \
	types/.obj44@40098c07 \
	types/.obj49@40098c07 \
	types/.obj56@40098c07
.obj57@40098c07.__eContainer := .obj1@40098c07
.obj57@40098c07.imports := 
.obj57@40098c07.name := embox.test.util
.obj57@40098c07.origin := 

# .obj6@40098c07
.obj6@40098c07 := MyModuleType
.obj6@40098c07.__eContents := \
	sourcesMembers/.obj3@40098c07 \
	dependsMembers/.obj5@40098c07
.obj6@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj6@40098c07.dependent := 
.obj6@40098c07.subTypes := 
.obj6@40098c07.modifiers := 
.obj6@40098c07.name := array_test
.obj6@40098c07.origin := 3:8
.obj6@40098c07.superType := 
.obj6@40098c07.customStorage := 

# .obj3@40098c07
.obj3@40098c07 := MySourceMember
.obj3@40098c07.__eContents := \
	files/.obj2@40098c07
.obj3@40098c07.__eContainer := /sourcesMembers.obj6@40098c07
.obj3@40098c07.module := 

# .obj2@40098c07
.obj2@40098c07 := MyFileName
.obj2@40098c07.__eContents := 
.obj2@40098c07.__eContainer := /files.obj3@40098c07
.obj2@40098c07.fileName := array_test.c

# .obj5@40098c07
.obj5@40098c07 := MyDependsMember
.obj5@40098c07.__eContents := 
.obj5@40098c07.__eContainer := /dependsMembers.obj6@40098c07
.obj5@40098c07.modules := \
	.obj4@40098c07./
.obj5@40098c07.module := 

# .obj4@40098c07
.obj4@40098c07 := ELink
.obj4@40098c07.eSource := MyFile_DependsMember_modules.obj5@40098c07
.obj4@40098c07.eTarget := 
.obj4@40098c07.name := embox.framework.LibFramework
.obj4@40098c07.origin := 6:10

# .obj11@40098c07
.obj11@40098c07 := MyModuleType
.obj11@40098c07.__eContents := \
	sourcesMembers/.obj8@40098c07 \
	dependsMembers/.obj10@40098c07
.obj11@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj11@40098c07.dependent := 
.obj11@40098c07.subTypes := 
.obj11@40098c07.modifiers := 
.obj11@40098c07.name := bit_test
.obj11@40098c07.origin := 9:8
.obj11@40098c07.superType := 
.obj11@40098c07.customStorage := 

# .obj8@40098c07
.obj8@40098c07 := MySourceMember
.obj8@40098c07.__eContents := \
	files/.obj7@40098c07
.obj8@40098c07.__eContainer := /sourcesMembers.obj11@40098c07
.obj8@40098c07.module := 

# .obj7@40098c07
.obj7@40098c07 := MyFileName
.obj7@40098c07.__eContents := 
.obj7@40098c07.__eContainer := /files.obj8@40098c07
.obj7@40098c07.fileName := bit_test.c

# .obj10@40098c07
.obj10@40098c07 := MyDependsMember
.obj10@40098c07.__eContents := 
.obj10@40098c07.__eContainer := /dependsMembers.obj11@40098c07
.obj10@40098c07.modules := \
	.obj9@40098c07./
.obj10@40098c07.module := 

# .obj9@40098c07
.obj9@40098c07 := ELink
.obj9@40098c07.eSource := MyFile_DependsMember_modules.obj10@40098c07
.obj9@40098c07.eTarget := 
.obj9@40098c07.name := embox.framework.LibFramework
.obj9@40098c07.origin := 12:10

# .obj18@40098c07
.obj18@40098c07 := MyModuleType
.obj18@40098c07.__eContents := \
	sourcesMembers/.obj13@40098c07 \
	dependsMembers/.obj15@40098c07 \
	dependsMembers/.obj17@40098c07
.obj18@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj18@40098c07.dependent := 
.obj18@40098c07.subTypes := 
.obj18@40098c07.modifiers := 
.obj18@40098c07.name := bitmap_test
.obj18@40098c07.origin := 15:8
.obj18@40098c07.superType := 
.obj18@40098c07.customStorage := 

# .obj13@40098c07
.obj13@40098c07 := MySourceMember
.obj13@40098c07.__eContents := \
	files/.obj12@40098c07
.obj13@40098c07.__eContainer := /sourcesMembers.obj18@40098c07
.obj13@40098c07.module := 

# .obj12@40098c07
.obj12@40098c07 := MyFileName
.obj12@40098c07.__eContents := 
.obj12@40098c07.__eContainer := /files.obj13@40098c07
.obj12@40098c07.fileName := bitmap_test.c

# .obj15@40098c07
.obj15@40098c07 := MyDependsMember
.obj15@40098c07.__eContents := 
.obj15@40098c07.__eContainer := /dependsMembers.obj18@40098c07
.obj15@40098c07.modules := \
	.obj14@40098c07./
.obj15@40098c07.module := 

# .obj14@40098c07
.obj14@40098c07 := ELink
.obj14@40098c07.eSource := MyFile_DependsMember_modules.obj15@40098c07
.obj14@40098c07.eTarget := 
.obj14@40098c07.name := embox.util.Bitmap
.obj14@40098c07.origin := 18:10

# .obj17@40098c07
.obj17@40098c07 := MyDependsMember
.obj17@40098c07.__eContents := 
.obj17@40098c07.__eContainer := /dependsMembers.obj18@40098c07
.obj17@40098c07.modules := \
	.obj16@40098c07./
.obj17@40098c07.module := 

# .obj16@40098c07
.obj16@40098c07 := ELink
.obj16@40098c07.eSource := MyFile_DependsMember_modules.obj17@40098c07
.obj16@40098c07.eTarget := 
.obj16@40098c07.name := embox.framework.LibFramework
.obj16@40098c07.origin := 19:10

# .obj25@40098c07
.obj25@40098c07 := MyModuleType
.obj25@40098c07.__eContents := \
	sourcesMembers/.obj20@40098c07 \
	dependsMembers/.obj22@40098c07 \
	dependsMembers/.obj24@40098c07
.obj25@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj25@40098c07.dependent := 
.obj25@40098c07.subTypes := 
.obj25@40098c07.modifiers := 
.obj25@40098c07.name := slist_test
.obj25@40098c07.origin := 22:8
.obj25@40098c07.superType := 
.obj25@40098c07.customStorage := 

# .obj20@40098c07
.obj20@40098c07 := MySourceMember
.obj20@40098c07.__eContents := \
	files/.obj19@40098c07
.obj20@40098c07.__eContainer := /sourcesMembers.obj25@40098c07
.obj20@40098c07.module := 

# .obj19@40098c07
.obj19@40098c07 := MyFileName
.obj19@40098c07.__eContents := 
.obj19@40098c07.__eContainer := /files.obj20@40098c07
.obj19@40098c07.fileName := slist_test.c

# .obj22@40098c07
.obj22@40098c07 := MyDependsMember
.obj22@40098c07.__eContents := 
.obj22@40098c07.__eContainer := /dependsMembers.obj25@40098c07
.obj22@40098c07.modules := \
	.obj21@40098c07./
.obj22@40098c07.module := 

# .obj21@40098c07
.obj21@40098c07 := ELink
.obj21@40098c07.eSource := MyFile_DependsMember_modules.obj22@40098c07
.obj21@40098c07.eTarget := 
.obj21@40098c07.name := embox.util.LibUtil
.obj21@40098c07.origin := 25:10

# .obj24@40098c07
.obj24@40098c07 := MyDependsMember
.obj24@40098c07.__eContents := 
.obj24@40098c07.__eContainer := /dependsMembers.obj25@40098c07
.obj24@40098c07.modules := \
	.obj23@40098c07./
.obj24@40098c07.module := 

# .obj23@40098c07
.obj23@40098c07 := ELink
.obj23@40098c07.eSource := MyFile_DependsMember_modules.obj24@40098c07
.obj23@40098c07.eTarget := 
.obj23@40098c07.name := embox.framework.LibFramework
.obj23@40098c07.origin := 26:10

# .obj30@40098c07
.obj30@40098c07 := MyModuleType
.obj30@40098c07.__eContents := \
	sourcesMembers/.obj27@40098c07 \
	dependsMembers/.obj29@40098c07
.obj30@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj30@40098c07.dependent := 
.obj30@40098c07.subTypes := 
.obj30@40098c07.modifiers := 
.obj30@40098c07.name := tree_test
.obj30@40098c07.origin := 29:8
.obj30@40098c07.superType := 
.obj30@40098c07.customStorage := 

# .obj27@40098c07
.obj27@40098c07 := MySourceMember
.obj27@40098c07.__eContents := \
	files/.obj26@40098c07
.obj27@40098c07.__eContainer := /sourcesMembers.obj30@40098c07
.obj27@40098c07.module := 

# .obj26@40098c07
.obj26@40098c07 := MyFileName
.obj26@40098c07.__eContents := 
.obj26@40098c07.__eContainer := /files.obj27@40098c07
.obj26@40098c07.fileName := tree_test.c

# .obj29@40098c07
.obj29@40098c07 := MyDependsMember
.obj29@40098c07.__eContents := 
.obj29@40098c07.__eContainer := /dependsMembers.obj30@40098c07
.obj29@40098c07.modules := \
	.obj28@40098c07./
.obj29@40098c07.module := 

# .obj28@40098c07
.obj28@40098c07 := ELink
.obj28@40098c07.eSource := MyFile_DependsMember_modules.obj29@40098c07
.obj28@40098c07.eTarget := 
.obj28@40098c07.name := embox.framework.LibFramework
.obj28@40098c07.origin := 32:10

# .obj37@40098c07
.obj37@40098c07 := MyModuleType
.obj37@40098c07.__eContents := \
	sourcesMembers/.obj32@40098c07 \
	dependsMembers/.obj34@40098c07 \
	dependsMembers/.obj36@40098c07
.obj37@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj37@40098c07.dependent := 
.obj37@40098c07.subTypes := 
.obj37@40098c07.modifiers := 
.obj37@40098c07.name := ring_buff_test
.obj37@40098c07.origin := 35:8
.obj37@40098c07.superType := 
.obj37@40098c07.customStorage := 

# .obj32@40098c07
.obj32@40098c07 := MySourceMember
.obj32@40098c07.__eContents := \
	files/.obj31@40098c07
.obj32@40098c07.__eContainer := /sourcesMembers.obj37@40098c07
.obj32@40098c07.module := 

# .obj31@40098c07
.obj31@40098c07 := MyFileName
.obj31@40098c07.__eContents := 
.obj31@40098c07.__eContainer := /files.obj32@40098c07
.obj31@40098c07.fileName := ring_buff_test.c

# .obj34@40098c07
.obj34@40098c07 := MyDependsMember
.obj34@40098c07.__eContents := 
.obj34@40098c07.__eContainer := /dependsMembers.obj37@40098c07
.obj34@40098c07.modules := \
	.obj33@40098c07./
.obj34@40098c07.module := 

# .obj33@40098c07
.obj33@40098c07 := ELink
.obj33@40098c07.eSource := MyFile_DependsMember_modules.obj34@40098c07
.obj33@40098c07.eTarget := 
.obj33@40098c07.name := embox.util.LibUtil
.obj33@40098c07.origin := 38:10

# .obj36@40098c07
.obj36@40098c07 := MyDependsMember
.obj36@40098c07.__eContents := 
.obj36@40098c07.__eContainer := /dependsMembers.obj37@40098c07
.obj36@40098c07.modules := \
	.obj35@40098c07./
.obj36@40098c07.module := 

# .obj35@40098c07
.obj35@40098c07 := ELink
.obj35@40098c07.eSource := MyFile_DependsMember_modules.obj36@40098c07
.obj35@40098c07.eTarget := 
.obj35@40098c07.name := embox.framework.LibFramework
.obj35@40098c07.origin := 39:10

# .obj44@40098c07
.obj44@40098c07 := MyModuleType
.obj44@40098c07.__eContents := \
	sourcesMembers/.obj39@40098c07 \
	dependsMembers/.obj41@40098c07 \
	dependsMembers/.obj43@40098c07
.obj44@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj44@40098c07.dependent := 
.obj44@40098c07.subTypes := 
.obj44@40098c07.modifiers := 
.obj44@40098c07.name := hashtable_test
.obj44@40098c07.origin := 42:8
.obj44@40098c07.superType := 
.obj44@40098c07.customStorage := 

# .obj39@40098c07
.obj39@40098c07 := MySourceMember
.obj39@40098c07.__eContents := \
	files/.obj38@40098c07
.obj39@40098c07.__eContainer := /sourcesMembers.obj44@40098c07
.obj39@40098c07.module := 

# .obj38@40098c07
.obj38@40098c07 := MyFileName
.obj38@40098c07.__eContents := 
.obj38@40098c07.__eContainer := /files.obj39@40098c07
.obj38@40098c07.fileName := hashtable_test.c

# .obj41@40098c07
.obj41@40098c07 := MyDependsMember
.obj41@40098c07.__eContents := 
.obj41@40098c07.__eContainer := /dependsMembers.obj44@40098c07
.obj41@40098c07.modules := \
	.obj40@40098c07./
.obj41@40098c07.module := 

# .obj40@40098c07
.obj40@40098c07 := ELink
.obj40@40098c07.eSource := MyFile_DependsMember_modules.obj41@40098c07
.obj40@40098c07.eTarget := 
.obj40@40098c07.name := embox.util.hashtable
.obj40@40098c07.origin := 45:10

# .obj43@40098c07
.obj43@40098c07 := MyDependsMember
.obj43@40098c07.__eContents := 
.obj43@40098c07.__eContainer := /dependsMembers.obj44@40098c07
.obj43@40098c07.modules := \
	.obj42@40098c07./
.obj43@40098c07.module := 

# .obj42@40098c07
.obj42@40098c07 := ELink
.obj42@40098c07.eSource := MyFile_DependsMember_modules.obj43@40098c07
.obj42@40098c07.eTarget := 
.obj42@40098c07.name := embox.framework.LibFramework
.obj42@40098c07.origin := 46:10

# .obj49@40098c07
.obj49@40098c07 := MyModuleType
.obj49@40098c07.__eContents := \
	sourcesMembers/.obj46@40098c07 \
	dependsMembers/.obj48@40098c07
.obj49@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj49@40098c07.dependent := 
.obj49@40098c07.subTypes := 
.obj49@40098c07.modifiers := 
.obj49@40098c07.name := dlist_test
.obj49@40098c07.origin := 49:8
.obj49@40098c07.superType := 
.obj49@40098c07.customStorage := 

# .obj46@40098c07
.obj46@40098c07 := MySourceMember
.obj46@40098c07.__eContents := \
	files/.obj45@40098c07
.obj46@40098c07.__eContainer := /sourcesMembers.obj49@40098c07
.obj46@40098c07.module := 

# .obj45@40098c07
.obj45@40098c07 := MyFileName
.obj45@40098c07.__eContents := 
.obj45@40098c07.__eContainer := /files.obj46@40098c07
.obj45@40098c07.fileName := dlist_test.c

# .obj48@40098c07
.obj48@40098c07 := MyDependsMember
.obj48@40098c07.__eContents := 
.obj48@40098c07.__eContainer := /dependsMembers.obj49@40098c07
.obj48@40098c07.modules := \
	.obj47@40098c07./
.obj48@40098c07.module := 

# .obj47@40098c07
.obj47@40098c07 := ELink
.obj47@40098c07.eSource := MyFile_DependsMember_modules.obj48@40098c07
.obj47@40098c07.eTarget := 
.obj47@40098c07.name := embox.framework.LibFramework
.obj47@40098c07.origin := 52:10

# .obj56@40098c07
.obj56@40098c07 := MyModuleType
.obj56@40098c07.__eContents := \
	sourcesMembers/.obj51@40098c07 \
	dependsMembers/.obj53@40098c07 \
	dependsMembers/.obj55@40098c07
.obj56@40098c07.__eContainer := fileContentRoot/types.obj57@40098c07
.obj56@40098c07.dependent := 
.obj56@40098c07.subTypes := 
.obj56@40098c07.modifiers := 
.obj56@40098c07.name := indexator_test
.obj56@40098c07.origin := 55:8
.obj56@40098c07.superType := 
.obj56@40098c07.customStorage := 

# .obj51@40098c07
.obj51@40098c07 := MySourceMember
.obj51@40098c07.__eContents := \
	files/.obj50@40098c07
.obj51@40098c07.__eContainer := /sourcesMembers.obj56@40098c07
.obj51@40098c07.module := 

# .obj50@40098c07
.obj50@40098c07 := MyFileName
.obj50@40098c07.__eContents := 
.obj50@40098c07.__eContainer := /files.obj51@40098c07
.obj50@40098c07.fileName := indexator_test.c

# .obj53@40098c07
.obj53@40098c07 := MyDependsMember
.obj53@40098c07.__eContents := 
.obj53@40098c07.__eContainer := /dependsMembers.obj56@40098c07
.obj53@40098c07.modules := \
	.obj52@40098c07./
.obj53@40098c07.module := 

# .obj52@40098c07
.obj52@40098c07 := ELink
.obj52@40098c07.eSource := MyFile_DependsMember_modules.obj53@40098c07
.obj52@40098c07.eTarget := 
.obj52@40098c07.name := embox.util.indexator
.obj52@40098c07.origin := 58:10

# .obj55@40098c07
.obj55@40098c07 := MyDependsMember
.obj55@40098c07.__eContents := 
.obj55@40098c07.__eContainer := /dependsMembers.obj56@40098c07
.obj55@40098c07.modules := \
	.obj54@40098c07./
.obj55@40098c07.module := 

# .obj54@40098c07
.obj54@40098c07 := ELink
.obj54@40098c07.eSource := MyFile_DependsMember_modules.obj55@40098c07
.obj54@40098c07.eTarget := 
.obj54@40098c07.name := embox.framework.LibFramework
.obj54@40098c07.origin := 59:10


__resource-mk/.cache/mybuild/files/src/tests/util/Mybuild.mk := .obj1@40098c07
