# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@206e34d8

# .obj1@206e34d8
.obj1@206e34d8 := MyFileResource
.obj1@206e34d8.issues := 
.obj1@206e34d8.contentsRoot := .obj26@206e34d8
.obj1@206e34d8.resourceSet := 
.obj1@206e34d8.fileName := src/drivers/net/rtl8139/Mybuild
.obj1@206e34d8.exports := \
	embox.driver.net \
	embox.driver.net.rtl8139
.obj1@206e34d8.exports.embox.driver.net := \
	.obj26@206e34d8
.obj1@206e34d8.exports.embox.driver.net.rtl8139 := \
	.obj25@206e34d8

# .obj26@206e34d8
.obj26@206e34d8 := MyFileContentRoot
.obj26@206e34d8.__eContents := \
	types/.obj25@206e34d8
.obj26@206e34d8.__eContainer := .obj1@206e34d8
.obj26@206e34d8.imports := 
.obj26@206e34d8.name := embox.driver.net
.obj26@206e34d8.origin := 

# .obj25@206e34d8
.obj25@206e34d8 := MyModuleType
.obj25@206e34d8.__eContents := \
	sourcesMembers/.obj8@206e34d8 \
	sourcesMembers/.obj10@206e34d8 \
	dependsMembers/.obj12@206e34d8 \
	dependsMembers/.obj14@206e34d8 \
	dependsMembers/.obj16@206e34d8 \
	dependsMembers/.obj18@206e34d8 \
	dependsMembers/.obj20@206e34d8 \
	dependsMembers/.obj22@206e34d8 \
	dependsMembers/.obj24@206e34d8
.obj25@206e34d8.__eContainer := fileContentRoot/types.obj26@206e34d8
.obj25@206e34d8.dependent := 
.obj25@206e34d8.subTypes := 
.obj25@206e34d8.modifiers := 
.obj25@206e34d8.name := rtl8139
.obj25@206e34d8.origin := 3:8
.obj25@206e34d8.superType := 
.obj25@206e34d8.customStorage := 

# .obj8@206e34d8
.obj8@206e34d8 := MySourceMember
.obj8@206e34d8.__eContents := \
	files/.obj7@206e34d8 \
	annotations/.obj6@206e34d8
.obj8@206e34d8.__eContainer := /sourcesMembers.obj25@206e34d8
.obj8@206e34d8.module := 

# .obj7@206e34d8
.obj7@206e34d8 := MyFileName
.obj7@206e34d8.__eContents := 
.obj7@206e34d8.__eContainer := /files.obj8@206e34d8
.obj7@206e34d8.fileName := rtl8139.h

# .obj6@206e34d8
.obj6@206e34d8 := MyAnnotation
.obj6@206e34d8.__eContents := \
	bindings/.obj5@206e34d8
.obj6@206e34d8.__eContainer := target/annotations.obj8@206e34d8
.obj6@206e34d8.type := .obj2@206e34d8./

# .obj5@206e34d8
.obj5@206e34d8 := MyOptionBinding
.obj5@206e34d8.__eContents := \
	value/.obj4@206e34d8
.obj5@206e34d8.__eContainer := /bindings.obj6@206e34d8
.obj5@206e34d8.option := .obj3@206e34d8./

# .obj4@206e34d8
.obj4@206e34d8 := MyStringLiteral
.obj4@206e34d8.__eContents := 
.obj4@206e34d8.__eContainer := /value.obj5@206e34d8
.obj4@206e34d8.value := drivers/net

# .obj3@206e34d8
.obj3@206e34d8 := ELink
.obj3@206e34d8.eSource := MyFile_OptionBinding_option.obj5@206e34d8
.obj3@206e34d8.eTarget := 
.obj3@206e34d8.name := path
.obj3@206e34d8.origin := 4:17

# .obj2@206e34d8
.obj2@206e34d8 := ELink
.obj2@206e34d8.eSource := MyFile_Annotation_type.obj6@206e34d8
.obj2@206e34d8.eTarget := 
.obj2@206e34d8.name := IncludeExport
.obj2@206e34d8.origin := 4:3

# .obj10@206e34d8
.obj10@206e34d8 := MySourceMember
.obj10@206e34d8.__eContents := \
	files/.obj9@206e34d8
.obj10@206e34d8.__eContainer := /sourcesMembers.obj25@206e34d8
.obj10@206e34d8.module := 

# .obj9@206e34d8
.obj9@206e34d8 := MyFileName
.obj9@206e34d8.__eContents := 
.obj9@206e34d8.__eContainer := /files.obj10@206e34d8
.obj9@206e34d8.fileName := rtl8139.c

# .obj12@206e34d8
.obj12@206e34d8 := MyDependsMember
.obj12@206e34d8.__eContents := 
.obj12@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj12@206e34d8.modules := \
	.obj11@206e34d8./
.obj12@206e34d8.module := 

# .obj11@206e34d8
.obj11@206e34d8 := ELink
.obj11@206e34d8.eSource := MyFile_DependsMember_modules.obj12@206e34d8
.obj11@206e34d8.eTarget := 
.obj11@206e34d8.name := embox.net.skbuff
.obj11@206e34d8.origin := 8:10

# .obj14@206e34d8
.obj14@206e34d8 := MyDependsMember
.obj14@206e34d8.__eContents := 
.obj14@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj14@206e34d8.modules := \
	.obj13@206e34d8./
.obj14@206e34d8.module := 

# .obj13@206e34d8
.obj13@206e34d8 := ELink
.obj13@206e34d8.eSource := MyFile_DependsMember_modules.obj14@206e34d8
.obj13@206e34d8.eTarget := 
.obj13@206e34d8.name := embox.compat.libc.all
.obj13@206e34d8.origin := 9:10

# .obj16@206e34d8
.obj16@206e34d8 := MyDependsMember
.obj16@206e34d8.__eContents := 
.obj16@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj16@206e34d8.modules := \
	.obj15@206e34d8./
.obj16@206e34d8.module := 

# .obj15@206e34d8
.obj15@206e34d8 := ELink
.obj15@206e34d8.eSource := MyFile_DependsMember_modules.obj16@206e34d8
.obj15@206e34d8.eTarget := 
.obj15@206e34d8.name := embox.driver.pci
.obj15@206e34d8.origin := 10:10

# .obj18@206e34d8
.obj18@206e34d8 := MyDependsMember
.obj18@206e34d8.__eContents := 
.obj18@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj18@206e34d8.modules := \
	.obj17@206e34d8./
.obj18@206e34d8.module := 

# .obj17@206e34d8
.obj17@206e34d8 := ELink
.obj17@206e34d8.eSource := MyFile_DependsMember_modules.obj18@206e34d8
.obj17@206e34d8.eTarget := 
.obj17@206e34d8.name := embox.net.l2.ethernet
.obj17@206e34d8.origin := 11:10

# .obj20@206e34d8
.obj20@206e34d8 := MyDependsMember
.obj20@206e34d8.__eContents := 
.obj20@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj20@206e34d8.modules := \
	.obj19@206e34d8./
.obj20@206e34d8.module := 

# .obj19@206e34d8
.obj19@206e34d8 := ELink
.obj19@206e34d8.eSource := MyFile_DependsMember_modules.obj20@206e34d8
.obj19@206e34d8.eTarget := 
.obj19@206e34d8.name := embox.kernel.irq
.obj19@206e34d8.origin := 12:10

# .obj22@206e34d8
.obj22@206e34d8 := MyDependsMember
.obj22@206e34d8.__eContents := 
.obj22@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj22@206e34d8.modules := \
	.obj21@206e34d8./
.obj22@206e34d8.module := 

# .obj21@206e34d8
.obj21@206e34d8 := ELink
.obj21@206e34d8.eSource := MyFile_DependsMember_modules.obj22@206e34d8
.obj21@206e34d8.eTarget := 
.obj21@206e34d8.name := embox.net.dev
.obj21@206e34d8.origin := 13:10

# .obj24@206e34d8
.obj24@206e34d8 := MyDependsMember
.obj24@206e34d8.__eContents := 
.obj24@206e34d8.__eContainer := /dependsMembers.obj25@206e34d8
.obj24@206e34d8.modules := \
	.obj23@206e34d8./
.obj24@206e34d8.module := 

# .obj23@206e34d8
.obj23@206e34d8 := ELink
.obj23@206e34d8.eSource := MyFile_DependsMember_modules.obj24@206e34d8
.obj23@206e34d8.eTarget := 
.obj23@206e34d8.name := embox.net.entry_api
.obj23@206e34d8.origin := 14:10


__resource-mk/.cache/mybuild/files/src/drivers/net/rtl8139/Mybuild.mk := .obj1@206e34d8
