# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@594d1211

# .obj1@594d1211
.obj1@594d1211 := MyFileResource
.obj1@594d1211.issues := 
.obj1@594d1211.contentsRoot := .obj26@594d1211
.obj1@594d1211.resourceSet := 
.obj1@594d1211.fileName := src/cmds/testing/fb_draw_image/Mybuild
.obj1@594d1211.exports := \
	embox.cmd.testing \
	embox.cmd.testing.fb_draw_image
.obj1@594d1211.exports.embox.cmd.testing := \
	.obj26@594d1211
.obj1@594d1211.exports.embox.cmd.testing.fb_draw_image := \
	.obj25@594d1211

# .obj26@594d1211
.obj26@594d1211 := MyFileContentRoot
.obj26@594d1211.__eContents := \
	types/.obj25@594d1211
.obj26@594d1211.__eContainer := .obj1@594d1211
.obj26@594d1211.imports := 
.obj26@594d1211.name := embox.cmd.testing
.obj26@594d1211.origin := 

# .obj25@594d1211
.obj25@594d1211 := MyModuleType
.obj25@594d1211.__eContents := \
	sourcesMembers/.obj16@594d1211 \
	dependsMembers/.obj18@594d1211 \
	dependsMembers/.obj20@594d1211 \
	dependsMembers/.obj22@594d1211 \
	dependsMembers/.obj24@594d1211 \
	annotations/.obj3@594d1211 \
	annotations/.obj14@594d1211
.obj25@594d1211.__eContainer := fileContentRoot/types.obj26@594d1211
.obj25@594d1211.dependent := 
.obj25@594d1211.subTypes := 
.obj25@594d1211.modifiers := 
.obj25@594d1211.name := fb_draw_image
.obj25@594d1211.origin := 16:8
.obj25@594d1211.superType := 
.obj25@594d1211.customStorage := 

# .obj16@594d1211
.obj16@594d1211 := MySourceMember
.obj16@594d1211.__eContents := \
	files/.obj15@594d1211
.obj16@594d1211.__eContainer := /sourcesMembers.obj25@594d1211
.obj16@594d1211.module := 

# .obj15@594d1211
.obj15@594d1211 := MyFileName
.obj15@594d1211.__eContents := 
.obj15@594d1211.__eContainer := /files.obj16@594d1211
.obj15@594d1211.fileName := fb_draw_image.c

# .obj18@594d1211
.obj18@594d1211 := MyDependsMember
.obj18@594d1211.__eContents := 
.obj18@594d1211.__eContainer := /dependsMembers.obj25@594d1211
.obj18@594d1211.modules := \
	.obj17@594d1211./
.obj18@594d1211.module := 

# .obj17@594d1211
.obj17@594d1211 := ELink
.obj17@594d1211.eSource := MyFile_DependsMember_modules.obj18@594d1211
.obj17@594d1211.eTarget := 
.obj17@594d1211.name := embox.fs.file_format
.obj17@594d1211.origin := 19:10

# .obj20@594d1211
.obj20@594d1211 := MyDependsMember
.obj20@594d1211.__eContents := 
.obj20@594d1211.__eContainer := /dependsMembers.obj25@594d1211
.obj20@594d1211.modules := \
	.obj19@594d1211./
.obj20@594d1211.module := 

# .obj19@594d1211
.obj19@594d1211 := ELink
.obj19@594d1211.eSource := MyFile_DependsMember_modules.obj20@594d1211
.obj19@594d1211.eTarget := 
.obj19@594d1211.name := embox.lib.bmp
.obj19@594d1211.origin := 20:10

# .obj22@594d1211
.obj22@594d1211 := MyDependsMember
.obj22@594d1211.__eContents := 
.obj22@594d1211.__eContainer := /dependsMembers.obj25@594d1211
.obj22@594d1211.modules := \
	.obj21@594d1211./
.obj22@594d1211.module := 

# .obj21@594d1211
.obj21@594d1211 := ELink
.obj21@594d1211.eSource := MyFile_DependsMember_modules.obj22@594d1211
.obj21@594d1211.eTarget := 
.obj21@594d1211.name := embox.lib.png
.obj21@594d1211.origin := 21:10

# .obj24@594d1211
.obj24@594d1211 := MyDependsMember
.obj24@594d1211.__eContents := 
.obj24@594d1211.__eContainer := /dependsMembers.obj25@594d1211
.obj24@594d1211.modules := \
	.obj23@594d1211./
.obj24@594d1211.module := 

# .obj23@594d1211
.obj23@594d1211 := ELink
.obj23@594d1211.eSource := MyFile_DependsMember_modules.obj24@594d1211
.obj23@594d1211.eTarget := 
.obj23@594d1211.name := embox.lib.fb_draw
.obj23@594d1211.origin := 22:10

# .obj3@594d1211
.obj3@594d1211 := MyAnnotation
.obj3@594d1211.__eContents := 
.obj3@594d1211.__eContainer := target/annotations.obj25@594d1211
.obj3@594d1211.type := .obj2@594d1211./

# .obj2@594d1211
.obj2@594d1211 := ELink
.obj2@594d1211.eSource := MyFile_Annotation_type.obj3@594d1211
.obj2@594d1211.eTarget := 
.obj2@594d1211.name := AutoCmd
.obj2@594d1211.origin := 3:2

# .obj14@594d1211
.obj14@594d1211 := MyAnnotation
.obj14@594d1211.__eContents := \
	bindings/.obj7@594d1211 \
	bindings/.obj10@594d1211 \
	bindings/.obj13@594d1211
.obj14@594d1211.__eContainer := target/annotations.obj25@594d1211
.obj14@594d1211.type := .obj4@594d1211./

# .obj7@594d1211
.obj7@594d1211 := MyOptionBinding
.obj7@594d1211.__eContents := \
	value/.obj6@594d1211
.obj7@594d1211.__eContainer := /bindings.obj14@594d1211
.obj7@594d1211.option := .obj5@594d1211./

# .obj6@594d1211
.obj6@594d1211 := MyStringLiteral
.obj6@594d1211.__eContents := 
.obj6@594d1211.__eContainer := /value.obj7@594d1211
.obj6@594d1211.value := fb_draw_image

# .obj5@594d1211
.obj5@594d1211 := ELink
.obj5@594d1211.eSource := MyFile_OptionBinding_option.obj7@594d1211
.obj5@594d1211.eTarget := 
.obj5@594d1211.name := name
.obj5@594d1211.origin := 4:6

# .obj10@594d1211
.obj10@594d1211 := MyOptionBinding
.obj10@594d1211.__eContents := \
	value/.obj9@594d1211
.obj10@594d1211.__eContainer := /bindings.obj14@594d1211
.obj10@594d1211.option := .obj8@594d1211./

# .obj9@594d1211
.obj9@594d1211 := MyStringLiteral
.obj9@594d1211.__eContents := 
.obj9@594d1211.__eContainer := /value.obj10@594d1211
.obj9@594d1211.value := demo application draw images to the framebuffer

# .obj8@594d1211
.obj8@594d1211 := ELink
.obj8@594d1211.eSource := MyFile_OptionBinding_option.obj10@594d1211
.obj8@594d1211.eTarget := 
.obj8@594d1211.name := help
.obj8@594d1211.origin := 5:2

# .obj13@594d1211
.obj13@594d1211 := MyOptionBinding
.obj13@594d1211.__eContents := \
	value/.obj12@594d1211
.obj13@594d1211.__eContainer := /bindings.obj14@594d1211
.obj13@594d1211.option := .obj11@594d1211./

# .obj12@594d1211
.obj12@594d1211 := MyStringLiteral
.obj12@594d1211.__eContents := 
.obj12@594d1211.__eContainer := /value.obj13@594d1211
.obj12@594d1211.value := $(\0)$(\n)		NAME$(\n)			fb_draw_image$(\n)		SYNOPSIS$(\n)			fb_draw_image [FILE]$(\n)		DESCRIPTION$(\n)			if [FILE] format is supporting then draw it to the framebuffer$(\n)		AUTHORS$(\n)			Filipp Chubukov$(\n)	

# .obj11@594d1211
.obj11@594d1211 := ELink
.obj11@594d1211.eSource := MyFile_OptionBinding_option.obj13@594d1211
.obj11@594d1211.eTarget := 
.obj11@594d1211.name := man
.obj11@594d1211.origin := 6:2

# .obj4@594d1211
.obj4@594d1211 := ELink
.obj4@594d1211.eSource := MyFile_Annotation_type.obj14@594d1211
.obj4@594d1211.eTarget := 
.obj4@594d1211.name := Cmd
.obj4@594d1211.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/testing/fb_draw_image/Mybuild.mk := .obj1@594d1211
