# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@43e9763b

# .obj1@43e9763b
.obj1@43e9763b := MyFileResource
.obj1@43e9763b.issues := 
.obj1@43e9763b.contentsRoot := .obj30@43e9763b
.obj1@43e9763b.resourceSet := 
.obj1@43e9763b.fileName := src/cmds/sys/Date.my
.obj1@43e9763b.exports := \
	embox.cmd.sys \
	embox.cmd.sys.date
.obj1@43e9763b.exports.embox.cmd.sys := \
	.obj30@43e9763b
.obj1@43e9763b.exports.embox.cmd.sys.date := \
	.obj29@43e9763b

# .obj30@43e9763b
.obj30@43e9763b := MyFileContentRoot
.obj30@43e9763b.__eContents := \
	types/.obj29@43e9763b
.obj30@43e9763b.__eContainer := .obj1@43e9763b
.obj30@43e9763b.imports := 
.obj30@43e9763b.name := embox.cmd.sys
.obj30@43e9763b.origin := 

# .obj29@43e9763b
.obj29@43e9763b := MyModuleType
.obj29@43e9763b.__eContents := \
	sourcesMembers/.obj16@43e9763b \
	dependsMembers/.obj18@43e9763b \
	dependsMembers/.obj20@43e9763b \
	dependsMembers/.obj22@43e9763b \
	dependsMembers/.obj24@43e9763b \
	dependsMembers/.obj26@43e9763b \
	dependsMembers/.obj28@43e9763b \
	annotations/.obj3@43e9763b \
	annotations/.obj14@43e9763b
.obj29@43e9763b.__eContainer := fileContentRoot/types.obj30@43e9763b
.obj29@43e9763b.dependent := 
.obj29@43e9763b.subTypes := 
.obj29@43e9763b.modifiers := 
.obj29@43e9763b.name := date
.obj29@43e9763b.origin := 16:8
.obj29@43e9763b.superType := 
.obj29@43e9763b.customStorage := 

# .obj16@43e9763b
.obj16@43e9763b := MySourceMember
.obj16@43e9763b.__eContents := \
	files/.obj15@43e9763b
.obj16@43e9763b.__eContainer := /sourcesMembers.obj29@43e9763b
.obj16@43e9763b.module := 

# .obj15@43e9763b
.obj15@43e9763b := MyFileName
.obj15@43e9763b.__eContents := 
.obj15@43e9763b.__eContainer := /files.obj16@43e9763b
.obj15@43e9763b.fileName := date.c

# .obj18@43e9763b
.obj18@43e9763b := MyDependsMember
.obj18@43e9763b.__eContents := 
.obj18@43e9763b.__eContainer := /dependsMembers.obj29@43e9763b
.obj18@43e9763b.modules := \
	.obj17@43e9763b./
.obj18@43e9763b.module := 

# .obj17@43e9763b
.obj17@43e9763b := ELink
.obj17@43e9763b.eSource := MyFile_DependsMember_modules.obj18@43e9763b
.obj17@43e9763b.eTarget := 
.obj17@43e9763b.name := embox.compat.libc.time
.obj17@43e9763b.origin := 19:10

# .obj20@43e9763b
.obj20@43e9763b := MyDependsMember
.obj20@43e9763b.__eContents := 
.obj20@43e9763b.__eContainer := /dependsMembers.obj29@43e9763b
.obj20@43e9763b.modules := \
	.obj19@43e9763b./
.obj20@43e9763b.module := 

# .obj19@43e9763b
.obj19@43e9763b := ELink
.obj19@43e9763b.eSource := MyFile_DependsMember_modules.obj20@43e9763b
.obj19@43e9763b.eTarget := 
.obj19@43e9763b.name := embox.compat.libc.stdio.scanf
.obj19@43e9763b.origin := 20:10

# .obj22@43e9763b
.obj22@43e9763b := MyDependsMember
.obj22@43e9763b.__eContents := 
.obj22@43e9763b.__eContainer := /dependsMembers.obj29@43e9763b
.obj22@43e9763b.modules := \
	.obj21@43e9763b./
.obj22@43e9763b.module := 

# .obj21@43e9763b
.obj21@43e9763b := ELink
.obj21@43e9763b.eSource := MyFile_DependsMember_modules.obj22@43e9763b
.obj21@43e9763b.eTarget := 
.obj21@43e9763b.name := embox.compat.posix.util.getopt
.obj21@43e9763b.origin := 22:10

# .obj24@43e9763b
.obj24@43e9763b := MyDependsMember
.obj24@43e9763b.__eContents := 
.obj24@43e9763b.__eContainer := /dependsMembers.obj29@43e9763b
.obj24@43e9763b.modules := \
	.obj23@43e9763b./
.obj24@43e9763b.module := 

# .obj23@43e9763b
.obj23@43e9763b := ELink
.obj23@43e9763b.eSource := MyFile_DependsMember_modules.obj24@43e9763b
.obj23@43e9763b.eTarget := 
.obj23@43e9763b.name := embox.compat.posix.util.gettimeofday
.obj23@43e9763b.origin := 24:10

# .obj26@43e9763b
.obj26@43e9763b := MyDependsMember
.obj26@43e9763b.__eContents := 
.obj26@43e9763b.__eContainer := /dependsMembers.obj29@43e9763b
.obj26@43e9763b.modules := \
	.obj25@43e9763b./
.obj26@43e9763b.module := 

# .obj25@43e9763b
.obj25@43e9763b := ELink
.obj25@43e9763b.eSource := MyFile_DependsMember_modules.obj26@43e9763b
.obj25@43e9763b.eTarget := 
.obj25@43e9763b.name := embox.kernel.time.clock_source
.obj25@43e9763b.origin := 25:10

# .obj28@43e9763b
.obj28@43e9763b := MyDependsMember
.obj28@43e9763b.__eContents := 
.obj28@43e9763b.__eContainer := /dependsMembers.obj29@43e9763b
.obj28@43e9763b.modules := \
	.obj27@43e9763b./
.obj28@43e9763b.module := 

# .obj27@43e9763b
.obj27@43e9763b := ELink
.obj27@43e9763b.eSource := MyFile_DependsMember_modules.obj28@43e9763b
.obj27@43e9763b.eTarget := 
.obj27@43e9763b.name := embox.kernel.time.timekeeper
.obj27@43e9763b.origin := 26:10

# .obj3@43e9763b
.obj3@43e9763b := MyAnnotation
.obj3@43e9763b.__eContents := 
.obj3@43e9763b.__eContainer := target/annotations.obj29@43e9763b
.obj3@43e9763b.type := .obj2@43e9763b./

# .obj2@43e9763b
.obj2@43e9763b := ELink
.obj2@43e9763b.eSource := MyFile_Annotation_type.obj3@43e9763b
.obj2@43e9763b.eTarget := 
.obj2@43e9763b.name := AutoCmd
.obj2@43e9763b.origin := 3:2

# .obj14@43e9763b
.obj14@43e9763b := MyAnnotation
.obj14@43e9763b.__eContents := \
	bindings/.obj7@43e9763b \
	bindings/.obj10@43e9763b \
	bindings/.obj13@43e9763b
.obj14@43e9763b.__eContainer := target/annotations.obj29@43e9763b
.obj14@43e9763b.type := .obj4@43e9763b./

# .obj7@43e9763b
.obj7@43e9763b := MyOptionBinding
.obj7@43e9763b.__eContents := \
	value/.obj6@43e9763b
.obj7@43e9763b.__eContainer := /bindings.obj14@43e9763b
.obj7@43e9763b.option := .obj5@43e9763b./

# .obj6@43e9763b
.obj6@43e9763b := MyStringLiteral
.obj6@43e9763b.__eContents := 
.obj6@43e9763b.__eContainer := /value.obj7@43e9763b
.obj6@43e9763b.value := date

# .obj5@43e9763b
.obj5@43e9763b := ELink
.obj5@43e9763b.eSource := MyFile_OptionBinding_option.obj7@43e9763b
.obj5@43e9763b.eTarget := 
.obj5@43e9763b.name := name
.obj5@43e9763b.origin := 4:6

# .obj10@43e9763b
.obj10@43e9763b := MyOptionBinding
.obj10@43e9763b.__eContents := \
	value/.obj9@43e9763b
.obj10@43e9763b.__eContainer := /bindings.obj14@43e9763b
.obj10@43e9763b.option := .obj8@43e9763b./

# .obj9@43e9763b
.obj9@43e9763b := MyStringLiteral
.obj9@43e9763b.__eContents := 
.obj9@43e9763b.__eContainer := /value.obj10@43e9763b
.obj9@43e9763b.value := Print or set the system date and times

# .obj8@43e9763b
.obj8@43e9763b := ELink
.obj8@43e9763b.eSource := MyFile_OptionBinding_option.obj10@43e9763b
.obj8@43e9763b.eTarget := 
.obj8@43e9763b.name := help
.obj8@43e9763b.origin := 5:2

# .obj13@43e9763b
.obj13@43e9763b := MyOptionBinding
.obj13@43e9763b.__eContents := \
	value/.obj12@43e9763b
.obj13@43e9763b.__eContainer := /bindings.obj14@43e9763b
.obj13@43e9763b.option := .obj11@43e9763b./

# .obj12@43e9763b
.obj12@43e9763b := MyStringLiteral
.obj12@43e9763b.__eContents := 
.obj12@43e9763b.__eContainer := /value.obj13@43e9763b
.obj12@43e9763b.value := $(\0)$(\n)		NAME$(\n)			date - Print or set the system date and time$(\n)		SYNOPSIS$(\n)			date -s CCYYMMDDhhmm.ss$(\n)		DESCRIPTION$(\n)			Display the current time or set the system date.$(\n)		AUTHORS$(\n)			Alexander Kalmuk$(\n)	

# .obj11@43e9763b
.obj11@43e9763b := ELink
.obj11@43e9763b.eSource := MyFile_OptionBinding_option.obj13@43e9763b
.obj11@43e9763b.eTarget := 
.obj11@43e9763b.name := man
.obj11@43e9763b.origin := 6:2

# .obj4@43e9763b
.obj4@43e9763b := ELink
.obj4@43e9763b.eSource := MyFile_Annotation_type.obj14@43e9763b
.obj4@43e9763b.eTarget := 
.obj4@43e9763b.name := Cmd
.obj4@43e9763b.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/sys/Date.my.mk := .obj1@43e9763b
