# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@6193db79

# .obj1@6193db79
.obj1@6193db79 := MyFileResource
.obj1@6193db79.issues := 
.obj1@6193db79.contentsRoot := .obj18@6193db79
.obj1@6193db79.resourceSet := 
.obj1@6193db79.fileName := src/cmds/sys/Time.my
.obj1@6193db79.exports := \
	embox.cmd.sys \
	embox.cmd.sys.time
.obj1@6193db79.exports.embox.cmd.sys := \
	.obj18@6193db79
.obj1@6193db79.exports.embox.cmd.sys.time := \
	.obj17@6193db79

# .obj18@6193db79
.obj18@6193db79 := MyFileContentRoot
.obj18@6193db79.__eContents := \
	types/.obj17@6193db79
.obj18@6193db79.__eContainer := .obj1@6193db79
.obj18@6193db79.imports := 
.obj18@6193db79.name := embox.cmd.sys
.obj18@6193db79.origin := 

# .obj17@6193db79
.obj17@6193db79 := MyModuleType
.obj17@6193db79.__eContents := \
	sourcesMembers/.obj16@6193db79 \
	annotations/.obj3@6193db79 \
	annotations/.obj14@6193db79
.obj17@6193db79.__eContainer := fileContentRoot/types.obj18@6193db79
.obj17@6193db79.dependent := 
.obj17@6193db79.subTypes := 
.obj17@6193db79.modifiers := 
.obj17@6193db79.name := time
.obj17@6193db79.origin := 17:8
.obj17@6193db79.superType := 
.obj17@6193db79.customStorage := 

# .obj16@6193db79
.obj16@6193db79 := MySourceMember
.obj16@6193db79.__eContents := \
	files/.obj15@6193db79
.obj16@6193db79.__eContainer := /sourcesMembers.obj17@6193db79
.obj16@6193db79.module := 

# .obj15@6193db79
.obj15@6193db79 := MyFileName
.obj15@6193db79.__eContents := 
.obj15@6193db79.__eContainer := /files.obj16@6193db79
.obj15@6193db79.fileName := time.c

# .obj3@6193db79
.obj3@6193db79 := MyAnnotation
.obj3@6193db79.__eContents := 
.obj3@6193db79.__eContainer := target/annotations.obj17@6193db79
.obj3@6193db79.type := .obj2@6193db79./

# .obj2@6193db79
.obj2@6193db79 := ELink
.obj2@6193db79.eSource := MyFile_Annotation_type.obj3@6193db79
.obj2@6193db79.eTarget := 
.obj2@6193db79.name := AutoCmd
.obj2@6193db79.origin := 3:2

# .obj14@6193db79
.obj14@6193db79 := MyAnnotation
.obj14@6193db79.__eContents := \
	bindings/.obj7@6193db79 \
	bindings/.obj10@6193db79 \
	bindings/.obj13@6193db79
.obj14@6193db79.__eContainer := target/annotations.obj17@6193db79
.obj14@6193db79.type := .obj4@6193db79./

# .obj7@6193db79
.obj7@6193db79 := MyOptionBinding
.obj7@6193db79.__eContents := \
	value/.obj6@6193db79
.obj7@6193db79.__eContainer := /bindings.obj14@6193db79
.obj7@6193db79.option := .obj5@6193db79./

# .obj6@6193db79
.obj6@6193db79 := MyStringLiteral
.obj6@6193db79.__eContents := 
.obj6@6193db79.__eContainer := /value.obj7@6193db79
.obj6@6193db79.value := time

# .obj5@6193db79
.obj5@6193db79 := ELink
.obj5@6193db79.eSource := MyFile_OptionBinding_option.obj7@6193db79
.obj5@6193db79.eTarget := 
.obj5@6193db79.name := name
.obj5@6193db79.origin := 4:6

# .obj10@6193db79
.obj10@6193db79 := MyOptionBinding
.obj10@6193db79.__eContents := \
	value/.obj9@6193db79
.obj10@6193db79.__eContainer := /bindings.obj14@6193db79
.obj10@6193db79.option := .obj8@6193db79./

# .obj9@6193db79
.obj9@6193db79 := MyStringLiteral
.obj9@6193db79.__eContents := 
.obj9@6193db79.__eContainer := /value.obj10@6193db79
.obj9@6193db79.value := Shows time of a command execution

# .obj8@6193db79
.obj8@6193db79 := ELink
.obj8@6193db79.eSource := MyFile_OptionBinding_option.obj10@6193db79
.obj8@6193db79.eTarget := 
.obj8@6193db79.name := help
.obj8@6193db79.origin := 5:2

# .obj13@6193db79
.obj13@6193db79 := MyOptionBinding
.obj13@6193db79.__eContents := \
	value/.obj12@6193db79
.obj13@6193db79.__eContainer := /bindings.obj14@6193db79
.obj13@6193db79.option := .obj11@6193db79./

# .obj12@6193db79
.obj12@6193db79 := MyStringLiteral
.obj12@6193db79.__eContents := 
.obj12@6193db79.__eContainer := /value.obj13@6193db79
.obj12@6193db79.value := $(\0)$(\n)		NAME$(\n)			time - time a simple command or give resource usage$(\n)		SYNOPSIS$(\n)			time <command> [arguments]$(\n)		DESCRIPTION$(\n)			The time command runs the specified program command with$(\n)			the given arguments.$(\n)		AUTHOR$(\n)			Anton Bondarev$(\n)	

# .obj11@6193db79
.obj11@6193db79 := ELink
.obj11@6193db79.eSource := MyFile_OptionBinding_option.obj13@6193db79
.obj11@6193db79.eTarget := 
.obj11@6193db79.name := man
.obj11@6193db79.origin := 6:2

# .obj4@6193db79
.obj4@6193db79 := ELink
.obj4@6193db79.eSource := MyFile_Annotation_type.obj14@6193db79
.obj4@6193db79.eTarget := 
.obj4@6193db79.name := Cmd
.obj4@6193db79.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/sys/Time.my.mk := .obj1@6193db79
