# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@2647c750

# .obj1@2647c750
.obj1@2647c750 := MyFileResource
.obj1@2647c750.issues := 
.obj1@2647c750.contentsRoot := .obj20@2647c750
.obj1@2647c750.resourceSet := 
.obj1@2647c750.fileName := src/cmds/fs/Chmod.my
.obj1@2647c750.exports := \
	embox.cmd \
	embox.cmd.chmod
.obj1@2647c750.exports.embox.cmd := \
	.obj20@2647c750
.obj1@2647c750.exports.embox.cmd.chmod := \
	.obj19@2647c750

# .obj20@2647c750
.obj20@2647c750 := MyFileContentRoot
.obj20@2647c750.__eContents := \
	types/.obj19@2647c750
.obj20@2647c750.__eContainer := .obj1@2647c750
.obj20@2647c750.imports := 
.obj20@2647c750.name := embox.cmd
.obj20@2647c750.origin := 

# .obj19@2647c750
.obj19@2647c750 := MyModuleType
.obj19@2647c750.__eContents := \
	sourcesMembers/.obj16@2647c750 \
	dependsMembers/.obj18@2647c750 \
	annotations/.obj3@2647c750 \
	annotations/.obj14@2647c750
.obj19@2647c750.__eContainer := fileContentRoot/types.obj20@2647c750
.obj19@2647c750.dependent := 
.obj19@2647c750.subTypes := 
.obj19@2647c750.modifiers := 
.obj19@2647c750.name := chmod
.obj19@2647c750.origin := 20:8
.obj19@2647c750.superType := 
.obj19@2647c750.customStorage := 

# .obj16@2647c750
.obj16@2647c750 := MySourceMember
.obj16@2647c750.__eContents := \
	files/.obj15@2647c750
.obj16@2647c750.__eContainer := /sourcesMembers.obj19@2647c750
.obj16@2647c750.module := 

# .obj15@2647c750
.obj15@2647c750 := MyFileName
.obj15@2647c750.__eContents := 
.obj15@2647c750.__eContainer := /files.obj16@2647c750
.obj15@2647c750.fileName := chmod.c

# .obj18@2647c750
.obj18@2647c750 := MyDependsMember
.obj18@2647c750.__eContents := 
.obj18@2647c750.__eContainer := /dependsMembers.obj19@2647c750
.obj18@2647c750.modules := \
	.obj17@2647c750./
.obj18@2647c750.module := 

# .obj17@2647c750
.obj17@2647c750 := ELink
.obj17@2647c750.eSource := MyFile_DependsMember_modules.obj18@2647c750
.obj17@2647c750.eTarget := 
.obj17@2647c750.name := embox.compat.posix.fs.chmod
.obj17@2647c750.origin := 23:10

# .obj3@2647c750
.obj3@2647c750 := MyAnnotation
.obj3@2647c750.__eContents := 
.obj3@2647c750.__eContainer := target/annotations.obj19@2647c750
.obj3@2647c750.type := .obj2@2647c750./

# .obj2@2647c750
.obj2@2647c750 := ELink
.obj2@2647c750.eSource := MyFile_Annotation_type.obj3@2647c750
.obj2@2647c750.eTarget := 
.obj2@2647c750.name := AutoCmd
.obj2@2647c750.origin := 3:2

# .obj14@2647c750
.obj14@2647c750 := MyAnnotation
.obj14@2647c750.__eContents := \
	bindings/.obj7@2647c750 \
	bindings/.obj10@2647c750 \
	bindings/.obj13@2647c750
.obj14@2647c750.__eContainer := target/annotations.obj19@2647c750
.obj14@2647c750.type := .obj4@2647c750./

# .obj7@2647c750
.obj7@2647c750 := MyOptionBinding
.obj7@2647c750.__eContents := \
	value/.obj6@2647c750
.obj7@2647c750.__eContainer := /bindings.obj14@2647c750
.obj7@2647c750.option := .obj5@2647c750./

# .obj6@2647c750
.obj6@2647c750 := MyStringLiteral
.obj6@2647c750.__eContents := 
.obj6@2647c750.__eContainer := /value.obj7@2647c750
.obj6@2647c750.value := chmod

# .obj5@2647c750
.obj5@2647c750 := ELink
.obj5@2647c750.eSource := MyFile_OptionBinding_option.obj7@2647c750
.obj5@2647c750.eTarget := 
.obj5@2647c750.name := name
.obj5@2647c750.origin := 4:6

# .obj10@2647c750
.obj10@2647c750 := MyOptionBinding
.obj10@2647c750.__eContents := \
	value/.obj9@2647c750
.obj10@2647c750.__eContainer := /bindings.obj14@2647c750
.obj10@2647c750.option := .obj8@2647c750./

# .obj9@2647c750
.obj9@2647c750 := MyStringLiteral
.obj9@2647c750.__eContents := 
.obj9@2647c750.__eContainer := /value.obj10@2647c750
.obj9@2647c750.value := Change the mode of each FILE to MODE

# .obj8@2647c750
.obj8@2647c750 := ELink
.obj8@2647c750.eSource := MyFile_OptionBinding_option.obj10@2647c750
.obj8@2647c750.eTarget := 
.obj8@2647c750.name := help
.obj8@2647c750.origin := 5:2

# .obj13@2647c750
.obj13@2647c750 := MyOptionBinding
.obj13@2647c750.__eContents := \
	value/.obj12@2647c750
.obj13@2647c750.__eContainer := /bindings.obj14@2647c750
.obj13@2647c750.option := .obj11@2647c750./

# .obj12@2647c750
.obj12@2647c750 := MyStringLiteral
.obj12@2647c750.__eContents := 
.obj12@2647c750.__eContainer := /value.obj13@2647c750
.obj12@2647c750.value := $(\0)$(\n)NAME$(\n)	chmod$(\n)SYNOPSIS:$(\n)	chmod [OPTION]... MODE[,MODE]... FILE...$(\n)	Each MODE is of the form '[ugoa]*([-+=]([rwxX]*))'$(\n)DESCRIPTION$(\n)	Change the mode of each FILE to MODE.$(\n)OPTIONS$(\n)	-R	change files and directories recursively$(\n)	-h	display this help and exit$(\n)AUTHORS$(\n)	Vita Loginova$(\n)

# .obj11@2647c750
.obj11@2647c750 := ELink
.obj11@2647c750.eSource := MyFile_OptionBinding_option.obj13@2647c750
.obj11@2647c750.eTarget := 
.obj11@2647c750.name := man
.obj11@2647c750.origin := 6:2

# .obj4@2647c750
.obj4@2647c750 := ELink
.obj4@2647c750.eSource := MyFile_Annotation_type.obj14@2647c750
.obj4@2647c750.eTarget := 
.obj4@2647c750.name := Cmd
.obj4@2647c750.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/fs/Chmod.my.mk := .obj1@2647c750
