# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@0bb5ab7b

# .obj1@0bb5ab7b
.obj1@0bb5ab7b := MyFileResource
.obj1@0bb5ab7b.issues := 
.obj1@0bb5ab7b.contentsRoot := .obj30@0bb5ab7b
.obj1@0bb5ab7b.resourceSet := 
.obj1@0bb5ab7b.fileName := src/cmds/fs/Ls.my
.obj1@0bb5ab7b.exports := \
	embox.cmd.fs \
	embox.cmd.fs.ls
.obj1@0bb5ab7b.exports.embox.cmd.fs := \
	.obj30@0bb5ab7b
.obj1@0bb5ab7b.exports.embox.cmd.fs.ls := \
	.obj29@0bb5ab7b

# .obj30@0bb5ab7b
.obj30@0bb5ab7b := MyFileContentRoot
.obj30@0bb5ab7b.__eContents := \
	types/.obj29@0bb5ab7b
.obj30@0bb5ab7b.__eContainer := .obj1@0bb5ab7b
.obj30@0bb5ab7b.imports := 
.obj30@0bb5ab7b.name := embox.cmd.fs
.obj30@0bb5ab7b.origin := 

# .obj29@0bb5ab7b
.obj29@0bb5ab7b := MyModuleType
.obj29@0bb5ab7b.__eContents := \
	sourcesMembers/.obj16@0bb5ab7b \
	dependsMembers/.obj18@0bb5ab7b \
	dependsMembers/.obj20@0bb5ab7b \
	dependsMembers/.obj22@0bb5ab7b \
	dependsMembers/.obj24@0bb5ab7b \
	dependsMembers/.obj26@0bb5ab7b \
	dependsMembers/.obj28@0bb5ab7b \
	annotations/.obj3@0bb5ab7b \
	annotations/.obj14@0bb5ab7b
.obj29@0bb5ab7b.__eContainer := fileContentRoot/types.obj30@0bb5ab7b
.obj29@0bb5ab7b.dependent := 
.obj29@0bb5ab7b.subTypes := 
.obj29@0bb5ab7b.modifiers := 
.obj29@0bb5ab7b.name := ls
.obj29@0bb5ab7b.origin := 23:8
.obj29@0bb5ab7b.superType := 
.obj29@0bb5ab7b.customStorage := 

# .obj16@0bb5ab7b
.obj16@0bb5ab7b := MySourceMember
.obj16@0bb5ab7b.__eContents := \
	files/.obj15@0bb5ab7b
.obj16@0bb5ab7b.__eContainer := /sourcesMembers.obj29@0bb5ab7b
.obj16@0bb5ab7b.module := 

# .obj15@0bb5ab7b
.obj15@0bb5ab7b := MyFileName
.obj15@0bb5ab7b.__eContents := 
.obj15@0bb5ab7b.__eContainer := /files.obj16@0bb5ab7b
.obj15@0bb5ab7b.fileName := ls.c

# .obj18@0bb5ab7b
.obj18@0bb5ab7b := MyDependsMember
.obj18@0bb5ab7b.__eContents := 
.obj18@0bb5ab7b.__eContainer := /dependsMembers.obj29@0bb5ab7b
.obj18@0bb5ab7b.modules := \
	.obj17@0bb5ab7b./
.obj18@0bb5ab7b.module := 

# .obj17@0bb5ab7b
.obj17@0bb5ab7b := ELink
.obj17@0bb5ab7b.eSource := MyFile_DependsMember_modules.obj18@0bb5ab7b
.obj17@0bb5ab7b.eTarget := 
.obj17@0bb5ab7b.name := embox.compat.libc.all
.obj17@0bb5ab7b.origin := 26:10

# .obj20@0bb5ab7b
.obj20@0bb5ab7b := MyDependsMember
.obj20@0bb5ab7b.__eContents := 
.obj20@0bb5ab7b.__eContainer := /dependsMembers.obj29@0bb5ab7b
.obj20@0bb5ab7b.modules := \
	.obj19@0bb5ab7b./
.obj20@0bb5ab7b.module := 

# .obj19@0bb5ab7b
.obj19@0bb5ab7b := ELink
.obj19@0bb5ab7b.eSource := MyFile_DependsMember_modules.obj20@0bb5ab7b
.obj19@0bb5ab7b.eTarget := 
.obj19@0bb5ab7b.name := embox.compat.posix.util.getopt
.obj19@0bb5ab7b.origin := 27:10

# .obj22@0bb5ab7b
.obj22@0bb5ab7b := MyDependsMember
.obj22@0bb5ab7b.__eContents := 
.obj22@0bb5ab7b.__eContainer := /dependsMembers.obj29@0bb5ab7b
.obj22@0bb5ab7b.modules := \
	.obj21@0bb5ab7b./
.obj22@0bb5ab7b.module := 

# .obj21@0bb5ab7b
.obj21@0bb5ab7b := ELink
.obj21@0bb5ab7b.eSource := MyFile_DependsMember_modules.obj22@0bb5ab7b
.obj21@0bb5ab7b.eTarget := 
.obj21@0bb5ab7b.name := embox.compat.posix.passwd
.obj21@0bb5ab7b.origin := 28:10

# .obj24@0bb5ab7b
.obj24@0bb5ab7b := MyDependsMember
.obj24@0bb5ab7b.__eContents := 
.obj24@0bb5ab7b.__eContainer := /dependsMembers.obj29@0bb5ab7b
.obj24@0bb5ab7b.modules := \
	.obj23@0bb5ab7b./
.obj24@0bb5ab7b.module := 

# .obj23@0bb5ab7b
.obj23@0bb5ab7b := ELink
.obj23@0bb5ab7b.eSource := MyFile_DependsMember_modules.obj24@0bb5ab7b
.obj23@0bb5ab7b.eTarget := 
.obj23@0bb5ab7b.name := embox.compat.posix.fs.dirent
.obj23@0bb5ab7b.origin := 29:10

# .obj26@0bb5ab7b
.obj26@0bb5ab7b := MyDependsMember
.obj26@0bb5ab7b.__eContents := 
.obj26@0bb5ab7b.__eContainer := /dependsMembers.obj29@0bb5ab7b
.obj26@0bb5ab7b.modules := \
	.obj25@0bb5ab7b./
.obj26@0bb5ab7b.module := 

# .obj25@0bb5ab7b
.obj25@0bb5ab7b := ELink
.obj25@0bb5ab7b.eSource := MyFile_DependsMember_modules.obj26@0bb5ab7b
.obj25@0bb5ab7b.eTarget := 
.obj25@0bb5ab7b.name := embox.util.LibUtil
.obj25@0bb5ab7b.origin := 30:10

# .obj28@0bb5ab7b
.obj28@0bb5ab7b := MyDependsMember
.obj28@0bb5ab7b.__eContents := 
.obj28@0bb5ab7b.__eContainer := /dependsMembers.obj29@0bb5ab7b
.obj28@0bb5ab7b.modules := \
	.obj27@0bb5ab7b./
.obj28@0bb5ab7b.module := 

# .obj27@0bb5ab7b
.obj27@0bb5ab7b := ELink
.obj27@0bb5ab7b.eSource := MyFile_DependsMember_modules.obj28@0bb5ab7b
.obj27@0bb5ab7b.eTarget := 
.obj27@0bb5ab7b.name := embox.framework.LibFramework
.obj27@0bb5ab7b.origin := 31:10

# .obj3@0bb5ab7b
.obj3@0bb5ab7b := MyAnnotation
.obj3@0bb5ab7b.__eContents := 
.obj3@0bb5ab7b.__eContainer := target/annotations.obj29@0bb5ab7b
.obj3@0bb5ab7b.type := .obj2@0bb5ab7b./

# .obj2@0bb5ab7b
.obj2@0bb5ab7b := ELink
.obj2@0bb5ab7b.eSource := MyFile_Annotation_type.obj3@0bb5ab7b
.obj2@0bb5ab7b.eTarget := 
.obj2@0bb5ab7b.name := AutoCmd
.obj2@0bb5ab7b.origin := 3:2

# .obj14@0bb5ab7b
.obj14@0bb5ab7b := MyAnnotation
.obj14@0bb5ab7b.__eContents := \
	bindings/.obj7@0bb5ab7b \
	bindings/.obj10@0bb5ab7b \
	bindings/.obj13@0bb5ab7b
.obj14@0bb5ab7b.__eContainer := target/annotations.obj29@0bb5ab7b
.obj14@0bb5ab7b.type := .obj4@0bb5ab7b./

# .obj7@0bb5ab7b
.obj7@0bb5ab7b := MyOptionBinding
.obj7@0bb5ab7b.__eContents := \
	value/.obj6@0bb5ab7b
.obj7@0bb5ab7b.__eContainer := /bindings.obj14@0bb5ab7b
.obj7@0bb5ab7b.option := .obj5@0bb5ab7b./

# .obj6@0bb5ab7b
.obj6@0bb5ab7b := MyStringLiteral
.obj6@0bb5ab7b.__eContents := 
.obj6@0bb5ab7b.__eContainer := /value.obj7@0bb5ab7b
.obj6@0bb5ab7b.value := ls

# .obj5@0bb5ab7b
.obj5@0bb5ab7b := ELink
.obj5@0bb5ab7b.eSource := MyFile_OptionBinding_option.obj7@0bb5ab7b
.obj5@0bb5ab7b.eTarget := 
.obj5@0bb5ab7b.name := name
.obj5@0bb5ab7b.origin := 4:6

# .obj10@0bb5ab7b
.obj10@0bb5ab7b := MyOptionBinding
.obj10@0bb5ab7b.__eContents := \
	value/.obj9@0bb5ab7b
.obj10@0bb5ab7b.__eContainer := /bindings.obj14@0bb5ab7b
.obj10@0bb5ab7b.option := .obj8@0bb5ab7b./

# .obj9@0bb5ab7b
.obj9@0bb5ab7b := MyStringLiteral
.obj9@0bb5ab7b.__eContents := 
.obj9@0bb5ab7b.__eContainer := /value.obj10@0bb5ab7b
.obj9@0bb5ab7b.value := List directory contents

# .obj8@0bb5ab7b
.obj8@0bb5ab7b := ELink
.obj8@0bb5ab7b.eSource := MyFile_OptionBinding_option.obj10@0bb5ab7b
.obj8@0bb5ab7b.eTarget := 
.obj8@0bb5ab7b.name := help
.obj8@0bb5ab7b.origin := 5:2

# .obj13@0bb5ab7b
.obj13@0bb5ab7b := MyOptionBinding
.obj13@0bb5ab7b.__eContents := \
	value/.obj12@0bb5ab7b
.obj13@0bb5ab7b.__eContainer := /bindings.obj14@0bb5ab7b
.obj13@0bb5ab7b.option := .obj11@0bb5ab7b./

# .obj12@0bb5ab7b
.obj12@0bb5ab7b := MyStringLiteral
.obj12@0bb5ab7b.__eContents := 
.obj12@0bb5ab7b.__eContainer := /value.obj13@0bb5ab7b
.obj12@0bb5ab7b.value := $(\0)$(\n)		NAME$(\n)			ls - list directory contents$(\n)		SYNOPSIS$(\n)			ls [OPTION]... [FILE]...$(\n)		DESCRIPTION$(\n)			List information about the FILEs$(\n)			(the current directory by default).$(\n)		OPTIONS$(\n)			FILE -  path of directory.$(\n)				defaults '/' (root dir).$(\n)				Path format is /dir/filename.$(\n)			-l - use a long listing format$(\n)			-R - list subdirectories recursively$(\n)		AUTHORS$(\n)			Anton Bondarev$(\n)	

# .obj11@0bb5ab7b
.obj11@0bb5ab7b := ELink
.obj11@0bb5ab7b.eSource := MyFile_OptionBinding_option.obj13@0bb5ab7b
.obj11@0bb5ab7b.eTarget := 
.obj11@0bb5ab7b.name := man
.obj11@0bb5ab7b.origin := 6:2

# .obj4@0bb5ab7b
.obj4@0bb5ab7b := ELink
.obj4@0bb5ab7b.eSource := MyFile_Annotation_type.obj14@0bb5ab7b
.obj4@0bb5ab7b.eTarget := 
.obj4@0bb5ab7b.name := Cmd
.obj4@0bb5ab7b.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/fs/Ls.my.mk := .obj1@0bb5ab7b
