# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@3f07c848

# .obj1@3f07c848
.obj1@3f07c848 := MyFileResource
.obj1@3f07c848.issues := 
.obj1@3f07c848.contentsRoot := .obj14@3f07c848
.obj1@3f07c848.resourceSet := 
.obj1@3f07c848.fileName := src/drivers/clock/dm816x/Mybuild
.obj1@3f07c848.exports := \
	embox.driver.clock \
	embox.driver.clock.dm816x_timer
.obj1@3f07c848.exports.embox.driver.clock := \
	.obj14@3f07c848
.obj1@3f07c848.exports.embox.driver.clock.dm816x_timer := \
	.obj13@3f07c848

# .obj14@3f07c848
.obj14@3f07c848 := MyFileContentRoot
.obj14@3f07c848.__eContents := \
	types/.obj13@3f07c848
.obj14@3f07c848.__eContainer := .obj1@3f07c848
.obj14@3f07c848.imports := 
.obj14@3f07c848.name := embox.driver.clock
.obj14@3f07c848.origin := 

# .obj13@3f07c848
.obj13@3f07c848 := MyModuleType
.obj13@3f07c848.__eContents := \
	sourcesMembers/.obj4@3f07c848 \
	dependsMembers/.obj6@3f07c848 \
	dependsMembers/.obj8@3f07c848 \
	dependsMembers/.obj12@3f07c848
.obj13@3f07c848.__eContainer := fileContentRoot/types.obj14@3f07c848
.obj13@3f07c848.dependent := 
.obj13@3f07c848.subTypes := 
.obj13@3f07c848.modifiers := 
.obj13@3f07c848.name := dm816x_timer
.obj13@3f07c848.origin := 3:8
.obj13@3f07c848.superType := .obj2@3f07c848./
.obj13@3f07c848.customStorage := 

# .obj4@3f07c848
.obj4@3f07c848 := MySourceMember
.obj4@3f07c848.__eContents := \
	files/.obj3@3f07c848
.obj4@3f07c848.__eContainer := /sourcesMembers.obj13@3f07c848
.obj4@3f07c848.module := 

# .obj3@3f07c848
.obj3@3f07c848 := MyFileName
.obj3@3f07c848.__eContents := 
.obj3@3f07c848.__eContainer := /files.obj4@3f07c848
.obj3@3f07c848.fileName := dm816x_timer.c

# .obj6@3f07c848
.obj6@3f07c848 := MyDependsMember
.obj6@3f07c848.__eContents := 
.obj6@3f07c848.__eContainer := /dependsMembers.obj13@3f07c848
.obj6@3f07c848.modules := \
	.obj5@3f07c848./
.obj6@3f07c848.module := 

# .obj5@3f07c848
.obj5@3f07c848 := ELink
.obj5@3f07c848.eSource := MyFile_DependsMember_modules.obj6@3f07c848
.obj5@3f07c848.eTarget := 
.obj5@3f07c848.name := embox.kernel.irq
.obj5@3f07c848.origin := 6:10

# .obj8@3f07c848
.obj8@3f07c848 := MyDependsMember
.obj8@3f07c848.__eContents := 
.obj8@3f07c848.__eContainer := /dependsMembers.obj13@3f07c848
.obj8@3f07c848.modules := \
	.obj7@3f07c848./
.obj8@3f07c848.module := 

# .obj7@3f07c848
.obj7@3f07c848 := ELink
.obj7@3f07c848.eSource := MyFile_DependsMember_modules.obj8@3f07c848
.obj7@3f07c848.eTarget := 
.obj7@3f07c848.name := embox.kernel.time.clock_source
.obj7@3f07c848.origin := 7:10

# .obj12@3f07c848
.obj12@3f07c848 := MyDependsMember
.obj12@3f07c848.__eContents := \
	annotations/.obj10@3f07c848
.obj12@3f07c848.__eContainer := /dependsMembers.obj13@3f07c848
.obj12@3f07c848.modules := \
	.obj11@3f07c848./
.obj12@3f07c848.module := 

# .obj10@3f07c848
.obj10@3f07c848 := MyAnnotation
.obj10@3f07c848.__eContents := 
.obj10@3f07c848.__eContainer := target/annotations.obj12@3f07c848
.obj10@3f07c848.type := .obj9@3f07c848./

# .obj9@3f07c848
.obj9@3f07c848 := ELink
.obj9@3f07c848.eSource := MyFile_Annotation_type.obj10@3f07c848
.obj9@3f07c848.eTarget := 
.obj9@3f07c848.name := NoRuntime
.obj9@3f07c848.origin := 8:3

# .obj11@3f07c848
.obj11@3f07c848 := ELink
.obj11@3f07c848.eSource := MyFile_DependsMember_modules.obj12@3f07c848
.obj11@3f07c848.eTarget := 
.obj11@3f07c848.name := embox.kernel.time.timer_handler
.obj11@3f07c848.origin := 8:21

# .obj2@3f07c848
.obj2@3f07c848 := ELink
.obj2@3f07c848.eSource := MyFile_ModuleType_superType.obj13@3f07c848
.obj2@3f07c848.eTarget := 
.obj2@3f07c848.name := embox.arch.clock
.obj2@3f07c848.origin := 3:29


__resource-mk/.cache/mybuild/files/src/drivers/clock/dm816x/Mybuild.mk := .obj1@3f07c848
