# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@511be5d4

# .obj1@511be5d4
.obj1@511be5d4 := MyFileResource
.obj1@511be5d4.issues := 
.obj1@511be5d4.contentsRoot := .obj22@511be5d4
.obj1@511be5d4.resourceSet := 
.obj1@511be5d4.fileName := src/drivers/clock/e2k/Mybuild
.obj1@511be5d4.exports := \
	embox.driver.clock \
	embox.driver.clock.e2k \
	embox.driver.clock.e2k.irq_num \
	embox.driver.clock.e2k.freq
.obj1@511be5d4.exports.embox.driver.clock := \
	.obj22@511be5d4
.obj1@511be5d4.exports.embox.driver.clock.e2k := \
	.obj21@511be5d4
.obj1@511be5d4.exports.embox.driver.clock.e2k.irq_num := \
	.obj3@511be5d4
.obj1@511be5d4.exports.embox.driver.clock.e2k.freq := \
	.obj6@511be5d4

# .obj22@511be5d4
.obj22@511be5d4 := MyFileContentRoot
.obj22@511be5d4.__eContents := \
	types/.obj21@511be5d4
.obj22@511be5d4.__eContainer := .obj1@511be5d4
.obj22@511be5d4.imports := 
.obj22@511be5d4.name := embox.driver.clock
.obj22@511be5d4.origin := 

# .obj21@511be5d4
.obj21@511be5d4 := MyModuleType
.obj21@511be5d4.__eContents := \
	sourcesMembers/.obj10@511be5d4 \
	optionsMembers/.obj5@511be5d4 \
	optionsMembers/.obj8@511be5d4 \
	dependsMembers/.obj12@511be5d4 \
	dependsMembers/.obj16@511be5d4 \
	dependsMembers/.obj20@511be5d4
.obj21@511be5d4.__eContainer := fileContentRoot/types.obj22@511be5d4
.obj21@511be5d4.dependent := 
.obj21@511be5d4.subTypes := 
.obj21@511be5d4.modifiers := 
.obj21@511be5d4.name := e2k
.obj21@511be5d4.origin := 3:8
.obj21@511be5d4.superType := .obj2@511be5d4./
.obj21@511be5d4.customStorage := 

# .obj10@511be5d4
.obj10@511be5d4 := MySourceMember
.obj10@511be5d4.__eContents := \
	files/.obj9@511be5d4
.obj10@511be5d4.__eContainer := /sourcesMembers.obj21@511be5d4
.obj10@511be5d4.module := 

# .obj9@511be5d4
.obj9@511be5d4 := MyFileName
.obj9@511be5d4.__eContents := 
.obj9@511be5d4.__eContainer := /files.obj10@511be5d4
.obj9@511be5d4.fileName := e2k.c

# .obj5@511be5d4
.obj5@511be5d4 := MyOptionMember
.obj5@511be5d4.__eContents := \
	options/.obj3@511be5d4
.obj5@511be5d4.__eContainer := /optionsMembers.obj21@511be5d4
.obj5@511be5d4.module := 

# .obj3@511be5d4
.obj3@511be5d4 := MyNumberOption
.obj3@511be5d4.__eContents := \
	defaultValue/.obj4@511be5d4
.obj3@511be5d4.__eContainer := /options.obj5@511be5d4
.obj3@511be5d4.name := irq_num
.obj3@511be5d4.origin := 

# .obj4@511be5d4
.obj4@511be5d4 := MyNumberLiteral
.obj4@511be5d4.__eContents := 
.obj4@511be5d4.__eContainer := /defaultValue.obj3@511be5d4
.obj4@511be5d4.value := 2

# .obj8@511be5d4
.obj8@511be5d4 := MyOptionMember
.obj8@511be5d4.__eContents := \
	options/.obj6@511be5d4
.obj8@511be5d4.__eContainer := /optionsMembers.obj21@511be5d4
.obj8@511be5d4.module := 

# .obj6@511be5d4
.obj6@511be5d4 := MyNumberOption
.obj6@511be5d4.__eContents := \
	defaultValue/.obj7@511be5d4
.obj6@511be5d4.__eContainer := /options.obj8@511be5d4
.obj6@511be5d4.name := freq
.obj6@511be5d4.origin := 

# .obj7@511be5d4
.obj7@511be5d4 := MyNumberLiteral
.obj7@511be5d4.__eContents := 
.obj7@511be5d4.__eContainer := /defaultValue.obj6@511be5d4
.obj7@511be5d4.value := 10

# .obj12@511be5d4
.obj12@511be5d4 := MyDependsMember
.obj12@511be5d4.__eContents := 
.obj12@511be5d4.__eContainer := /dependsMembers.obj21@511be5d4
.obj12@511be5d4.modules := \
	.obj11@511be5d4./
.obj12@511be5d4.module := 

# .obj11@511be5d4
.obj11@511be5d4 := ELink
.obj11@511be5d4.eSource := MyFile_DependsMember_modules.obj12@511be5d4
.obj11@511be5d4.eTarget := 
.obj11@511be5d4.name := embox.kernel.irq
.obj11@511be5d4.origin := 9:10

# .obj16@511be5d4
.obj16@511be5d4 := MyDependsMember
.obj16@511be5d4.__eContents := \
	annotations/.obj14@511be5d4
.obj16@511be5d4.__eContainer := /dependsMembers.obj21@511be5d4
.obj16@511be5d4.modules := \
	.obj15@511be5d4./
.obj16@511be5d4.module := 

# .obj14@511be5d4
.obj14@511be5d4 := MyAnnotation
.obj14@511be5d4.__eContents := 
.obj14@511be5d4.__eContainer := target/annotations.obj16@511be5d4
.obj14@511be5d4.type := .obj13@511be5d4./

# .obj13@511be5d4
.obj13@511be5d4 := ELink
.obj13@511be5d4.eSource := MyFile_Annotation_type.obj14@511be5d4
.obj13@511be5d4.eTarget := 
.obj13@511be5d4.name := NoRuntime
.obj13@511be5d4.origin := 10:3

# .obj15@511be5d4
.obj15@511be5d4 := ELink
.obj15@511be5d4.eSource := MyFile_DependsMember_modules.obj16@511be5d4
.obj15@511be5d4.eTarget := 
.obj15@511be5d4.name := embox.kernel.time.clock_source
.obj15@511be5d4.origin := 10:21

# .obj20@511be5d4
.obj20@511be5d4 := MyDependsMember
.obj20@511be5d4.__eContents := \
	annotations/.obj18@511be5d4
.obj20@511be5d4.__eContainer := /dependsMembers.obj21@511be5d4
.obj20@511be5d4.modules := \
	.obj19@511be5d4./
.obj20@511be5d4.module := 

# .obj18@511be5d4
.obj18@511be5d4 := MyAnnotation
.obj18@511be5d4.__eContents := 
.obj18@511be5d4.__eContainer := target/annotations.obj20@511be5d4
.obj18@511be5d4.type := .obj17@511be5d4./

# .obj17@511be5d4
.obj17@511be5d4 := ELink
.obj17@511be5d4.eSource := MyFile_Annotation_type.obj18@511be5d4
.obj17@511be5d4.eTarget := 
.obj17@511be5d4.name := NoRuntime
.obj17@511be5d4.origin := 11:3

# .obj19@511be5d4
.obj19@511be5d4 := ELink
.obj19@511be5d4.eSource := MyFile_DependsMember_modules.obj20@511be5d4
.obj19@511be5d4.eTarget := 
.obj19@511be5d4.name := embox.kernel.time.timer_handler
.obj19@511be5d4.origin := 11:21

# .obj2@511be5d4
.obj2@511be5d4 := ELink
.obj2@511be5d4.eSource := MyFile_ModuleType_superType.obj21@511be5d4
.obj2@511be5d4.eTarget := 
.obj2@511be5d4.name := embox.arch.clock
.obj2@511be5d4.origin := 3:20


__resource-mk/.cache/mybuild/files/src/drivers/clock/e2k/Mybuild.mk := .obj1@511be5d4
