# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@7e84826b

# .obj1@7e84826b
.obj1@7e84826b := MyFileResource
.obj1@7e84826b.issues := 
.obj1@7e84826b.contentsRoot := .obj13@7e84826b
.obj1@7e84826b.resourceSet := 
.obj1@7e84826b.fileName := src/arch/arm/Mybuild
.obj1@7e84826b.exports := \
	embox.arch.arm \
	embox.arch.arm.cmsis \
	embox.arch.arm.head \
	embox.arch.arm.head.mmu_boot \
	embox.arch.arm.static_irq_table
.obj1@7e84826b.exports.embox.arch.arm := \
	.obj13@7e84826b
.obj1@7e84826b.exports.embox.arch.arm.cmsis := \
	.obj2@7e84826b
.obj1@7e84826b.exports.embox.arch.arm.head := \
	.obj8@7e84826b
.obj1@7e84826b.exports.embox.arch.arm.head.mmu_boot := \
	.obj3@7e84826b
.obj1@7e84826b.exports.embox.arch.arm.static_irq_table := \
	.obj12@7e84826b

# .obj13@7e84826b
.obj13@7e84826b := MyFileContentRoot
.obj13@7e84826b.__eContents := \
	types/.obj2@7e84826b \
	types/.obj8@7e84826b \
	types/.obj12@7e84826b
.obj13@7e84826b.__eContainer := .obj1@7e84826b
.obj13@7e84826b.imports := 
.obj13@7e84826b.name := embox.arch.arm
.obj13@7e84826b.origin := 

# .obj2@7e84826b
.obj2@7e84826b := MyModuleType
.obj2@7e84826b.__eContents := 
.obj2@7e84826b.__eContainer := fileContentRoot/types.obj13@7e84826b
.obj2@7e84826b.dependent := 
.obj2@7e84826b.subTypes := 
.obj2@7e84826b.modifiers := abstract
.obj2@7e84826b.name := cmsis
.obj2@7e84826b.origin := 5:17
.obj2@7e84826b.superType := 
.obj2@7e84826b.customStorage := 

# .obj8@7e84826b
.obj8@7e84826b := MyModuleType
.obj8@7e84826b.__eContents := \
	sourcesMembers/.obj7@7e84826b \
	optionsMembers/.obj5@7e84826b
.obj8@7e84826b.__eContainer := fileContentRoot/types.obj13@7e84826b
.obj8@7e84826b.dependent := 
.obj8@7e84826b.subTypes := 
.obj8@7e84826b.modifiers := 
.obj8@7e84826b.name := head
.obj8@7e84826b.origin := 8:8
.obj8@7e84826b.superType := 
.obj8@7e84826b.customStorage := 

# .obj7@7e84826b
.obj7@7e84826b := MySourceMember
.obj7@7e84826b.__eContents := \
	files/.obj6@7e84826b
.obj7@7e84826b.__eContainer := /sourcesMembers.obj8@7e84826b
.obj7@7e84826b.module := 

# .obj6@7e84826b
.obj6@7e84826b := MyFileName
.obj6@7e84826b.__eContents := 
.obj6@7e84826b.__eContainer := /files.obj7@7e84826b
.obj6@7e84826b.fileName := head.S

# .obj5@7e84826b
.obj5@7e84826b := MyOptionMember
.obj5@7e84826b.__eContents := \
	options/.obj3@7e84826b
.obj5@7e84826b.__eContainer := /optionsMembers.obj8@7e84826b
.obj5@7e84826b.module := 

# .obj3@7e84826b
.obj3@7e84826b := MyBooleanOption
.obj3@7e84826b.__eContents := \
	defaultValue/.obj4@7e84826b
.obj3@7e84826b.__eContainer := /options.obj5@7e84826b
.obj3@7e84826b.name := mmu_boot
.obj3@7e84826b.origin := 

# .obj4@7e84826b
.obj4@7e84826b := MyBooleanLiteral
.obj4@7e84826b.__eContents := 
.obj4@7e84826b.__eContainer := /defaultValue.obj3@7e84826b
.obj4@7e84826b.isValue := 

# .obj12@7e84826b
.obj12@7e84826b := MyModuleType
.obj12@7e84826b.__eContents := \
	sourcesMembers/.obj11@7e84826b
.obj12@7e84826b.__eContainer := fileContentRoot/types.obj13@7e84826b
.obj12@7e84826b.dependent := 
.obj12@7e84826b.subTypes := 
.obj12@7e84826b.modifiers := 
.obj12@7e84826b.name := static_irq_table
.obj12@7e84826b.origin := 13:8
.obj12@7e84826b.superType := .obj9@7e84826b./
.obj12@7e84826b.customStorage := 

# .obj11@7e84826b
.obj11@7e84826b := MySourceMember
.obj11@7e84826b.__eContents := \
	files/.obj10@7e84826b
.obj11@7e84826b.__eContainer := /sourcesMembers.obj12@7e84826b
.obj11@7e84826b.module := 

# .obj10@7e84826b
.obj10@7e84826b := MyFileName
.obj10@7e84826b.__eContents := 
.obj10@7e84826b.__eContainer := /files.obj11@7e84826b
.obj10@7e84826b.fileName := static_irq_table.lds.S

# .obj9@7e84826b
.obj9@7e84826b := ELink
.obj9@7e84826b.eSource := MyFile_ModuleType_superType.obj12@7e84826b
.obj9@7e84826b.eTarget := 
.obj9@7e84826b.name := embox.kernel.static_irq_table_impl
.obj9@7e84826b.origin := 13:33


__resource-mk/.cache/mybuild/files/src/arch/arm/Mybuild.mk := .obj1@7e84826b
