# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@e4ce09df

# .obj1@e4ce09df
.obj1@e4ce09df := MyFileResource
.obj1@e4ce09df.issues := 
.obj1@e4ce09df.contentsRoot := .obj50@e4ce09df
.obj1@e4ce09df.resourceSet := 
.obj1@e4ce09df.fileName := platform/nuklear/cmd/grfx_skinning/Mybuild
.obj1@e4ce09df.exports := \
	embox.cmd.grfxs \
	embox.cmd.grfxs.grfx_skinning
.obj1@e4ce09df.exports.embox.cmd.grfxs := \
	.obj50@e4ce09df
.obj1@e4ce09df.exports.embox.cmd.grfxs.grfx_skinning := \
	.obj49@e4ce09df

# .obj50@e4ce09df
.obj50@e4ce09df := MyFileContentRoot
.obj50@e4ce09df.__eContents := \
	types/.obj49@e4ce09df
.obj50@e4ce09df.__eContainer := .obj1@e4ce09df
.obj50@e4ce09df.imports := 
.obj50@e4ce09df.name := embox.cmd.grfxs
.obj50@e4ce09df.origin := 

# .obj49@e4ce09df
.obj49@e4ce09df := MyModuleType
.obj49@e4ce09df.__eContents := \
	sourcesMembers/.obj38@e4ce09df \
	sourcesMembers/.obj46@e4ce09df \
	dependsMembers/.obj40@e4ce09df \
	dependsMembers/.obj42@e4ce09df \
	dependsMembers/.obj48@e4ce09df \
	annotations/.obj3@e4ce09df \
	annotations/.obj14@e4ce09df \
	annotations/.obj20@e4ce09df \
	annotations/.obj26@e4ce09df
.obj49@e4ce09df.__eContainer := fileContentRoot/types.obj50@e4ce09df
.obj49@e4ce09df.dependent := 
.obj49@e4ce09df.subTypes := 
.obj49@e4ce09df.modifiers := 
.obj49@e4ce09df.name := grfx_skinning
.obj49@e4ce09df.origin := 16:8
.obj49@e4ce09df.superType := 
.obj49@e4ce09df.customStorage := 

# .obj38@e4ce09df
.obj38@e4ce09df := MySourceMember
.obj38@e4ce09df.__eContents := \
	files/.obj37@e4ce09df \
	annotations/.obj31@e4ce09df \
	annotations/.obj36@e4ce09df
.obj38@e4ce09df.__eContainer := /sourcesMembers.obj49@e4ce09df
.obj38@e4ce09df.module := 

# .obj37@e4ce09df
.obj37@e4ce09df := MyFileName
.obj37@e4ce09df.__eContents := 
.obj37@e4ce09df.__eContainer := /files.obj38@e4ce09df
.obj37@e4ce09df.fileName := grfx_skinning.c

# .obj31@e4ce09df
.obj31@e4ce09df := MyAnnotation
.obj31@e4ce09df.__eContents := \
	bindings/.obj29@e4ce09df
.obj31@e4ce09df.__eContainer := target/annotations.obj38@e4ce09df
.obj31@e4ce09df.type := .obj27@e4ce09df./

# .obj29@e4ce09df
.obj29@e4ce09df := MyOptionBinding
.obj29@e4ce09df.__eContents := \
	value/.obj28@e4ce09df
.obj29@e4ce09df.__eContainer := /bindings.obj31@e4ce09df
.obj29@e4ce09df.option := .obj30@e4ce09df./

# .obj28@e4ce09df
.obj28@e4ce09df := MyStringLiteral
.obj28@e4ce09df.__eContents := 
.obj28@e4ce09df.__eContainer := /value.obj29@e4ce09df
.obj28@e4ce09df.value := $$(EXTERNAL_BUILD_DIR)/third_party/lib/nuklear/install

# .obj30@e4ce09df
.obj30@e4ce09df := ELink
.obj30@e4ce09df.eSource := MyFile_OptionBinding_option.obj29@e4ce09df
.obj30@e4ce09df.eTarget := 
.obj30@e4ce09df.name := value
.obj30@e4ce09df.origin := 17:14

# .obj27@e4ce09df
.obj27@e4ce09df := ELink
.obj27@e4ce09df.eSource := MyFile_Annotation_type.obj31@e4ce09df
.obj27@e4ce09df.eTarget := 
.obj27@e4ce09df.name := IncludePath
.obj27@e4ce09df.origin := 17:3

# .obj36@e4ce09df
.obj36@e4ce09df := MyAnnotation
.obj36@e4ce09df.__eContents := \
	bindings/.obj34@e4ce09df
.obj36@e4ce09df.__eContainer := target/annotations.obj38@e4ce09df
.obj36@e4ce09df.type := .obj32@e4ce09df./

# .obj34@e4ce09df
.obj34@e4ce09df := MyOptionBinding
.obj34@e4ce09df.__eContents := \
	value/.obj33@e4ce09df
.obj34@e4ce09df.__eContainer := /bindings.obj36@e4ce09df
.obj34@e4ce09df.option := .obj35@e4ce09df./

# .obj33@e4ce09df
.obj33@e4ce09df := MyStringLiteral
.obj33@e4ce09df.__eContents := 
.obj33@e4ce09df.__eContainer := /value.obj34@e4ce09df
.obj33@e4ce09df.value := $$(EXTERNAL_BUILD_DIR)/third_party/lib/stb/install

# .obj35@e4ce09df
.obj35@e4ce09df := ELink
.obj35@e4ce09df.eSource := MyFile_OptionBinding_option.obj34@e4ce09df
.obj35@e4ce09df.eTarget := 
.obj35@e4ce09df.name := value
.obj35@e4ce09df.origin := 18:14

# .obj32@e4ce09df
.obj32@e4ce09df := ELink
.obj32@e4ce09df.eSource := MyFile_Annotation_type.obj36@e4ce09df
.obj32@e4ce09df.eTarget := 
.obj32@e4ce09df.name := IncludePath
.obj32@e4ce09df.origin := 18:3

# .obj46@e4ce09df
.obj46@e4ce09df := MySourceMember
.obj46@e4ce09df.__eContents := \
	files/.obj45@e4ce09df \
	annotations/.obj44@e4ce09df
.obj46@e4ce09df.__eContainer := /sourcesMembers.obj49@e4ce09df
.obj46@e4ce09df.module := 

# .obj45@e4ce09df
.obj45@e4ce09df := MyFileName
.obj45@e4ce09df.__eContents := 
.obj45@e4ce09df.__eContainer := /files.obj46@e4ce09df
.obj45@e4ce09df.fileName := gwen.png

# .obj44@e4ce09df
.obj44@e4ce09df := MyAnnotation
.obj44@e4ce09df.__eContents := 
.obj44@e4ce09df.__eContainer := target/annotations.obj46@e4ce09df
.obj44@e4ce09df.type := .obj43@e4ce09df./

# .obj43@e4ce09df
.obj43@e4ce09df := ELink
.obj43@e4ce09df.eSource := MyFile_Annotation_type.obj44@e4ce09df
.obj43@e4ce09df.eTarget := 
.obj43@e4ce09df.name := InitFS
.obj43@e4ce09df.origin := 23:3

# .obj40@e4ce09df
.obj40@e4ce09df := MyDependsMember
.obj40@e4ce09df.__eContents := 
.obj40@e4ce09df.__eContainer := /dependsMembers.obj49@e4ce09df
.obj40@e4ce09df.modules := \
	.obj39@e4ce09df./
.obj40@e4ce09df.module := 

# .obj39@e4ce09df
.obj39@e4ce09df := ELink
.obj39@e4ce09df.eSource := MyFile_DependsMember_modules.obj40@e4ce09df
.obj39@e4ce09df.eTarget := 
.obj39@e4ce09df.name := third_party.lib.nuklear
.obj39@e4ce09df.origin := 20:10

# .obj42@e4ce09df
.obj42@e4ce09df := MyDependsMember
.obj42@e4ce09df.__eContents := 
.obj42@e4ce09df.__eContainer := /dependsMembers.obj49@e4ce09df
.obj42@e4ce09df.modules := \
	.obj41@e4ce09df./
.obj42@e4ce09df.module := 

# .obj41@e4ce09df
.obj41@e4ce09df := ELink
.obj41@e4ce09df.eSource := MyFile_DependsMember_modules.obj42@e4ce09df
.obj41@e4ce09df.eTarget := 
.obj41@e4ce09df.name := third_party.lib.stb
.obj41@e4ce09df.origin := 21:10

# .obj48@e4ce09df
.obj48@e4ce09df := MyDependsMember
.obj48@e4ce09df.__eContents := 
.obj48@e4ce09df.__eContainer := /dependsMembers.obj49@e4ce09df
.obj48@e4ce09df.modules := \
	.obj47@e4ce09df./
.obj48@e4ce09df.module := 

# .obj47@e4ce09df
.obj47@e4ce09df := ELink
.obj47@e4ce09df.eSource := MyFile_DependsMember_modules.obj48@e4ce09df
.obj47@e4ce09df.eTarget := 
.obj47@e4ce09df.name := platform.nuklear.nk_embox_renderer
.obj47@e4ce09df.origin := 26:10

# .obj3@e4ce09df
.obj3@e4ce09df := MyAnnotation
.obj3@e4ce09df.__eContents := 
.obj3@e4ce09df.__eContainer := target/annotations.obj49@e4ce09df
.obj3@e4ce09df.type := .obj2@e4ce09df./

# .obj2@e4ce09df
.obj2@e4ce09df := ELink
.obj2@e4ce09df.eSource := MyFile_Annotation_type.obj3@e4ce09df
.obj2@e4ce09df.eTarget := 
.obj2@e4ce09df.name := AutoCmd
.obj2@e4ce09df.origin := 3:2

# .obj14@e4ce09df
.obj14@e4ce09df := MyAnnotation
.obj14@e4ce09df.__eContents := \
	bindings/.obj7@e4ce09df \
	bindings/.obj10@e4ce09df \
	bindings/.obj13@e4ce09df
.obj14@e4ce09df.__eContainer := target/annotations.obj49@e4ce09df
.obj14@e4ce09df.type := .obj4@e4ce09df./

# .obj7@e4ce09df
.obj7@e4ce09df := MyOptionBinding
.obj7@e4ce09df.__eContents := \
	value/.obj6@e4ce09df
.obj7@e4ce09df.__eContainer := /bindings.obj14@e4ce09df
.obj7@e4ce09df.option := .obj5@e4ce09df./

# .obj6@e4ce09df
.obj6@e4ce09df := MyStringLiteral
.obj6@e4ce09df.__eContents := 
.obj6@e4ce09df.__eContainer := /value.obj7@e4ce09df
.obj6@e4ce09df.value := grfx_skinning

# .obj5@e4ce09df
.obj5@e4ce09df := ELink
.obj5@e4ce09df.eSource := MyFile_OptionBinding_option.obj7@e4ce09df
.obj5@e4ce09df.eTarget := 
.obj5@e4ce09df.name := name
.obj5@e4ce09df.origin := 4:6

# .obj10@e4ce09df
.obj10@e4ce09df := MyOptionBinding
.obj10@e4ce09df.__eContents := \
	value/.obj9@e4ce09df
.obj10@e4ce09df.__eContainer := /bindings.obj14@e4ce09df
.obj10@e4ce09df.option := .obj8@e4ce09df./

# .obj9@e4ce09df
.obj9@e4ce09df := MyStringLiteral
.obj9@e4ce09df.__eContents := 
.obj9@e4ce09df.__eContainer := /value.obj10@e4ce09df
.obj9@e4ce09df.value := This command just run example with nuklear graphics.

# .obj8@e4ce09df
.obj8@e4ce09df := ELink
.obj8@e4ce09df.eSource := MyFile_OptionBinding_option.obj10@e4ce09df
.obj8@e4ce09df.eTarget := 
.obj8@e4ce09df.name := help
.obj8@e4ce09df.origin := 5:2

# .obj13@e4ce09df
.obj13@e4ce09df := MyOptionBinding
.obj13@e4ce09df.__eContents := \
	value/.obj12@e4ce09df
.obj13@e4ce09df.__eContainer := /bindings.obj14@e4ce09df
.obj13@e4ce09df.option := .obj11@e4ce09df./

# .obj12@e4ce09df
.obj12@e4ce09df := MyStringLiteral
.obj12@e4ce09df.__eContents := 
.obj12@e4ce09df.__eContainer := /value.obj13@e4ce09df
.obj12@e4ce09df.value := $(\0)$(\n)		NAME$(\n)			grfx_skinning$(\n)		SYNOPSIS$(\n)			It provides graphics by nuklear GUI. $(\n)		AUTHORS$(\n)Aleksandra Butrova ;)$(\n)	

# .obj11@e4ce09df
.obj11@e4ce09df := ELink
.obj11@e4ce09df.eSource := MyFile_OptionBinding_option.obj13@e4ce09df
.obj11@e4ce09df.eTarget := 
.obj11@e4ce09df.name := man
.obj11@e4ce09df.origin := 6:2

# .obj4@e4ce09df
.obj4@e4ce09df := ELink
.obj4@e4ce09df.eSource := MyFile_Annotation_type.obj14@e4ce09df
.obj4@e4ce09df.eTarget := 
.obj4@e4ce09df.name := Cmd
.obj4@e4ce09df.origin := 4:2

# .obj20@e4ce09df
.obj20@e4ce09df := MyAnnotation
.obj20@e4ce09df.__eContents := \
	bindings/.obj18@e4ce09df
.obj20@e4ce09df.__eContainer := target/annotations.obj49@e4ce09df
.obj20@e4ce09df.type := .obj15@e4ce09df./

# .obj18@e4ce09df
.obj18@e4ce09df := MyOptionBinding
.obj18@e4ce09df.__eContents := \
	value/.obj17@e4ce09df
.obj18@e4ce09df.__eContainer := /bindings.obj20@e4ce09df
.obj18@e4ce09df.option := .obj19@e4ce09df./

# .obj17@e4ce09df
.obj17@e4ce09df := MyTypeReferenceLiteral
.obj17@e4ce09df.__eContents := 
.obj17@e4ce09df.__eContainer := /value.obj18@e4ce09df
.obj17@e4ce09df.value := .obj16@e4ce09df./

# .obj16@e4ce09df
.obj16@e4ce09df := ELink
.obj16@e4ce09df.eSource := MyFile_TypeReferenceLiteral_value.obj17@e4ce09df
.obj16@e4ce09df.eTarget := 
.obj16@e4ce09df.name := third_party.lib.nuklear
.obj16@e4ce09df.origin := 14:15

# .obj19@e4ce09df
.obj19@e4ce09df := ELink
.obj19@e4ce09df.eSource := MyFile_OptionBinding_option.obj18@e4ce09df
.obj19@e4ce09df.eTarget := 
.obj19@e4ce09df.name := value
.obj19@e4ce09df.origin := 14:14

# .obj15@e4ce09df
.obj15@e4ce09df := ELink
.obj15@e4ce09df.eSource := MyFile_Annotation_type.obj20@e4ce09df
.obj15@e4ce09df.eTarget := 
.obj15@e4ce09df.name := BuildDepends
.obj15@e4ce09df.origin := 14:2

# .obj26@e4ce09df
.obj26@e4ce09df := MyAnnotation
.obj26@e4ce09df.__eContents := \
	bindings/.obj24@e4ce09df
.obj26@e4ce09df.__eContainer := target/annotations.obj49@e4ce09df
.obj26@e4ce09df.type := .obj21@e4ce09df./

# .obj24@e4ce09df
.obj24@e4ce09df := MyOptionBinding
.obj24@e4ce09df.__eContents := \
	value/.obj23@e4ce09df
.obj24@e4ce09df.__eContainer := /bindings.obj26@e4ce09df
.obj24@e4ce09df.option := .obj25@e4ce09df./

# .obj23@e4ce09df
.obj23@e4ce09df := MyTypeReferenceLiteral
.obj23@e4ce09df.__eContents := 
.obj23@e4ce09df.__eContainer := /value.obj24@e4ce09df
.obj23@e4ce09df.value := .obj22@e4ce09df./

# .obj22@e4ce09df
.obj22@e4ce09df := ELink
.obj22@e4ce09df.eSource := MyFile_TypeReferenceLiteral_value.obj23@e4ce09df
.obj22@e4ce09df.eTarget := 
.obj22@e4ce09df.name := third_party.lib.stb
.obj22@e4ce09df.origin := 15:15

# .obj25@e4ce09df
.obj25@e4ce09df := ELink
.obj25@e4ce09df.eSource := MyFile_OptionBinding_option.obj24@e4ce09df
.obj25@e4ce09df.eTarget := 
.obj25@e4ce09df.name := value
.obj25@e4ce09df.origin := 15:14

# .obj21@e4ce09df
.obj21@e4ce09df := ELink
.obj21@e4ce09df.eSource := MyFile_Annotation_type.obj26@e4ce09df
.obj21@e4ce09df.eTarget := 
.obj21@e4ce09df.name := BuildDepends
.obj21@e4ce09df.origin := 15:2


__resource-mk/.cache/mybuild/files/platform/nuklear/cmd/grfx_skinning/Mybuild.mk := .obj1@e4ce09df
