# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@c3abaede

# .obj1@c3abaede
.obj1@c3abaede := MyFileResource
.obj1@c3abaede.issues := 
.obj1@c3abaede.contentsRoot := .obj18@c3abaede
.obj1@c3abaede.resourceSet := 
.obj1@c3abaede.fileName := src/cmds/Armv7a_debug.my
.obj1@c3abaede.exports := \
	embox.cmd \
	embox.cmd.armv7a_debug
.obj1@c3abaede.exports.embox.cmd := \
	.obj18@c3abaede
.obj1@c3abaede.exports.embox.cmd.armv7a_debug := \
	.obj17@c3abaede

# .obj18@c3abaede
.obj18@c3abaede := MyFileContentRoot
.obj18@c3abaede.__eContents := \
	types/.obj17@c3abaede
.obj18@c3abaede.__eContainer := .obj1@c3abaede
.obj18@c3abaede.imports := 
.obj18@c3abaede.name := embox.cmd
.obj18@c3abaede.origin := 

# .obj17@c3abaede
.obj17@c3abaede := MyModuleType
.obj17@c3abaede.__eContents := \
	sourcesMembers/.obj16@c3abaede \
	annotations/.obj3@c3abaede \
	annotations/.obj14@c3abaede
.obj17@c3abaede.__eContainer := fileContentRoot/types.obj18@c3abaede
.obj17@c3abaede.dependent := 
.obj17@c3abaede.subTypes := 
.obj17@c3abaede.modifiers := 
.obj17@c3abaede.name := armv7a_debug
.obj17@c3abaede.origin := 7:8
.obj17@c3abaede.superType := 
.obj17@c3abaede.customStorage := 

# .obj16@c3abaede
.obj16@c3abaede := MySourceMember
.obj16@c3abaede.__eContents := \
	files/.obj15@c3abaede
.obj16@c3abaede.__eContainer := /sourcesMembers.obj17@c3abaede
.obj16@c3abaede.module := 

# .obj15@c3abaede
.obj15@c3abaede := MyFileName
.obj15@c3abaede.__eContents := 
.obj15@c3abaede.__eContainer := /files.obj16@c3abaede
.obj15@c3abaede.fileName := armv7a_debug.c

# .obj3@c3abaede
.obj3@c3abaede := MyAnnotation
.obj3@c3abaede.__eContents := 
.obj3@c3abaede.__eContainer := target/annotations.obj17@c3abaede
.obj3@c3abaede.type := .obj2@c3abaede./

# .obj2@c3abaede
.obj2@c3abaede := ELink
.obj2@c3abaede.eSource := MyFile_Annotation_type.obj3@c3abaede
.obj2@c3abaede.eTarget := 
.obj2@c3abaede.name := AutoCmd
.obj2@c3abaede.origin := 3:2

# .obj14@c3abaede
.obj14@c3abaede := MyAnnotation
.obj14@c3abaede.__eContents := \
	bindings/.obj7@c3abaede \
	bindings/.obj10@c3abaede \
	bindings/.obj13@c3abaede
.obj14@c3abaede.__eContainer := target/annotations.obj17@c3abaede
.obj14@c3abaede.type := .obj4@c3abaede./

# .obj7@c3abaede
.obj7@c3abaede := MyOptionBinding
.obj7@c3abaede.__eContents := \
	value/.obj6@c3abaede
.obj7@c3abaede.__eContainer := /bindings.obj14@c3abaede
.obj7@c3abaede.option := .obj5@c3abaede./

# .obj6@c3abaede
.obj6@c3abaede := MyStringLiteral
.obj6@c3abaede.__eContents := 
.obj6@c3abaede.__eContainer := /value.obj7@c3abaede
.obj6@c3abaede.value := armv7a_debug

# .obj5@c3abaede
.obj5@c3abaede := ELink
.obj5@c3abaede.eSource := MyFile_OptionBinding_option.obj7@c3abaede
.obj5@c3abaede.eTarget := 
.obj5@c3abaede.name := name
.obj5@c3abaede.origin := 4:6

# .obj10@c3abaede
.obj10@c3abaede := MyOptionBinding
.obj10@c3abaede.__eContents := \
	value/.obj9@c3abaede
.obj10@c3abaede.__eContainer := /bindings.obj14@c3abaede
.obj10@c3abaede.option := .obj8@c3abaede./

# .obj9@c3abaede
.obj9@c3abaede := MyStringLiteral
.obj9@c3abaede.__eContents := 
.obj9@c3abaede.__eContainer := /value.obj10@c3abaede
.obj9@c3abaede.value := ARMV7A Debug

# .obj8@c3abaede
.obj8@c3abaede := ELink
.obj8@c3abaede.eSource := MyFile_OptionBinding_option.obj10@c3abaede
.obj8@c3abaede.eTarget := 
.obj8@c3abaede.name := help
.obj8@c3abaede.origin := 5:2

# .obj13@c3abaede
.obj13@c3abaede := MyOptionBinding
.obj13@c3abaede.__eContents := \
	value/.obj12@c3abaede
.obj13@c3abaede.__eContainer := /bindings.obj14@c3abaede
.obj13@c3abaede.option := .obj11@c3abaede./

# .obj12@c3abaede
.obj12@c3abaede := MyStringLiteral
.obj12@c3abaede.__eContents := 
.obj12@c3abaede.__eContainer := /value.obj13@c3abaede
.obj12@c3abaede.value := 

# .obj11@c3abaede
.obj11@c3abaede := ELink
.obj11@c3abaede.eSource := MyFile_OptionBinding_option.obj13@c3abaede
.obj11@c3abaede.eTarget := 
.obj11@c3abaede.name := man
.obj11@c3abaede.origin := 6:2

# .obj4@c3abaede
.obj4@c3abaede := ELink
.obj4@c3abaede.eSource := MyFile_Annotation_type.obj14@c3abaede
.obj4@c3abaede.eTarget := 
.obj4@c3abaede.name := Cmd
.obj4@c3abaede.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/Armv7a_debug.my.mk := .obj1@c3abaede
