# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@be23f5e7

# .obj1@be23f5e7
.obj1@be23f5e7 := MyFileResource
.obj1@be23f5e7.issues := 
.obj1@be23f5e7.contentsRoot := .obj20@be23f5e7
.obj1@be23f5e7.resourceSet := 
.obj1@be23f5e7.fileName := src/drivers/gpio/imx/Mybuild
.obj1@be23f5e7.exports := \
	embox.driver.gpio \
	embox.driver.gpio.imx \
	embox.driver.gpio.imx.gpio_chip_id \
	embox.driver.gpio.imx.base_addr \
	embox.driver.gpio.imx.gpio_ports \
	embox.driver.gpio.imx.log_level
.obj1@be23f5e7.exports.embox.driver.gpio := \
	.obj20@be23f5e7
.obj1@be23f5e7.exports.embox.driver.gpio.imx := \
	.obj19@be23f5e7
.obj1@be23f5e7.exports.embox.driver.gpio.imx.gpio_chip_id := \
	.obj3@be23f5e7
.obj1@be23f5e7.exports.embox.driver.gpio.imx.base_addr := \
	.obj6@be23f5e7
.obj1@be23f5e7.exports.embox.driver.gpio.imx.gpio_ports := \
	.obj9@be23f5e7
.obj1@be23f5e7.exports.embox.driver.gpio.imx.log_level := \
	.obj12@be23f5e7

# .obj20@be23f5e7
.obj20@be23f5e7 := MyFileContentRoot
.obj20@be23f5e7.__eContents := \
	types/.obj19@be23f5e7
.obj20@be23f5e7.__eContainer := .obj1@be23f5e7
.obj20@be23f5e7.imports := 
.obj20@be23f5e7.name := embox.driver.gpio
.obj20@be23f5e7.origin := 

# .obj19@be23f5e7
.obj19@be23f5e7 := MyModuleType
.obj19@be23f5e7.__eContents := \
	sourcesMembers/.obj16@be23f5e7 \
	optionsMembers/.obj5@be23f5e7 \
	optionsMembers/.obj8@be23f5e7 \
	optionsMembers/.obj11@be23f5e7 \
	optionsMembers/.obj14@be23f5e7 \
	dependsMembers/.obj18@be23f5e7
.obj19@be23f5e7.__eContainer := fileContentRoot/types.obj20@be23f5e7
.obj19@be23f5e7.dependent := 
.obj19@be23f5e7.subTypes := 
.obj19@be23f5e7.modifiers := 
.obj19@be23f5e7.name := imx
.obj19@be23f5e7.origin := 3:8
.obj19@be23f5e7.superType := .obj2@be23f5e7./
.obj19@be23f5e7.customStorage := 

# .obj16@be23f5e7
.obj16@be23f5e7 := MySourceMember
.obj16@be23f5e7.__eContents := \
	files/.obj15@be23f5e7
.obj16@be23f5e7.__eContainer := /sourcesMembers.obj19@be23f5e7
.obj16@be23f5e7.module := 

# .obj15@be23f5e7
.obj15@be23f5e7 := MyFileName
.obj15@be23f5e7.__eContents := 
.obj15@be23f5e7.__eContainer := /files.obj16@be23f5e7
.obj15@be23f5e7.fileName := imx.c

# .obj5@be23f5e7
.obj5@be23f5e7 := MyOptionMember
.obj5@be23f5e7.__eContents := \
	options/.obj3@be23f5e7
.obj5@be23f5e7.__eContainer := /optionsMembers.obj19@be23f5e7
.obj5@be23f5e7.module := 

# .obj3@be23f5e7
.obj3@be23f5e7 := MyNumberOption
.obj3@be23f5e7.__eContents := \
	defaultValue/.obj4@be23f5e7
.obj3@be23f5e7.__eContainer := /options.obj5@be23f5e7
.obj3@be23f5e7.name := gpio_chip_id
.obj3@be23f5e7.origin := 

# .obj4@be23f5e7
.obj4@be23f5e7 := MyNumberLiteral
.obj4@be23f5e7.__eContents := 
.obj4@be23f5e7.__eContainer := /defaultValue.obj3@be23f5e7
.obj4@be23f5e7.value := 0

# .obj8@be23f5e7
.obj8@be23f5e7 := MyOptionMember
.obj8@be23f5e7.__eContents := \
	options/.obj6@be23f5e7
.obj8@be23f5e7.__eContainer := /optionsMembers.obj19@be23f5e7
.obj8@be23f5e7.module := 

# .obj6@be23f5e7
.obj6@be23f5e7 := MyNumberOption
.obj6@be23f5e7.__eContents := \
	defaultValue/.obj7@be23f5e7
.obj6@be23f5e7.__eContainer := /options.obj8@be23f5e7
.obj6@be23f5e7.name := base_addr
.obj6@be23f5e7.origin := 

# .obj7@be23f5e7
.obj7@be23f5e7 := MyNumberLiteral
.obj7@be23f5e7.__eContents := 
.obj7@be23f5e7.__eContainer := /defaultValue.obj6@be23f5e7
.obj7@be23f5e7.value := 34193408

# .obj11@be23f5e7
.obj11@be23f5e7 := MyOptionMember
.obj11@be23f5e7.__eContents := \
	options/.obj9@be23f5e7
.obj11@be23f5e7.__eContainer := /optionsMembers.obj19@be23f5e7
.obj11@be23f5e7.module := 

# .obj9@be23f5e7
.obj9@be23f5e7 := MyNumberOption
.obj9@be23f5e7.__eContents := \
	defaultValue/.obj10@be23f5e7
.obj9@be23f5e7.__eContainer := /options.obj11@be23f5e7
.obj9@be23f5e7.name := gpio_ports
.obj9@be23f5e7.origin := 

# .obj10@be23f5e7
.obj10@be23f5e7 := MyNumberLiteral
.obj10@be23f5e7.__eContents := 
.obj10@be23f5e7.__eContainer := /defaultValue.obj9@be23f5e7
.obj10@be23f5e7.value := 4

# .obj14@be23f5e7
.obj14@be23f5e7 := MyOptionMember
.obj14@be23f5e7.__eContents := \
	options/.obj12@be23f5e7
.obj14@be23f5e7.__eContainer := /optionsMembers.obj19@be23f5e7
.obj14@be23f5e7.module := 

# .obj12@be23f5e7
.obj12@be23f5e7 := MyNumberOption
.obj12@be23f5e7.__eContents := \
	defaultValue/.obj13@be23f5e7
.obj12@be23f5e7.__eContainer := /options.obj14@be23f5e7
.obj12@be23f5e7.name := log_level
.obj12@be23f5e7.origin := 

# .obj13@be23f5e7
.obj13@be23f5e7 := MyNumberLiteral
.obj13@be23f5e7.__eContents := 
.obj13@be23f5e7.__eContainer := /defaultValue.obj12@be23f5e7
.obj13@be23f5e7.value := 0

# .obj18@be23f5e7
.obj18@be23f5e7 := MyDependsMember
.obj18@be23f5e7.__eContents := 
.obj18@be23f5e7.__eContainer := /dependsMembers.obj19@be23f5e7
.obj18@be23f5e7.modules := \
	.obj17@be23f5e7./
.obj18@be23f5e7.module := 

# .obj17@be23f5e7
.obj17@be23f5e7 := ELink
.obj17@be23f5e7.eSource := MyFile_DependsMember_modules.obj18@be23f5e7
.obj17@be23f5e7.eTarget := 
.obj17@be23f5e7.name := embox.driver.gpio.core
.obj17@be23f5e7.origin := 11:10

# .obj2@be23f5e7
.obj2@be23f5e7 := ELink
.obj2@be23f5e7.eSource := MyFile_ModuleType_superType.obj19@be23f5e7
.obj2@be23f5e7.eTarget := 
.obj2@be23f5e7.name := api
.obj2@be23f5e7.origin := 3:20


__resource-mk/.cache/mybuild/files/src/drivers/gpio/imx/Mybuild.mk := .obj1@be23f5e7
