# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@82e7076b

# .obj1@82e7076b
.obj1@82e7076b := MyFileResource
.obj1@82e7076b.issues := 
.obj1@82e7076b.contentsRoot := .obj26@82e7076b
.obj1@82e7076b.resourceSet := 
.obj1@82e7076b.fileName := src/cmds/hardware/Clock.my
.obj1@82e7076b.exports := \
	embox.cmd \
	embox.cmd.clock
.obj1@82e7076b.exports.embox.cmd := \
	.obj26@82e7076b
.obj1@82e7076b.exports.embox.cmd.clock := \
	.obj25@82e7076b

# .obj26@82e7076b
.obj26@82e7076b := MyFileContentRoot
.obj26@82e7076b.__eContents := \
	types/.obj25@82e7076b
.obj26@82e7076b.__eContainer := .obj1@82e7076b
.obj26@82e7076b.imports := 
.obj26@82e7076b.name := embox.cmd
.obj26@82e7076b.origin := 

# .obj25@82e7076b
.obj25@82e7076b := MyModuleType
.obj25@82e7076b.__eContents := \
	sourcesMembers/.obj16@82e7076b \
	dependsMembers/.obj18@82e7076b \
	dependsMembers/.obj20@82e7076b \
	dependsMembers/.obj22@82e7076b \
	dependsMembers/.obj24@82e7076b \
	annotations/.obj3@82e7076b \
	annotations/.obj14@82e7076b
.obj25@82e7076b.__eContainer := fileContentRoot/types.obj26@82e7076b
.obj25@82e7076b.dependent := 
.obj25@82e7076b.subTypes := 
.obj25@82e7076b.modifiers := 
.obj25@82e7076b.name := clock
.obj25@82e7076b.origin := 16:8
.obj25@82e7076b.superType := 
.obj25@82e7076b.customStorage := 

# .obj16@82e7076b
.obj16@82e7076b := MySourceMember
.obj16@82e7076b.__eContents := \
	files/.obj15@82e7076b
.obj16@82e7076b.__eContainer := /sourcesMembers.obj25@82e7076b
.obj16@82e7076b.module := 

# .obj15@82e7076b
.obj15@82e7076b := MyFileName
.obj15@82e7076b.__eContents := 
.obj15@82e7076b.__eContainer := /files.obj16@82e7076b
.obj15@82e7076b.fileName := clock.c

# .obj18@82e7076b
.obj18@82e7076b := MyDependsMember
.obj18@82e7076b.__eContents := 
.obj18@82e7076b.__eContainer := /dependsMembers.obj25@82e7076b
.obj18@82e7076b.modules := \
	.obj17@82e7076b./
.obj18@82e7076b.module := 

# .obj17@82e7076b
.obj17@82e7076b := ELink
.obj17@82e7076b.eSource := MyFile_DependsMember_modules.obj18@82e7076b
.obj17@82e7076b.eTarget := 
.obj17@82e7076b.name := embox.compat.libc.all
.obj17@82e7076b.origin := 19:10

# .obj20@82e7076b
.obj20@82e7076b := MyDependsMember
.obj20@82e7076b.__eContents := 
.obj20@82e7076b.__eContainer := /dependsMembers.obj25@82e7076b
.obj20@82e7076b.modules := \
	.obj19@82e7076b./
.obj20@82e7076b.module := 

# .obj19@82e7076b
.obj19@82e7076b := ELink
.obj19@82e7076b.eSource := MyFile_DependsMember_modules.obj20@82e7076b
.obj19@82e7076b.eTarget := 
.obj19@82e7076b.name := embox.compat.posix.LibPosix
.obj19@82e7076b.origin := 20:10

# .obj22@82e7076b
.obj22@82e7076b := MyDependsMember
.obj22@82e7076b.__eContents := 
.obj22@82e7076b.__eContainer := /dependsMembers.obj25@82e7076b
.obj22@82e7076b.modules := \
	.obj21@82e7076b./
.obj22@82e7076b.module := 

# .obj21@82e7076b
.obj21@82e7076b := ELink
.obj21@82e7076b.eSource := MyFile_DependsMember_modules.obj22@82e7076b
.obj21@82e7076b.eTarget := 
.obj21@82e7076b.name := embox.kernel.time.clock_source
.obj21@82e7076b.origin := 21:10

# .obj24@82e7076b
.obj24@82e7076b := MyDependsMember
.obj24@82e7076b.__eContents := 
.obj24@82e7076b.__eContainer := /dependsMembers.obj25@82e7076b
.obj24@82e7076b.modules := \
	.obj23@82e7076b./
.obj24@82e7076b.module := 

# .obj23@82e7076b
.obj23@82e7076b := ELink
.obj23@82e7076b.eSource := MyFile_DependsMember_modules.obj24@82e7076b
.obj23@82e7076b.eTarget := 
.obj23@82e7076b.name := embox.framework.LibFramework
.obj23@82e7076b.origin := 22:10

# .obj3@82e7076b
.obj3@82e7076b := MyAnnotation
.obj3@82e7076b.__eContents := 
.obj3@82e7076b.__eContainer := target/annotations.obj25@82e7076b
.obj3@82e7076b.type := .obj2@82e7076b./

# .obj2@82e7076b
.obj2@82e7076b := ELink
.obj2@82e7076b.eSource := MyFile_Annotation_type.obj3@82e7076b
.obj2@82e7076b.eTarget := 
.obj2@82e7076b.name := AutoCmd
.obj2@82e7076b.origin := 3:2

# .obj14@82e7076b
.obj14@82e7076b := MyAnnotation
.obj14@82e7076b.__eContents := \
	bindings/.obj7@82e7076b \
	bindings/.obj10@82e7076b \
	bindings/.obj13@82e7076b
.obj14@82e7076b.__eContainer := target/annotations.obj25@82e7076b
.obj14@82e7076b.type := .obj4@82e7076b./

# .obj7@82e7076b
.obj7@82e7076b := MyOptionBinding
.obj7@82e7076b.__eContents := \
	value/.obj6@82e7076b
.obj7@82e7076b.__eContainer := /bindings.obj14@82e7076b
.obj7@82e7076b.option := .obj5@82e7076b./

# .obj6@82e7076b
.obj6@82e7076b := MyStringLiteral
.obj6@82e7076b.__eContents := 
.obj6@82e7076b.__eContainer := /value.obj7@82e7076b
.obj6@82e7076b.value := clock

# .obj5@82e7076b
.obj5@82e7076b := ELink
.obj5@82e7076b.eSource := MyFile_OptionBinding_option.obj7@82e7076b
.obj5@82e7076b.eTarget := 
.obj5@82e7076b.name := name
.obj5@82e7076b.origin := 4:6

# .obj10@82e7076b
.obj10@82e7076b := MyOptionBinding
.obj10@82e7076b.__eContents := \
	value/.obj9@82e7076b
.obj10@82e7076b.__eContainer := /bindings.obj14@82e7076b
.obj10@82e7076b.option := .obj8@82e7076b./

# .obj9@82e7076b
.obj9@82e7076b := MyStringLiteral
.obj9@82e7076b.__eContents := 
.obj9@82e7076b.__eContainer := /value.obj10@82e7076b
.obj9@82e7076b.value := Print existing in system clock sources

# .obj8@82e7076b
.obj8@82e7076b := ELink
.obj8@82e7076b.eSource := MyFile_OptionBinding_option.obj10@82e7076b
.obj8@82e7076b.eTarget := 
.obj8@82e7076b.name := help
.obj8@82e7076b.origin := 5:2

# .obj13@82e7076b
.obj13@82e7076b := MyOptionBinding
.obj13@82e7076b.__eContents := \
	value/.obj12@82e7076b
.obj13@82e7076b.__eContainer := /bindings.obj14@82e7076b
.obj13@82e7076b.option := .obj11@82e7076b./

# .obj12@82e7076b
.obj12@82e7076b := MyStringLiteral
.obj12@82e7076b.__eContents := 
.obj12@82e7076b.__eContainer := /value.obj13@82e7076b
.obj12@82e7076b.value := $(\0)$(\n)		NAME$(\n)			clock - Print existing in system clock sources$(\n)		SYNOPSIS$(\n)			clock TODO$(\n)		DESCRIPTION$(\n)			Detailed description.$(\n)		AUTHORS$(\n)			Alina Kramar$(\n)	

# .obj11@82e7076b
.obj11@82e7076b := ELink
.obj11@82e7076b.eSource := MyFile_OptionBinding_option.obj13@82e7076b
.obj11@82e7076b.eTarget := 
.obj11@82e7076b.name := man
.obj11@82e7076b.origin := 6:2

# .obj4@82e7076b
.obj4@82e7076b := ELink
.obj4@82e7076b.eSource := MyFile_Annotation_type.obj14@82e7076b
.obj4@82e7076b.eTarget := 
.obj4@82e7076b.name := Cmd
.obj4@82e7076b.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/hardware/Clock.my.mk := .obj1@82e7076b
