# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@601a9f13

# .obj1@601a9f13
.obj1@601a9f13 := MyFileResource
.obj1@601a9f13.issues := 
.obj1@601a9f13.contentsRoot := .obj26@601a9f13
.obj1@601a9f13.resourceSet := 
.obj1@601a9f13.fileName := src/cmds/hardware/Memcpy.my
.obj1@601a9f13.exports := \
	embox.cmd \
	embox.cmd.memcpy
.obj1@601a9f13.exports.embox.cmd := \
	.obj26@601a9f13
.obj1@601a9f13.exports.embox.cmd.memcpy := \
	.obj25@601a9f13

# .obj26@601a9f13
.obj26@601a9f13 := MyFileContentRoot
.obj26@601a9f13.__eContents := \
	types/.obj25@601a9f13
.obj26@601a9f13.__eContainer := .obj1@601a9f13
.obj26@601a9f13.imports := 
.obj26@601a9f13.name := embox.cmd
.obj26@601a9f13.origin := 

# .obj25@601a9f13
.obj25@601a9f13 := MyModuleType
.obj25@601a9f13.__eContents := \
	sourcesMembers/.obj16@601a9f13 \
	dependsMembers/.obj20@601a9f13 \
	dependsMembers/.obj24@601a9f13 \
	annotations/.obj3@601a9f13 \
	annotations/.obj14@601a9f13
.obj25@601a9f13.__eContainer := fileContentRoot/types.obj26@601a9f13
.obj25@601a9f13.dependent := 
.obj25@601a9f13.subTypes := 
.obj25@601a9f13.modifiers := 
.obj25@601a9f13.name := memcpy
.obj25@601a9f13.origin := 19:8
.obj25@601a9f13.superType := 
.obj25@601a9f13.customStorage := 

# .obj16@601a9f13
.obj16@601a9f13 := MySourceMember
.obj16@601a9f13.__eContents := \
	files/.obj15@601a9f13
.obj16@601a9f13.__eContainer := /sourcesMembers.obj25@601a9f13
.obj16@601a9f13.module := 

# .obj15@601a9f13
.obj15@601a9f13 := MyFileName
.obj15@601a9f13.__eContents := 
.obj15@601a9f13.__eContainer := /files.obj16@601a9f13
.obj15@601a9f13.fileName := memcpy.c

# .obj20@601a9f13
.obj20@601a9f13 := MyDependsMember
.obj20@601a9f13.__eContents := \
	annotations/.obj18@601a9f13
.obj20@601a9f13.__eContainer := /dependsMembers.obj25@601a9f13
.obj20@601a9f13.modules := \
	.obj19@601a9f13./
.obj20@601a9f13.module := 

# .obj18@601a9f13
.obj18@601a9f13 := MyAnnotation
.obj18@601a9f13.__eContents := 
.obj18@601a9f13.__eContainer := target/annotations.obj20@601a9f13
.obj18@601a9f13.type := .obj17@601a9f13./

# .obj17@601a9f13
.obj17@601a9f13 := ELink
.obj17@601a9f13.eSource := MyFile_Annotation_type.obj18@601a9f13
.obj17@601a9f13.eTarget := 
.obj17@601a9f13.name := NoRuntime
.obj17@601a9f13.origin := 22:3

# .obj19@601a9f13
.obj19@601a9f13 := ELink
.obj19@601a9f13.eSource := MyFile_DependsMember_modules.obj20@601a9f13
.obj19@601a9f13.eTarget := 
.obj19@601a9f13.name := embox.compat.libc.str
.obj19@601a9f13.origin := 22:21

# .obj24@601a9f13
.obj24@601a9f13 := MyDependsMember
.obj24@601a9f13.__eContents := \
	annotations/.obj22@601a9f13
.obj24@601a9f13.__eContainer := /dependsMembers.obj25@601a9f13
.obj24@601a9f13.modules := \
	.obj23@601a9f13./
.obj24@601a9f13.module := 

# .obj22@601a9f13
.obj22@601a9f13 := MyAnnotation
.obj22@601a9f13.__eContents := 
.obj22@601a9f13.__eContainer := target/annotations.obj24@601a9f13
.obj22@601a9f13.type := .obj21@601a9f13./

# .obj21@601a9f13
.obj21@601a9f13 := ELink
.obj21@601a9f13.eSource := MyFile_Annotation_type.obj22@601a9f13
.obj21@601a9f13.eTarget := 
.obj21@601a9f13.name := NoRuntime
.obj21@601a9f13.origin := 23:3

# .obj23@601a9f13
.obj23@601a9f13 := ELink
.obj23@601a9f13.eSource := MyFile_DependsMember_modules.obj24@601a9f13
.obj23@601a9f13.eTarget := 
.obj23@601a9f13.name := embox.framework.LibFramework
.obj23@601a9f13.origin := 23:21

# .obj3@601a9f13
.obj3@601a9f13 := MyAnnotation
.obj3@601a9f13.__eContents := 
.obj3@601a9f13.__eContainer := target/annotations.obj25@601a9f13
.obj3@601a9f13.type := .obj2@601a9f13./

# .obj2@601a9f13
.obj2@601a9f13 := ELink
.obj2@601a9f13.eSource := MyFile_Annotation_type.obj3@601a9f13
.obj2@601a9f13.eTarget := 
.obj2@601a9f13.name := AutoCmd
.obj2@601a9f13.origin := 3:2

# .obj14@601a9f13
.obj14@601a9f13 := MyAnnotation
.obj14@601a9f13.__eContents := \
	bindings/.obj7@601a9f13 \
	bindings/.obj10@601a9f13 \
	bindings/.obj13@601a9f13
.obj14@601a9f13.__eContainer := target/annotations.obj25@601a9f13
.obj14@601a9f13.type := .obj4@601a9f13./

# .obj7@601a9f13
.obj7@601a9f13 := MyOptionBinding
.obj7@601a9f13.__eContents := \
	value/.obj6@601a9f13
.obj7@601a9f13.__eContainer := /bindings.obj14@601a9f13
.obj7@601a9f13.option := .obj5@601a9f13./

# .obj6@601a9f13
.obj6@601a9f13 := MyStringLiteral
.obj6@601a9f13.__eContents := 
.obj6@601a9f13.__eContainer := /value.obj7@601a9f13
.obj6@601a9f13.value := memcpy

# .obj5@601a9f13
.obj5@601a9f13 := ELink
.obj5@601a9f13.eSource := MyFile_OptionBinding_option.obj7@601a9f13
.obj5@601a9f13.eTarget := 
.obj5@601a9f13.name := name
.obj5@601a9f13.origin := 4:6

# .obj10@601a9f13
.obj10@601a9f13 := MyOptionBinding
.obj10@601a9f13.__eContents := \
	value/.obj9@601a9f13
.obj10@601a9f13.__eContainer := /bindings.obj14@601a9f13
.obj10@601a9f13.option := .obj8@601a9f13./

# .obj9@601a9f13
.obj9@601a9f13 := MyStringLiteral
.obj9@601a9f13.__eContents := 
.obj9@601a9f13.__eContainer := /value.obj10@601a9f13
.obj9@601a9f13.value := Copy contents of memory

# .obj8@601a9f13
.obj8@601a9f13 := ELink
.obj8@601a9f13.eSource := MyFile_OptionBinding_option.obj10@601a9f13
.obj8@601a9f13.eTarget := 
.obj8@601a9f13.name := help
.obj8@601a9f13.origin := 5:2

# .obj13@601a9f13
.obj13@601a9f13 := MyOptionBinding
.obj13@601a9f13.__eContents := \
	value/.obj12@601a9f13
.obj13@601a9f13.__eContainer := /bindings.obj14@601a9f13
.obj13@601a9f13.option := .obj11@601a9f13./

# .obj12@601a9f13
.obj12@601a9f13 := MyStringLiteral
.obj12@601a9f13.__eContents := 
.obj12@601a9f13.__eContainer := /value.obj13@601a9f13
.obj12@601a9f13.value := $(\0)$(\n)		NAME$(\n)			memcpy - copy memory$(\n)		SYNOPSIS$(\n)			mem [-h] <dest> <src> <n>$(\n)		DESCRIPTION$(\n)			Just memcpy()$(\n)		OPTIONS$(\n)			-h$(\n)				Shows usage$(\n)		AUTHORS$(\n)			Alexander Kalmuk$(\n)	

# .obj11@601a9f13
.obj11@601a9f13 := ELink
.obj11@601a9f13.eSource := MyFile_OptionBinding_option.obj13@601a9f13
.obj11@601a9f13.eTarget := 
.obj11@601a9f13.name := man
.obj11@601a9f13.origin := 6:2

# .obj4@601a9f13
.obj4@601a9f13 := ELink
.obj4@601a9f13.eSource := MyFile_Annotation_type.obj14@601a9f13
.obj4@601a9f13.eTarget := 
.obj4@601a9f13.name := Cmd
.obj4@601a9f13.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/hardware/Memcpy.my.mk := .obj1@601a9f13
