# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@6367ca52

# .obj1@6367ca52
.obj1@6367ca52 := MyFileResource
.obj1@6367ca52.issues := 
.obj1@6367ca52.contentsRoot := .obj98@6367ca52
.obj1@6367ca52.resourceSet := 
.obj1@6367ca52.fileName := src/kernel/task/resource/Mybuild
.obj1@6367ca52.exports := \
	embox.kernel.task.resource \
	embox.kernel.task.resource.errno \
	embox.kernel.task.resource.idesc_table \
	embox.kernel.task.resource.idesc_table.idesc_table_size \
	embox.kernel.task.resource.module_ptr \
	embox.kernel.task.resource.vfs \
	embox.kernel.task.resource.security \
	embox.kernel.task.resource.security.security_size \
	embox.kernel.task.resource.sig_table \
	embox.kernel.task.resource.sig_table.sig_table_size \
	embox.kernel.task.resource.thread_key_table
.obj1@6367ca52.exports.embox.kernel.task.resource := \
	.obj98@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.errno := \
	.obj10@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.idesc_table := \
	.obj37@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.idesc_table.idesc_table_size := \
	.obj18@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.module_ptr := \
	.obj40@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.vfs := \
	.obj43@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.security := \
	.obj59@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.security.security_size := \
	.obj44@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.sig_table := \
	.obj75@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.sig_table.sig_table_size := \
	.obj60@6367ca52
.obj1@6367ca52.exports.embox.kernel.task.resource.thread_key_table := \
	.obj97@6367ca52

# .obj98@6367ca52
.obj98@6367ca52 := MyFileContentRoot
.obj98@6367ca52.__eContents := \
	types/.obj10@6367ca52 \
	types/.obj37@6367ca52 \
	types/.obj40@6367ca52 \
	types/.obj43@6367ca52 \
	types/.obj59@6367ca52 \
	types/.obj75@6367ca52 \
	types/.obj97@6367ca52
.obj98@6367ca52.__eContainer := .obj1@6367ca52
.obj98@6367ca52.imports := 
.obj98@6367ca52.name := embox.kernel.task.resource
.obj98@6367ca52.origin := 

# .obj10@6367ca52
.obj10@6367ca52 := MyModuleType
.obj10@6367ca52.__eContents := \
	sourcesMembers/.obj3@6367ca52 \
	dependsMembers/.obj5@6367ca52 \
	dependsMembers/.obj9@6367ca52
.obj10@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj10@6367ca52.dependent := 
.obj10@6367ca52.subTypes := 
.obj10@6367ca52.modifiers := 
.obj10@6367ca52.name := errno
.obj10@6367ca52.origin := 3:8
.obj10@6367ca52.superType := 
.obj10@6367ca52.customStorage := 

# .obj3@6367ca52
.obj3@6367ca52 := MySourceMember
.obj3@6367ca52.__eContents := \
	files/.obj2@6367ca52
.obj3@6367ca52.__eContainer := /sourcesMembers.obj10@6367ca52
.obj3@6367ca52.module := 

# .obj2@6367ca52
.obj2@6367ca52 := MyFileName
.obj2@6367ca52.__eContents := 
.obj2@6367ca52.__eContainer := /files.obj3@6367ca52
.obj2@6367ca52.fileName := errno.c

# .obj5@6367ca52
.obj5@6367ca52 := MyDependsMember
.obj5@6367ca52.__eContents := 
.obj5@6367ca52.__eContainer := /dependsMembers.obj10@6367ca52
.obj5@6367ca52.modules := \
	.obj4@6367ca52./
.obj5@6367ca52.module := 

# .obj4@6367ca52
.obj4@6367ca52 := ELink
.obj4@6367ca52.eSource := MyFile_DependsMember_modules.obj5@6367ca52
.obj4@6367ca52.eTarget := 
.obj4@6367ca52.name := embox.kernel.task.task_resource
.obj4@6367ca52.origin := 6:10

# .obj9@6367ca52
.obj9@6367ca52 := MyDependsMember
.obj9@6367ca52.__eContents := \
	annotations/.obj7@6367ca52
.obj9@6367ca52.__eContainer := /dependsMembers.obj10@6367ca52
.obj9@6367ca52.modules := \
	.obj8@6367ca52./
.obj9@6367ca52.module := 

# .obj7@6367ca52
.obj7@6367ca52 := MyAnnotation
.obj7@6367ca52.__eContents := 
.obj7@6367ca52.__eContainer := target/annotations.obj9@6367ca52
.obj7@6367ca52.type := .obj6@6367ca52./

# .obj6@6367ca52
.obj6@6367ca52 := ELink
.obj6@6367ca52.eSource := MyFile_Annotation_type.obj7@6367ca52
.obj6@6367ca52.eTarget := 
.obj6@6367ca52.name := NoRuntime
.obj6@6367ca52.origin := 7:3

# .obj8@6367ca52
.obj8@6367ca52 := ELink
.obj8@6367ca52.eSource := MyFile_DependsMember_modules.obj9@6367ca52
.obj8@6367ca52.eTarget := 
.obj8@6367ca52.name := embox.compat.libc.assert
.obj8@6367ca52.origin := 7:21

# .obj37@6367ca52
.obj37@6367ca52 := MyModuleType
.obj37@6367ca52.__eContents := \
	sourcesMembers/.obj17@6367ca52 \
	sourcesMembers/.obj22@6367ca52 \
	optionsMembers/.obj20@6367ca52 \
	dependsMembers/.obj26@6367ca52 \
	dependsMembers/.obj28@6367ca52 \
	dependsMembers/.obj32@6367ca52 \
	dependsMembers/.obj36@6367ca52
.obj37@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj37@6367ca52.dependent := 
.obj37@6367ca52.subTypes := 
.obj37@6367ca52.modifiers := 
.obj37@6367ca52.name := idesc_table
.obj37@6367ca52.origin := 10:8
.obj37@6367ca52.superType := 
.obj37@6367ca52.customStorage := 

# .obj17@6367ca52
.obj17@6367ca52 := MySourceMember
.obj17@6367ca52.__eContents := \
	files/.obj16@6367ca52 \
	annotations/.obj15@6367ca52
.obj17@6367ca52.__eContainer := /sourcesMembers.obj37@6367ca52
.obj17@6367ca52.module := 

# .obj16@6367ca52
.obj16@6367ca52 := MyFileName
.obj16@6367ca52.__eContents := 
.obj16@6367ca52.__eContainer := /files.obj17@6367ca52
.obj16@6367ca52.fileName := idesc_table.h

# .obj15@6367ca52
.obj15@6367ca52 := MyAnnotation
.obj15@6367ca52.__eContents := \
	bindings/.obj14@6367ca52
.obj15@6367ca52.__eContainer := target/annotations.obj17@6367ca52
.obj15@6367ca52.type := .obj11@6367ca52./

# .obj14@6367ca52
.obj14@6367ca52 := MyOptionBinding
.obj14@6367ca52.__eContents := \
	value/.obj13@6367ca52
.obj14@6367ca52.__eContainer := /bindings.obj15@6367ca52
.obj14@6367ca52.option := .obj12@6367ca52./

# .obj13@6367ca52
.obj13@6367ca52 := MyStringLiteral
.obj13@6367ca52.__eContents := 
.obj13@6367ca52.__eContainer := /value.obj14@6367ca52
.obj13@6367ca52.value := kernel/task/resource

# .obj12@6367ca52
.obj12@6367ca52 := ELink
.obj12@6367ca52.eSource := MyFile_OptionBinding_option.obj14@6367ca52
.obj12@6367ca52.eTarget := 
.obj12@6367ca52.name := path
.obj12@6367ca52.origin := 11:17

# .obj11@6367ca52
.obj11@6367ca52 := ELink
.obj11@6367ca52.eSource := MyFile_Annotation_type.obj15@6367ca52
.obj11@6367ca52.eTarget := 
.obj11@6367ca52.name := IncludeExport
.obj11@6367ca52.origin := 11:3

# .obj22@6367ca52
.obj22@6367ca52 := MySourceMember
.obj22@6367ca52.__eContents := \
	files/.obj21@6367ca52
.obj22@6367ca52.__eContainer := /sourcesMembers.obj37@6367ca52
.obj22@6367ca52.module := 

# .obj21@6367ca52
.obj21@6367ca52 := MyFileName
.obj21@6367ca52.__eContents := 
.obj21@6367ca52.__eContainer := /files.obj22@6367ca52
.obj21@6367ca52.fileName := idesc_table.c

# .obj20@6367ca52
.obj20@6367ca52 := MyOptionMember
.obj20@6367ca52.__eContents := \
	options/.obj18@6367ca52
.obj20@6367ca52.__eContainer := /optionsMembers.obj37@6367ca52
.obj20@6367ca52.module := 

# .obj18@6367ca52
.obj18@6367ca52 := MyNumberOption
.obj18@6367ca52.__eContents := \
	defaultValue/.obj19@6367ca52
.obj18@6367ca52.__eContainer := /options.obj20@6367ca52
.obj18@6367ca52.name := idesc_table_size
.obj18@6367ca52.origin := 

# .obj19@6367ca52
.obj19@6367ca52 := MyNumberLiteral
.obj19@6367ca52.__eContents := 
.obj19@6367ca52.__eContainer := /defaultValue.obj18@6367ca52
.obj19@6367ca52.value := 64

# .obj26@6367ca52
.obj26@6367ca52 := MyDependsMember
.obj26@6367ca52.__eContents := \
	annotations/.obj24@6367ca52
.obj26@6367ca52.__eContainer := /dependsMembers.obj37@6367ca52
.obj26@6367ca52.modules := \
	.obj25@6367ca52./
.obj26@6367ca52.module := 

# .obj24@6367ca52
.obj24@6367ca52 := MyAnnotation
.obj24@6367ca52.__eContents := 
.obj24@6367ca52.__eContainer := target/annotations.obj26@6367ca52
.obj24@6367ca52.type := .obj23@6367ca52./

# .obj23@6367ca52
.obj23@6367ca52 := ELink
.obj23@6367ca52.eSource := MyFile_Annotation_type.obj24@6367ca52
.obj23@6367ca52.eTarget := 
.obj23@6367ca52.name := NoRuntime
.obj23@6367ca52.origin := 17:3

# .obj25@6367ca52
.obj25@6367ca52 := ELink
.obj25@6367ca52.eSource := MyFile_DependsMember_modules.obj26@6367ca52
.obj25@6367ca52.eTarget := 
.obj25@6367ca52.name := embox.fs.idesc
.obj25@6367ca52.origin := 17:21

# .obj28@6367ca52
.obj28@6367ca52 := MyDependsMember
.obj28@6367ca52.__eContents := 
.obj28@6367ca52.__eContainer := /dependsMembers.obj37@6367ca52
.obj28@6367ca52.modules := \
	.obj27@6367ca52./
.obj28@6367ca52.module := 

# .obj27@6367ca52
.obj27@6367ca52 := ELink
.obj27@6367ca52.eSource := MyFile_DependsMember_modules.obj28@6367ca52
.obj27@6367ca52.eTarget := 
.obj27@6367ca52.name := embox.kernel.task.task_resource
.obj27@6367ca52.origin := 18:10

# .obj32@6367ca52
.obj32@6367ca52 := MyDependsMember
.obj32@6367ca52.__eContents := \
	annotations/.obj30@6367ca52
.obj32@6367ca52.__eContainer := /dependsMembers.obj37@6367ca52
.obj32@6367ca52.modules := \
	.obj31@6367ca52./
.obj32@6367ca52.module := 

# .obj30@6367ca52
.obj30@6367ca52 := MyAnnotation
.obj30@6367ca52.__eContents := 
.obj30@6367ca52.__eContainer := target/annotations.obj32@6367ca52
.obj30@6367ca52.type := .obj29@6367ca52./

# .obj29@6367ca52
.obj29@6367ca52 := ELink
.obj29@6367ca52.eSource := MyFile_Annotation_type.obj30@6367ca52
.obj29@6367ca52.eTarget := 
.obj29@6367ca52.name := NoRuntime
.obj29@6367ca52.origin := 19:3

# .obj31@6367ca52
.obj31@6367ca52 := ELink
.obj31@6367ca52.eSource := MyFile_DependsMember_modules.obj32@6367ca52
.obj31@6367ca52.eTarget := 
.obj31@6367ca52.name := embox.kernel.task.idesc
.obj31@6367ca52.origin := 19:21

# .obj36@6367ca52
.obj36@6367ca52 := MyDependsMember
.obj36@6367ca52.__eContents := \
	annotations/.obj34@6367ca52
.obj36@6367ca52.__eContainer := /dependsMembers.obj37@6367ca52
.obj36@6367ca52.modules := \
	.obj35@6367ca52./
.obj36@6367ca52.module := 

# .obj34@6367ca52
.obj34@6367ca52 := MyAnnotation
.obj34@6367ca52.__eContents := 
.obj34@6367ca52.__eContainer := target/annotations.obj36@6367ca52
.obj34@6367ca52.type := .obj33@6367ca52./

# .obj33@6367ca52
.obj33@6367ca52 := ELink
.obj33@6367ca52.eSource := MyFile_Annotation_type.obj34@6367ca52
.obj33@6367ca52.eTarget := 
.obj33@6367ca52.name := NoRuntime
.obj33@6367ca52.origin := 20:3

# .obj35@6367ca52
.obj35@6367ca52 := ELink
.obj35@6367ca52.eSource := MyFile_DependsMember_modules.obj36@6367ca52
.obj35@6367ca52.eTarget := 
.obj35@6367ca52.name := embox.compat.libc.assert
.obj35@6367ca52.origin := 20:21

# .obj40@6367ca52
.obj40@6367ca52 := MyModuleType
.obj40@6367ca52.__eContents := \
	sourcesMembers/.obj39@6367ca52
.obj40@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj40@6367ca52.dependent := 
.obj40@6367ca52.subTypes := 
.obj40@6367ca52.modifiers := 
.obj40@6367ca52.name := module_ptr
.obj40@6367ca52.origin := 23:8
.obj40@6367ca52.superType := 
.obj40@6367ca52.customStorage := 

# .obj39@6367ca52
.obj39@6367ca52 := MySourceMember
.obj39@6367ca52.__eContents := \
	files/.obj38@6367ca52
.obj39@6367ca52.__eContainer := /sourcesMembers.obj40@6367ca52
.obj39@6367ca52.module := 

# .obj38@6367ca52
.obj38@6367ca52 := MyFileName
.obj38@6367ca52.__eContents := 
.obj38@6367ca52.__eContainer := /files.obj39@6367ca52
.obj38@6367ca52.fileName := module_ptr.c

# .obj43@6367ca52
.obj43@6367ca52 := MyModuleType
.obj43@6367ca52.__eContents := \
	sourcesMembers/.obj42@6367ca52
.obj43@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj43@6367ca52.dependent := 
.obj43@6367ca52.subTypes := 
.obj43@6367ca52.modifiers := 
.obj43@6367ca52.name := vfs
.obj43@6367ca52.origin := 27:8
.obj43@6367ca52.superType := 
.obj43@6367ca52.customStorage := 

# .obj42@6367ca52
.obj42@6367ca52 := MySourceMember
.obj42@6367ca52.__eContents := \
	files/.obj41@6367ca52
.obj42@6367ca52.__eContainer := /sourcesMembers.obj43@6367ca52
.obj42@6367ca52.module := 

# .obj41@6367ca52
.obj41@6367ca52 := MyFileName
.obj41@6367ca52.__eContents := 
.obj41@6367ca52.__eContainer := /files.obj42@6367ca52
.obj41@6367ca52.fileName := vfs.c

# .obj59@6367ca52
.obj59@6367ca52 := MyModuleType
.obj59@6367ca52.__eContents := \
	sourcesMembers/.obj48@6367ca52 \
	optionsMembers/.obj46@6367ca52 \
	dependsMembers/.obj50@6367ca52 \
	dependsMembers/.obj54@6367ca52 \
	dependsMembers/.obj58@6367ca52
.obj59@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj59@6367ca52.dependent := 
.obj59@6367ca52.subTypes := 
.obj59@6367ca52.modifiers := 
.obj59@6367ca52.name := security
.obj59@6367ca52.origin := 31:8
.obj59@6367ca52.superType := 
.obj59@6367ca52.customStorage := 

# .obj48@6367ca52
.obj48@6367ca52 := MySourceMember
.obj48@6367ca52.__eContents := \
	files/.obj47@6367ca52
.obj48@6367ca52.__eContainer := /sourcesMembers.obj59@6367ca52
.obj48@6367ca52.module := 

# .obj47@6367ca52
.obj47@6367ca52 := MyFileName
.obj47@6367ca52.__eContents := 
.obj47@6367ca52.__eContainer := /files.obj48@6367ca52
.obj47@6367ca52.fileName := security.c

# .obj46@6367ca52
.obj46@6367ca52 := MyOptionMember
.obj46@6367ca52.__eContents := \
	options/.obj44@6367ca52
.obj46@6367ca52.__eContainer := /optionsMembers.obj59@6367ca52
.obj46@6367ca52.module := 

# .obj44@6367ca52
.obj44@6367ca52 := MyNumberOption
.obj44@6367ca52.__eContents := \
	defaultValue/.obj45@6367ca52
.obj44@6367ca52.__eContainer := /options.obj46@6367ca52
.obj44@6367ca52.name := security_size
.obj44@6367ca52.origin := 

# .obj45@6367ca52
.obj45@6367ca52 := MyNumberLiteral
.obj45@6367ca52.__eContents := 
.obj45@6367ca52.__eContainer := /defaultValue.obj44@6367ca52
.obj45@6367ca52.value := 32

# .obj50@6367ca52
.obj50@6367ca52 := MyDependsMember
.obj50@6367ca52.__eContents := 
.obj50@6367ca52.__eContainer := /dependsMembers.obj59@6367ca52
.obj50@6367ca52.modules := \
	.obj49@6367ca52./
.obj50@6367ca52.module := 

# .obj49@6367ca52
.obj49@6367ca52 := ELink
.obj49@6367ca52.eSource := MyFile_DependsMember_modules.obj50@6367ca52
.obj49@6367ca52.eTarget := 
.obj49@6367ca52.name := embox.kernel.task.task_resource
.obj49@6367ca52.origin := 35:10

# .obj54@6367ca52
.obj54@6367ca52 := MyDependsMember
.obj54@6367ca52.__eContents := \
	annotations/.obj52@6367ca52
.obj54@6367ca52.__eContainer := /dependsMembers.obj59@6367ca52
.obj54@6367ca52.modules := \
	.obj53@6367ca52./
.obj54@6367ca52.module := 

# .obj52@6367ca52
.obj52@6367ca52 := MyAnnotation
.obj52@6367ca52.__eContents := 
.obj52@6367ca52.__eContainer := target/annotations.obj54@6367ca52
.obj52@6367ca52.type := .obj51@6367ca52./

# .obj51@6367ca52
.obj51@6367ca52 := ELink
.obj51@6367ca52.eSource := MyFile_Annotation_type.obj52@6367ca52
.obj51@6367ca52.eTarget := 
.obj51@6367ca52.name := NoRuntime
.obj51@6367ca52.origin := 36:3

# .obj53@6367ca52
.obj53@6367ca52 := ELink
.obj53@6367ca52.eSource := MyFile_DependsMember_modules.obj54@6367ca52
.obj53@6367ca52.eTarget := 
.obj53@6367ca52.name := embox.compat.libc.assert
.obj53@6367ca52.origin := 36:21

# .obj58@6367ca52
.obj58@6367ca52 := MyDependsMember
.obj58@6367ca52.__eContents := \
	annotations/.obj56@6367ca52
.obj58@6367ca52.__eContainer := /dependsMembers.obj59@6367ca52
.obj58@6367ca52.modules := \
	.obj57@6367ca52./
.obj58@6367ca52.module := 

# .obj56@6367ca52
.obj56@6367ca52 := MyAnnotation
.obj56@6367ca52.__eContents := 
.obj56@6367ca52.__eContainer := target/annotations.obj58@6367ca52
.obj56@6367ca52.type := .obj55@6367ca52./

# .obj55@6367ca52
.obj55@6367ca52 := ELink
.obj55@6367ca52.eSource := MyFile_Annotation_type.obj56@6367ca52
.obj55@6367ca52.eTarget := 
.obj55@6367ca52.name := NoRuntime
.obj55@6367ca52.origin := 37:3

# .obj57@6367ca52
.obj57@6367ca52 := ELink
.obj57@6367ca52.eSource := MyFile_DependsMember_modules.obj58@6367ca52
.obj57@6367ca52.eTarget := 
.obj57@6367ca52.name := embox.compat.libc.str
.obj57@6367ca52.origin := 37:21

# .obj75@6367ca52
.obj75@6367ca52 := MyModuleType
.obj75@6367ca52.__eContents := \
	sourcesMembers/.obj64@6367ca52 \
	optionsMembers/.obj62@6367ca52 \
	dependsMembers/.obj66@6367ca52 \
	dependsMembers/.obj70@6367ca52 \
	dependsMembers/.obj74@6367ca52
.obj75@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj75@6367ca52.dependent := 
.obj75@6367ca52.subTypes := 
.obj75@6367ca52.modifiers := 
.obj75@6367ca52.name := sig_table
.obj75@6367ca52.origin := 40:8
.obj75@6367ca52.superType := 
.obj75@6367ca52.customStorage := 

# .obj64@6367ca52
.obj64@6367ca52 := MySourceMember
.obj64@6367ca52.__eContents := \
	files/.obj63@6367ca52
.obj64@6367ca52.__eContainer := /sourcesMembers.obj75@6367ca52
.obj64@6367ca52.module := 

# .obj63@6367ca52
.obj63@6367ca52 := MyFileName
.obj63@6367ca52.__eContents := 
.obj63@6367ca52.__eContainer := /files.obj64@6367ca52
.obj63@6367ca52.fileName := sig_table.c

# .obj62@6367ca52
.obj62@6367ca52 := MyOptionMember
.obj62@6367ca52.__eContents := \
	options/.obj60@6367ca52
.obj62@6367ca52.__eContainer := /optionsMembers.obj75@6367ca52
.obj62@6367ca52.module := 

# .obj60@6367ca52
.obj60@6367ca52 := MyNumberOption
.obj60@6367ca52.__eContents := \
	defaultValue/.obj61@6367ca52
.obj60@6367ca52.__eContainer := /options.obj62@6367ca52
.obj60@6367ca52.name := sig_table_size
.obj60@6367ca52.origin := 

# .obj61@6367ca52
.obj61@6367ca52 := MyNumberLiteral
.obj61@6367ca52.__eContents := 
.obj61@6367ca52.__eContainer := /defaultValue.obj60@6367ca52
.obj61@6367ca52.value := 64

# .obj66@6367ca52
.obj66@6367ca52 := MyDependsMember
.obj66@6367ca52.__eContents := 
.obj66@6367ca52.__eContainer := /dependsMembers.obj75@6367ca52
.obj66@6367ca52.modules := \
	.obj65@6367ca52./
.obj66@6367ca52.module := 

# .obj65@6367ca52
.obj65@6367ca52 := ELink
.obj65@6367ca52.eSource := MyFile_DependsMember_modules.obj66@6367ca52
.obj65@6367ca52.eTarget := 
.obj65@6367ca52.name := embox.kernel.task.task_resource
.obj65@6367ca52.origin := 45:10

# .obj70@6367ca52
.obj70@6367ca52 := MyDependsMember
.obj70@6367ca52.__eContents := \
	annotations/.obj68@6367ca52
.obj70@6367ca52.__eContainer := /dependsMembers.obj75@6367ca52
.obj70@6367ca52.modules := \
	.obj69@6367ca52./
.obj70@6367ca52.module := 

# .obj68@6367ca52
.obj68@6367ca52 := MyAnnotation
.obj68@6367ca52.__eContents := 
.obj68@6367ca52.__eContainer := target/annotations.obj70@6367ca52
.obj68@6367ca52.type := .obj67@6367ca52./

# .obj67@6367ca52
.obj67@6367ca52 := ELink
.obj67@6367ca52.eSource := MyFile_Annotation_type.obj68@6367ca52
.obj67@6367ca52.eTarget := 
.obj67@6367ca52.name := NoRuntime
.obj67@6367ca52.origin := 46:3

# .obj69@6367ca52
.obj69@6367ca52 := ELink
.obj69@6367ca52.eSource := MyFile_DependsMember_modules.obj70@6367ca52
.obj69@6367ca52.eTarget := 
.obj69@6367ca52.name := embox.compat.libc.assert
.obj69@6367ca52.origin := 46:21

# .obj74@6367ca52
.obj74@6367ca52 := MyDependsMember
.obj74@6367ca52.__eContents := \
	annotations/.obj72@6367ca52
.obj74@6367ca52.__eContainer := /dependsMembers.obj75@6367ca52
.obj74@6367ca52.modules := \
	.obj73@6367ca52./
.obj74@6367ca52.module := 

# .obj72@6367ca52
.obj72@6367ca52 := MyAnnotation
.obj72@6367ca52.__eContents := 
.obj72@6367ca52.__eContainer := target/annotations.obj74@6367ca52
.obj72@6367ca52.type := .obj71@6367ca52./

# .obj71@6367ca52
.obj71@6367ca52 := ELink
.obj71@6367ca52.eSource := MyFile_Annotation_type.obj72@6367ca52
.obj71@6367ca52.eTarget := 
.obj71@6367ca52.name := NoRuntime
.obj71@6367ca52.origin := 47:3

# .obj73@6367ca52
.obj73@6367ca52 := ELink
.obj73@6367ca52.eSource := MyFile_DependsMember_modules.obj74@6367ca52
.obj73@6367ca52.eTarget := 
.obj73@6367ca52.name := embox.compat.libc.str
.obj73@6367ca52.origin := 47:21

# .obj97@6367ca52
.obj97@6367ca52 := MyModuleType
.obj97@6367ca52.__eContents := \
	sourcesMembers/.obj78@6367ca52 \
	dependsMembers/.obj80@6367ca52 \
	dependsMembers/.obj84@6367ca52 \
	dependsMembers/.obj88@6367ca52 \
	dependsMembers/.obj92@6367ca52 \
	dependsMembers/.obj96@6367ca52
.obj97@6367ca52.__eContainer := fileContentRoot/types.obj98@6367ca52
.obj97@6367ca52.dependent := 
.obj97@6367ca52.subTypes := 
.obj97@6367ca52.modifiers := 
.obj97@6367ca52.name := thread_key_table
.obj97@6367ca52.origin := 50:8
.obj97@6367ca52.superType := 
.obj97@6367ca52.customStorage := 

# .obj78@6367ca52
.obj78@6367ca52 := MySourceMember
.obj78@6367ca52.__eContents := \
	files/.obj76@6367ca52 \
	files/.obj77@6367ca52
.obj78@6367ca52.__eContainer := /sourcesMembers.obj97@6367ca52
.obj78@6367ca52.module := 

# .obj76@6367ca52
.obj76@6367ca52 := MyFileName
.obj76@6367ca52.__eContents := 
.obj76@6367ca52.__eContainer := /files.obj78@6367ca52
.obj76@6367ca52.fileName := thread_key_table.c

# .obj77@6367ca52
.obj77@6367ca52 := MyFileName
.obj77@6367ca52.__eContents := 
.obj77@6367ca52.__eContainer := /files.obj78@6367ca52
.obj77@6367ca52.fileName := thread_key_table.h

# .obj80@6367ca52
.obj80@6367ca52 := MyDependsMember
.obj80@6367ca52.__eContents := 
.obj80@6367ca52.__eContainer := /dependsMembers.obj97@6367ca52
.obj80@6367ca52.modules := \
	.obj79@6367ca52./
.obj80@6367ca52.module := 

# .obj79@6367ca52
.obj79@6367ca52 := ELink
.obj79@6367ca52.eSource := MyFile_DependsMember_modules.obj80@6367ca52
.obj79@6367ca52.eTarget := 
.obj79@6367ca52.name := embox.kernel.task.task_resource
.obj79@6367ca52.origin := 53:10

# .obj84@6367ca52
.obj84@6367ca52 := MyDependsMember
.obj84@6367ca52.__eContents := \
	annotations/.obj82@6367ca52
.obj84@6367ca52.__eContainer := /dependsMembers.obj97@6367ca52
.obj84@6367ca52.modules := \
	.obj83@6367ca52./
.obj84@6367ca52.module := 

# .obj82@6367ca52
.obj82@6367ca52 := MyAnnotation
.obj82@6367ca52.__eContents := 
.obj82@6367ca52.__eContainer := target/annotations.obj84@6367ca52
.obj82@6367ca52.type := .obj81@6367ca52./

# .obj81@6367ca52
.obj81@6367ca52 := ELink
.obj81@6367ca52.eSource := MyFile_Annotation_type.obj82@6367ca52
.obj81@6367ca52.eTarget := 
.obj81@6367ca52.name := NoRuntime
.obj81@6367ca52.origin := 54:3

# .obj83@6367ca52
.obj83@6367ca52 := ELink
.obj83@6367ca52.eSource := MyFile_DependsMember_modules.obj84@6367ca52
.obj83@6367ca52.eTarget := 
.obj83@6367ca52.name := embox.kernel.thread.mutex
.obj83@6367ca52.origin := 54:21

# .obj88@6367ca52
.obj88@6367ca52 := MyDependsMember
.obj88@6367ca52.__eContents := \
	annotations/.obj86@6367ca52
.obj88@6367ca52.__eContainer := /dependsMembers.obj97@6367ca52
.obj88@6367ca52.modules := \
	.obj87@6367ca52./
.obj88@6367ca52.module := 

# .obj86@6367ca52
.obj86@6367ca52 := MyAnnotation
.obj86@6367ca52.__eContents := 
.obj86@6367ca52.__eContainer := target/annotations.obj88@6367ca52
.obj86@6367ca52.type := .obj85@6367ca52./

# .obj85@6367ca52
.obj85@6367ca52 := ELink
.obj85@6367ca52.eSource := MyFile_Annotation_type.obj86@6367ca52
.obj85@6367ca52.eTarget := 
.obj85@6367ca52.name := NoRuntime
.obj85@6367ca52.origin := 55:3

# .obj87@6367ca52
.obj87@6367ca52 := ELink
.obj87@6367ca52.eSource := MyFile_DependsMember_modules.obj88@6367ca52
.obj87@6367ca52.eTarget := 
.obj87@6367ca52.name := embox.kernel.thread.thread_local
.obj87@6367ca52.origin := 55:21

# .obj92@6367ca52
.obj92@6367ca52 := MyDependsMember
.obj92@6367ca52.__eContents := \
	annotations/.obj90@6367ca52
.obj92@6367ca52.__eContainer := /dependsMembers.obj97@6367ca52
.obj92@6367ca52.modules := \
	.obj91@6367ca52./
.obj92@6367ca52.module := 

# .obj90@6367ca52
.obj90@6367ca52 := MyAnnotation
.obj90@6367ca52.__eContents := 
.obj90@6367ca52.__eContainer := target/annotations.obj92@6367ca52
.obj90@6367ca52.type := .obj89@6367ca52./

# .obj89@6367ca52
.obj89@6367ca52 := ELink
.obj89@6367ca52.eSource := MyFile_Annotation_type.obj90@6367ca52
.obj89@6367ca52.eTarget := 
.obj89@6367ca52.name := NoRuntime
.obj89@6367ca52.origin := 56:3

# .obj91@6367ca52
.obj91@6367ca52 := ELink
.obj91@6367ca52.eSource := MyFile_DependsMember_modules.obj92@6367ca52
.obj91@6367ca52.eTarget := 
.obj91@6367ca52.name := embox.compat.libc.assert
.obj91@6367ca52.origin := 56:21

# .obj96@6367ca52
.obj96@6367ca52 := MyDependsMember
.obj96@6367ca52.__eContents := \
	annotations/.obj94@6367ca52
.obj96@6367ca52.__eContainer := /dependsMembers.obj97@6367ca52
.obj96@6367ca52.modules := \
	.obj95@6367ca52./
.obj96@6367ca52.module := 

# .obj94@6367ca52
.obj94@6367ca52 := MyAnnotation
.obj94@6367ca52.__eContents := 
.obj94@6367ca52.__eContainer := target/annotations.obj96@6367ca52
.obj94@6367ca52.type := .obj93@6367ca52./

# .obj93@6367ca52
.obj93@6367ca52 := ELink
.obj93@6367ca52.eSource := MyFile_Annotation_type.obj94@6367ca52
.obj93@6367ca52.eTarget := 
.obj93@6367ca52.name := NoRuntime
.obj93@6367ca52.origin := 57:3

# .obj95@6367ca52
.obj95@6367ca52 := ELink
.obj95@6367ca52.eSource := MyFile_DependsMember_modules.obj96@6367ca52
.obj95@6367ca52.eTarget := 
.obj95@6367ca52.name := embox.util.indexator
.obj95@6367ca52.origin := 57:21


__resource-mk/.cache/mybuild/files/src/kernel/task/resource/Mybuild.mk := .obj1@6367ca52
