# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@5a28b551

# .obj1@5a28b551
.obj1@5a28b551 := MyFileResource
.obj1@5a28b551.issues := 
.obj1@5a28b551.contentsRoot := .obj73@5a28b551
.obj1@5a28b551.resourceSet := 
.obj1@5a28b551.fileName := src/fs/driver/jffs2/Mybuild
.obj1@5a28b551.exports := \
	embox.fs.driver \
	embox.fs.driver.jffs2 \
	embox.fs.driver.jffs2.inode_quantity \
	embox.fs.driver.jffs2.jffs2_descriptor_quantity
.obj1@5a28b551.exports.embox.fs.driver := \
	.obj73@5a28b551
.obj1@5a28b551.exports.embox.fs.driver.jffs2 := \
	.obj72@5a28b551
.obj1@5a28b551.exports.embox.fs.driver.jffs2.inode_quantity := \
	.obj49@5a28b551
.obj1@5a28b551.exports.embox.fs.driver.jffs2.jffs2_descriptor_quantity := \
	.obj52@5a28b551

# .obj73@5a28b551
.obj73@5a28b551 := MyFileContentRoot
.obj73@5a28b551.__eContents := \
	types/.obj72@5a28b551
.obj73@5a28b551.__eContainer := .obj1@5a28b551
.obj73@5a28b551.imports := 
.obj73@5a28b551.name := embox.fs.driver
.obj73@5a28b551.origin := 

# .obj72@5a28b551
.obj72@5a28b551 := MyModuleType
.obj72@5a28b551.__eContents := \
	sourcesMembers/.obj22@5a28b551 \
	sourcesMembers/.obj34@5a28b551 \
	sourcesMembers/.obj40@5a28b551 \
	sourcesMembers/.obj48@5a28b551 \
	optionsMembers/.obj51@5a28b551 \
	optionsMembers/.obj54@5a28b551 \
	dependsMembers/.obj57@5a28b551 \
	dependsMembers/.obj59@5a28b551 \
	dependsMembers/.obj61@5a28b551 \
	dependsMembers/.obj63@5a28b551 \
	dependsMembers/.obj65@5a28b551 \
	dependsMembers/.obj67@5a28b551 \
	dependsMembers/.obj69@5a28b551 \
	dependsMembers/.obj71@5a28b551 \
	annotations/.obj9@5a28b551 \
	annotations/.obj15@5a28b551
.obj72@5a28b551.__eContainer := fileContentRoot/types.obj73@5a28b551
.obj72@5a28b551.dependent := 
.obj72@5a28b551.subTypes := 
.obj72@5a28b551.modifiers := 
.obj72@5a28b551.name := jffs2
.obj72@5a28b551.origin := 5:8
.obj72@5a28b551.superType := 
.obj72@5a28b551.customStorage := 

# .obj22@5a28b551
.obj22@5a28b551 := MySourceMember
.obj22@5a28b551.__eContents := \
	files/.obj21@5a28b551 \
	annotations/.obj20@5a28b551
.obj22@5a28b551.__eContainer := /sourcesMembers.obj72@5a28b551
.obj22@5a28b551.module := 

# .obj21@5a28b551
.obj21@5a28b551 := MyFileName
.obj21@5a28b551.__eContents := 
.obj21@5a28b551.__eContainer := /files.obj22@5a28b551
.obj21@5a28b551.fileName := jffs2.h

# .obj20@5a28b551
.obj20@5a28b551 := MyAnnotation
.obj20@5a28b551.__eContents := \
	bindings/.obj19@5a28b551
.obj20@5a28b551.__eContainer := target/annotations.obj22@5a28b551
.obj20@5a28b551.type := .obj16@5a28b551./

# .obj19@5a28b551
.obj19@5a28b551 := MyOptionBinding
.obj19@5a28b551.__eContents := \
	value/.obj18@5a28b551
.obj19@5a28b551.__eContainer := /bindings.obj20@5a28b551
.obj19@5a28b551.option := .obj17@5a28b551./

# .obj18@5a28b551
.obj18@5a28b551 := MyStringLiteral
.obj18@5a28b551.__eContents := 
.obj18@5a28b551.__eContainer := /value.obj19@5a28b551
.obj18@5a28b551.value := fs

# .obj17@5a28b551
.obj17@5a28b551 := ELink
.obj17@5a28b551.eSource := MyFile_OptionBinding_option.obj19@5a28b551
.obj17@5a28b551.eTarget := 
.obj17@5a28b551.name := path
.obj17@5a28b551.origin := 6:17

# .obj16@5a28b551
.obj16@5a28b551 := ELink
.obj16@5a28b551.eSource := MyFile_Annotation_type.obj20@5a28b551
.obj16@5a28b551.eTarget := 
.obj16@5a28b551.name := IncludeExport
.obj16@5a28b551.origin := 6:3

# .obj34@5a28b551
.obj34@5a28b551 := MySourceMember
.obj34@5a28b551.__eContents := \
	files/.obj28@5a28b551 \
	files/.obj29@5a28b551 \
	files/.obj30@5a28b551 \
	files/.obj31@5a28b551 \
	files/.obj32@5a28b551 \
	files/.obj33@5a28b551 \
	annotations/.obj27@5a28b551
.obj34@5a28b551.__eContainer := /sourcesMembers.obj72@5a28b551
.obj34@5a28b551.module := 

# .obj28@5a28b551
.obj28@5a28b551 := MyFileName
.obj28@5a28b551.__eContents := 
.obj28@5a28b551.__eContainer := /files.obj34@5a28b551
.obj28@5a28b551.fileName := build.c

# .obj29@5a28b551
.obj29@5a28b551 := MyFileName
.obj29@5a28b551.__eContents := 
.obj29@5a28b551.__eContainer := /files.obj34@5a28b551
.obj29@5a28b551.fileName := compr_rtime.c

# .obj30@5a28b551
.obj30@5a28b551 := MyFileName
.obj30@5a28b551.__eContents := 
.obj30@5a28b551.__eContainer := /files.obj34@5a28b551
.obj30@5a28b551.fileName := compr_rubin.c

# .obj31@5a28b551
.obj31@5a28b551 := MyFileName
.obj31@5a28b551.__eContents := 
.obj31@5a28b551.__eContainer := /files.obj34@5a28b551
.obj31@5a28b551.fileName := compr_zlib.c

# .obj32@5a28b551
.obj32@5a28b551 := MyFileName
.obj32@5a28b551.__eContents := 
.obj32@5a28b551.__eContainer := /files.obj34@5a28b551
.obj32@5a28b551.fileName := compr.c

# .obj33@5a28b551
.obj33@5a28b551 := MyFileName
.obj33@5a28b551.__eContents := 
.obj33@5a28b551.__eContainer := /files.obj34@5a28b551
.obj33@5a28b551.fileName := debug.c

# .obj27@5a28b551
.obj27@5a28b551 := MyAnnotation
.obj27@5a28b551.__eContents := \
	bindings/.obj25@5a28b551
.obj27@5a28b551.__eContainer := target/annotations.obj34@5a28b551
.obj27@5a28b551.type := .obj23@5a28b551./

# .obj25@5a28b551
.obj25@5a28b551 := MyOptionBinding
.obj25@5a28b551.__eContents := \
	value/.obj24@5a28b551
.obj25@5a28b551.__eContainer := /bindings.obj27@5a28b551
.obj25@5a28b551.option := .obj26@5a28b551./

# .obj24@5a28b551
.obj24@5a28b551 := MyStringLiteral
.obj24@5a28b551.__eContents := 
.obj24@5a28b551.__eContainer := /value.obj25@5a28b551
.obj24@5a28b551.value := $$(EXTERNAL_BUILD_DIR)/third_party/zlib/libs/zlib-1.2.8

# .obj26@5a28b551
.obj26@5a28b551 := ELink
.obj26@5a28b551.eSource := MyFile_OptionBinding_option.obj25@5a28b551
.obj26@5a28b551.eTarget := 
.obj26@5a28b551.name := value
.obj26@5a28b551.origin := 9:14

# .obj23@5a28b551
.obj23@5a28b551 := ELink
.obj23@5a28b551.eSource := MyFile_Annotation_type.obj27@5a28b551
.obj23@5a28b551.eTarget := 
.obj23@5a28b551.name := IncludePath
.obj23@5a28b551.origin := 9:3

# .obj40@5a28b551
.obj40@5a28b551 := MySourceMember
.obj40@5a28b551.__eContents := \
	files/.obj35@5a28b551 \
	files/.obj36@5a28b551 \
	files/.obj37@5a28b551 \
	files/.obj38@5a28b551 \
	files/.obj39@5a28b551
.obj40@5a28b551.__eContainer := /sourcesMembers.obj72@5a28b551
.obj40@5a28b551.module := 

# .obj35@5a28b551
.obj35@5a28b551 := MyFileName
.obj35@5a28b551.__eContents := 
.obj35@5a28b551.__eContainer := /files.obj40@5a28b551
.obj35@5a28b551.fileName := dir.c

# .obj36@5a28b551
.obj36@5a28b551 := MyFileName
.obj36@5a28b551.__eContents := 
.obj36@5a28b551.__eContainer := /files.obj40@5a28b551
.obj36@5a28b551.fileName := erase.c

# .obj37@5a28b551
.obj37@5a28b551 := MyFileName
.obj37@5a28b551.__eContents := 
.obj37@5a28b551.__eContainer := /files.obj40@5a28b551
.obj37@5a28b551.fileName := gc.c

# .obj38@5a28b551
.obj38@5a28b551 := MyFileName
.obj38@5a28b551.__eContents := 
.obj38@5a28b551.__eContainer := /files.obj40@5a28b551
.obj38@5a28b551.fileName := scan.c

# .obj39@5a28b551
.obj39@5a28b551 := MyFileName
.obj39@5a28b551.__eContents := 
.obj39@5a28b551.__eContainer := /files.obj40@5a28b551
.obj39@5a28b551.fileName := jffs2.c

# .obj48@5a28b551
.obj48@5a28b551 := MySourceMember
.obj48@5a28b551.__eContents := \
	files/.obj41@5a28b551 \
	files/.obj42@5a28b551 \
	files/.obj43@5a28b551 \
	files/.obj44@5a28b551 \
	files/.obj45@5a28b551 \
	files/.obj46@5a28b551 \
	files/.obj47@5a28b551
.obj48@5a28b551.__eContainer := /sourcesMembers.obj72@5a28b551
.obj48@5a28b551.module := 

# .obj41@5a28b551
.obj41@5a28b551 := MyFileName
.obj41@5a28b551.__eContents := 
.obj41@5a28b551.__eContainer := /files.obj48@5a28b551
.obj41@5a28b551.fileName := read.c

# .obj42@5a28b551
.obj42@5a28b551 := MyFileName
.obj42@5a28b551.__eContents := 
.obj42@5a28b551.__eContainer := /files.obj48@5a28b551
.obj42@5a28b551.fileName := readinode.c

# .obj43@5a28b551
.obj43@5a28b551 := MyFileName
.obj43@5a28b551.__eContents := 
.obj43@5a28b551.__eContainer := /files.obj48@5a28b551
.obj43@5a28b551.fileName := nodelist.c

# .obj44@5a28b551
.obj44@5a28b551 := MyFileName
.obj44@5a28b551.__eContents := 
.obj44@5a28b551.__eContainer := /files.obj48@5a28b551
.obj44@5a28b551.fileName := write.c

# .obj45@5a28b551
.obj45@5a28b551 := MyFileName
.obj45@5a28b551.__eContents := 
.obj45@5a28b551.__eContainer := /files.obj48@5a28b551
.obj45@5a28b551.fileName := malloc_jffs2.c

# .obj46@5a28b551
.obj46@5a28b551 := MyFileName
.obj46@5a28b551.__eContents := 
.obj46@5a28b551.__eContainer := /files.obj48@5a28b551
.obj46@5a28b551.fileName := nodemgmt.c

# .obj47@5a28b551
.obj47@5a28b551 := MyFileName
.obj47@5a28b551.__eContents := 
.obj47@5a28b551.__eContainer := /files.obj48@5a28b551
.obj47@5a28b551.fileName := flashio.c

# .obj51@5a28b551
.obj51@5a28b551 := MyOptionMember
.obj51@5a28b551.__eContents := \
	options/.obj49@5a28b551
.obj51@5a28b551.__eContainer := /optionsMembers.obj72@5a28b551
.obj51@5a28b551.module := 

# .obj49@5a28b551
.obj49@5a28b551 := MyNumberOption
.obj49@5a28b551.__eContents := \
	defaultValue/.obj50@5a28b551
.obj49@5a28b551.__eContainer := /options.obj51@5a28b551
.obj49@5a28b551.name := inode_quantity
.obj49@5a28b551.origin := 

# .obj50@5a28b551
.obj50@5a28b551 := MyNumberLiteral
.obj50@5a28b551.__eContents := 
.obj50@5a28b551.__eContainer := /defaultValue.obj49@5a28b551
.obj50@5a28b551.value := 64

# .obj54@5a28b551
.obj54@5a28b551 := MyOptionMember
.obj54@5a28b551.__eContents := \
	options/.obj52@5a28b551
.obj54@5a28b551.__eContainer := /optionsMembers.obj72@5a28b551
.obj54@5a28b551.module := 

# .obj52@5a28b551
.obj52@5a28b551 := MyNumberOption
.obj52@5a28b551.__eContents := \
	defaultValue/.obj53@5a28b551
.obj52@5a28b551.__eContainer := /options.obj54@5a28b551
.obj52@5a28b551.name := jffs2_descriptor_quantity
.obj52@5a28b551.origin := 

# .obj53@5a28b551
.obj53@5a28b551 := MyNumberLiteral
.obj53@5a28b551.__eContents := 
.obj53@5a28b551.__eContainer := /defaultValue.obj52@5a28b551
.obj53@5a28b551.value := 4

# .obj57@5a28b551
.obj57@5a28b551 := MyDependsMember
.obj57@5a28b551.__eContents := 
.obj57@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj57@5a28b551.modules := \
	.obj55@5a28b551./ \
	.obj56@5a28b551./
.obj57@5a28b551.module := 

# .obj55@5a28b551
.obj55@5a28b551 := ELink
.obj55@5a28b551.eSource := MyFile_DependsMember_modules.obj57@5a28b551
.obj55@5a28b551.eTarget := 
.obj55@5a28b551.name := embox.fs.node
.obj55@5a28b551.origin := 16:10

# .obj56@5a28b551
.obj56@5a28b551 := ELink
.obj56@5a28b551.eSource := MyFile_DependsMember_modules.obj57@5a28b551
.obj56@5a28b551.eTarget := 
.obj56@5a28b551.name := embox.fs.driver.repo
.obj56@5a28b551.origin := 16:25

# .obj59@5a28b551
.obj59@5a28b551 := MyDependsMember
.obj59@5a28b551.__eContents := 
.obj59@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj59@5a28b551.modules := \
	.obj58@5a28b551./
.obj59@5a28b551.module := 

# .obj58@5a28b551
.obj58@5a28b551 := ELink
.obj58@5a28b551.eSource := MyFile_DependsMember_modules.obj59@5a28b551
.obj58@5a28b551.eTarget := 
.obj58@5a28b551.name := embox.fs.driver.fat
.obj58@5a28b551.origin := 17:10

# .obj61@5a28b551
.obj61@5a28b551 := MyDependsMember
.obj61@5a28b551.__eContents := 
.obj61@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj61@5a28b551.modules := \
	.obj60@5a28b551./
.obj61@5a28b551.module := 

# .obj60@5a28b551
.obj60@5a28b551 := ELink
.obj60@5a28b551.eSource := MyFile_DependsMember_modules.obj61@5a28b551
.obj60@5a28b551.eTarget := 
.obj60@5a28b551.name := embox.mem.page_api
.obj60@5a28b551.origin := 18:10

# .obj63@5a28b551
.obj63@5a28b551 := MyDependsMember
.obj63@5a28b551.__eContents := 
.obj63@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj63@5a28b551.modules := \
	.obj62@5a28b551./
.obj63@5a28b551.module := 

# .obj62@5a28b551
.obj62@5a28b551 := ELink
.obj62@5a28b551.eSource := MyFile_DependsMember_modules.obj63@5a28b551
.obj62@5a28b551.eTarget := 
.obj62@5a28b551.name := embox.mem.pool
.obj62@5a28b551.origin := 19:10

# .obj65@5a28b551
.obj65@5a28b551 := MyDependsMember
.obj65@5a28b551.__eContents := 
.obj65@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj65@5a28b551.modules := \
	.obj64@5a28b551./
.obj65@5a28b551.module := 

# .obj64@5a28b551
.obj64@5a28b551 := ELink
.obj64@5a28b551.eSource := MyFile_DependsMember_modules.obj65@5a28b551
.obj64@5a28b551.eTarget := 
.obj64@5a28b551.name := embox.driver.flash.core
.obj64@5a28b551.origin := 20:10

# .obj67@5a28b551
.obj67@5a28b551 := MyDependsMember
.obj67@5a28b551.__eContents := 
.obj67@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj67@5a28b551.modules := \
	.obj66@5a28b551./
.obj67@5a28b551.module := 

# .obj66@5a28b551
.obj66@5a28b551 := ELink
.obj66@5a28b551.eSource := MyFile_DependsMember_modules.obj67@5a28b551
.obj66@5a28b551.eTarget := 
.obj66@5a28b551.name := third_party.zlib.libs
.obj66@5a28b551.origin := 21:10

# .obj69@5a28b551
.obj69@5a28b551 := MyDependsMember
.obj69@5a28b551.__eContents := 
.obj69@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj69@5a28b551.modules := \
	.obj68@5a28b551./
.obj69@5a28b551.module := 

# .obj68@5a28b551
.obj68@5a28b551 := ELink
.obj68@5a28b551.eSource := MyFile_DependsMember_modules.obj69@5a28b551
.obj68@5a28b551.eTarget := 
.obj68@5a28b551.name := third_party.lib.util.rbtree
.obj68@5a28b551.origin := 22:10

# .obj71@5a28b551
.obj71@5a28b551 := MyDependsMember
.obj71@5a28b551.__eContents := 
.obj71@5a28b551.__eContainer := /dependsMembers.obj72@5a28b551
.obj71@5a28b551.modules := \
	.obj70@5a28b551./
.obj71@5a28b551.module := 

# .obj70@5a28b551
.obj70@5a28b551 := ELink
.obj70@5a28b551.eSource := MyFile_DependsMember_modules.obj71@5a28b551
.obj70@5a28b551.eTarget := 
.obj70@5a28b551.name := embox.driver.flash.emulator
.obj70@5a28b551.origin := 23:10

# .obj9@5a28b551
.obj9@5a28b551 := MyAnnotation
.obj9@5a28b551.__eContents := \
	bindings/.obj5@5a28b551 \
	bindings/.obj8@5a28b551
.obj9@5a28b551.__eContainer := target/annotations.obj72@5a28b551
.obj9@5a28b551.type := .obj2@5a28b551./

# .obj5@5a28b551
.obj5@5a28b551 := MyOptionBinding
.obj5@5a28b551.__eContents := \
	value/.obj4@5a28b551
.obj5@5a28b551.__eContainer := /bindings.obj9@5a28b551
.obj5@5a28b551.option := .obj3@5a28b551./

# .obj4@5a28b551
.obj4@5a28b551 := MyNumberLiteral
.obj4@5a28b551.__eContents := 
.obj4@5a28b551.__eContainer := /value.obj5@5a28b551
.obj4@5a28b551.value := 2

# .obj3@5a28b551
.obj3@5a28b551 := ELink
.obj3@5a28b551.eSource := MyFile_OptionBinding_option.obj5@5a28b551
.obj3@5a28b551.eTarget := 
.obj3@5a28b551.name := stage
.obj3@5a28b551.origin := 3:8

# .obj8@5a28b551
.obj8@5a28b551 := MyOptionBinding
.obj8@5a28b551.__eContents := \
	value/.obj7@5a28b551
.obj8@5a28b551.__eContainer := /bindings.obj9@5a28b551
.obj8@5a28b551.option := .obj6@5a28b551./

# .obj7@5a28b551
.obj7@5a28b551 := MyStringLiteral
.obj7@5a28b551.__eContents := 
.obj7@5a28b551.__eContainer := /value.obj8@5a28b551
.obj7@5a28b551.value := true

# .obj6@5a28b551
.obj6@5a28b551 := ELink
.obj6@5a28b551.eSource := MyFile_OptionBinding_option.obj8@5a28b551
.obj6@5a28b551.eTarget := 
.obj6@5a28b551.name := script
.obj6@5a28b551.origin := 3:16

# .obj2@5a28b551
.obj2@5a28b551 := ELink
.obj2@5a28b551.eSource := MyFile_Annotation_type.obj9@5a28b551
.obj2@5a28b551.eTarget := 
.obj2@5a28b551.name := Build
.obj2@5a28b551.origin := 3:2

# .obj15@5a28b551
.obj15@5a28b551 := MyAnnotation
.obj15@5a28b551.__eContents := \
	bindings/.obj13@5a28b551
.obj15@5a28b551.__eContainer := target/annotations.obj72@5a28b551
.obj15@5a28b551.type := .obj10@5a28b551./

# .obj13@5a28b551
.obj13@5a28b551 := MyOptionBinding
.obj13@5a28b551.__eContents := \
	value/.obj12@5a28b551
.obj13@5a28b551.__eContainer := /bindings.obj15@5a28b551
.obj13@5a28b551.option := .obj14@5a28b551./

# .obj12@5a28b551
.obj12@5a28b551 := MyTypeReferenceLiteral
.obj12@5a28b551.__eContents := 
.obj12@5a28b551.__eContainer := /value.obj13@5a28b551
.obj12@5a28b551.value := .obj11@5a28b551./

# .obj11@5a28b551
.obj11@5a28b551 := ELink
.obj11@5a28b551.eSource := MyFile_TypeReferenceLiteral_value.obj12@5a28b551
.obj11@5a28b551.eTarget := 
.obj11@5a28b551.name := third_party.zlib.zlib_download
.obj11@5a28b551.origin := 4:15

# .obj14@5a28b551
.obj14@5a28b551 := ELink
.obj14@5a28b551.eSource := MyFile_OptionBinding_option.obj13@5a28b551
.obj14@5a28b551.eTarget := 
.obj14@5a28b551.name := value
.obj14@5a28b551.origin := 4:14

# .obj10@5a28b551
.obj10@5a28b551 := ELink
.obj10@5a28b551.eSource := MyFile_Annotation_type.obj15@5a28b551
.obj10@5a28b551.eTarget := 
.obj10@5a28b551.name := BuildDepends
.obj10@5a28b551.origin := 4:2


__resource-mk/.cache/mybuild/files/src/fs/driver/jffs2/Mybuild.mk := .obj1@5a28b551
