# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@c57370cf

# .obj1@c57370cf
.obj1@c57370cf := MyFileResource
.obj1@c57370cf.issues := 
.obj1@c57370cf.contentsRoot := .obj18@c57370cf
.obj1@c57370cf.resourceSet := 
.obj1@c57370cf.fileName := src/cmds/hardware/mm/mmutrans/Mybuild
.obj1@c57370cf.exports := \
	embox.cmd.hw \
	embox.cmd.hw.mmutrans
.obj1@c57370cf.exports.embox.cmd.hw := \
	.obj18@c57370cf
.obj1@c57370cf.exports.embox.cmd.hw.mmutrans := \
	.obj17@c57370cf

# .obj18@c57370cf
.obj18@c57370cf := MyFileContentRoot
.obj18@c57370cf.__eContents := \
	types/.obj17@c57370cf
.obj18@c57370cf.__eContainer := .obj1@c57370cf
.obj18@c57370cf.imports := 
.obj18@c57370cf.name := embox.cmd.hw
.obj18@c57370cf.origin := 

# .obj17@c57370cf
.obj17@c57370cf := MyModuleType
.obj17@c57370cf.__eContents := \
	sourcesMembers/.obj16@c57370cf \
	annotations/.obj3@c57370cf \
	annotations/.obj14@c57370cf
.obj17@c57370cf.__eContainer := fileContentRoot/types.obj18@c57370cf
.obj17@c57370cf.dependent := 
.obj17@c57370cf.subTypes := 
.obj17@c57370cf.modifiers := 
.obj17@c57370cf.name := mmutrans
.obj17@c57370cf.origin := 16:9
.obj17@c57370cf.superType := 
.obj17@c57370cf.customStorage := 

# .obj16@c57370cf
.obj16@c57370cf := MySourceMember
.obj16@c57370cf.__eContents := \
	files/.obj15@c57370cf
.obj16@c57370cf.__eContainer := /sourcesMembers.obj17@c57370cf
.obj16@c57370cf.module := 

# .obj15@c57370cf
.obj15@c57370cf := MyFileName
.obj15@c57370cf.__eContents := 
.obj15@c57370cf.__eContainer := /files.obj16@c57370cf
.obj15@c57370cf.fileName := mmutrans.c

# .obj3@c57370cf
.obj3@c57370cf := MyAnnotation
.obj3@c57370cf.__eContents := 
.obj3@c57370cf.__eContainer := target/annotations.obj17@c57370cf
.obj3@c57370cf.type := .obj2@c57370cf./

# .obj2@c57370cf
.obj2@c57370cf := ELink
.obj2@c57370cf.eSource := MyFile_Annotation_type.obj3@c57370cf
.obj2@c57370cf.eTarget := 
.obj2@c57370cf.name := AutoCmd
.obj2@c57370cf.origin := 3:2

# .obj14@c57370cf
.obj14@c57370cf := MyAnnotation
.obj14@c57370cf.__eContents := \
	bindings/.obj7@c57370cf \
	bindings/.obj10@c57370cf \
	bindings/.obj13@c57370cf
.obj14@c57370cf.__eContainer := target/annotations.obj17@c57370cf
.obj14@c57370cf.type := .obj4@c57370cf./

# .obj7@c57370cf
.obj7@c57370cf := MyOptionBinding
.obj7@c57370cf.__eContents := \
	value/.obj6@c57370cf
.obj7@c57370cf.__eContainer := /bindings.obj14@c57370cf
.obj7@c57370cf.option := .obj5@c57370cf./

# .obj6@c57370cf
.obj6@c57370cf := MyStringLiteral
.obj6@c57370cf.__eContents := 
.obj6@c57370cf.__eContainer := /value.obj7@c57370cf
.obj6@c57370cf.value := mmutrans

# .obj5@c57370cf
.obj5@c57370cf := ELink
.obj5@c57370cf.eSource := MyFile_OptionBinding_option.obj7@c57370cf
.obj5@c57370cf.eTarget := 
.obj5@c57370cf.name := name
.obj5@c57370cf.origin := 4:6

# .obj10@c57370cf
.obj10@c57370cf := MyOptionBinding
.obj10@c57370cf.__eContents := \
	value/.obj9@c57370cf
.obj10@c57370cf.__eContainer := /bindings.obj14@c57370cf
.obj10@c57370cf.option := .obj8@c57370cf./

# .obj9@c57370cf
.obj9@c57370cf := MyStringLiteral
.obj9@c57370cf.__eContents := 
.obj9@c57370cf.__eContainer := /value.obj10@c57370cf
.obj9@c57370cf.value := Managing virtual memory table

# .obj8@c57370cf
.obj8@c57370cf := ELink
.obj8@c57370cf.eSource := MyFile_OptionBinding_option.obj10@c57370cf
.obj8@c57370cf.eTarget := 
.obj8@c57370cf.name := help
.obj8@c57370cf.origin := 5:2

# .obj13@c57370cf
.obj13@c57370cf := MyOptionBinding
.obj13@c57370cf.__eContents := \
	value/.obj12@c57370cf
.obj13@c57370cf.__eContainer := /bindings.obj14@c57370cf
.obj13@c57370cf.option := .obj11@c57370cf./

# .obj12@c57370cf
.obj12@c57370cf := MyStringLiteral
.obj12@c57370cf.__eContents := 
.obj12@c57370cf.__eContainer := /value.obj13@c57370cf
.obj12@c57370cf.value := $(\0)$(\n)		NAME$(\n)			mmutrans - testing virtual memory table$(\n)		SYNOPSIS$(\n)$(\n)		DESCRIPTION$(\n)			Detailed description.$(\n)		AUTHORS$(\n)			Anton Bondarev$(\n)	

# .obj11@c57370cf
.obj11@c57370cf := ELink
.obj11@c57370cf.eSource := MyFile_OptionBinding_option.obj13@c57370cf
.obj11@c57370cf.eTarget := 
.obj11@c57370cf.name := man
.obj11@c57370cf.origin := 6:2

# .obj4@c57370cf
.obj4@c57370cf := ELink
.obj4@c57370cf.eSource := MyFile_Annotation_type.obj14@c57370cf
.obj4@c57370cf.eTarget := 
.obj4@c57370cf.name := Cmd
.obj4@c57370cf.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/hardware/mm/mmutrans/Mybuild.mk := .obj1@c57370cf
