# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@6cca7c70

# .obj1@6cca7c70
.obj1@6cca7c70 := MyFileResource
.obj1@6cca7c70.issues := 
.obj1@6cca7c70.contentsRoot := .obj20@6cca7c70
.obj1@6cca7c70.resourceSet := 
.obj1@6cca7c70.fileName := src/cmds/hardware/sensors/adxl345/Mybuild
.obj1@6cca7c70.exports := \
	embox.cmd.hardware.sensors \
	embox.cmd.hardware.sensors.adxl345
.obj1@6cca7c70.exports.embox.cmd.hardware.sensors := \
	.obj20@6cca7c70
.obj1@6cca7c70.exports.embox.cmd.hardware.sensors.adxl345 := \
	.obj19@6cca7c70

# .obj20@6cca7c70
.obj20@6cca7c70 := MyFileContentRoot
.obj20@6cca7c70.__eContents := \
	types/.obj19@6cca7c70
.obj20@6cca7c70.__eContainer := .obj1@6cca7c70
.obj20@6cca7c70.imports := 
.obj20@6cca7c70.name := embox.cmd.hardware.sensors
.obj20@6cca7c70.origin := 

# .obj19@6cca7c70
.obj19@6cca7c70 := MyModuleType
.obj19@6cca7c70.__eContents := \
	sourcesMembers/.obj16@6cca7c70 \
	dependsMembers/.obj18@6cca7c70 \
	annotations/.obj3@6cca7c70 \
	annotations/.obj14@6cca7c70
.obj19@6cca7c70.__eContainer := fileContentRoot/types.obj20@6cca7c70
.obj19@6cca7c70.dependent := 
.obj19@6cca7c70.subTypes := 
.obj19@6cca7c70.modifiers := 
.obj19@6cca7c70.name := adxl345
.obj19@6cca7c70.origin := 16:8
.obj19@6cca7c70.superType := 
.obj19@6cca7c70.customStorage := 

# .obj16@6cca7c70
.obj16@6cca7c70 := MySourceMember
.obj16@6cca7c70.__eContents := \
	files/.obj15@6cca7c70
.obj16@6cca7c70.__eContainer := /sourcesMembers.obj19@6cca7c70
.obj16@6cca7c70.module := 

# .obj15@6cca7c70
.obj15@6cca7c70 := MyFileName
.obj15@6cca7c70.__eContents := 
.obj15@6cca7c70.__eContainer := /files.obj16@6cca7c70
.obj15@6cca7c70.fileName := adxl345.c

# .obj18@6cca7c70
.obj18@6cca7c70 := MyDependsMember
.obj18@6cca7c70.__eContents := 
.obj18@6cca7c70.__eContainer := /dependsMembers.obj19@6cca7c70
.obj18@6cca7c70.modules := \
	.obj17@6cca7c70./
.obj18@6cca7c70.module := 

# .obj17@6cca7c70
.obj17@6cca7c70 := ELink
.obj17@6cca7c70.eSource := MyFile_DependsMember_modules.obj18@6cca7c70
.obj17@6cca7c70.eTarget := 
.obj17@6cca7c70.name := embox.driver.sensors.adxl345
.obj17@6cca7c70.origin := 19:10

# .obj3@6cca7c70
.obj3@6cca7c70 := MyAnnotation
.obj3@6cca7c70.__eContents := 
.obj3@6cca7c70.__eContainer := target/annotations.obj19@6cca7c70
.obj3@6cca7c70.type := .obj2@6cca7c70./

# .obj2@6cca7c70
.obj2@6cca7c70 := ELink
.obj2@6cca7c70.eSource := MyFile_Annotation_type.obj3@6cca7c70
.obj2@6cca7c70.eTarget := 
.obj2@6cca7c70.name := AutoCmd
.obj2@6cca7c70.origin := 3:2

# .obj14@6cca7c70
.obj14@6cca7c70 := MyAnnotation
.obj14@6cca7c70.__eContents := \
	bindings/.obj7@6cca7c70 \
	bindings/.obj10@6cca7c70 \
	bindings/.obj13@6cca7c70
.obj14@6cca7c70.__eContainer := target/annotations.obj19@6cca7c70
.obj14@6cca7c70.type := .obj4@6cca7c70./

# .obj7@6cca7c70
.obj7@6cca7c70 := MyOptionBinding
.obj7@6cca7c70.__eContents := \
	value/.obj6@6cca7c70
.obj7@6cca7c70.__eContainer := /bindings.obj14@6cca7c70
.obj7@6cca7c70.option := .obj5@6cca7c70./

# .obj6@6cca7c70
.obj6@6cca7c70 := MyStringLiteral
.obj6@6cca7c70.__eContents := 
.obj6@6cca7c70.__eContainer := /value.obj7@6cca7c70
.obj6@6cca7c70.value := adxl345

# .obj5@6cca7c70
.obj5@6cca7c70 := ELink
.obj5@6cca7c70.eSource := MyFile_OptionBinding_option.obj7@6cca7c70
.obj5@6cca7c70.eTarget := 
.obj5@6cca7c70.name := name
.obj5@6cca7c70.origin := 4:6

# .obj10@6cca7c70
.obj10@6cca7c70 := MyOptionBinding
.obj10@6cca7c70.__eContents := \
	value/.obj9@6cca7c70
.obj10@6cca7c70.__eContainer := /bindings.obj14@6cca7c70
.obj10@6cca7c70.option := .obj8@6cca7c70./

# .obj9@6cca7c70
.obj9@6cca7c70 := MyStringLiteral
.obj9@6cca7c70.__eContents := 
.obj9@6cca7c70.__eContainer := /value.obj10@6cca7c70
.obj9@6cca7c70.value := Test adxl345 accelerometer data

# .obj8@6cca7c70
.obj8@6cca7c70 := ELink
.obj8@6cca7c70.eSource := MyFile_OptionBinding_option.obj10@6cca7c70
.obj8@6cca7c70.eTarget := 
.obj8@6cca7c70.name := help
.obj8@6cca7c70.origin := 5:2

# .obj13@6cca7c70
.obj13@6cca7c70 := MyOptionBinding
.obj13@6cca7c70.__eContents := \
	value/.obj12@6cca7c70
.obj13@6cca7c70.__eContainer := /bindings.obj14@6cca7c70
.obj13@6cca7c70.option := .obj11@6cca7c70./

# .obj12@6cca7c70
.obj12@6cca7c70 := MyStringLiteral
.obj12@6cca7c70.__eContents := 
.obj12@6cca7c70.__eContainer := /value.obj13@6cca7c70
.obj12@6cca7c70.value := $(\0)$(\n)		NAME$(\n)			adxl345 - accelerometer test$(\n)		SYNOPSIS$(\n)			adxl345$(\n)		DESCRIPTION$(\n)			Print x/y/z accelerometer data in infinite loop$(\n)		AUTHORS$(\n)			Denis Deryugin$(\n)	

# .obj11@6cca7c70
.obj11@6cca7c70 := ELink
.obj11@6cca7c70.eSource := MyFile_OptionBinding_option.obj13@6cca7c70
.obj11@6cca7c70.eTarget := 
.obj11@6cca7c70.name := man
.obj11@6cca7c70.origin := 6:2

# .obj4@6cca7c70
.obj4@6cca7c70 := ELink
.obj4@6cca7c70.eSource := MyFile_Annotation_type.obj14@6cca7c70
.obj4@6cca7c70.eTarget := 
.obj4@6cca7c70.name := Cmd
.obj4@6cca7c70.origin := 4:2


__resource-mk/.cache/mybuild/files/src/cmds/hardware/sensors/adxl345/Mybuild.mk := .obj1@6cca7c70
