# Generated by GNU Make 4.2.1. Do not edit.

# PERSIST_OBJECTS:
#   .obj1@54f9288e

# .obj1@54f9288e
.obj1@54f9288e := MyFileResource
.obj1@54f9288e.issues := 
.obj1@54f9288e.contentsRoot := .obj23@54f9288e
.obj1@54f9288e.resourceSet := 
.obj1@54f9288e.fileName := src/drivers/sensors/adxl345/Mybuild
.obj1@54f9288e.exports := \
	embox.driver.sensors \
	embox.driver.sensors.adxl345 \
	embox.driver.sensors.adxl345.log_level \
	embox.driver.sensors.adxl345.bus \
	embox.driver.sensors.adxl345.addr
.obj1@54f9288e.exports.embox.driver.sensors := \
	.obj23@54f9288e
.obj1@54f9288e.exports.embox.driver.sensors.adxl345 := \
	.obj22@54f9288e
.obj1@54f9288e.exports.embox.driver.sensors.adxl345.log_level := \
	.obj2@54f9288e
.obj1@54f9288e.exports.embox.driver.sensors.adxl345.bus := \
	.obj5@54f9288e
.obj1@54f9288e.exports.embox.driver.sensors.adxl345.addr := \
	.obj8@54f9288e

# .obj23@54f9288e
.obj23@54f9288e := MyFileContentRoot
.obj23@54f9288e.__eContents := \
	types/.obj22@54f9288e
.obj23@54f9288e.__eContainer := .obj1@54f9288e
.obj23@54f9288e.imports := 
.obj23@54f9288e.name := embox.driver.sensors
.obj23@54f9288e.origin := 

# .obj22@54f9288e
.obj22@54f9288e := MyModuleType
.obj22@54f9288e.__eContents := \
	sourcesMembers/.obj17@54f9288e \
	sourcesMembers/.obj19@54f9288e \
	optionsMembers/.obj4@54f9288e \
	optionsMembers/.obj7@54f9288e \
	optionsMembers/.obj10@54f9288e \
	dependsMembers/.obj21@54f9288e
.obj22@54f9288e.__eContainer := fileContentRoot/types.obj23@54f9288e
.obj22@54f9288e.dependent := 
.obj22@54f9288e.subTypes := 
.obj22@54f9288e.modifiers := 
.obj22@54f9288e.name := adxl345
.obj22@54f9288e.origin := 3:8
.obj22@54f9288e.superType := 
.obj22@54f9288e.customStorage := 

# .obj17@54f9288e
.obj17@54f9288e := MySourceMember
.obj17@54f9288e.__eContents := \
	files/.obj16@54f9288e \
	annotations/.obj15@54f9288e
.obj17@54f9288e.__eContainer := /sourcesMembers.obj22@54f9288e
.obj17@54f9288e.module := 

# .obj16@54f9288e
.obj16@54f9288e := MyFileName
.obj16@54f9288e.__eContents := 
.obj16@54f9288e.__eContainer := /files.obj17@54f9288e
.obj16@54f9288e.fileName := adxl345.h

# .obj15@54f9288e
.obj15@54f9288e := MyAnnotation
.obj15@54f9288e.__eContents := \
	bindings/.obj14@54f9288e
.obj15@54f9288e.__eContainer := target/annotations.obj17@54f9288e
.obj15@54f9288e.type := .obj11@54f9288e./

# .obj14@54f9288e
.obj14@54f9288e := MyOptionBinding
.obj14@54f9288e.__eContents := \
	value/.obj13@54f9288e
.obj14@54f9288e.__eContainer := /bindings.obj15@54f9288e
.obj14@54f9288e.option := .obj12@54f9288e./

# .obj13@54f9288e
.obj13@54f9288e := MyStringLiteral
.obj13@54f9288e.__eContents := 
.obj13@54f9288e.__eContainer := /value.obj14@54f9288e
.obj13@54f9288e.value := drivers/sensors

# .obj12@54f9288e
.obj12@54f9288e := ELink
.obj12@54f9288e.eSource := MyFile_OptionBinding_option.obj14@54f9288e
.obj12@54f9288e.eTarget := 
.obj12@54f9288e.name := path
.obj12@54f9288e.origin := 10:17

# .obj11@54f9288e
.obj11@54f9288e := ELink
.obj11@54f9288e.eSource := MyFile_Annotation_type.obj15@54f9288e
.obj11@54f9288e.eTarget := 
.obj11@54f9288e.name := IncludeExport
.obj11@54f9288e.origin := 10:3

# .obj19@54f9288e
.obj19@54f9288e := MySourceMember
.obj19@54f9288e.__eContents := \
	files/.obj18@54f9288e
.obj19@54f9288e.__eContainer := /sourcesMembers.obj22@54f9288e
.obj19@54f9288e.module := 

# .obj18@54f9288e
.obj18@54f9288e := MyFileName
.obj18@54f9288e.__eContents := 
.obj18@54f9288e.__eContainer := /files.obj19@54f9288e
.obj18@54f9288e.fileName := adxl345.c

# .obj4@54f9288e
.obj4@54f9288e := MyOptionMember
.obj4@54f9288e.__eContents := \
	options/.obj2@54f9288e
.obj4@54f9288e.__eContainer := /optionsMembers.obj22@54f9288e
.obj4@54f9288e.module := 

# .obj2@54f9288e
.obj2@54f9288e := MyNumberOption
.obj2@54f9288e.__eContents := \
	defaultValue/.obj3@54f9288e
.obj2@54f9288e.__eContainer := /options.obj4@54f9288e
.obj2@54f9288e.name := log_level
.obj2@54f9288e.origin := 

# .obj3@54f9288e
.obj3@54f9288e := MyNumberLiteral
.obj3@54f9288e.__eContents := 
.obj3@54f9288e.__eContainer := /defaultValue.obj2@54f9288e
.obj3@54f9288e.value := 4

# .obj7@54f9288e
.obj7@54f9288e := MyOptionMember
.obj7@54f9288e.__eContents := \
	options/.obj5@54f9288e
.obj7@54f9288e.__eContainer := /optionsMembers.obj22@54f9288e
.obj7@54f9288e.module := 

# .obj5@54f9288e
.obj5@54f9288e := MyNumberOption
.obj5@54f9288e.__eContents := \
	defaultValue/.obj6@54f9288e
.obj5@54f9288e.__eContainer := /options.obj7@54f9288e
.obj5@54f9288e.name := bus
.obj5@54f9288e.origin := 

# .obj6@54f9288e
.obj6@54f9288e := MyNumberLiteral
.obj6@54f9288e.__eContents := 
.obj6@54f9288e.__eContainer := /defaultValue.obj5@54f9288e
.obj6@54f9288e.value := 0

# .obj10@54f9288e
.obj10@54f9288e := MyOptionMember
.obj10@54f9288e.__eContents := \
	options/.obj8@54f9288e
.obj10@54f9288e.__eContainer := /optionsMembers.obj22@54f9288e
.obj10@54f9288e.module := 

# .obj8@54f9288e
.obj8@54f9288e := MyNumberOption
.obj8@54f9288e.__eContents := \
	defaultValue/.obj9@54f9288e
.obj8@54f9288e.__eContainer := /options.obj10@54f9288e
.obj8@54f9288e.name := addr
.obj8@54f9288e.origin := 

# .obj9@54f9288e
.obj9@54f9288e := MyNumberLiteral
.obj9@54f9288e.__eContents := 
.obj9@54f9288e.__eContainer := /defaultValue.obj8@54f9288e
.obj9@54f9288e.value := 83

# .obj21@54f9288e
.obj21@54f9288e := MyDependsMember
.obj21@54f9288e.__eContents := 
.obj21@54f9288e.__eContainer := /dependsMembers.obj22@54f9288e
.obj21@54f9288e.modules := \
	.obj20@54f9288e./
.obj21@54f9288e.module := 

# .obj20@54f9288e
.obj20@54f9288e := ELink
.obj20@54f9288e.eSource := MyFile_DependsMember_modules.obj21@54f9288e
.obj20@54f9288e.eTarget := 
.obj20@54f9288e.name := embox.driver.adapters.i2c_designware
.obj20@54f9288e.origin := 15:10


__resource-mk/.cache/mybuild/files/src/drivers/sensors/adxl345/Mybuild.mk := .obj1@54f9288e
